;;; edgar-forms-registration.el --- EDGAR form registry rows: registration -*- lexical-binding: t; -*-

;;; Commentary:

;; Registration, proxy, investment-company and Reg CF/A forms (G7, G8, G10, G11).
;; Row shape: (FORM FAMILY BACKEND LEVEL SECTIONS-OR-FIELDS VOLUME NOTES).
;; Consumed by `edgar-forms'.

;;; Code:

(defconst edgar-forms-registration-rows
  '(("1" "G11 Reg CF & Reg A" pdf L1 nil 163 nil)
    ("1-A" "G11 Reg CF & Reg A" xml L1 nil 100 nil)
    ("1-A POS" "G11 Reg CF & Reg A" xml L1 nil 38 nil)
    ("1-A-W" "G11 Reg CF & Reg A" html L1 nil 7 nil)
    ("1-K" "G11 Reg CF & Reg A" xml L1 nil 422 nil)
    ("1-SA" "G11 Reg CF & Reg A" html L1 nil 18 nil)
    ("1-U" "G11 Reg CF & Reg A" html L1 nil 676 nil)
    ("1-Z" "G11 Reg CF & Reg A" xml L1 nil 286 nil)
    ("10-12B" "G7 Prospectuses & registration" html L1 nil 17 nil)
    ("10-12G" "G7 Prospectuses & registration" html L1 nil 40 nil)
    ("20FR12B" "G7 Prospectuses & registration" html L1 nil 8 nil)
    ("20FR12G" "G7 Prospectuses & registration" html L1 nil 2 nil)
    ("24F-2NT" "G10 Investment-company registration" xml L1 nil 839 nil)
    ("253G1" "G11 Reg CF & Reg A" html L1 nil 6 nil)
    ("253G2" "G11 Reg CF & Reg A" html L1 nil 66 nil)
    ("40-17F1" "G10 Investment-company registration" html L1 nil 30 nil)
    ("40-17F2" "G10 Investment-company registration" html L1 nil 134 nil)
    ("40-17G" "G10 Investment-company registration" html L1 nil 434 nil)
    ("40-24B2" "G10 Investment-company registration" html L1 nil 13 nil)
    ("40-33" "G10 Investment-company registration" html L1 nil 8 nil)
    ("40-6B" "G10 Investment-company registration" html L1 nil 17 nil)
    ("40-8F-2" "G10 Investment-company registration" html L1 nil 2 nil)
    ("40-APP" "G10 Investment-company registration" html L1 nil 1909 nil)
    ("40FR12B" "G7 Prospectuses & registration" html L1 nil 7 nil)
    ("40FR12G" "G7 Prospectuses & registration" html L1 nil 2 nil)
    ("424B1" "G7 Prospectuses & registration" html L2 (named-headings) 4 nil)
    ("424B2" "G7 Prospectuses & registration" html L1 nil 49609 nil)
    ("424B3" "G7 Prospectuses & registration" html L1 nil 2607 nil)
    ("424B4" "G7 Prospectuses & registration" html L1 nil 170 nil)
    ("424B5" "G7 Prospectuses & registration" html L1 nil 968 nil)
    ("424B7" "G7 Prospectuses & registration" html L1 nil 69 nil)
    ("424B8" "G7 Prospectuses & registration" html L1 nil 52 nil)
    ("424H" "G7 Prospectuses & registration" html L1 nil 81 nil)
    ("424I" "G7 Prospectuses & registration" html L1 nil 10 nil)
    ("425" "G8 Proxy & M&A" html L1 nil 1546 nil)
    ("485APOS" "G10 Investment-company registration" html L1 nil 511 nil)
    ("485BPOS" "G10 Investment-company registration" html L2 (investment-objective fees-and-expenses principal-risks) 2352 nil)
    ("485BXT" "G10 Investment-company registration" html L1 nil 1286 nil)
    ("486APOS" "G10 Investment-company registration" html L1 nil 18 nil)
    ("486BPOS" "G10 Investment-company registration" html L1 nil 83 nil)
    ("486BXT" "G10 Investment-company registration" html L1 nil 8 nil)
    ("487" "G10 Investment-company registration" html L1 nil 229 nil)
    ("497" "G10 Investment-company registration" html L1 nil 4175 nil)
    ("497AD" "G10 Investment-company registration" html L1 nil 95 nil)
    ("497J" "G10 Investment-company registration" html L1 nil 2190 nil)
    ("497K" "G10 Investment-company registration" html L2 (summary-prospectus-named-sections) 6592 nil)
    ("497VPI" "G10 Investment-company registration" html L1 nil 912 nil)
    ("497VPSUB" "G10 Investment-company registration" html L1 nil 2 nil)
    ("497VPU" "G10 Investment-company registration" html L1 nil 1800 nil)
    ("8-A12B" "G7 Prospectuses & registration" html L1 nil 494 nil)
    ("8-A12G" "G7 Prospectuses & registration" html L1 nil 15 nil)
    ("APP NTC" "G10 Investment-company registration" pdf L1 nil 65 nil)
    ("APP ORDR" "G10 Investment-company registration" pdf L1 nil 63 nil)
    ("APP WD" "G10 Investment-company registration" html L1 nil 47 nil)
    ("APP WDG" "G10 Investment-company registration" pdf L1 nil 13 nil)
    ("ARS" "G8 Proxy & M&A" pdf L1 nil 1883 nil)
    ("AW" "G7 Prospectuses & registration" html L1 nil 48 nil)
    ("C" "G11 Reg CF & Reg A" xml L2 (issuer offering financials signature) 500 nil)
    ("C-AR" "G11 Reg CF & Reg A" xml L2 (issuer period annual-report signature) 549 nil)
    ("C-AR-W" "G11 Reg CF & Reg A" xml L1 nil 2 nil)
    ("C-TR" "G11 Reg CF & Reg A" xml L1 nil 89 nil)
    ("C-TR-W" "G11 Reg CF & Reg A" xml L1 nil 4 nil)
    ("C-U" "G11 Reg CF & Reg A" xml L1 nil 163 nil)
    ("C-W" "G11 Reg CF & Reg A" xml L1 nil 17 nil)
    ("CB" "G8 Proxy & M&A" html L1 nil 46 nil)
    ("CT ORDER" "G10 Investment-company registration" pdf L1 nil 11 nil)
    ("DEF 14A" "G8 Proxy & M&A" html L2 nil 2694 nil)
    ("DEF 14C" "G8 Proxy & M&A" html L2 nil 89 nil)
    ("DEFA14A" "G8 Proxy & M&A" html L1 nil 3042 nil)
    ("DEFA14C" "G8 Proxy & M&A" html L1 nil 1 nil)
    ("DEFC14A" "G8 Proxy & M&A" html L1 nil 52 nil)
    ("DEFM14A" "G8 Proxy & M&A" html L2 nil 67 nil)
    ("DEFM14C" "G8 Proxy & M&A" html L1 nil 4 nil)
    ("DEFR14A" "G8 Proxy & M&A" html L1 nil 47 nil)
    ("DEFR14C" "G8 Proxy & M&A" html L1 nil 2 nil)
    ("DEL AM" "G10 Investment-company registration" html L1 nil 16 nil)
    ("DFAN14A" "G8 Proxy & M&A" html L1 nil 338 nil)
    ("DFRN14A" "G8 Proxy & M&A" html L1 nil 10 nil)
    ("DOS" "G7 Prospectuses & registration" xml L1 nil 7 nil)
    ("DOSLTR" "G7 Prospectuses & registration" text L1 nil 1 nil)
    ("DRS" "G7 Prospectuses & registration" html L2 nil 343 nil)
    ("DRSLTR" "G7 Prospectuses & registration" html L1 nil 4 nil)
    ("EFFECT" "G7 Prospectuses & registration" xml L1 nil 1165 nil)
    ("F-1" "G7 Prospectuses & registration" html L1 nil 215 nil)
    ("F-10" "G7 Prospectuses & registration" html L1 nil 14 nil)
    ("F-10EF" "G7 Prospectuses & registration" html L1 nil 1 nil)
    ("F-10POS" "G7 Prospectuses & registration" html L1 nil 30 nil)
    ("F-1MEF" "G7 Prospectuses & registration" html L1 nil 3 nil)
    ("F-3" "G7 Prospectuses & registration" html L1 nil 109 nil)
    ("F-3ASR" "G7 Prospectuses & registration" html L1 nil 25 nil)
    ("F-3MEF" "G7 Prospectuses & registration" html L1 nil 1 nil)
    ("F-4" "G7 Prospectuses & registration" html L2 (named-headings) 61 nil)
    ("F-6" "G7 Prospectuses & registration" html L1 nil 44 nil)
    ("F-6 POS" "G7 Prospectuses & registration" html L1 nil 100 nil)
    ("F-6EF" "G7 Prospectuses & registration" html L1 nil 246 nil)
    ("F-N" "G7 Prospectuses & registration" html L1 nil 1 nil)
    ("F-X" "G7 Prospectuses & registration" html L1 nil 54 nil)
    ("FWP" "G7 Prospectuses & registration" html L1 nil 6481 nil)
    ("MSD" "G10 Investment-company registration" text L1 nil 2 nil)
    ("N-14" "G10 Investment-company registration" html L1 nil 30 nil)
    ("N-14 8C" "G10 Investment-company registration" html L1 nil 15 nil)
    ("N-1A" "G10 Investment-company registration" html L2 (investment-objective fees-and-expenses principal-risks) 13 nil)
    ("N-2" "G10 Investment-company registration" html L1 nil 149 nil)
    ("N-2 POSASR" "G10 Investment-company registration" html L1 nil 1 nil)
    ("N-2ASR" "G10 Investment-company registration" html L1 nil 9 nil)
    ("N-2MEF" "G10 Investment-company registration" html L1 nil 1 nil)
    ("N-4" "G10 Investment-company registration" html L1 nil 15 nil)
    ("N-6" "G10 Investment-company registration" html L1 nil 5 nil)
    ("POS AM" "G7 Prospectuses & registration" html L1 nil 308 nil)
    ("POS AMI" "G7 Prospectuses & registration" html L1 nil 50 nil)
    ("POS EX" "G7 Prospectuses & registration" html L1 nil 135 nil)
    ("POSASR" "G7 Prospectuses & registration" html L1 nil 47 nil)
    ("PRE 14A" "G8 Proxy & M&A" html L1 nil 480 nil)
    ("PRE 14C" "G8 Proxy & M&A" html L1 nil 63 nil)
    ("PREC14A" "G8 Proxy & M&A" html L1 nil 43 nil)
    ("PREM14A" "G8 Proxy & M&A" html L1 nil 39 nil)
    ("PREM14C" "G8 Proxy & M&A" html L1 nil 3 nil)
    ("PREN14A" "G8 Proxy & M&A" html L1 nil 2 nil)
    ("PRER14A" "G8 Proxy & M&A" html L1 nil 44 nil)
    ("PRER14C" "G8 Proxy & M&A" html L1 nil 3 nil)
    ("PRRN14A" "G8 Proxy & M&A" html L1 nil 26 nil)
    ("PX14A6G" "G8 Proxy & M&A" html L1 nil 92 nil)
    ("QUALIF" "G11 Reg CF & Reg A" xml L1 nil 53 nil)
    ("RW" "G7 Prospectuses & registration" html L1 nil 95 nil)
    ("S-1" "G7 Prospectuses & registration" html L2 (prospectus-summary part-ii-items) 718 nil)
    ("S-11" "G7 Prospectuses & registration" html L1 nil 14 nil)
    ("S-1MEF" "G7 Prospectuses & registration" html L1 nil 36 nil)
    ("S-3" "G7 Prospectuses & registration" html L2 (generic-named-sections) 308 nil)
    ("S-3ASR" "G7 Prospectuses & registration" html L1 nil 357 nil)
    ("S-3D" "G7 Prospectuses & registration" html L1 nil 1 nil)
    ("S-3DPOS" "G7 Prospectuses & registration" html L1 nil 5 nil)
    ("S-3MEF" "G7 Prospectuses & registration" html L1 nil 4 nil)
    ("S-4" "G7 Prospectuses & registration" html L1 nil 227 nil)
    ("S-6" "G10 Investment-company registration" html L1 nil 333 nil)
    ("S-8" "G7 Prospectuses & registration" html L1 nil 850 nil)
    ("S-8 POS" "G7 Prospectuses & registration" html L1 nil 607 nil)
    ("S-B" "G7 Prospectuses & registration" html L1 nil 10 nil)
    ("SC 14D9" "G8 Proxy & M&A" html L2 nil 64 nil)
    ("SC 14N" "G8 Proxy & M&A" html L1 nil 2 nil)
    ("SC TO-C" "G8 Proxy & M&A" html L2 nil 50 nil)
    ("SC TO-I" "G8 Proxy & M&A" html L2 nil 336 nil)
    ("SC TO-T" "G8 Proxy & M&A" html L2 nil 140 nil)
    ("SC14D1F" "G8 Proxy & M&A" html L1 nil 8 nil)
    ("SC14D9C" "G8 Proxy & M&A" html L1 nil 28 nil)
    ("SF-1" "G7 Prospectuses & registration" html L1 nil 4 nil)
    ("SF-3" "G7 Prospectuses & registration" html L1 nil 5 nil)
    ("SUPPL" "G7 Prospectuses & registration" html L1 nil 33 nil))
  "Registry rows for one group of form families.")

(provide 'edgar-forms-registration)

;;; edgar-forms-registration.el ends here
