(:form "10-K" :text-bucket 19 :text-head
       "ablp-20251231 Table of Contents UNITED STATES SECURITIES AND"
       :sections
       (("I.1" 15 "Item 1. Business The words “we” and “our” in this ")
	("I.1A" 15
	 "Item 1A. Risk Factors Please consider this section")
	("I.1B" 6 "Item 1B. Unresolved Staff Comments Neither AB nor ")
	("I.1C" 12
	 "Item 1C. Cybersecurity Cyber Risk Management and S")
	("I.2" 10 "Item 2. Properties Our headquarters is located at ")
	("I.3" 10 "Item 3. Legal Proceedings Legal Proceedings For si")
	("I.4" 7 "Item 4. Mine Safety Disclosures Not applicable. 20")
	("II.5" 12
	 "Item 5. Market for Registrant’s Common Equity, Rel")
	("II.6" 4 "Item 6. [Reserved] 28")
	("II.7" 16
	 "Item 7. Management’s Discussion and Analysis of Fi")
	("II.7A" 11
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 17
	 "Item 8. Financial Statements and Supplementary Dat")
	("II.9" 7 "Item 9. Changes in and Disagreements with Accounta")
	("II.9A" 12
	 "Item 9A. Controls and Procedures Disclosure Contro")
	("II.9B" 9
	 "Item 9B. Other Information Both AB and AB Holding ")
	("II.9C" 7
	 "Item 9C. Disclosure Regarding Foreign Jurisdiction")
	("III.10" 15
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 16
	 "Item 11. Executive Compensation Compensation Discu")
	("III.12" 13
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 12
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 10
	 "Item 14. Principal Accounting Fees and Services Fe")
	("IV.15" 13
	 "Item 15. Exhibits, Financial Statement Schedules (")
	("IV.16" 11
	 "Item 16. Form 10-K Summary 157 Signatures 158 2025")))
