(:form "10-K" :text-bucket 17 :text-head
       "ablp-20251231 Table of Contents UNITED STATES SECURITIES AND"
       :sections
       (("I.1" 15 "Item 1. Business The words “we” and “our” in this ")
	("I.1A" 15
	 "Item 1A. Risk Factors Please consider this section")
	("I.1B" 6 "Item 1B. Unresolved Staff Comments Neither AB nor ")
	("I.1C" 12
	 "Item 1C. Cybersecurity Cyber Risk Management and S")
	("I.2" 10 "Item 2. Properties Our headquarters is located at ")
	("I.3" 10 "Item 3. Legal Proceedings Legal Proceedings For si")
	("I.4" 7 "Item 4. Mine Safety Disclosures Not applicable. 20")
	("II.5" 12
	 "Item 5. Market for Registrant’s Common Equity, Rel")
	("II.6" 4 "Item 6. [Reserved] 28")
	("II.7" 16
	 "Item 7. Management’s Discussion and Analysis of Fi")
	("II.7A" 6
	 "Item 7A. Quantitative and Qualitative 54 Disclosur")
	("II.8" 5 "Item 8. Financial Statements and 55 Supplementary ")
	("II.9" 6 "Item 9. Changes in and Disagreements with 106 Acco")
	("II.9A" 5 "Item 9A. Controls and Procedures 106")
	("II.9B" 5 "Item 9B. Other Information 107")
	("II.9C" 6
	 "Item 9C. Disclosure Regarding Foreign 107 Jurisdic")
	("III.10" 6
	 "Item 10. Directors, Executive Officers and 108 Cor")
	("III.11" 5 "Item 11. Executive Compensation 122")
	("III.12" 6
	 "Item 12. Security Ownership of Certain 149 Benefic")
	("III.13" 6
	 "Item 13. Certain Relationships and Related 153 Tra")
	("III.14" 5
	 "Item 14. Principal Accounting Fees and 154 Service")
	("IV.15" 5
	 "Item 15. Exhibits, Financial Statement 155 Schedul")
	("IV.16" 11
	 "Item 16. Form 10-K Summary 157 Signatures 158 2025")))
