(:form "10-K" :text-bucket 17 :text-head
       "aapl-20250927 UNITED STATES SECURITIES AND EXCHANGE COMMISSI"
       :sections
       (("I.1" 14 "Item 1. Business Company Background The Company de")
	("I.1A" 16
	 "Item 1A. Risk Factors The following summarizes fac")
	("I.1B" 5 "Item 1B. Unresolved Staff Comments None.")
	("I.1C" 11
	 "Item 1C. Cybersecurity The Company’s management, l")
	("I.2" 9 "Item 2. Properties The Company’s headquarters is l")
	("I.3" 12 "Item 3. Legal Proceedings Digital Markets Act Inve")
	("I.4" 7 "Item 4. Mine Safety Disclosures Not applicable. Ap")
	("II.5" 11
	 "Item 5. Market for Registrant’s Common Equity, Rel")
	("II.6" 7 "Item 6. [Reserved] Apple Inc. | 2025 Form 10-K | 2")
	("II.7" 14
	 "Item 7. Management’s Discussion and Analysis of Fi")
	("II.7A" 11
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 16
	 "Item 8. Financial Statements and Supplementary Dat")
	("II.9" 6 "Item 9. Changes in and Disagreements with 52 Accou")
	("II.9A" 12
	 "Item 9A. Controls and Procedures Evaluation of Dis")
	("II.9B" 9
	 "Item 9B. Other Information On October 31, 2025, th")
	("II.9C" 6
	 "Item 9C. Disclosure Regarding Foreign Jurisdiction")
	("III.10" 8
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 7
	 "Item 11. Executive Compensation The information re")
	("III.12" 7
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 7
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 8
	 "Item 14. Principal Accountant Fees and Services Th")
	("IV.15" 13
	 "Item 15. Exhibit and Financial Statement Schedules")
	("IV.16" 11
	 "Item 16. Form 10-K Summary None. Apple Inc. | 2025")))
