(:form "10-K" :text-bucket 18 :text-head
       "10-K 1 d17062d10k.htm FORM 10-K Form 10-K Table of Contents "
       :sections
       (("I.1" 15 "Item 1. Business Company Background The Company de")
	("I.1A" 15
	 "Item 1A. Risk Factors The following discussion of ")
	("I.1B" 5 "Item 1B. Unresolved Staff Comments 18")
	("I.2" 10
	 "Item 2. Properties The Companys headquarters are ")
	("I.3" 11 "Item 3. Legal Proceedings The Company is subject t")
	("I.4" 7 "Item 4. Mine Safety Disclosures Not applicable. Ap")
	("II.5" 12
	 "Item 5. Market for Registrants Common Equity, Rel")
	("II.6" 11
	 "Item 6. Selected Financial Data The information se")
	("II.7" 16
	 "Item 7. Managements Discussion and Analysis of Fi")
	("II.7A" 12
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 17
	 "Item 8. Financial Statements and Supplementary Dat")
	("II.9" 7 "Item 9. Changes in and Disagreements With Accounta")
	("II.9A" 12
	 "Item 9A. Controls and Procedures Evaluation of Dis")
	("II.9B" 7
	 "Item 9B. Other Information Not applicable. Apple I")
	("III.10" 10
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 9
	 "Item 11. Executive Compensation The information re")
	("III.12" 8
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 9
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 9
	 "Item 14. Principal Accounting Fees and Services Th")
	("IV.15" 13
	 "Item 15. Exhibits, Financial Statement Schedules (")))
