(:form "10-Q" :text-bucket 17 :text-head
       "Form 10-Q Table of Contents UNITED STATES SECURITIES AND EXC"
       :sections
       (("I.1" 15 "ITEM 1. Financial Statements GAMESTOP CORP. CONDEN")
	("I.2" 15
	 "ITEM 2. Managements Discussion and Analysis of Fi")
	("I.3" 11 "ITEM 3. Quantitative and Qualitative Disclosures A")
	("I.4" 10 "ITEM 4. Controls and Procedures (a) Evaluation of ")
	("II.1" 9 "ITEM 1. Legal Proceedings In the ordinary course o")
	("II.1A" 10
	 "ITEM 1A. Risk Factors In addition to the other inf")
	("II.2" 10
	 "ITEM 2. Unregistered Sales of Equity Securities an")
	("II.6" 12
	 "ITEM 6. Exhibits Exhibits Exhibit Description Numb")))
