(:form "253G2" :text-bucket 17 :text-head
       "Document Filed Pursuant to Rule 253(g)(2) File No. 024-12688"
       :sections
       (("I.1" 16 "Item 1. Condensed Consolidated Financial Statement")
	("I.2" 12 "Item 2. Management's Discussion and Analysis of Fi")
	("I.3" 7 "Item 3. Quantitative and Qualitative Disclosures A")
	("I.4" 10 "Item 4. Controls and Procedures Evaluation of Disc")
	("II.1" 9 "Item 1. Legal Proceedings From time to time, we ma")
	("II.1A" 9
	 "Item 1A. Risk Factors An investment in shares of o")
	("II.2" 10
	 "Item 2. Unregistered Sales of Equity Securities an")
	("II.4" 5 "Item 4. Mine Safety Disclosures Not applicable.")
	("II.5" 8 "Item 5. Other Information (a) None. (b) None. (c) ")
	("II.6" 11
	 "Item 6. Exhibits Incorporated by Reference Exhibit")))
