(:form "40-17G" :text-bucket 17 :text-head
       "40-17G 1 d56800d4017g.htm 1290 FUNDS 40-17G 1290 Funds 40-17"
       :sections
       (("1" 8 "Item 1. Name of Insured (the “Insured”) Bond Numbe")
	("2" 7 "Item 2. Bond Period: from 12:01 a.m. on   April 27")
	("3" 10 "Item 3. Limit of Liability—   Subject to Sections ")
	("4" 8 "Item 4. Offices or Premises Covered--All the Insur")
	("5" 16 "Item 5. The liability of ICI Mutual Insurance Comp")))
