(:form "485APOS" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on June"
       :sections
       (("28" 14 "ITEM 28. Exhibits (a)(1) Agreement and Declaration")
	("29" 7 "ITEM 29. Persons Controlled by or Under Common Con")
	("30" 11 "ITEM 30. Indemnification As permitted by Section 1")
	("31" 9 "ITEM 31. Business and Other Connections of the Inv")
	("32" 9 "ITEM 32. Principal Underwriter (a) The principal u")
	("33" 10 "ITEM 33. Location of Accounts and Records The acco")
	("34" 7 "ITEM 34. Management Services There are no manageme")
	("35" 10 "ITEM 35. Undertakings Not applicable. SIGNATURES P")))
