(:form "485BPOS" :text-bucket 19 :text-head
       "AS FILED WITH THE U.S. SECURITIES AND EXCHANGE COMMISSION ON"
       :sections
       (("28" 14 "Item 28. Exhibits (a) (1) Certificate of Trust of ")
	("29" 8 "Item 29. Persons Controlled by or under Common Con")
	("30" 12 "Item 30. Indemnification Article IX of the Registr")
	("31" 12 "Item 31. Business and other Connections of the Inv")
	("32" 13 "Item 32. Foreside Fund Services, LLC Item 32(a) Fo")
	("33" 10 "Item 33. Location of Accounts and Records: Books o")
	("34" 5 "Item 34. Management Services Not Applicable.")
	("35" 11 "Item 35. Undertakings Not Applicable. C-14 SIGNATU")))
