(:form "486APOS" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on Apri"
       :sections
       (("25" 11 "Item 25. Financial Statements and Exhibits (1) Fin")
	("26" 5 "Item 26. Marketing Arrangements Not applicable.")
	("27" 6 "Item 27. Other Expenses of Issuance and Distributi")
	("28" 8 "Item 28. Persons Controlled by or Under Common Con")
	("29" 7 "Item 29. Number of Holders of Securities Number of")
	("30" 11 "Item 30. Indemnification Reference is made to Arti")
	("31" 9 "Item 31. Business and Other Connections of Investm")
	("32" 9 "Item 32. Location of Accounts and Records Ultimus ")
	("33" 5 "Item 33. Management Services Not Applicable.")
	("34" 12 "Item 34. Undertakings 1. Not Applicable. 2. Not Ap")))
