(:form "486BPOS" :text-bucket 19 :text-head
       "As filed with the Securities and Exchange Commission on July"
       :sections
       (("25" 11 "Item 25. Financial Statements and Exhibits (1) Fin")
	("26" 7 "Item 26. Marketing Arrangements See the Distributi")
	("27" 6 "Item 27. Other Expenses of Issuance and Distributi")
	("28" 10 "Item 28. Persons Controlled by or Under Common Con")
	("29" 8 "Item 29. Number of Holders of Securities As of Jun")
	("30" 10 "Item 30. Indemnification Reference is made to Arti")
	("31" 9 "Item 31. Business and Other Connections of Investm")
	("32" 9 "Item 32. Location of Accounts and Records All acco")
	("33" 5 "Item 33. Management Services Not applicable.")
	("34" 13 "Item 34. Undertakings 1. Not applicable. 2. Not ap")))
