(:form "486BXT" :text-bucket 14 :text-head
       "486BXT 1 ea0299591-01_486bxt.htm 486BXT As filed with the Se"
       :sections
       (("25" 12 "Item 25. Financial Statements and Exhibits (1) Fin")
	("26" 7 "Item 26. Marketing Arrangements The information co")
	("27" 6 "Item 27. Other Expenses of Issuance or Distributio")
	("28" 8 "Item 28. Persons Controlled by or Under Common Con")
	("29" 8 "Item 29. Number of Holders of Securities As of [ ]")
	("30" 10 "Item 30. Indemnification Reference is made to Arti")
	("31" 8 "Item 31. Business and Other Connections of Investm")
	("32" 8 "Item 32. Location of Accounts and Records The book")
	("33" 5 "Item 33. Management Services Not applicable.")
	("34" 13 "Item 34. Undertakings 1. The Registrant undertakes")))
