(:form "8-K12B" :text-bucket 13 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington,"
       :sections
       (("1.01" 8 "Item 1.01 Entry into a Material Definitive Agreeme")
	("3.01" 8 "Item 3.01 Notice of Delisting or Failure to Satisf")
	("3.02" 7 "Item 3.02 Unregistered Sales of Equity Securities.")
	("3.03" 7 "Item 3.03 Material Modification to Rights of Secur")
	("5.01" 7 "Item 5.01 Changes in Control of Registrant. The in")
	("5.02" 12
	 "Item 5.02 Departure of Directors or Certain Office")
	("5.03" 9 "Item 5.03 Amendments to Articles of Incorporation ")
	("5.05" 9 "Item 5.05 Amendments to the Registrant’s Code of E")
	("8.01" 10
	 "Item 8.01 Other Events. Press Release On June 16, ")
	("9.01" 10
	 "Item 9.01. Financial Statements and Exhibits. (d) ")))
