(:form "8-K" :text-bucket 14 :text-head
       "mdxg-20260729 UNITED STATES SECURITIES AND EXCHANGE COMMISSI"
       :sections
       (("1.01" 13
	 "Item 1.01 Entry into a Material Definitive Agreeme")
	("7" 13 "Item 7.01 by reference. The information in Item 7.")
	("7.01" 8 "Item 7.01 Regulation FD Disclosure. On July 29, 20")
	("9.01" 10
	 "Item 9.01 Financial Statements and Exhibits. (d) E")))
