(:form "ATS-N/OFA" :text-length 75484 :text-sha256
       "4715ab0b908a609894c05b671cfb19519730502ba14a5c1e4d2545fcaeb19e59"
       :text-head
       "ATS-N/OFA0000753835-26-000009LIVE0000753835XXXXXXXX013-00187falsefalseBNPP Cortex ATSWe are now subj"
       :structure
       (("headerdata" ("submissiontype" "accessionnumber" "filerinfo"))
	("formdata" ("cover" "partone" "parttwo" "partthree"))))
