(:form "ATS-N/UA" :text-length 109574 :text-sha256
       "045fecdd7d7338efe91a6341553bc60a6f49751230f339b243b9556c1021ac16"
       :text-head
       "ATS-N/UA0000902664-26-002690LIVE0001692652XXXXXXXX013-00156falsefalseOneChronosNThis Updating Amendm"
       :structure
       (("headerdata" ("submissiontype" "accessionnumber" "filerinfo"))
	("formdata" ("cover" "partone" "parttwo" "partthree"))))
