(:form "ATS-N/MA" :text-length 431 :text-sha256
       "0ca07b1d4d6c7656a8481bcddddd6fafbff639bef940db288f2431f4dbcb9963"
       :text-head
       "ATS-N/MAY0001491895-26-0000110001491895XXXXXXXX013-00200OTC LinkThe purpose of this amendment is to "
       :structure
       (("submissiontype" nil) ("rboperatespursuanttoformats" nil)
	("accessionnumber" nil)
	("filercredentials" ("filercik" "filerccc"))
	("filenumber" nil) ("txnmsstockatsname" nil)
	("tastatementaboutamendment" nil) ("livetestflag" nil)
	("flags" ("overrideinternetflag" "confirmingcopyflag"))))
