(:form "CFPORTAL/A" :text-length 1134 :text-sha256
       "c654df3583f98bc76d716743a9414f401b5e4886997dfaffaca5aa1d42fcdb6c"
       :text-head
       "CFPORTAL/A0001803619XXXXXXXXtruefalseAmendment to Direct Owners and Executive Officers and address.F"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("identifyinginformation" "formoforganization" "successions"
	  "controlrelationships" "disclosureanswers"
	  "nonsecuritiesrelatedbusiness" "escrowarrangements"
	  "execution" "schedulea" "scheduleb" "schedulec"))))
