(:form "CFPORTAL-W" :text-length 1600 :text-sha256
       "102048551163266b47cd04db5b52b979f567fa620cdb358476c83b398dddf6d2"
       :text-head
       "CFPORTAL-W0001774391XXXXXXXXtruefalseEquityVest, LLCEquityVestwww.equityvest.org88-076352311315 CRAI"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("identifyinginformation" "formoforganization" "successions"
	  "controlrelationships" "disclosureanswers"
	  "nonsecuritiesrelatedbusiness" "escrowarrangements"
	  "execution" "schedulea" "scheduleb" "schedulec" "scheduled"))))
