(:form "CORRESP" :markers
       ("SEC Comment Letter dated September 30, 2025"
	"The Staff’s comments as reflected in the Comment Letter")
       :document-snapshot
       (:form "CORRESP" :format html :primary-document
	      (:type "CORRESP" :sequence "1" :filename "filename1.htm"
		     :description nil :format html)
	      :text-length 5136 :text-sha256
	      "f6f8d0a77976a07e81a3f6f8c21a3dd220b1e1acdde83dcc26b31980214a8a5e"
	      :paragraph-count 28 :named-section-count 0
	      :named-section-head nil :tag-counts
	      (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 28)
	       ("table" . 5) ("h1" . 0) ("h2" . 0))))
