(:form "10-KT" :text-bucket 16 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington,"
       :sections
       (("1" 4 "Item 1. Business. 3")
	("1A" 4 "Item 1A. Risk Factors. 10")
	("1B" 5 "Item 1B. Unresolved Staff Comments. 10")
	("1C" 4 "Item 1C. Cybersecurity. 10")
	("2" 4 "Item 2 Properties. 10")
	("3" 4 "Item 3. Legal proceedings. 10")
	("4" 6 "Item 4. Mine Safety Disclosures. 10 PART II 11")
	("5" 7 "Item 5. Market for Registrant’s Common Equity, Rel")
	("6" 4 "Item 6. [Reserved]")
	("7" 6 "Item 7. Management’s Discussion and Analysis of Fi")
	("7A" 6 "Item 7A. Quantitative and Qualitative Disclosures ")
	("8" 5 "Item 8. Financial Statements and Supplementary Dat")
	("9" 6 "Item 9. Changes in and Disagreements with Accounta")
	("9A" 5 "Item 9A. Controls and Procedures. 13")
	("9B" 5 "Item 9B. Other Information. 14")
	("9C" 6 "Item 9C. Disclosure Regarding Foreign Jurisdiction")
	("10" 6 "Item 10 Directors, Executive Officers and Corporat")
	("11" 5 "Item 11. Executive Compensation. 18")
	("12" 6 "Item 12. Security Ownership of Certain Beneficial ")
	("13" 6 "Item 13. Certain Relationships and Related Transac")
	("14" 6 "Item 14. Principal Accountant Fees and Services. 2")
	("15" 5 "Item 15. Exhibit and Financial Statement Schedules")
	("16" 6 "Item 16. Form 10-K Summary. 23 Signatures 24 2")
	("I.1" 14 "Item 1. Business Unless otherwise stated or the co")
	("I.1A" 6 "Item 1A. Risk Factors Not required for smaller rep")
	("I.1B" 6 "Item 1B. Unresolved Staff Comments Not required fo")
	("I.1C" 10
	 "Item 1C. Cybersecurity Risk Management and Strateg")
	("I.2" 7 "Item 2. Properties Our principal executive offices")
	("I.3" 9 "Item 3. Legal Proceedings In June of 2025, a lawsu")
	("I.4" 6 "Item 4. Mine Safety Disclosures Not applicable. 10")
	("II.5" 10
	 "Item 5. Market for Registrant’s Common Equity, Rel")
	("II.7" 12
	 "Item 7. Management’s Discussion and Analysis of Fi")
	("II.7A" 7
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 7 "Item 8. Financial Statements and Supplementary Dat")
	("II.9" 11
	 "Item 9. Changes in and Disagreements with Accounta")
	("II.9A" 10
	 "Item 9A. Controls and Procedures The Company is re")
	("II.9B" 8
	 "Item 9B. Other Information. Rule 10b5-1 Trading Ar")
	("II.9C" 6
	 "Item 9C. Disclosure Regarding Foreign Jurisdiction")
	("III.10" 14
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 12
	 "Item 11. Executive Compensation EXECUTIVE COMPENSA")
	("III.12" 11
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 11
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 11
	 "Item 14. Principal Accountant Fees and Services TA")
	("IV.15" 12
	 "Item 15. Exhibits and Financial Statement Schedule")
	("IV.16" 15
	 "Item 16. Form 10-K Summary None. 23 SIGNATURES Pur")))
