(:form "20-F" :text-bucket 19 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION WASHINGTON,"
       :sections
       (("I.1" 6 "ITEM 1. Identity Of Directors, Senior Management A")
	("I.2" 6 "ITEM 2. Offer Statistics And Expected Timetable No")
	("I.3" 17 "ITEM 3. Key Information 3.A. [RESERVED] 3.B. CAPIT")
	("I.4" 16 "ITEM 4. Information On The Company 4.A. HISTORY AN")
	("I.4A" 6 "ITEM 4A. Unresolved Staff Comments Not Applicable.")
	("I.5" 14 "ITEM 5. Operating And Financial Review And Prospec")
	("I.6" 16 "ITEM 6. Directors, Senior Management And Employees")
	("I.7" 12 "ITEM 7. Major Shareholders And Related Party Trans")
	("I.8" 11 "ITEM 8. FINANCIAL INFORMATION 8.A. CONSOLIDATED ST")
	("I.9" 10 "ITEM 9. The Offer And Listing 9.A. OFFER AND LISTI")
	("I.10" 15
	 "ITEM 10. Additional Information 10.A. SHARE CAPITA")
	("I.11" 8 "ITEM 11. Quantitative And Qualitative Disclosure O")
	("I.12" 12
	 "ITEM 12. Description Of Securities Other Than Equi")
	("II.13" 6
	 "ITEM 13. Defaults, Dividend Arrearages and Delinqu")
	("II.14" 6
	 "ITEM 14. Material Modifications To The Rights Of S")
	("II.15" 11
	 "ITEM 15. Controls And Procedures A. Disclosure Con")
	("II.16" 4 "ITEM 16. [reserved]")
	("II.16A" 8
	 "ITEM 16A. Audit Committee Financial Expert Our boa")
	("II.16B" 9
	 "ITEM 16B. Code Of Ethics We have adopted a Code of")
	("II.16C" 13
	 "ITEM 16C. Principal Accountant Fees And Services F")
	("III.17" 6
	 "ITEM 17. Financial Statements The Registrant has r")
	("III.18" 8
	 "ITEM 18. Financial Statements See the financial st")
	("III.19" 16
	 "ITEM 19. Exhibits Exhibit No. Description 1.1 Stea")))
