(:form "20-F" :text-bucket 19 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION WASHINGTON,"
       :sections
       (("I.1" 6 "Item 1. Identity of Directors, Senior Management a")
	("I.2" 6 "Item 2. Offer Statistics and Expected Timetable No")
	("I.3" 17 "Item 3. Key Information A. [Reserved] B. Capitaliz")
	("I.4" 15 "Item 4. Information on the Company A. History and ")
	("I.5" 15 "Item 5. Operating and Financial Review and Prospec")
	("I.6" 15 "Item 6. Directors, Senior Management and Employees")
	("I.7" 13 "Item 7. Major Shareholders and Related Party Trans")
	("I.8" 11 "Item 8. Financial Information A. Consolidated Stat")
	("I.9" 8 "Item 9. The Offer and Listing A. Offering and List")
	("I.10" 15
	 "Item 10. Additional Information A. Share Capital D")
	("I.11" 11
	 "Item 11. Quantitative and Qualitative Disclosures ")
	("I.12" 6 "Item 12. Description of Securities Other than Equi")
	("II.14" 8
	 "Item 14. Material Modifications to the Rights of S")
	("II.15" 12
	 "Item 15. Controls and Procedures Evaluation of Dis")
	("II.16" 4 "Item 16. [Reserved]")
	("II.16A" 9
	 "Item 16A. Audit Committee Financial Expert Our Boa")
	("II.16B" 9
	 "Item 16B. Code of Ethics We have adopted a Code of")
	("II.16C" 13
	 "Item 16C. Principal Accountant Fees and Services O")
	("III.17" 6
	 "Item 17. Financial Statements We have responded to")
	("III.18" 16
	 "Item 18. Financial Statements INDEX TO CONSOLIDATE")
	("III.19" 12
	 "Item 19. Exhibits Exhibit Description of Documents")))
