(:form "N-1A" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on Sept"
       :sections
       (("28" 11 "Item 28. Exhibits EXHIBIT (a)(1) — Certificate of ")
	("29" 6 "Item 29. Person Controlled or Under Common Control")
	("30" 11 "Item 30. Indemnification Reference is made to the ")
	("31" 11 "Item 31. Business and Other Connections of Investm")
	("32" 9 "Item 32. Principal Underwriters (a) Quasar Distrib")
	("33" 6 "Item 33. Location of Accounts and Records Omitted ")
	("34" 5 "Item 34. Management Services Not applicable.")
	("35" 10 "Item 35. Undertakings The Registrant undertakes to")))
