(:form "485BPOS" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on Apri"
       :sections
       (("28" 13 "Item 28. Exhibits (a) (1) Certificate of Trust dat")
	("29" 10 "Item 29. Persons Controlled by or Under Common Con")
	("30" 11 "Item 30. Indemnification Pursuant to the Agreement")
	("31" 10 "Item 31. Business and Other Connections of the Inv")
	("32" 11 "Item 32. Foreside Financial Services, LLC (f/k/a B")
	("33" 9 "Item 33. Location of Accounts and Records The book")
	("34" 5 "Item 34. Management Services Not applicable.")
	("35" 10 "Item 35. Undertakings Not applicable C-7 SIGNATURE")))
