(:form "10-KT" :text-bucket 16 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington,"
       :sections
       (("9" 7 "Item 9. Changes in and Disagreements with Accounta")
	("9C" 6 "ITEM 9C. Disclosure regarding foreign jurisdiction")
	("15" 11 "Item 15. Exhibits, Financial Statement Schedules 2")
	("I.1" 10 "Item 1. Business. General Non-Invasive Monitoring ")
	("I.1A" 13
	 "Item 1A. Risk Factors. Our future operating result")
	("I.1B" 5 "Item 1B. Other Information None")
	("I.1C" 9 "Item 1C. Cybersecurity We are currently a shell co")
	("I.2" 9 "Item 2. Properties. Our principal corporate office")
	("I.4" 6 "Item 4. Mine Safety Disclosures. Not applicable. 7")
	("II.5" 10
	 "Item 5. Market for Registrant’s Common Equity, Rel")
	("II.6" 4 "Item 6. [Reserved].")
	("II.7" 13
	 "Item 7. Management’s Discussion and Analysis of Fi")
	("II.7A" 7
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 14
	 "Item 8. Financial Statements and Supplementary Dat")
	("II.9A" 12
	 "Item 9A. Controls and Procedures. The Company’s ma")
	("II.9B" 8
	 "Item 9B. Other Information. During the five months")
	("II.9C" 6
	 "Item 9C. Disclosure Regarding Foreign Jurisdiction")
	("III.10" 13
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 11
	 "Item 11. Executive Compensation. Summary Compensat")
	("III.12" 11
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 12
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 10
	 "Item 14. Principal Accountant Fees and Services. F")
	("IV.15" 13
	 "Item 15. Exhibits, Financial Statement Schedules (")))
