(:form "485BPOS" :text-bucket 19 :text-head
       "As filed with the Securities and Exchange Commission on Nove"
       :sections
       (("28" 13 "ITEM 28. EXHIBITS (a) (1) Certificate of Trust of ")
	("29" 6 "ITEM 29. PERSONS CONTROLLED BY OR UNDER COMMON CON")
	("30" 10 "ITEM 30. INDEMNIFICATION Reference is made to Arti")
	("31" 10 "ITEM 31. BUSINESS AND OTHER CONNECTIONS OF THE INV")
	("32" 13 "ITEM 32. PRINCIPAL UNDERWRITERS (a) Foreside Fund ")
	("33" 9 "ITEM 33. LOCATION OF ACCOUNTS AND RECORDS Each acc")
	("34" 5 "ITEM 34. MANAGEMENT SERVICES Not applicable.")
	("35" 10 "ITEM 35. UNDERTAKINGS Not applicable. C-13 SIGNATU")))
