(:form "N-1A" :text-bucket 18 :text-head
       "Corgi ETF Trust I: Form N-1A AS FILED WITH THE U.S. SECURITI"
       :sections
       (("28" 11 "Item 28. Exhibits Exhibit No. Description of Exhib")
	("29" 7 "Item 29. Persons Controlled by or Under Common Con")
	("30" 10 "Item 30. Indemnification Reference is made to Arti")
	("31" 9 "Item 31. Business and Other Connections of Investm")
	("32" 9 "Item 32. Principal Underwriter The principal under")
	("33" 9 "Item 33. Location of Accounts and Records The book")
	("34" 5 "Item 34. Management Services Not applicable.")
	("35" 10 "Item 35. Undertakings Not applicable. SIGNATURES P")))
