(:form "10-Q" :text-bucket 16 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington,"
       :sections
       (("I.1" 15 "Item 1. Interim Financial Statements. NEW AMERICA ")
	("I.2" 14 "Item 2. Management’s Discussion and Analysis of Fi")
	("I.3" 8 "Item 3. Quantitative and Qualitative Disclosures A")
	("I.4" 10 "Item 4. Controls and Procedures Evaluation of Disc")
	("II.1A" 8
	 "Item 1A. Risk Factors Investing in our securities ")
	("II.2" 11
	 "Item 2. Unregistered Sales of Equity Securities an")
	("II.5" 5 "Item 5. Other Information None")
	("II.6" 11
	 "Item 6. Exhibits The following exhibits are filed ")))
