(:form "10-K" :text-bucket 13 :text-head
       "Document UNITED STATES SECURITIES AND EXCHANGE COMMISSION Wa"
       :sections
       (("I.1" 4 "Item 1. Business.")
	("I.1A" 4 "Item 1A. Risk Factors.")
	("I.1B" 5 "Item 1B. Unresolved Staff Comments. None.")
	("I.2" 4 "Item 2. Properties.")
	("I.3" 4 "Item 3. Legal Proceedings.")
	("I.4" 10 "Item 4. Mine Safety Disclosures. Not applicable. S")
	("II.5" 6 "Item 5. Market for Registrant's Common Equity, Rel")
	("II.6" 5 "Item 6. Selected Financial Data.")
	("II.7" 6 "Item 7. Management's Discussion and Analysis of Fi")
	("II.7A" 6
	 "Item 7A. Quantitative and Qualitative Disclosures ")
	("II.8" 5 "Item 8. Financial Statements and Supplementary Dat")
	("II.9" 6 "Item 9. Changes in and Disagreements With Accounta")
	("II.9A" 5 "Item 9A. Controls and Procedures")
	("II.9B" 7
	 "Item 9B. Other Information. None. ----------------")
	("III.10" 6
	 "Item 10. Directors, Executive Officers and Corpora")
	("III.11" 5 "Item 11. Executive Compensation.")
	("III.12" 6
	 "Item 12. Security Ownership of Certain Beneficial ")
	("III.13" 6
	 "Item 13. Certain Relationships and Related Transac")
	("III.14" 10
	 "Item 14. Principal Accountant Fees and Services. S")
	("IV.15" 8
	 "Item 15. Exhibits and Financial Statement Schedule")
	("IV.16" 12
	 "Item 16. Form 10-K Summary. None. Supplemental Inf")))
