(:form "F-1" :text-bucket 17 :text-head
       "F-1 1 tm2527757d2_f1.htm F-1 As filed with the United States"
       :sections
       (("II.6" 10
	 "ITEM 6: INDEMNIFICATION OF DIRECTORS AND OFFICERS ")
	("II.7" 13
	 "ITEM 7. RECENT SALES OF UNREGISTERED SECURITIES In")
	("II.8" 13
	 "ITEM 8. EXHIBITS AND FINANCIAL STATEMENT SCHEDULES")
	("II.9" 13
	 "ITEM 9. UNDERTAKINGS The undersigned Registrant he")))
