(:form "F-1" :text-bucket 19 :text-head
       "Registration No. 333- UNITED STATES SECURITIES AND EXCHANGE "
       :sections
       (("II.6" 12
	 "Item 6. Indemnification of Directors and Officers.")
	("II.7" 11
	 "Item 7. Recent Sales of Unregistered Securities. S")
	("II.8" 10
	 "Item 8. Exhibits and Financial Statement Schedules")
	("II.9" 13
	 "Item 9. Undertakings The undersigned registrant he")))
