(:form "F-1" :text-bucket 17 :text-head
       "As filed with the United States Securities and Exchange Comm"
       :sections
       (("II.6" 10
	 "ITEM 6: INDEMNIFICATION OF DIRECTORS AND OFFICERS ")
	("II.7" 13
	 "ITEM 7. RECENT SALES OF UNREGISTERED SECURITIES In")
	("II.8" 13
	 "ITEM 8. EXHIBITS AND FINANCIAL STATEMENT SCHEDULES")
	("II.9" 13
	 "ITEM 9. UNDERTAKINGS The undersigned Registrant he")))
