((:slug "24f-2nt-ab"
  :format xml
  :min-paragraphs 0
  :min-tables 0
  :text-marker "AB CAP FUND, INC."
  :node-name "registrationfeedue"
  :node-marker "0.00")
 (:slug "40-17g-1290"
  :format html
  :min-paragraphs 500
  :min-tables 100
  :text-marker "1290 Funds 40-17G")
 (:slug "485apos-360"
  :format html
  :min-paragraphs 1000
  :min-tables 100
  :text-marker "POST-EFFECTIVE AMENDMENT"
  :section "28"
  :body-marker "Exhibits")
 (:slug "485bxt-ark"
  :format html
  :min-paragraphs 40
  :min-tables 5
  :text-marker "FORM N-1A")
 (:slug "497vpi-allianz"
  :format html
  :min-paragraphs 0
  :min-tables 5
  :text-marker "Income Benefit Supplement dated May 1, 2026")
 (:slug "497vpu-allianz-ny"
  :format html
  :min-paragraphs 0
  :min-tables 8
  :text-marker "Updating Summary Prospectus")
 (:slug "s-6-ft12946"
  :format html
  :min-paragraphs 80
  :min-tables 20
  :text-marker "For Registration Under the Securities Act of 1933"))
