((:slug "nrsro-ce-2026-q2" :submission-snapshot
	(:form "NRSRO-CE/A" :format pdf :primary-document
	       (:type "NRSRO-CE/A" :sequence "1" :filename
		      "d928396dnrsrocea.pdf" :description "NRSRO-CE/A"
		      :format pdf-uuencoded)
	       :text-length 30456 :text-sha256
	       "a80f7e2824dccf9945ae3c75126d3559fad70f6a832c02819ae0341962b2352e"
	       :paragraph-count 105 :named-section-count 82
	       :named-section-head
	       ("OMB APPROVAL" "APPLICATION FOR REGISTRATION AS A"
		"RATING ORGANIZATION (NRSRO)")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0)))
	:direct-snapshot
	(:form "NRSRO-CE/A" :format pdf :primary-document
	       (:type "NRSRO-CE/A" :sequence nil :filename
		      "d928396dnrsrocea.pdf" :description nil :format
		      pdf)
	       :text-length 30456 :text-sha256
	       "a80f7e2824dccf9945ae3c75126d3559fad70f6a832c02819ae0341962b2352e"
	       :paragraph-count 105 :named-section-count 82
	       :named-section-head
	       ("OMB APPROVAL" "APPLICATION FOR REGISTRATION AS A"
		"RATING ORGANIZATION (NRSRO)")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0))))
 (:slug "nrsro-upd-2026-q2" :submission-snapshot
	(:form "NRSRO-UPD" :format pdf :primary-document
	       (:type "NRSRO-UPD" :sequence "1" :filename
		      "UpdateJune.pdf" :description nil :format
		      pdf-uuencoded)
	       :text-length 18658 :text-sha256
	       "99e8953e12ea447de663389c6e760741e8c2f6e3051caaf166c90612e426d088"
	       :paragraph-count 85 :named-section-count 12
	       :named-section-head
	       ("OMB APPROVAL" "APPLICATION FOR REGISTRATION AS A"
		"RATING ORGANIZATION (NRSRO)")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0)))
	:direct-snapshot
	(:form "NRSRO-UPD" :format pdf :primary-document
	       (:type "NRSRO-UPD" :sequence nil :filename
		      "UpdateJune.pdf" :description nil :format pdf)
	       :text-length 18658 :text-sha256
	       "99e8953e12ea447de663389c6e760741e8c2f6e3051caaf166c90612e426d088"
	       :paragraph-count 85 :named-section-count 12
	       :named-section-head
	       ("OMB APPROVAL" "APPLICATION FOR REGISTRATION AS A"
		"RATING ORGANIZATION (NRSRO)")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0))))
 (:slug "sec-staff-actio-2026-q2" :submission-snapshot
	(:form "SEC STAFF ACTIO" :format pdf :primary-document
	       (:type "ORDER" :sequence "1" :filename "filename1.pdf"
		      :description nil :format pdf-uuencoded)
	       :text-length 1715 :text-sha256
	       "7004c1e0f0080e76902d31008f9955073e20a9914700776243c3a70dc62ea593"
	       :paragraph-count 5 :named-section-count 3
	       :named-section-head
	       ("UNITED STATES OF AMERICA" "1934, AS AMENDED"
		"Suzanne Hayes")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0)))
	:direct-snapshot
	(:form "SEC STAFF ACTIO" :format pdf :primary-document
	       (:type "SEC STAFF ACTIO" :sequence nil :filename
		      "filename1.pdf" :description nil :format pdf)
	       :text-length 1715 :text-sha256
	       "7004c1e0f0080e76902d31008f9955073e20a9914700776243c3a70dc62ea593"
	       :paragraph-count 5 :named-section-count 3
	       :named-section-head
	       ("UNITED STATES OF AMERICA" "1934, AS AMENDED"
		"Suzanne Hayes")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0))))
 (:slug "sec-staff-lette-2026-q2" :submission-snapshot
	(:form "SEC STAFF LETTE" :format pdf :primary-document
	       (:type "SERIOUS DEFICIENCIES" :sequence "1" :filename
		      "filename1.pdf" :description nil :format
		      pdf-uuencoded)
	       :text-length 1549 :text-sha256
	       "92db73f105469fed86980e778276bf0ba7daeb058fe8b39baf43314122952122"
	       :paragraph-count 6 :named-section-count 4
	       :named-section-head
	       ("Ngai Seak Hong" "Re: MAO SHAN HUANG HOLDINGS LIMITED"
		"Sincerely,")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0)))
	:direct-snapshot
	(:form "SEC STAFF LETTE" :format pdf :primary-document
	       (:type "SEC STAFF LETTE" :sequence nil :filename
		      "filename1.pdf" :description nil :format pdf)
	       :text-length 1549 :text-sha256
	       "92db73f105469fed86980e778276bf0ba7daeb058fe8b39baf43314122952122"
	       :paragraph-count 6 :named-section-count 4
	       :named-section-head
	       ("Ngai Seak Hong" "Re: MAO SHAN HUANG HOLDINGS LIMITED"
		"Sincerely,")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0)))))
