(:form "SF-3" :text-bucket 19 :text-head
       "SF-3 Table of Contents As filed with the Securities and Exch"
       :sections
       (("II.12" 10
	 "Item 12. Other Expenses of Issuance and Distributi")
	("II.13" 12
	 "Item 13. Indemnification of Directors and Officers")
	("II.14" 12
	 "Item 14. Exhibits. Exhibit Description Number 1.1 ")
	("II.15" 13
	 "Item 15. Undertakings. (a) Rule 415 Offering: The ")))
