(:form "SF-1" :text-bucket 19 :text-head
       "SF-1 Table of Contents As filed with the Securities and Exch"
       :sections
       (("II.12" 9
	 "Item 12. Other Expenses of Issuance and Distributi")
	("II.13" 12
	 "Item 13. Indemnification of Directors and Officers")
	("II.14" 11
	 "Item 14.   Exhibits List of Exhibits EXHIBIT DESCR")
	("II.15" 13
	 "Item 15. Undertakings (a) The undersigned registra")))
