(:form "S-3D" :text-bucket 16 :text-head
       "S-3D As filed with the Securities and Exchange Commission on"
       :sections
       (("II.14" 9
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 12
	 "Item 15. Indemnification of Directors and Officers")
	("II.16" 9
	 "Item 16. Exhibits. The following is a list of exhi")
	("II.17" 13
	 "Item 17. Undertakings. a. The undersigned registra")))
