(:form "10-12B" :text-bucket 13 :text-head
       "10-12B As filed with the U.S. Securities and Exchange Commis"
       :sections
       (("1" 9 "Item 1. Business. The information required by this")
	("1A" 8 "Item 1A. Risk Factors. The information required by")
	("2" 9 "Item 2. Financial Information. The information req")
	("3" 7 "Item 3. Properties. The information required by th")
	("4" 8 "Item 4. Security Ownership of Certain Beneficial O")
	("5" 7 "Item 5. Directors and Executive Officers. The info")
	("6" 8 "Item 6. Executive Compensation. The information re")
	("7" 8 "Item 7. Certain Relationships and Related Transact")
	("8" 8 "Item 8. Legal Proceedings. The information require")
	("9" 8 "Item 9. Market Price of, and Dividends on, the Reg")
	("10" 7 "Item 10. Recent Sales of Unregistered Securities. ")
	("11" 8 "Item 11. Description of Registrant’s Securities to")
	("12" 7 "Item 12. Indemnification of Directors and Officers")
	("13" 8 "Item 13. Financial Statements and Supplementary Da")
	("14" 7 "Item 14. Changes in and Disagreements with Account")
	("15" 11 "Item 15. Financial Statements and Exhibits. (a)Fin")))
