(:form "10-12G" :text-bucket 16 :text-head
       "As filed with the U.S. Securities and Exchange Commission on"
       :sections
       (("1" 14 "Item 1. Business. Margaree Acquisition Corp. was i")
	("1A" 7 "Item 1A. Risk Factors. As a “smaller reporting com")
	("2" 13 "Item 2. Financial Information. Management’s Discus")
	("3" 8 "Item 3. Properties. The Company neither rents nor ")
	("4" 9 "Item 4. Security Ownership of Certain Beneficial O")
	("5" 12 "Item 5. Directors and Executive Officers. (a) Iden")
	("6" 11 "Item 6. Executive Compensation. The following tabl")
	("7" 14 "Item 7. Certain Relationships and Related Transact")
	("8" 8 "Item 8. Legal Proceedings. There are presently no ")
	("9" 10 "Item 9. Market Price of and Dividends on the Regis")
	("10" 10 "Item 10. Recent Sales of Unregistered Securities. ")
	("11" 11 "Item 11. Description of Registrant’s Securities to")
	("12" 11 "Item 12. Indemnification of Directors and Officers")
	("13" 8 "Item 13. Financial Statements and Supplementary Da")
	("14" 8 "Item 14. Changes in and Disagreements with Account")
	("15" 14 "Item 15. Financial Statements and Exhibits. (a) Fi")))
