(:form "POS AM" :text-bucket 15 :text-head
       "tm2612724-1_posam - none - 3.5781428s TABLE OF CONTENTS As f"
       :sections
       (("II.14" 10
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 12
	 "Item 15. Indemnification of Directors and Officers")
	("II.16" 10 "Item 16. Exhibits Exhibit ​ ​ ​ ​ ​ Incorporation ")
	("II.17" 13
	 "Item 17. Undertakings (a) The undersigned registra")))
