(:form "S-11" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on June"
       :sections
       (("II.31" 9
	 "Item 31. Other Expenses of Issuance and Distributi")
	("II.32" 5
	 "Item 32. Sales to Special Parties. Not applicable.")
	("II.33" 12
	 "Item 33. Recent Sales of Unregistered Securities. ")
	("II.34" 12
	 "Item 34. Indemnification of Directors and Officers")
	("II.35" 6
	 "Item 35. Treatment of Proceeds from Stock Being Re")
	("II.36" 8
	 "Item 36. Financial Statements and Exhibits. (a) Fi")
	("II.37" 14
	 "Item 37. Undertakings. (i) The undersigned registr")))
