(:form "POS EX" :text-bucket 15 :text-head
       "govx20260417d_posex.htm As filed with the Securities and Exc"
       :sections
       (("II.13" 8
	 "Item 13. Other Expenses of Issuance and Distributi")
	("II.14" 12
	 "Item 14. Indemnification of Directors and Officers")
	("II.15" 10
	 "Item 15. Recent Sales of Unregistered Securities. ")
	("II.16" 13
	 "Item 16. Exhibits and Financial Statement Schedule")
	("II.17" 13
	 "Item 17. Undertakings (a) The undersigned Registra")))
