(:form "20FR12B" :text-bucket 19 :text-head
       "20FR12B Table of Contents As filed with the Securities and E"
       :sections
       (("I.1" 11 "Item 1. Identity of Directors, Senior Management a")
	("I.2" 7 "Item 2. Offer Statistics and Expected Timetable No")
	("I.3" 17 "Item 3. Key Information A. [Reserved] B. Capitaliz")
	("I.4" 16 "Item 4. Information on the Company A. History and ")
	("I.4A" 5 "Item 4A. Unresolved Staff Comments Not applicable.")
	("I.5" 16 "Item 5. Operating and Financial Review and Prospec")
	("I.6" 15 "Item 6. Directors, Senior Management and Employees")
	("I.7" 13 "Item 7. Major Shareholders and Related Party Trans")
	("I.8" 10 "Item 8. Financial Information A. Consolidated Stat")
	("I.9" 9 "Item 9. The Offer and Listing A. Offer and Listing")
	("I.10" 16
	 "Item 10. Additional Information A. Share Capital A")
	("I.11" 7 "Item 11. Quantitative and Qualitative Disclosures ")
	("I.12" 8 "Item 12. Description of Securities Other than Equi")
	("II.13" 6
	 "Item 13. Defaults, Dividend Arrearages and Delinqu")
	("II.14" 6
	 "Item 14. Material Modifications to the Rights of S")
	("II.15" 5 "Item 15. Controls and Procedures Not applicable.")
	("II.16" 4 "Item 16. [Reserved]")
	("II.16A" 5
	 "Item 16A. Audit Committee Financial Expert Not app")
	("II.16B" 5 "Item 16B. Code of Ethics Not applicable.")
	("II.16C" 9
	 "Item 16C. Principal Accountant Fees and Services N")
	("III.17" 7
	 "Item 17. Financial Statements We are providing our")
	("III.18" 8
	 "Item 18. Financial Statements See pages F-1 throug")
	("III.19" 17
	 "Item 19. Exhibits The following exhibits are filed")))
