(:form "DSTRBRPT" :text-bucket 16 :text-head
       "DSTRBRPT File No. 83-1 Regulation IA Rule 3 UNITED STATES SE"
       :sections
       (("1" 7 "Item 1. Description of Securities See cover page a")
	("2" 6 "Item 2. Distribution of Securities See pages 54 th")
	("3" 8 "Item 3. Distribution Spread Price to the Public Se")
	("4" 6 "Item 4. Discounts and Commissions to Sub-Underwrit")
	("5" 5 "Item 5. Other Expenses of Distribution Not applica")
	("6" 6 "Item 6. Application of Proceeds See page 5 of the ")
	("7" 16 "Item 7. Exhibits (A) Opinion of the Chief Counsel ")))
