(:form "DRS" :text-bucket 17 :text-head
       "DRS Table of Contents Confidential Treatment Requested by GE"
       :sections
       (("II.13" 9
	 "Item 13. Other Expenses of Issuance and Distributi")
	("II.14" 11
	 "Item 14. Indemnification of Directors and Officers")
	("II.15" 9
	 "Item 15. Recent Sales of Unregistered Securities. ")
	("II.16" 8
	 "Item 16. Exhibits, Financial Statements and Financ")
	("II.17" 14
	 "Item 17. Undertakings. The undersigned registrant ")))
