(:form "15F-12G" :text-bucket 12 :text-head
       "Red Metal Resources Ltd. : Form 15F-12G - Filed by newsfilec"
       :sections
       (("1" 9 "Item 1. Exchange Act Reporting History A. Red Meta")
	("2" 8 "Item 2. Recent United States Market Activity The C")
	("3" 10 "Item 3. Foreign Listing and Primary Trading Market")
	("4" 10 "Item 4. Comparative Trading Volume Data The Compan")
	("5" 6 "Item 5. Alternative Record Holder Information Not ")
	("6" 5 "Item 6. Debt Securities Not applicable.")
	("7" 9 "Item 7. Notice Requirement A. Pursuant to Rule 12h")
	("8" 5 "Item 8. Prior Form 15 Filers Not applicable.")
	("II.9" 8 "Item 9. Rule 12g3-2(b) Exemption All information r")
	("III.10" 6
	 "Item 10. Exhibits Exhibit 99.1 Press Release of Re")
	("III.11" 10
	 "Item 11. Undertakings The undersigned issuer hereb")))
