(:form "F-6 POS" :text-bucket 13 :text-head
       "As filed with the Securities and Exchange Commission on Apri"
       :sections
       (("I.1" 11 "Item 1. DESCRIPTION OF SECURITIES TO BE REGISTERED")
	("I.2" 9 "Item 2. AVAILABLE INFORMATION Quhuo Limited (the “")
	("II.3" 10
	 "Item 3. EXHIBITS (a)(i) Form of Deposit Agreement,")
	("II.4" 12
	 "Item 4. UNDERTAKINGS (a) The Depositary hereby und")))
