(:form "SC14D1F" :text-bucket 12 :text-head
       "As filed with the Securities and Exchange Commission on Augu"
       :sections
       (("I.1" 7 "Item 1. Home Jurisdiction Documents. Offer to Purc")
	("I.2" 7 "Item 2. Informational Legends. See “Notice to Shar")
	("III.1" 10
	 "Item 1. Undertakings. (a) The bidder undertakes to")
	("III.2" 8
	 "Item 2. Consent to Service of Process (a) The bidd")))
