(:form "S-3ASR" :text-bucket 16 :text-head
       "S-3ASR Table of Contents As filed with the Securities and Ex"
       :sections
       (("II.14" 10
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 10
	 "Item 15. Indemnification of Directors and Officers")
	("II.16" 11
	 "Item 16. Exhibits Exhibit Description Number   1.1")
	("II.17" 13
	 "Item 17. Undertakings (a) The undersigned registra")))
