(:form "S-3DPOS" :text-bucket 16 :text-head
       "As filed with the Securities and Exchange Commission on May "
       :sections
       (("II.14" 8
	 "ITEM 14. OTHER EXPENSES OF ISSUANCE AND DISTRIBUTI")
	("II.15" 11
	 "ITEM 15. INDEMNIFICATION OF DIRECTORS AND OFFICERS")
	("II.16" 10
	 "ITEM 16. EXHIBITS. All exhibits filed with or inco")
	("II.17" 12
	 "ITEM 17. UNDERTAKINGS (a) The Registrants hereby u")))
