(:form "F-6" :text-bucket 13 :text-head
       "As filed with the U.S. Securities and Exchange Commission on"
       :sections
       (("I.1" 11 "Item 1. DESCRIPTION OF SECURITIES TO BE REGISTERED")
	("I.2" 9 "Item 2. AVAILABLE INFORMATION Paragraph (8) EasyJe")
	("II.3" 10
	 "Item 3. EXHIBITS (a) Form of Deposit Agreement. Fo")
	("II.4" 12
	 "Item 4. UNDERTAKINGS (a) The Depositary hereby und")))
