(:form "425" :text-bucket 16 :text-head
       "Criteo 425 UNITED STATES SECURITIES AND EXCHANGE COMMISSION "
       :sections
       (("1.02" 8 "ITEM 1.02 Termination of a Material Definitive Agr")
	("3.01" 8 "ITEM 3.01 Notice of Delisting or Failure to Satisf")
	("3.03" 9 "ITEM 3.03 Material Modification to Rights of Secur")
	("5.03" 9 "ITEM 5.03 Amendments to the Articles of Incorporat")
	("8.01" 13
	 "ITEM 8.01 Other Events. The information set forth ")
	("9.01" 16
	 "ITEM 9.01 Financial Statements and Exhibits. (d) E")))
