(:form "15F-12B" :text-bucket 12 :text-head
       "UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington,"
       :sections
       (("I.1" 9 "Item 1. Exchange Act Reporting History A. Westpac ")
	("I.2" 8 "Item 2. Recent United States Market Activity A. Th")
	("I.3" 6 "Item 3. Foreign Listing and Primary Trading Market")
	("I.4" 5 "Item 4. Comparative Trading Volume Data Not applic")
	("I.5" 6 "Item 5. Alternative Record Holder Information Not ")
	("I.6" 10 "Item 6. Debt Securities The number of record holde")
	("I.7" 8 "Item 7. Notice Requirement A. As required by Rule ")
	("I.8" 5 "Item 8. Prior Form 15 Filers Not applicable.")
	("II.9" 7 "Item 9. Rule 12g3-2(b) Exemption The Company will ")
	("III.10" 6
	 "Item 10. Exhibits Exhibit 99.1 Media Release pursu")
	("III.11" 10
	 "Item 11. Undertakings The undersigned issuer hereb")))
