(:form "MA/A" :text-length 4312 :text-sha256
       "50cac841762b3486c4720fefd20dbd76f9e1fea59331543dfc336f25a2fcca69"
       :text-head
       "MA/A0001620072XXXXXXXXCarol Shortall2156206250cshortall@capmark.orgcshortall@capmark.orgCapital Mark"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("firmname" "irsnum" "registrations" "principalofficeaddress"
	  "additionaloffices" "mailingaddressdifferent"
	  "mailingaddress" "primarywebaddress" "cco" "contactperson"
	  "booksandrecordslocations" "formoforganization"
	  "monthoffiscalyearend" "organizedjurisdiction"
	  "dateoforganization" "isprcapplicant" "numberofemployees"
	  "employeesengagedinmaa" "maaemployeesregbd" "maaregia"
	  "numberofsolicitingfirms" "clientsservedasma"
	  "typesofclients" "numberofsolicitedme" "numberofsolicitedop"
	  "totalnumberofsolicitedmeandop" "typesofsolicitedpersons"
	  "meoropcompensationtypes" "solicitationcompensationtypes"
	  "engagedactivities" "isengagedinothernonmaabusiness"
	  "totalfiaassociatedpersons" "participationinterestmact"
	  "disclosureanswers" "hasannualreceiptslessthan7million"
	  "isaffiliatedwithreceiptsmorethan7million" "schedulea"
	  "schedulec" "drpinfo" "maexecutionpage" "controls"))))
