(:form "MA-W" :text-length 409 :text-sha256
       "13140967429f3dba0bf873d48246b54757b470a548a65d8bc05cd9d2f5a433f4"
       :text-head
       "MA-W0001783919XXXXXXXX867-02480Irene Carroll602-684-3184icarroll@Ftgadvisorsllc.comFTG Advisors, LLC"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("fulllegalname" "filenumber" "contactpersoninfo"
	  "isadvisorycontract" "isunsatisfiedjudgementsorliens"
	  "isreceivedanyprepaidfee" "isborrowednotrepaid"
	  "booksandrecords" "execution"))))
