(:form "N-1A" :text-bucket 19 :text-head
       "N-1A 1 ea0271727-01_n1a.htm N-1A As filed with the Securitie"
       :sections
       (("28" 10 "Item 28. Exhibits Exhibit No. Description (a) (1) ")
	("29" 6 "Item 29. Persons Controlled By or Under Common Con")
	("30" 10 "Item 30. Indemnification Under the terms of the De")
	("31" 10 "Item 31. Business and Other Connections of the Inv")
	("32" 13 "Item 32. Principal Underwriter (a) Foreside Fund S")
	("33" 9 "Item 33. Location of Accounts and Records All acco")
	("34" 5 "Item 34. Management Services Not Applicable.")
	("35" 11 "Item 35. Undertakings Not Applicable. C-7 Signatur")))
