(:form "N-2" :text-bucket 18 :text-head
       "As filed with the Securities and Exchange Commission on Marc"
       :sections
       (("25" 9 "ITEM 25. FINANCIAL STATEMENTS AND EXHIBITS (1) Fin")
	("26" 5 "ITEM 26. MARKETING ARRANGEMENTS Not Applicable.")
	("27" 8 "ITEM 27. OTHER EXPENSES OF ISSUANCE AND DISTRIBUTI")
	("28" 8 "ITEM 28. PERSONS CONTROLLED BY OR UNDER COMMON CON")
	("29" 7 "ITEM 29. NUMBER OF HOLDERS OF SECURITIES Set forth")
	("30" 12 "ITEM 30. INDEMNIFICATION Section 2-418 of the Mary")
	("31" 9 "ITEM 31. BUSINESS AND OTHER CONNECTIONS OF ADVISER")
	("32" 9 "ITEM 32. LOCATION OF ACCOUNTS AND RECORDS All acco")
	("33" 5 "ITEM 33. MANAGEMENT SERVICES Not Applicable.")
	("34" 12 "ITEM 34. UNDERTAKINGS (1) We undertake to suspend ")))
