(:form "N-2ASR" :text-bucket 19 :text-head
       "BlackRock Enhanced Large Cap Core Fund - N-2ASR As filed wit"
       :sections
       (("25" 13 "Item 25. Financial Statements And Exhibits The agr")
	("26" 8 "Item 26. Marketing Arrangements The information co")
	("27" 9 "Item 27. Other Expenses Of Issuance And Distributi")
	("28" 6 "Item 28. Persons Controlled By Or Under Common Con")
	("29" 7 "Item 29. Number Of Holders Of Shares As of July 1,")
	("30" 13 "Item 30. Indemnification Reference is made to Sect")
	("31" 9 "Item 31. Business And Other Connections Of Investm")
	("32" 6 "Item 32. Location Of Accounts And Records Omitted ")
	("33" 7 "Item 33. Management Services Not Applicable C-6 --")
	("34" 13 "Item 34. Undertakings (1) Not applicable. (2) Not ")))
