(:form "N-4" :text-bucket 18 :text-head
       "N-4 Table of Contents --------------------------------------"
       :sections
       (("27" 14 "Item 27. Exhibits  (a) (i) Consent in writing in L")
	("28" 10 "Item 28. Directors and Officers of the Depositor T")
	("29" 13 "Item 29. Persons Controlled by or Under Common Con")
	("30" 11 "Item 30. Indemnification The amended and restated ")
	("31" 10 "Item 31. Principal Underwriter (a) RiverSource Dis")
	("32" 5 "Item 32. Location of Accounts and Records Not appl")
	("33" 5 "Item 33. Management Services Not applicable.")
	("34" 12 "Item 34. Fee Representation The RiverSource Life I")))
