(:form "N-6" :text-bucket 18 :text-head
       "EDGAR HTML As filed with the Securities and Exchange Commiss"
       :sections
       (("30" 12 "Item 30. EXHIBITS (a) Resolution of the Board of D")
	("31" 9 "Item 31. Directors and Officers of the Depositor  ")
	("32" 8 "Item 32. Persons Controlled by or Under Common Con")
	("33" 11 "Item 33. Indemnification (a) Brief description of ")
	("34" 11 "Item 34. Principal Underwriter (a) Lincoln Financi")
	("35" 6 "Item 35. Location of Accounts and Records This inf")
	("36" 5 "Item 36. Management Services Not applicable.")
	("37" 11 "Item 37. Fee Representation Lincoln Life represent")))
