(:form "S-1" :text-bucket 17 :text-head
       "As filed with the Securities and Exchange Commission on June"
       :sections
       (("II.13" 9
	 "Item 13. Other Expenses of Issuance and Distributi")
	("II.14" 13
	 "Item 14. Indemnification of Directors and Officers")
	("II.15" 12
	 "Item 15. Recent Sales of Unregistered Securities T")
	("II.16" 7
	 "Item 16. Exhibits and Financial Statement Schedule")
	("II.17" 14
	 "Item 17. Undertakings Insofar as indemnification f")))
