(:form "S-1" :text-bucket 16 :text-head
       "S-1 1 ea0295800-s1_biomx.htm REGISTRATION STATEMENT As filed"
       :sections
       (("9" 12 "Item 9.01 of Form 8-K). These documents contain im")
	("II.13" 9
	 "Item 13. Other Expenses of Issuance and Distributi")
	("II.14" 11
	 "Item 14. Indemnification of Directors and Officers")
	("II.15" 11
	 "Item 15. Recent Sales of Unregistered Securities T")
	("II.16" 13
	 "Item 16. Exhibits and Financial Statement Schedule")
	("II.17" 12
	 "Item 17. Undertakings (a) The undersigned registra")))
