(:form "S-3" :text-bucket 17 :text-head
       "S-3 1 forms-3.htm S-3 As filed with the Securities and Excha"
       :sections
       (("7" 11 "Item 7.01 of Form 8-K and exhibits accompanying su")
	("II.14" 9
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 11
	 "Item 15. Indemnification of Directors and Officers")
	("II.16" 11
	 "Item 16. Exhibits. Exhibit Description of Document")
	("II.17" 13
	 "Item 17. Undertakings (a) The undersigned Registra")))
