(:form "S-3" :text-bucket 16 :text-head
       "amix20260721_s3.htm As filed with the Securities and Exchang"
       :sections
       (("II.14" 9
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 12
	 "Item 15. Indemnification of Officers and Directors")
	("II.16" 10
	 "Item 16. Exhibits Exhibit Description Number 4.1 F")
	("II.17" 13
	 "Item 17. Undertakings The undersigned registrant h")))
