(:form "S-3" :text-bucket 17 :text-head
       "S-3 Table of Contents As filed with the Securities and Excha"
       :sections
       (("II.14" 9
	 "Item 14. Other Expenses of Issuance and Distributi")
	("II.15" 12
	 "Item 15. Indemnification of Directors and Officers")
	("II.16" 10
	 "Item 16. Exhibits. Exhibit Index Exhibit No. Descr")
	("II.17" 13
	 "Item 17. Undertakings. The undersigned Registrant ")))
