(:form "S-8 POS" :text-bucket 14 :text-head
       "S-8 POS As filed with the Securities and Exchange Commission"
       :sections
       (("II.3" 11
	 "Item 3. Incorporation of Documents by Reference. W")
	("II.4" 5 "Item 4. Description of Securities. Not applicable.")
	("II.5" 6 "Item 5. Interests of Named Experts and Counsel. No")
	("II.6" 12
	 "Item 6. Indemnification of Directors and Officers.")
	("II.7" 7 "Item 7. Exemption from Registration Claimed. Not a")
	("II.8" 11
	 "Item 8. Exhibits. Exhibit Number  3.1 Amended and ")
	("II.9" 13
	 "Item 9. Undertakings. (a) The undersigned Registra")))
