(:form "S-8" :text-bucket 14 :text-head
       "Document As filed with the Securities and Exchange Commissio"
       :sections
       (("II.3" 10
	 "Item 3. Incorporation of Documents by Reference. T")
	("II.4" 11
	 "Item 4. Description of Securities. Deferred Compen")
	("II.5" 6 "Item 5. Interests of Named Experts and Counsel. No")
	("II.6" 12
	 "Item 6. Indemnification of Directors and Officers.")
	("II.7" 5 "Item 7. Exemption from Registration Claimed. Not a")
	("II.8" 7 "Item 8. Exhibits. See the Exhibit Index immediatel")
	("II.9" 13
	 "Item 9. Undertakings. (a)The undersigned Registran")))
