((:slug "index-sp-15d2-2026-q2" :document-snapshot
	(:form "SP 15D2" :format html :primary-document
	       (:type "SP 15D2" :sequence "1" :filename
		      "tm2611679d1_sp15d2.htm" :description "SP 15D2"
		      :format html)
	       :text-length 28375 :text-sha256
	       "b123edd2ed997ccd1e1bb2ad08b381611e7ced64b59b2f48be097692032cf4e8"
	       :paragraph-count 285 :named-section-count 0
	       :named-section-head nil :tag-counts
	       (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 285)
		("table" . 14) ("h1" . 0) ("h2" . 0))))
 (:slug "index-annlrpt-2026-q2" :document-snapshot
	(:form "ANNLRPT/A" :format html :primary-document
	       (:type "ANNLRPT/A" :sequence "1" :filename
		      "ef20071379_annlrpta.htm" :description
		      "ANNLRPT/A" :format html)
	       :text-length 370491 :text-sha256
	       "3dcccc89d945b8feaeebd37d13bae615b95faac4346a652d744a424dda6ed43b"
	       :paragraph-count 1951 :named-section-count 0
	       :named-section-head nil :tag-counts
	       (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 1951)
		("table" . 242) ("h1" . 0) ("h2" . 0))))
 (:slug "index-6b-ordr-2026-q2" :document-snapshot
	(:form "6B ORDR" :format pdf :primary-document
	       (:type "6B ORDR" :sequence nil :filename
		      "filename1.pdf" :description nil :format pdf)
	       :text-length 2109 :text-sha256
	       "0d26b2a29faed9220d51c858e425a7185beecbf3678365be9b71f7ecbd2f061a"
	       :paragraph-count 15 :named-section-count 5
	       :named-section-head
	       ("UNITED STATES OF AMERICA"
		"SECURITIES AND EXCHANGE COMMISSION"
		"INVESTMENT COMPANY ACT OF 1940")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0))))
 (:slug "index-6b-ntc-2026-q2" :document-snapshot
	(:form "6B NTC" :format pdf :primary-document
	       (:type "6B NTC" :sequence nil :filename "filename1.pdf"
		      :description nil :format pdf)
	       :text-length 3587 :text-sha256
	       "84d614ff68316b70ebeb089ba66f6f302deec487d77916e4bc6674856a7d1006"
	       :paragraph-count 46 :named-section-count 2
	       :named-section-head
	       ("SECURITIES AND EXCHANGE COMMISSION"
		"FOR FURTHER INFORMATION CONTACT: Jill Ehrlich, Senior Counsel, or Daniele")
	       :tag-counts
	       (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
		("table" . 0) ("h1" . 0) ("h2" . 0))))
 (:slug "index-15f-12g-2026-q2" :document-snapshot
	(:form "15F-12G" :format html :primary-document
	       (:type "15F-12G" :sequence "1" :filename
		      "form15f12g.htm" :description "FORM 15F-12G"
		      :format html)
	       :text-length 8390 :text-sha256
	       "50bd60e37f049ec9899127a81c1f40776f67257c101772e1a697bba698f6b808"
	       :paragraph-count 40 :named-section-count 0
	       :named-section-head nil :tag-counts
	       (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 40)
		("table" . 22) ("h1" . 0) ("h2" . 0))))
 (:slug "index-15f-12b-2026-q2" :document-snapshot
	(:form "15F-12B" :format html :primary-document
	       (:type "15F-12B" :sequence "1" :filename
		      "tm2612452d1_15f12b.htm" :description
		      "FORM 15F-12B" :format html)
	       :text-length 8844 :text-sha256
	       "d5e51f125bc8751c7f2346a617207dae787c04e4d59f50dcbae0df3410466dfe"
	       :paragraph-count 141 :named-section-count 0
	       :named-section-head nil :tag-counts
	       (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 141)
		("table" . 12) ("h1" . 0) ("h2" . 0))))
 (:slug "index-305b2-2026-q3" :document-snapshot
	(:form "305B2" :format html :primary-document
	       (:type "305B2" :sequence "1" :filename
		      "tm2623171d1_305b2.htm" :description "305B2"
		      :format html)
	       :text-length 3576 :text-sha256
	       "c65eeb4197e1e08146f6f0f39a3d542eb162abeae40a4c96128fec33599ac714"
	       :paragraph-count 92 :named-section-count 0
	       :named-section-head nil :tag-counts
	       (("html" . 1) ("head" . 1) ("body" . 1) ("p" . 92)
		("table" . 13) ("h1" . 0) ("h2" . 0)))))
