(:form "SBSE/A" :text-length 13997 :text-sha256
       "8f1128fc0e6bbdc2b0a3b72608bafa511403abe218836a023e40bcfd40471aaa"
       :text-head
       "SBSE/A0001910878XXXXXXXXtruefalseGIFMS Capital Company, LLC98-13746160001910878GIFMS CAPITAL COMPANY"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("applicant" "schedulea" "scheduleb" "scheduled" "schedulee"
	  "schedulef" "regulatorydrpinfo" "execution"))))
