(:form "SBSE-A/A" :text-length 4208 :text-sha256
       "faaf8b09cf1d5cc34580799ad048818baf3d2cf79e00ca297128c48dd8e44889"
       :text-head
       "SBSE-A/A0001012467XXXXXXXXtruefalse291281Citigroup Global Markets Ltd00-00000002912810001012467XKZZ2"
       :structure
       (("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("applicant" "schedulea" "scheduleb" "schedulef" "execution"))))
