(:form "SC 13E3" :text-bucket 16 :text-head
       "tm2611660-1_sc13e3 - none - 3.8593989s ​ ​ ​ UNITED STATES S"
       :sections
       (("1" 7 "Item 1. Summary Term Sheet The information set for")
	("2" 10 "Item 2. Subject Company Information (a) Name and A")
	("3" 9 "Item 3. Identity and Background of Filing Person (")
	("4" 12 "Item 4. Terms of the Transaction (a)(1) Tender Off")
	("5" 13 "Item 5. Past Contacts, Transactions, Negotiations ")
	("6" 11 "Item 6. Purposes of the Transaction and Plans or P")
	("7" 12 "Item 7. Purposes, Alternatives, Reasons and Effect")
	("8" 12 "Item 8. Fairness of the Transaction (a) – (b) Fair")
	("9" 11 "Item 9. Reports, Opinions, Appraisals and Negotiat")
	("10" 10 "Item 10. Source and Amount of Funds or Other Consi")
	("11" 11 "Item 11. Interest in Securities of the Subject Com")
	("12" 11 "Item 12. The Solicitation or Recommendation (d) In")
	("13" 10 "Item 13. Financial Statements (a) Financial Inform")
	("14" 10 "Item 14. Persons/Assets, Retained, Employed, Compe")
	("15" 9 "Item 15. Additional Information (b) The informatio")
	("16" 13 "Item 16. Exhibits The following exhibits are filed")))
