(:form "SC 13D/A" :text-bucket 14 :text-head
       "------------------------------------------------------------"
       :sections
       (("1" 9 "Item 1. Security and Issuer. This Amendment No. 1 ")
	("2" 10 "Item 2. Identity and Background. Item 2 of the Sch")
	("3" 10 "Item 3. Source and Amount of Funds and Other Consi")
	("5" 10 "Item 5. Interests in Securities of the Issuer. Ite")
	("6" 7 "Item 6. Contracts, Arrangements, Understandings or")
	("7" 10 "Item 7. Materials to be Filed as Exhibits. 1. Join")))
