(:form "SC 13G/A" :text-bucket 12 :text-head
       "SECURITIES AND EXCHANGE COMMISSION Washington, D.C. 20549 SC"
       :sections
       (("3" 9 "Item 3 If this statement is filed pursuant to rule")
	("4" 9 "Item 4 Ownership (a) Amount Beneficially Owned: 2,")
	("5" 6 "Item 5 Ownership of Five Percent or Less of a Clas")
	("6" 6 "Item 6 Ownership of More than Five Percent on Beha")
	("7" 7 "Item 7 Identification and Classification of the Su")
	("8" 6 "Item 8 Identification and Classification of Member")
	("9" 6 "Item 9 Notice of Dissolution of Group. NOT APPLICA")
	("10" 9 "Item 10 Certification. By signing below I certify ")))
