(:form "SC 14D9" :text-bucket 18 :text-head
       "SC 14D9 UNITED STATES SECURITIES AND EXCHANGE COMMISSION Was"
       :sections
       (("1" 10 "Item 1. Subject Company Information. (a) Name and ")
	("2" 13 "Item 2. Identity and Background of Filing Person. ")
	("3" 15 "Item 3. Past Contacts, Transactions, Negotiations ")
	("4" 16 "Item 4. The Solicitation or Recommendation. (a) Re")
	("5" 10 "Item 5. Person/Assets, Retained, Employed, Compens")
	("6" 13 "Item 6. Interest in Securities of the Subject Comp")
	("7" 9 "Item 7. Purposes of the Transactions and Plans or ")
	("8" 15 "Item 8. Additional Information. (a) Golden Parachu")
	("9" 15 "Item 9. Exhibits. The following Exhibits are filed")))
