(:form "SC 14N" :text-bucket 14 :text-head
       "zge20260318_sc14n.htm UNITED STATES SECURITIES AND EXCHANGE "
       :sections
       (("3" 11 "Item 3. Ownership (a) Securities entitled to be vo")
	("4" 8 "Item 4. Statement of Ownership From a Nominating S")
	("5" 6 "Item 5. Disclosure Required for Shareholder Nomina")
	("6" 13 "Item 6. Disclosure Required by § 240.14a-18 (a) Th")
	("7" 6 "Item 7. Notice of Dissolution of Group or Terminat")
	("8" 10 "Item 8. Signatures After reasonable inquiry and to")))
