(:form "SC 14D9" :text-bucket 18 :text-head
       "SC 14D9 Table of Contents UNITED STATES SECURITIES AND EXCHA"
       :sections
       (("1" 10 "Item 1. Subject Company Information. (a) Name and ")
	("2" 13 "Item 2. Identity and Background of Filing Person. ")
	("3" 15 "Item 3. Past Contacts, Transactions, Negotiations ")
	("4" 17 "Item 4. The Solicitation or Recommendation. On Nov")
	("5" 11 "Item 5. Person/Assets Retained, Employed, Compensa")
	("6" 10 "Item 6. Interest in Securities of the Subject Comp")
	("7" 9 "Item 7. Purposes of the Transaction and Plans or P")
	("8" 14 "Item 8. Additional Information. Golden Parachute C")
	("9" 15 "Item 9. Exhibits. Exhibit Description No. (a)(1) O")))
