(:form "SC TO-I" :text-bucket 13 :text-head
       "SC TO-I 1 f45598d1.htm SC TO-I SC TO-I UNITED STATES SECURIT"
       :sections
       (("1" 7 "Item 1. Summary Term Sheet. Reference is made to t")
	("2" 10 "Item 2. Subject Company Information. (a) The name ")
	("3" 9 "Item 3. Identity and Background of Filing Person. ")
	("4" 9 "Item 4. Terms of the Transaction. (a) (1) Referenc")
	("5" 10 "Item 5. Past Contracts, Transactions, Negotiations")
	("6" 9 "Item 6. Purposes Of This Tender Offer And Plans Or")
	("7" 9 "Item 7. Source and Amount of Funds or Other Consid")
	("8" 7 "Item 8. Interest in Securities of the Subject Comp")
	("9" 7 "Item 9. Persons/Assets Retained, Employed, Compens")
	("10" 8 "Item 10. Financial Statements. (a) The audited ann")
	("11" 8 "Item 11. Additional Information. (a) (1) None. (2)")
	("12" 9 "Item 12. Exhibits. (a)(1) (i) Cover Letter to Offe")))
