(:form "SC TO-T" :text-bucket 14 :text-head
       "SC TO-T UNITED STATES SECURITIES AND EXCHANGE COMMISSION Was"
       :sections
       (("1" 7 "Item 1. Summary Term Sheet. The information set fo")
	("2" 10 "Item 2. Subject Company Information. (a) Name and ")
	("3" 9 "Item 3. Identity and Background of Filing Person. ")
	("4" 9 "Item 4. Terms of the Transaction. (a) Material Ter")
	("5" 8 "Item 5. Past Contacts, Transactions, Negotiations ")
	("6" 9 "Item 6. Purposes of the Transaction and Plans or P")
	("7" 9 "Item 7. Source and Amount of Funds or Other Consid")
	("8" 8 "Item 8. Interest in Securities of the Subject Comp")
	("9" 8 "Item 9. Persons/Assets Retained, Employed, Compens")
	("10" 10 "Item 10. Financial Statements. (a) Financial Infor")
	("11" 9 "Item 11. Additional Information. (a) Agreements, R")
	("12" 12 "Item 12. Exhibits. Exhibit No. Description (a)(1)(")
	("13" 9 "Item 13. Information Required by Schedule 13E-3. N")))
