(:form "SC TO-T" :text-bucket 14 :text-head
       "QuickLinks -- Click here to rapidly navigate through this do"
       :sections
       (("1" 7 "Item 1. Summary Term Sheet. The information set fo")
	("2" 9 "Item 2. Subject Company Information. (a) The name ")
	("3" 8 "Item 3. Identity and Background of the Filing Pers")
	("4" 10 "Item 4. Terms of the Transaction. (a)(1)(i) - (vii")
	("5" 9 "Item 5. Past Contacts, Transactions, Negotiations ")
	("6" 9 "Item 6. Purposes of the Transaction and Plans or P")
	("7" 8 "Item 7. Source and Amount of Funds or Other Consid")
	("8" 9 "Item 8. Interest in Securities of the Subject Comp")
	("9" 8 "Item 9. Persons/Assets, Retained, Employed, Compen")
	("10" 5 "Item 10. Financial Statements. Not applicable.")
	("11" 10 "Item 11. Additional Information. (a)(1) The inform")
	("12" 13 "Item 12. Exhibits. Exhibit No. Description (a)(1)(")))
