(:form "SC TO-I" :text-bucket 13 :text-head
       "SC TO-I 1 sctoi0425_pamt.htm ISSUER TENDER OFFER STATEMENT U"
       :sections
       (("1" 7 "Item 1. Summary Term Sheet. The information set fo")
	("2" 9 "Item 2. Subject Company Information. (a) The name ")
	("3" 8 "Item 3. Identity and Background of Filing Person. ")
	("4" 10 "Item 4. Terms of the Transaction. (a) The followin")
	("5" 8 "Item 5. Past Contacts, Transactions, Negotiations ")
	("6" 8 "Item 6. Purposes of the Transaction and Plans or P")
	("7" 9 "Item 7. Source and Amount of Funds or Other Consid")
	("8" 8 "Item 8. Interest in Securities of the Subject Comp")
	("9" 7 "Item 9. Persons/Assets, Retained, Employed, Compen")
	("10" 5 "Item 10. Financial Statements. Not applicable.")
	("11" 9 "Item 11. Additional Information. (a) The informati")
	("12" 11 "Item 12. Exhibits. (a)(1)(A)* Offer to Purchase da")
	("13" 11 "Item 13. Information Required by Schedule 13E-3. N")))
