(:form "SCHEDULE 13G" :text-bucket 12 :text-head
       "------------------------------------------------------------"
       :sections
       (("1" 7 "Item 1. (a) Name of issuer: GameStop Corp. (b) Add")
	("2" 8 "Item 2. (a) Name of person filing: Ali Ehad Turker")
	("3" 10 "Item 3. If this statement is filed pursuant to §§ ")
	("4" 8 "Item 4. Ownership (a) Amount beneficially owned: 1")
	("5" 6 "Item 5. Ownership of 5 Percent or Less of a Class.")
	("6" 6 "Item 6. Ownership of more than 5 Percent on Behalf")
	("7" 7 "Item 7. Identification and Classification of the S")
	("8" 6 "Item 8. Identification and Classification of Membe")
	("9" 8 "Item 9. Notice of Dissolution of Group. Not Applic")
	("10" 9 "Item 10. Certifications: By signing below I certif")))
