(:form "TA-1/A" :text-length 3701 :text-sha256
       "359e6b164d1a49f548bc45be8c45be2441a8ece345928344145b43bea0370000"
       :text-head
       "X0405TA-1/A0000027048XXXXXXXX084-00448trueLIVESECSS&C GIDS, Inc.DST SYSTEMS INC /TA4015881055 Broadw"
       :structure
       (("schemaversion" nil)
	("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("registrant" "independentregistrant" "disciplinaryhistory"
	  "signature"))))
