(:form "TA-W" :text-length 266 :text-sha256
       "52e876d8ffe0bc71215c6ec28cb3a46424acc75e350981c67f5fa4187ea96e16"
       :text-head
       "X0205TA-W0001938417XXXXXXXXLIVEfalse084-06865Dominion Stock Transfer, Inc.Dominion Stock Transfer, I"
       :structure
       (("schemaversion" nil)
	("headerdata" ("submissiontype" "filerinfo"))
	("formdata"
	 ("registrant" "withdrawal" "legalaction" "documentretention"
	  "signaturedata"))))
