(:form "UPLOAD" :markers
       ("This is to advise you that we do not intend to review"
	"Estate & Construction")
       :document-snapshot
       (:form "UPLOAD" :format text :primary-document
	      (:type "TEXT-EXTRACT" :sequence "2" :filename
		     "filename2.txt" :description nil :format text)
	      :text-length 1298 :text-sha256
	      "7e45c0c5a37284f9dacb4bc53a3d5542563329e1791939bd111b5347959d9eaf"
	      :paragraph-count 8 :named-section-count 3
	      :named-section-head
	      ("Adam Katz" "Sincerely," "Division of") :tag-counts
	      (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
	       ("table" . 0) ("h1" . 0) ("h2" . 0))))
