(:form "UPLOAD" :markers
       ("This is to advise you that we do not intend to review"
	"Estate & Construction")
       :document-snapshot
       (:form "UPLOAD" :format text :primary-document
	      (:type "TEXT-EXTRACT" :sequence "2" :filename
		     "filename2.txt" :description nil :format text)
	      :text-length 1359 :text-sha256
	      "b4f92e444142e81153e4180b8f1ae12d602db0b8ea5280393b2716c80cbc8c95"
	      :paragraph-count 8 :named-section-count 3
	      :named-section-head
	      ("Adam Katz" "Sincerely," "Division of") :tag-counts
	      (("html" . 0) ("head" . 0) ("body" . 0) ("p" . 0)
	       ("table" . 0) ("h1" . 0) ("h2" . 0))))
