(:sections
 (("1"
   "Management’s Discussion and Analysis of Financial Condition and Results of Operations."
   "As of March 31, 2026 and December 31, 2025, we had approximately $698,000 and $398,000, respectively, in cash."
   "As of June 29, 2026, the Company’s board has authorized and completed a final dividend payment in an aggregate amount of $1.2 million.")
  ("2"
   "Other Information Conflicts of Interest We expect to do business with entities owned or controlled by affiliates."
   "and the Chief Strategy Officer from the second quarter of 2022 to October 2024."
   "Changes in Composition of our Board of Directors Not applicable as of June 29, 2026.")
  ("3" "Changes in operating assets and liabilities:"
   "As March 31, 2026 and September 2025, the Company had 25,351 shares of preferred stock, or Fig Gaming Shares, outstanding."
   "NOTES TO UNAUDITED FINANCIAL STATEMENTS 1.")
  ("4"
   "Description of Exhibit 2.1.1 Second Amended and Restated Certificate of Incorporation of the Company (incorporated herein by reference to Exhibit No."
   "6.14 to the Company’s 2023 1-SA semiannual report (File number 24R-00037) filed with the SEC on June 29, 2023)."
   "/s/ Lee Charles (Chuck) Pettid Lee Charles (Chuck) Pettid President Date:"))
 :text
 ("We recognized revenue of $312,000 and $875,000 in the six months ended March 31, 2026 and 2025, respectively."
  "As of the date of this Form 1-SA, Fig has provided $150,000 to publish Classic Wizardry Re-release 2:"
  "As of March 31, 2026, the Company owed its Parent a total of $1,864,292."
  "The Company had no allocation of rent expense from our Parent during the six months ended March 31, 2026 and March 31, 2025."))
