(:sections
 (("1"
   "On June 25, 2026, the parties consummated the transactions contemplated by the Consignment Agreement and title of the Painting passed to the Buyer."
   "A detailed breakdown of the IRR calculation is attached to this Form 1-U as Exhibit 99.1."))
 :text
 ("20549 FORM 1-U CURRENT REPORT Pursuant to Regulation A of the Securities Act of 1933 June 29, 2026 Date of Report:"
  "On June 25, 2026, the parties consummated the transactions contemplated by the Consignment Agreement and title of the Painting passed to the Buyer."
  "A detailed breakdown of the IRR calculation is attached to this Form 1-U as Exhibit 99.1."))
