(:sections
 (("I.1" "Distribution and Pool Performance Information."
   "On June 17, 2026 a distribution was made to holders of the certificates issued by Morgan Stanley Bank of America Merrill Lynch Trust 2015-C21."
   "filed its most recent Form ABS-15G on February 6, 2026.")
  ("II.9"
   "Item 9. Other Information. KeyBank National Association, in its capaci")
  ("II.10"
   "(a) The following is a list of documents filed as part of this Report on Form 10-D:"
   "(b) The exhibits required to be filed by the Registrant pursuant to this Form are listed above."
   "(Depositor) /s/ Jane Lam Jane Lam, President Date:"))
 :text
 ("On June 17, 2026 a distribution was made to holders of the certificates issued by Morgan Stanley Bank of America Merrill Lynch Trust 2015-C21."
  "The CIK number for Morgan Stanley Mortgage Capital Holdings LLC is 0001541557."
  "The CIK number for Starwood Mortgage Funding III LLC is 0001682532."
  "(b) The exhibits required to be filed by the Registrant pursuant to this Form are listed above."))
