(:sections
 (("III.10"
   "Gracias will not stand for re-election when his current term expires at the 2021 annual meeting of stockholders."
   "Antonio Gracias has been a member of the Board since May 2007 and served as our Lead Independent Director from September 2010 to April 2019."
   "http://ir.tesla.com/corporate-governance/highlights.")
  ("III.11"
   "We had no other executive officers serving at the end of our fiscal year ended December 31, 2019."
   "Musk has not accepted his salary in the amounts of $23,760, $56,380, and $49,920 for 2019, 2018, and 2017, respectively."
   "None of such persons is or was formerly an officer or an employee of Tesla.")
  ("III.12"
   "(2) The weighted average exercise price is calculated based solely on the outstanding stock options."
   "Kirkhorn (5) 45,925 * Jerome Guillen (6) 87,064 * Andrew Baglino (7) 31,010 * Robyn Denholm (8) 165,107 * Ira Ehrenpreis (9) 138,873 * Lawrence J."
   "(15) Includes 23,611 shares issuable upon exercise of options exercisable within 60 days after December 31, 2019.")
  ("III.13"
   "For purposes of these procedures, “related person” and “transaction” have the meanings contained in Item 404 of Regulation S-K."
   "SpaceX purchased an aggregate $0.6 million of such parts in 2019 and an aggregate $0.6 million of such parts in 2020 through March."
   "The Board concluded that because such arrangement is governed by a binding agreement with Tesla as to which Mr.")
  ("III.14"
   "The dollar amounts in the table and accompanying footnotes are in thousands."
   "(3) Tax Fees in 2018 and 2019 consisted of fees related to consultation and assistance with foreign taxation matters."
   "All PricewaterhouseCoopers LLP services and fees in fiscal 2018 and 2019 were pre-approved by the Audit Committee.")
  ("IV.15" "EXHIBITS AND FINANCIAL STATEMENT SCHEDULES 1."
   "S-1/A 333-164593 10.2 May 27, 2010 10.3** Form of Stock Option Agreement under S-1 333-164593 10.3 January 29, 2010 2003 Equity Incentive Plan."
   "Beijing Branch from Tesla Automobile (Beijing) Co., Ltd., dated as of September 26, 2019 (English translation)."))
 :text
 ("Antonio Gracias has been a member of the Board since May 2007 and served as our Lead Independent Director from September 2010 to April 2019."
  "• Year-end cash and cash equivalents balance of $6.3 billion, an approximately 70% increase from the end of 2018;"
  "(5) Includes $2,283,988,504 attributed to the 2018 CEO Performance Award, which is intended to compensate Mr."
  "Name Aggregate Number of Shares Underlying Options Outstanding Robyn Denholm 206,165 Ira Ehrenpreis 148,000 Lawrence J."
  "SpaceX purchased an aggregate $0.6 million of such parts in 2019 and an aggregate $0.6 million of such parts in 2020 through March."
  "10.22 Form of Call Option 8-K 001-34756 10.1 March 22, 2017 Confirmation relating to 2.375% Convertible Notes due March 15, 2022."))
