(:sections
 (("I.1"
   "The Company currently operates through two business segments;"
   "This transition report on Form 10-KT covers the transition period from August 1, 2025 to March 31, 2026."
   "Changes in applicable laws and regulations could increase compliance costs or restrict the Company’s ability to operate or expand its platform.")
  ("I.1A"
   "ITEM 1A. RISK FACTORS We are a smaller reporting company as defined by")
  ("I.1B"
   "ITEM 1B. UNRESOLVED STAFF COMMENTS We are a smaller reporting company ")
  ("I.1C"
   "ITEM 1C. CYBERSECURITY As of March 31, 2026, the Company has not ident")
  ("I.2"
   "DESCRIPTION OF PROPERTY We do not own any real estate or other properties."
   "Our office is located at 69 Wanke Boyu, Xili Liuxin 1st Rd, Nanshan District, Shenzhen, Guangdong 518052, China."
   "The Company does not own, rent, or lease any properties.")
  ("I.3"
   "LEGAL PROCEEDINGS From time to time, we may become involved in various lawsuits and legal proceedings which arise in the ordinary course of business.")
  ("I.4" "ITEM 4. MINE SAFETY DISCLOSURES Not applicable. 8")
  ("II.5"
   "We cannot assure you that there will be any liquidity for our common stock in the future."
   "(“ATXG”), wherein ATXG purchased 34,200,000 shares of Common Shares, par value $0.001 per share, of KMFG."
   "Recent Sales of Unregistered Securities No securities have been sold by the Company during the period covered by this Form 10-KT.")
  ("II.6" "ITEM 6. [RESERVED] 10")
  ("II.7"
   "This transition report covers the eight months transition period from August 1, 2025 to March 31, 2026."
   "As of March 31, 2025, the Company had cash and cash equivalents of $23,329, compared to $19,421 as of July 31, 2024."
   "No cash generate nor used any cash in investing and financing activity.")
  ("II.7A"
   "ITEM 7A. QUANTITATIVE AND QUALITATIVE DISCLOSURES ABOUT MARKET RISK We")
  ("II.8"
   "ITEM 8. FINANCIAL STATEMENTS AND SUPPLEMENTARY DATA The consolidated f")
  ("II.9"
   "ITEM 9. CHANGES IN AND DISAGREEMENTS WITH ACCOUNTANTS ON ACCOUNTING AN")
  ("II.9A"
   "Based on this evaluation, our Chief Executive Officer concluded as of March 31, 2026, that our disclosure controls and procedures were not effective."
   "Management assessed the effectiveness of the Company’s internal control over financial reporting as of March 31, 2026."
   "We anticipate that these initiatives will be at least partially, if not fully, implemented by the end of fiscal year 2027.")
  ("II.9B" "ITEM 9B. OTHER INFORMATION None.")
  ("II.9C"
   "DISCLOSURE REGARDING FOREIGN JURISDICTIONS THAT PREVENT INSPECTIONS Not Applicable.")
  ("III.10"
   "DIRECTORS, EXECUTIVE OFFICERS AND CORPORATE GOVERNANCE Set forth below are the present directors and executive officers of the Company."
   "78c(a)(26))), any registered entity (as defined in Section 1(a)(29) of the Commodity Exchange Act (7 U.S.C."
   "In the event our operations, employees and/or Directors expand in the future, we may take actions to adopt a formal Code of Ethics.")
  ("III.11"
   "Employment Agreements We do not have an employment or consulting agreement with any officers or Directors."
   "Executive Compensation Philosophy Our Board of Directors determines the compensation given to our executive officers in their sole determination.")
  ("III.12"
   "Neither the split nor the increase in authorized shares affected any stockholder’s ownership percentage of our common stock."
   "Beneficial ownership has been determined in accordance with Rule 13d-3 under the Exchange Act.")
  ("III.13"
   "CERTAIN RELATIONSHIPS AND RELATED TRANSACTIONS, DIRECTOR INDEPENDENCE On April 23, 2022, we issued 3,600,000 shares of our common stock to Ms."
   "Liu Lu, our Chief Executive Officer, President, Secretary, Treasurer, and Director in consideration of $3,600, or $0.001 per share."
   "All advances are unsecured, non-interest bearing, and repayable on demand, with no fixed terms of repayment.")
  ("III.14"
   "HML PLT has served as the Company’s independent registered public accounting firm since November 12, 2025."
   "The category of “Audit-related fees” includes employee benefit plan audits, internal control reviews and accounting consultation."
   "The category of “All other fees” generally includes advisory services related to accounting rules and regulations.")
  ("IV.1"
   "Comparative years reflects standalone parent only (unconsolidated)."
   "RELATED PARTY TRANSACTIONS 2026 2025 2024 Eight Months Ended Twelve Months Ended March 31, July 31, 2026 2025 2024 Due to related parties:"
   "During the period, the Company did not have any material recognizable subsequent events.")
  ("IV.15"
   "EXHIBITS AND FINANCIAL STATEMENT SCHEDULES (a) Consolidated Financial Statements The following are filed as part of this transition report:")
  ("IV.16"
   "FORM 10-KT SUMMARY As permitted, the registrant has elected not to supply a summary of information required by Form 10-KT."
   "As of July 31, 2025, the current liabilities of the Company exceeded its current assets by $82,066 and has a shareholders’ deficits of $82,066."
   "6723) We have served as the Company’s auditor since 2022."))
 :text
 ("(“ATXG”), wherein ATXG purchased 34,200,000 shares of Common Shares, par value $0.001 per share, of KMFG."
  "CERTAIN RELATIONSHIPS AND RELATED TRANSACTIONS, DIRECTOR INDEPENDENCE On April 23, 2022, we issued 3,600,000 shares of our common stock to Ms."
  "6723) We have served as the Company’s auditor since 2022."
  "The Company generates revenue from two primary sources:"
  "2026 2025 2024 Eight Months Ended Twelve Months Ended March 31, July 31, 2026 2025 2024 Tax jurisdictions from:"))
