(:sections
 (("I.1"
   "Its executive offices are located at 1 Becton Drive, Franklin Lakes, New Jersey 07417-1880 and its telephone number is (201) 847-6800.")
  ("I.2"
   "The executive offices of the Company are located in Franklin Lakes, New Jersey.")
  ("I.3"
   "ITEM 3. LEGAL PROCEEDINGS. The Company, along with a number of other m"))
 :text
 ("Its executive offices are located at 1 Becton Drive, Franklin Lakes, New Jersey 07417-1880 and its telephone number is (201) 847-6800."
  "The executive offices of the Company are located in Franklin Lakes, New Jersey."))
