(:sections
 (("I.1"
   "Total R&D expense was $8.1 billion, $6.0 billion and $4.5 billion in 2015, 2014 and 2013, respectively."
   "Further, the Companys references to website URLs are intended to be inactive textual references only."
   "The Company is a California corporation established in 1977.")
  ("I.1A"
   "Risk Factors The following discussion of risk factors contains forward-looking statements."
   "Purchase commitments typically cover forecasted component and manufacturing requirements for periods up to 150 days."
   "If the Companys effective tax rates were to increase, particularly in the U.S.")
  ("I.1B" "Item 1B. Unresolved Staff Comments 18")
  ("I.2"
   "Properties The Companys headquarters are located in Cupertino, California."
   "As of September 26, 2015, the Company owned or leased 25.6 million square feet of building space, primarily in the U.S."
   "Outside the U.S., the Company owned additional facilities for various purposes.")
  ("I.3" "Apple Inc., et al.) On April 11, 2012, the U.S."
   "The Company appealed the District Courts decision."
   "Apple eBooks Antitrust Litigation (United States of America v.")
  ("I.4"
   "Item 4. Mine Safety Disclosures Not applicable. Apple Inc. | 2015 Form")
  ("II.5"
   "The Company also plans to increase its dividend on an annual basis, subject to declaration by the Board of Directors."
   "May 2015 ASR 9,973 (2) (2) 9,973 (2) Open market and 15,882 $ 124.66 15,882 privately negotiated purchases August 2, 2015 to August 29, 2015:"
   "Technology $ 100 $ 103 $ 134 $ 141 $ 183 $ 183 Supersector Index Apple Inc.")
  ("II.6" "(2) Includes current and long-term portion of term debt.")
  ("II.7"
   "All information presented herein is based on the Companys fiscal calendar."
   "Fiscal 2015 Highlights Net sales rose 28% or $50.9 billion during 2015 compared to 2014, driven by a 52% year-over-year increase in iPhone® net sales."
   "Each of the terms the Company and Apple as used herein refers collectively to Apple Inc.")
  ("II.7A"
   "Interest Rate Risk The Companys exposure to changes in interest rates relates primarily to the Companys investment portfolio and outstanding debt."
   "The Companys practice is to hedge a portion of its material foreign exchange exposures, typically for up to 12 months."
   "Forecasted transactions, firm commitments and assets and liabilities denominated in foreign currencies were excluded from the model.")
  ("II.8"
   "Basic $ 9.28 $ 6.49 $ 5.72 Diluted $ 9.22 $ 6.45 $ 5.68 Shares used in computing earnings per share:"
   "Money market funds 1,798 0 0 1,798 1,798 0 0 Mutual funds 1,772 0 (144 ) 1,628 0 1,628 0 Subtotal 3,570 0 (144 ) 3,426 1,798 1,628 0 Level 2:"
   "/s/ Ernst & Young LLP San Jose, California October 28, 2015 Apple Inc.")
  ("II.9"
   "Item 9. Changes in and Disagreements With Accountants on 71 Accounting")
  ("II.9A" "generally accepted accounting principles (GAAP)."
   "The Companys internal control over financial reporting includes those policies and procedures that:")
  ("II.9B"
   "Item 9B. Other Information Not applicable. Apple Inc. | 2015 Form 10-K")
  ("III.10" "The Company has a code of ethics, Business Conduct:"
   "The code is available at investor.apple.com/corporate-governance.cfm.")
  ("III.11"
   "Item 11. Executive Compensation The information required by this Item ")
  ("III.12"
   "Item 12. Security Ownership of Certain Beneficial Owners and Managemen")
  ("III.13"
   "Item 13. Certain Relationships and Related Transactions, and Director ")
  ("III.14"
   "Item 14. Principal Accounting Fees and Services The information requir")
  ("IV.15"
   "Cook Chief Executive Officer and Director October 28, 2015 (Principal Executive Officer) TIMOTHY D."
   "8-K 10.1 3/5/14 10.9* Form of Restricted Stock Unit Award 8-K 10.2 3/5/14 Agreement under 2014 Employee Stock Plan as of February 28, 2014."
   "The Registrant hereby undertakes to furnish to the SEC, upon request, copies of any such instruments."))
 :text
 ("In September 2015, the Company announced the new Apple TV running on the Companys tvOS operating system and based on apps built for the television."
  "The Company is vigorously defending infringement actions in courts in a number of U.S."
  "Internet Services generated a total of $10.2 billion in net sales during 2014 compared to $9.3 billion during 2013."
  "Basic $ 9.28 $ 6.49 $ 5.72 Diluted $ 9.22 $ 6.45 $ 5.68 Shares used in computing earnings per share:"
  "2016 $ 1,288 2017 1,033 2018 786 2019 342 2020 166 Thereafter 178 Total $ 3,793 Apple Inc."))
