(:sections
 (("I.1"
   "Business The words “we” and “our” in this Form 10-K refer collectively to AB Holding and AB and its subsidiaries, or to their officers and employees."
   "400,884 412,772 355,746 (2.9) 16.0 Total Fixed Income 584,143 560,191 474,034 4.3 18.2 Alternatives/Multi-Asset Solutions(2):"
   "•our ability to further develop and market our brand;")
  ("I.1A"
   "The majority of the risk factors discussed below directly affect AB."
   "Our performance-based fees were $185.3 million, $271.0 million and $144.9 million in 2025, 2024 and 2023, respectively."
   "A broker cannot rely on the certification if it knows it is incorrect or unreliable.")
  ("I.1B"
   "Item 1B. Unresolved Staff Comments Neither AB nor AB Holding has unres")
  ("I.1C"
   "Enterprise risk, including cybersecurity risk, is overseen by the Audit and Risk Committee (\"Audit Committee\") on behalf of the Board."
   "See Item 1A Risk Factors - Operations, Technology and Cyber-Related Risks for a discussion of cybersecurity risks."
   "The full Board is updated on an as needed basis.")
  ("I.2"
   "Properties Our headquarters is located at 501 Commerce Street, Nashville, Tennessee."
   "Approximately 48,000 square feet is under a lease expiring in 2032 with the remaining 108,000 square feet under a lease expiring in 2033."
   "In London we currently lease approximately 68,000 square feet of space of which 28,000 is sublet to our unconsolidated joint venture.")
  ("I.3"
   "Legal Proceedings Legal Proceedings For significant litigation matters, we assess the likelihood of a negative outcome."
   "If a negative outcome is probable and the loss can be reasonably estimated, we record an estimated loss."
   "While it is possible we could incur losses from these matters, we cannot currently estimate such losses or their range.")
  ("I.4"
   "Item 4. Mine Safety Disclosures Not applicable. 2025 Annual Report 25 ")
  ("II.5"
   "Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities Market for AB Holding Units and AB Units;"
   "On December 31, 2025 (the last trading day of the year), the closing price of an AB Holding Unit on the NYSE was $38.48 per Unit."
   "AB Units bought by us or one of our affiliates during the fourth quarter of 2025 are as follows:")
  ("II.6" "Item 6. [Reserved] 28")
  ("II.7"
   "Gross sales increased $13.7 billion, from $13.0 billion in 2024 to $26.7 billion in 2025."
   "Base fees 1,127,086 1,047,606 942,302 7.6 11.2 Performance-based fees 117,690 172,128 91,012 (31.6) 89.1 1,244,776 1,219,734 1,033,314 2.1 18.0 Total:"
   "AB agreed to indemnify SG Canada for 66.7% of any amounts paid by SG Canada under the Canadian Regulatory Guarantee.")
  ("II.7A"
   "Item 7A. Quantitative and Qualitative 54 Disclosures about Market Risk")
  ("II.8" "Item 8. Financial Statements and 55 Supplementary Data")
  ("II.9"
   "Item 9. Changes in and Disagreements with 106 Accountants on Accountin")
  ("II.9A" "Item 9A. Controls and Procedures 106")
  ("II.9B" "Item 9B. Other Information 107")
  ("II.9C"
   "Item 9C. Disclosure Regarding Foreign 107 Jurisdictions that Prevent I")
  ("III.10"
   "Item 10. Directors, Executive Officers and 108 Corporate Governance")
  ("III.11" "Item 11. Executive Compensation 122")
  ("III.12"
   "Item 12. Security Ownership of Certain 149 Beneficial Owners and Manag")
  ("III.13"
   "Item 13. Certain Relationships and Related 153 Transactions, and Direc")
  ("III.14" "Item 14. Principal Accounting Fees and 154 Services")
  ("IV.15" "Item 15. Exhibits, Financial Statement 155 Schedules")
  ("IV.16" "AB Holding AllianceBernstein Holding L.P."
   "Bernstein Inc., and the related assumption of the liabilities of that business, completed on October 2, 2000."
   "Securities Act the Securities Act of 1933, as amended."))
 :text
 ("27,562 29,669 32,165 (7.1) (7.8) Total Fixed Income 120,465 118,389 127,973 1.8 (7.5) Alternatives/Multi-Asset Solutions(2):"
  "Information about our Executive Officers Please refer to \"Item 10."
  "Financial difficulties or operational challenges may require us to impair the investment's value in our financial statements."
  "A transferee must withhold 10% of the amount realized on the transfer unless an exception applies."
  "(15.11) (10.33) (7.10) MSCI ACWI Index) International Strategic Core Equity Absolute return 28.21 17.98 9.41 Relative return (vs."
  "The current carrying value of the liability as of December 31, 2025 of $123.8 million will accrete up to $134.0 million through December 31, 2027."))
