(:sections
 (("I.1"
   "As of September 27, 2025, the Company had approximately 166,000 full-time equivalent employees."
   "Further, the Company’s references to website URLs are intended to be inactive textual references only."
   "Products iPhone iPhone® is the Company’s line of smartphones based on its iOS operating system.")
  ("I.1A"
   "The Company may not be able to accurately predict, control or mitigate these risks."
   "As of September 27, 2025, the Company’s vendor non-trade receivables were concentrated among a few individual vendors located primarily in Asia."
   "The Company believes the price of its stock should reflect expectations of future growth and profitability.")
  ("I.1B" "Item 1B. Unresolved Staff Comments None.")
  ("I.1C" "engages in employee cybersecurity training;"
   "assesses security risk and compliance posture;"
   "A dedicated Supplier Trust team manages information security risks the Company is exposed to through its supplier relationships.")
  ("I.2"
   "Properties The Company’s headquarters is located in Cupertino, California.")
  ("I.3"
   "The Company has appealed the Commission’s Article 5(4) decision."
   "On September 30, 2024, the Company filed a motion with the California District Court to narrow or vacate the 2021 Injunction."
   "Also on April 23, 2025, the Commission issued preliminary findings in the Article 6(4) Investigation.")
  ("I.4"
   "Item 4. Mine Safety Disclosures Not applicable. Apple Inc. | 2025 Form")
  ("II.5"
   "Holders As of October 17, 2025, there were 22,429 shareholders of record."
   "1621 September 2020 September 2021 September 2022 September 2023 September 2024 September 2025 Apple Inc."
   "$ 100 $ 132 $ 136 $ 155 $ 208 $ 234 S&P 500 Index $ 100 $ 137 $ 115 $ 136 $ 185 $ 217 Dow Jones U.S.")
  ("II.6"
   "Item 6. [Reserved] Apple Inc. | 2025 Form 10-K | 20 ------------------")
  ("II.7"
   "This Item generally discusses 2025 and 2024 items and year-to-year comparisons between 2025 and 2024."
   "Products $ 112,887 $ 109,633 $ 108,803 Services 82,314 71,050 60,345 Total gross margin $ 195,201 $ 180,683 $ 169,148 Gross margin percentage:"
   "Reserves are adjusted considering changing facts and circumstances, such as the closing of a tax examination.")
  ("II.7A"
   "Quantitative and Qualitative Disclosures About Market Risk The Company is exposed to economic risk from interest rates and foreign exchange rates."
   "The Company uses various strategies to manage these risks;"
   "The VAR model used a Monte Carlo simulation.")
  ("II.8"
   "| 2025 Form 10-K | 28 ---------------------------------------------------------------------------------------------------- Apple Inc."
   "Products $ 307,003 $ 294,866 $ 298,085 Services 109,158 96,169 85,200 Total net sales 416,161 391,035 383,285 Cost of sales:"
   "/s/ Ernst & Young LLP San Jose, California October 31, 2025 Apple Inc.")
  ("II.9"
   "Item 9. Changes in and Disagreements with 52 Accountants on Accounting")
  ("II.9A"
   "The Company’s internal control over financial reporting includes those policies and procedures that:")
  ("II.9B" "Kondo will continue to work on other projects."
   "Borders will report to Kevan Parekh, the Company’s Chief Financial Officer.")
  ("II.9C"
   "Item 9C. Disclosure Regarding Foreign Jurisdictions that Prevent Inspe")
  ("III.10"
   "Item 10. Directors, Executive Officers and Corporate Governance The in")
  ("III.11"
   "Item 11. Executive Compensation The information required by this Item ")
  ("III.12"
   "Item 12. Security Ownership of Certain Beneficial Owners and Managemen")
  ("III.13"
   "Item 13. Certain Relationships and Related Transactions, and Director ")
  ("III.14"
   "Item 14. Principal Accountant Fees and Services The information requir")
  ("IV.15"
   "3.2 Amended and Restated Bylaws of the Registrant effective 8-K 3.2 8/23/24 as of August 20, 2024."
   "8-K 10.1 3/4/22 10.7* Form of Restricted Stock Unit Award Agreement under 2022 8-K 10.2 3/4/22 Employee Stock Plan effective as of March 4, 2022."
   "*Indicates management contract or compensatory plan or arrangement.")
  ("IV.16"
   "Cook Chief Executive Officer and Director October 31, 2025 (Principal Executive Officer) TIMOTHY D."
   "Levinson Director and Chair of the Board October 31, 2025 ARTHUR D."
   "Wagner Director October 31, 2025 SUSAN L."))
 :text
 ("The Company also offers digital content through subscription-based services, including Apple Arcade®, a game service;"
  "Manufacturing purchase obligations cover the Company’s forecasted component and manufacturing requirements, typically for periods up to 150 days."
  "As of September 27, 2025, the Company’s vendor non-trade receivables were concentrated among a few individual vendors located primarily in Asia."
  "As of September 27, 2025, the Company had manufacturing purchase obligations of $56.2 billion, with $55.4 billion payable within 12 months."
  "Treasury securities 16,150 45 (516) 15,679 212 4,087 11,380 U.S."
  "3.2 Amended and Restated Bylaws of the Registrant effective 8-K 3.2 8/23/24 as of August 20, 2024."))
