(:sections
 (("III.10"
   "Elon Musk and Kimbal Musk, who are brothers, there are no other family relationships among any of our directors or executive officers."
   "(“Chipotle”) until his retirement in March 2026, and was the President and Chief Strategy Officer of Chipotle from October 2024 to May 2025."
   "It is also the policy of Tesla to comply with all applicable securities laws when transacting in its own securities.")
  ("III.11"
   "We had no other executive officers serving at the end of our fiscal year ended December 31, 2025."
   "Musk ($2,240,640,000), is $40,932,480,000."
   "None of such persons is or was formerly an officer or an employee of Tesla.")
  ("III.12"
   "(2) The weighted average exercise price is calculated based solely on the outstanding stock options."
   "(2) Includes (i) 413,152,109 shares held by the Elon Musk Revocable Trust dated July 22, 2003 and (ii) 303,960,630 shares issuable to Mr."
   "See note (2) above for more information.")
  ("III.13"
   "For purposes of these procedures, “related person” and “transaction” have the meanings contained in Item 404 of Regulation S-K."
   "Under these agreements, Tesla incurred expenses of approximately $11.4 million in 2025 and $1.5 million through February 2026."
   "The Board concluded that none of these investments are material so as to impede the exercise of independent judgment by any of Messrs.")
  ("III.14"
   "The dollar amounts in the table and accompanying footnotes are in thousands."
   "(2) Audit-Related Fees in 2024 and 2025 consisted of fees for professional services for certain agreed upon procedures and other attestation services."
   "All PricewaterhouseCoopers LLP services and fees in fiscal years 2024 and 2025 were pre-approved by the Audit Committee.")
  ("IV.15" "EXHIBITS AND FINANCIAL STATEMENT SCHEDULES 1."
   "10.16** 2025 CEO Interim Restricted Stock Agreement, dated August 3, 2025 8-K 001-34756 10.1 August 4, 2025 10.17** Tesla, Inc."
   "and the State of Nevada, acting by and through the Nevada Governor’s Office of Economic Development."))
 :text
 ("Robyn Denholm has been a member of the Board since August 2014 and its Chair since November 2018."
  "equity securities between May 13 and October 4, 2022."
  "Equity Compensation 2025 CEO Interim Award The Special Committee recognized the lack of meaningful compensation for Mr."
  "The director may borrow up to 15% of 1,000 x $800, or $120,000, against such shares."
  "10-Q 001-34756 3.1 July 24, 2024 3.2 Amended and Restated Bylaws of the Registrant."))
