(:sections
 (("I.1"
   "Business The words “we” and “our” in this Form 10-K refer collectively to AB Holding and AB and its subsidiaries, or to their officers and employees."
   "400,884 412,772 355,746 (2.9) 16.0 Total Fixed Income 584,143 560,191 474,034 4.3 18.2 Alternatives/Multi-Asset Solutions(2):"
   "•our ability to further develop and market our brand;")
  ("I.1A"
   "The majority of the risk factors discussed below directly affect AB."
   "Our performance-based fees were $185.3 million, $271.0 million and $144.9 million in 2025, 2024 and 2023, respectively."
   "A broker cannot rely on the certification if it knows it is incorrect or unreliable.")
  ("I.1B"
   "Item 1B. Unresolved Staff Comments Neither AB nor AB Holding has unres")
  ("I.1C"
   "Enterprise risk, including cybersecurity risk, is overseen by the Audit and Risk Committee (\"Audit Committee\") on behalf of the Board."
   "See Item 1A Risk Factors - Operations, Technology and Cyber-Related Risks for a discussion of cybersecurity risks."
   "The full Board is updated on an as needed basis.")
  ("I.2"
   "Properties Our headquarters is located at 501 Commerce Street, Nashville, Tennessee."
   "Approximately 48,000 square feet is under a lease expiring in 2032 with the remaining 108,000 square feet under a lease expiring in 2033."
   "In London we currently lease approximately 68,000 square feet of space of which 28,000 is sublet to our unconsolidated joint venture.")
  ("I.3"
   "Legal Proceedings Legal Proceedings For significant litigation matters, we assess the likelihood of a negative outcome.")
  ("I.4"
   "Item 4. Mine Safety Disclosures Not applicable. 2025 Annual Report 25 ")
  ("II.5"
   "Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities Market for AB Holding Units and AB Units;"
   "On December 31, 2025 (the last trading day of the year), the closing price of an AB Holding Unit on the NYSE was $38.48 per Unit."
   "AB Units bought by us or one of our affiliates during the fourth quarter of 2025 are as follows:")
  ("II.6" "Item 6. [Reserved] 28")
  ("II.7"
   "Gross sales increased $13.7 billion, from $13.0 billion in 2024 to $26.7 billion in 2025."
   "Base fees 1,127,086 1,047,606 942,302 7.6 11.2 Performance-based fees 117,690 172,128 91,012 (31.6) 89.1 1,244,776 1,219,734 1,033,314 2.1 18.0 Total:"
   "•Our initiative to replace our investment management technology:")
  ("II.7A"
   "Treasury Bills, mutual funds, exchange-traded options and various separately-managed portfolios consisting of equity securities."
   "See Note 7 Derivative Instruments to our consolidated financial statements in Item 8."
   "Other investments include alternative investments and hedge funds we sponsor and other investment vehicles.")
  ("II.8"
   "federal securities laws and the applicable rules and regulations of the Securities and Exchange Commission and the PCAOB."
   "United States $ 881,162 $ 1,075,305 $ 714,732 Foreign 169,313 183,323 102,938 Total $ 1,050,475 $ 1,258,628 $ 817,670 Income tax expense:"
   "See Note 14 Commitments and Contingencies for further discussion of the BIS credit facility and Canadian Regulatory Guarantee.")
  ("II.9"
   "Item 9. Changes in and Disagreements with Accountants on Accounting an")
  ("II.9A"
   "Based on this evaluation, the CEO and the CFO concluded that the disclosure controls and procedures are effective."
   "Management assessed the effectiveness of AB Holding’s and AB’s internal control over financial reporting as of December 31, 2025."
   "The reports pertaining to AB Holding and AB each can be found in Item 8 of this Form 10-K.")
  ("II.9B"
   "Other Information Both AB and AB Holding reported all information required to be disclosed on Form 8-K during the fourth quarter of 2025."
   "Seth Bernstein, Chief Executive Officer of AB adopted a Rule 10b5-1 trading arrangement, as defined in Regulation S-K, (the \" Plan\"), Item 408.")
  ("II.9C"
   "Disclosure Regarding Foreign Jurisdictions that Prevent Inspections Not applicable.")
  ("III.10"
   "General Partner The Partnerships’ activities are managed and controlled by the General Partner."
   "6 02_438515-1_icon_executive .jpg 02_438515-1_icon_audit and risk.jpg Responsibilities:"
   "The Compliance Committee meets on a quarterly basis and at such other times as circumstances warrant.")
  ("III.11"
   "This CD&A should be read together with the compensation tables that follow this section."
   "(i) 159,937 restricted AB Holding Units in December 2025 that are scheduled to vest in equal increments on each December 1, 2026, 2027 and 2028;"
   "As of December 31, 2025, each Independent Director then serving either complied with this policy or was on track to do so within the allotted time.")
  ("III.12"
   "There are no AB Units to be issued pursuant to an equity compensation plan."
   "Pearson has the right to exercise within 60 days and (ii) 126,389 restricted stock units that will vest within 60 days and settle in EQH shares."
   "AB and AB Holding have obtained directors and officers/errors and omissions liability insurance.")
  ("III.13"
   "Other transactions with EQH Affiliates are submitted to the Audit Committee for their review and approval."
   "Equitable Holdings We provide investment management 12,279 services and ancillary accounting services."
   "(2)We provide investment management services unless otherwise indicated.")
  ("III.14"
   "(3)Tax fees consist of fees for tax consultation and tax compliance services."
   "(4)All other fees consist primarily of miscellaneous non-audit services in 2025 and due diligence tax and audit services in 2024."
   "The Audit Committee then affirmatively indicates its approval of the listed engagements.")
  ("IV.15"
   "Exhibits, Financial Statement Schedules (a)There is no document filed as part of this Form 10-K."
   "(incorporated by reference to Exhibit 10.09 to Form 10-K for the fiscal year ended December 31, 2023, as filed February 10, 2024)."
   "101.DEF XBRL Taxonomy Extension Definition Linkbase.")
  ("IV.16" "AB Holding AllianceBernstein Holding L.P."
   "Bernstein Inc., and the related assumption of the liabilities of that business, completed on October 2, 2000."
   "Securities Act the Securities Act of 1933, as amended."))
 :text
 ("Learning and continued development are central to our talent strategy."
  "For 2025 overall, the Bloomberg Global Aggregate Index returned 8.2% (USD, unhedged), and the Bloomberg U.S."
  "We recorded an initial investment in the JVs at fair value as of April 1, 2024 of $283.9 million."
  "The valuation of our Retirement Plan assets by pricing observability levels as of December 31, 2025 and 2024 was as follows (in thousands):"
  "In 2025, we experienced $11.3 billion in total net outflows, compared to $2.2 billion in net outflows in 2024."
  "As a result, she was ineligible for any potential payment or benefit upon a change in control of AB as of December 31, 2025."))
