(:sections
 (("I.1"
   "CONDENSED CONSOLIDATED BALANCE SHEETS August 3, July 28, February 2, 2013 2012 2013 (In millions, except per share data) (Unaudited) ASSETS:"
   "income tax returns for the fiscal years ended on January 28, 2012, January 29, 2011, January 30, 2010 and January 31, 2009."
   "Preferred stock     authorized 5.0 shares;")
  ("I.2"
   "Risk Factors, as well as Disclosure Regarding Forward-looking Statements and Item 1A."
   "13 Weeks Ended 26 Weeks Ended August 3, July 28, August 3, July 28, 2013 2012 2013 2012 Statement of Operations Data:"
   "You should not place undue reliance on these forward-looking statements.")
  ("I.3" "prime rate, (ii) the LIBO rate or (iii) the U.S."
   "We do not use derivative financial instruments to hedge interest rate exposure."
   "We limit our interest rate risk by investing our excess cash balances in short-term, highly-liquid instruments with a maturity of one year or less.")
  ("I.4"
   "ITEM 4. Controls and Procedures (a) Evaluation of Disclosure Controls ")
  ("II.1"
   "ITEM 1. Legal Proceedings In the ordinary course of the Companys busi")
  ("II.1A"
   "Risk Factors In addition to the other information set forth in this Form 10-Q, you should carefully consider the factors discussed in Item 1A."
   "Risk Factors in our Form 10-K for the fiscal year ended February 2, 2013 filed with the SEC on April 3, 2013."
   "The introduction of next-generation consoles could negatively impact the demand for existing products or our pre-owned business.")
  ("II.2" "The authorization has no expiration date.")
  ("II.6"
   "Exhibits Exhibits Exhibit Description Number 3.1 Third Amended and Restated Certificate of Incorporation."
   "10.1 Amended and Restated 2011 Incentive Plan.(1) 10.2 Executive Employment Agreement, dated as of May 10, 2013, between GameStop Corp."
   "(3) Incorporated by reference to the Registrants Form 8-K filed with the Securities and Exchange Commission on July 19, 2013."))
 :text
 ("Recently Issued Accounting Standards In July 2013, accounting standards update (ASU) 2013-11 Income Taxes (Topic 740):"
  "income tax returns for the fiscal years ended on January 28, 2012, January 29, 2011, January 30, 2010 and January 31, 2009."
  "13 Weeks Ended 26 Weeks Ended August 3, July 28, August 3, July 28, 2013 2012 2013 2012 Statement of Operations Data:"
  "Cash used in financing activities was $88.2 million and $284.9 million for the 26 weeks ended August 3, 2013 and July 28, 2012, respectively."
  "and  other factors described in the Form 10-K, including those set forth under the caption Item 1A."))
