(:sections
 (("I.1" "Class A common stock — $.001 par 0.2 0.2 0.2 value;"
   "Marketable securities(1) $ 206.6 $ — $ (0.6) $ 206.0 Digital assets(2) 0.2 — (0.1) 0.1 Equity investment(7) 4,874.8 72.1 — 4,946.9 Level 2:"
   "GameStop expects to recognize a non-cash charge in connection with the Exchange.")
  ("I.2"
   "You should not place undue reliance on these forward-looking statements."
   "During the six months ended August 1, 2026, Net sales decreased 19.7% in Europe, 1.0% in Australia, 0.2% in the United States and 100.0% in Canada."
   "Some accounting policies have a significant impact on amounts reported in these condensed consolidated financial statements.")
  ("I.3"
   "ITEM 3. QUANTITATIVE AND QUALITATIVE DISCLOSURES ABOUT MARKET RISK The")
  ("I.4"
   "ITEM 4. CONTROLS AND PROCEDURES Evaluation of Disclosure Controls and ")
  ("II.1"
   "ITEM 1. LEGAL PROCEEDINGS The matters described in Part I, Item 1 \"Not")
  ("II.1A"
   "ITEM 1A. RISK FACTORS In addition to the other information set forth i")
  ("II.2" "The new share authorization expires on June 2, 2029.")
  ("II.4" "ITEM 4. MINE SAFETY DISCLOSURES Not applicable.")
  ("II.5"
   "ITEM 5. OTHER INFORMATION Security Trading Plans of Directors and Exec")
  ("II.6" "10.1 Form of Exchange Agreement for 2030 Notes."
   "pursuant to Rule 13a-14(a)/15d-14(a) under the Securities Exchange Act of 1934, as adopted pursuant to Section 302 of the Sarbanes-Oxley Act of 2002."
   "The Company will provide a copy of such omitted documents to the Securities and Exchange Commission upon request."))
 :text
 ("Fiscal 2026 consists of 52 weeks ending January 30, 2027."
  "Effective July 15, 2026, we began phasing out the points-earning benefit of our GameStop Pro® Membership."
  "As of August 1, 2026, the balance of the 2032 Notes, net of debt issuance costs of $17.8 million was $2,682.2 million."
  "The OBBBA's provisions take effect on various dates between 2025 and 2027."
  "During the six months ended August 1, 2026, Net sales decreased 19.7% in Europe, 1.0% in Australia, 0.2% in the United States and 100.0% in Canada."))
