(:sections nil :text
	   ("Investments, at fair value $ 2,414,720,784 $ 2,123,242,938 Total investments 2,414,720,784 2,123,242,938 Receivables:"
	    "The contribution limit for these participants was limited to $34,750 in calendar year 2025."
	    "Forfeited Accounts The balance of forfeited accounts totaled $1,770 and $5,199 at December 31, 2025 and 2024, respectively."
	    "Total sales at market value related to The Campbell's Company common stock for 2025 and 2024 were $12,150,478 and $13,907,974, respectively."
	    "There have been no changes in the methodologies used at December 31, 2025 and 2024."
	    "The value of the asset transfer from the Sovos Brands 401(k) Plan was $35,358,127."))
