(:sections nil :text
	   ("Beginning of year 4,376,963 End of year $ 3,793,022 See accompanying notes to the financial statements."
	    "The forfeited account balances were approximately $1,832,000 and $1,425,000 as of December 31, 2017 and 2016, respectively."
	    "To the extent any assets of the Trust represent amounts allocated to a Code Section 415 suspense account, such amounts may revert to the Company."
	    "The Plan’s interest in the net assets of the Master Trust was approximately 99.7% and 96.7% at December 31, 2017 and 2016, respectively."
	    "As of December 31, 2017, the account consisted of approximately $234,839,000 of wrapper contracts and approximately $24,473,000 of cash equivalents."
	    "Description 23.1 Consent of Independent Registered Public Accounting Firm 15 SIGNATURES The Plan."))
