(:sections nil :text
	   ("Investments, at fair value $ 2,234,426,721 $ 2,294,293,957 Total investments 2,234,426,721 2,294,293,957 Receivables:"
	    "In addition, all employer contributions for plan year 2025 were pro-rated through March 21, 2025 for such employees."
	    "The 2025 and 2024 contributions were funded in 2026 and 2025, respectively, except the BATC pro-rated amount that was funded in 2024."
	    "Participant loans at December 31, 2025, had interest rates ranging from 4.25 percent to 9.50 percent."
	    "The following tables set forth the fair value measurements as of December 31, 2025 and 2024, respectively:"
	    "Class IV State Street Target Retirement 121,791,946 2035 Fund;"))
