(:sections nil :text
	   ("Beginning of year 53,475,452 End of year $ 61,055,110 Refer to Notes to Financial Statements."
	    "The forfeited account balances were $20,074 and $19,487 as of December 31, 2025 and 2024, respectively."
	    "No allowance for credit losses has been recorded as of December 31, 2025 or 2024."
	    "Investments as of December 31, 2024 were measured at fair value on a recurring basis (at least annually) as follows:"
	    "THRIFT PLAN NOTES TO FINANCIAL STATEMENTS $23,935,707 and $22,511,211, respectively."
	    "606,455 TOTAL ASSETS (HELD AT END OF YEAR) $ 61,055,036 * Parties-in-interest Note:"))
