(:sections nil :text
	   ("Report for the Calendar Year or Quarter Ended: 06-30-2026"
	    "Name: Newfound Research LLC Address: 200 Central Ave 4th Floor Suite 324 St. Petersburg, FL 33701"
	    "Form 13F File Number: 028-17093 CRD Number (if applicable): 000159064 SEC File Number (if applicable): 801-73042"
	    "Name: Corey Hoffstein Title: Chief Executive Officer Phone: 617-531-9773"
	    "X 13F NOTICE. (Check here if no holdings reported are in this report, and all holdings are reported by other reporting manager(s).)"
	    "Tidal 000164201 801-76857 0001600064 Investments LLC Mutual Fund 811-05010 0000810695 & Variable Insurance Trust RATIONAL 000111452 801-60176 0001143565 ADVISORS, INC."))
