(:sections nil :text
	   ("Report for the Calendar Year or Quarter Ended: 06-30-2026"
	    "Name: WATER ISLAND CAPITAL LLC Address: 104 5TH AVENUE 9TH FLOOR NEW YORK, NY 10011"
	    "Name: Philip E. Channen Title: Chief Compliance Officer Phone: 646-727-4463"
	    "X 13F HOLDINGS REPORT. (Check here if all holdings of this reporting manager are reported in this report.)"
	    "Form 13F Information Table Entry 85 Total:"
	    "Form 13F Information Table Value 1,075,083,365 Total:"))
