(:sections nil :text
	   ("Report for the Calendar Year or Quarter Ended: 09-30-2025"
	    "Name: Scion Asset Management, LLC Address: 20665 4th Street Suite 201 Saratoga, CA 95070"
	    "Form 13F File Number: 028-17276 CRD Number (if applicable): 000167772 SEC File Number (if applicable): 801-113529"
	    "Name: Michael J. Burry Title: Chief Executive Officer Phone: 408-441-8400"
	    "Number of Other Included Managers: 2 Form 13F Information Table Entry 8 Total:"
	    "Form 13F Information Table Value 1,381,198,076 Total:"))
