(:sections
 (("I.1"
   "ITEM 1 IDENTITY OF DIRECTORS, SENIOR MANAGEMENT AND ADVISERS Not appli")
  ("I.2"
   "ITEM 2 OFFER STATISTICS AND EXPECTED TIMETABLE Not applicable.")
  ("I.3" "CAPITALISATION AND INDEBTEDNESS Not applicable."
   "In 2025, there have been no significant changes to the conclusion from 2024."
   "Converting to low-carbon construction materials.")
  ("I.4"
   "Novo Industri A/S was the continuing company and its name was changed to Novo Nordisk A/S."
   "For capital expenditures expected in 2026, reference is made to pages 16-18 in the subsection ‘2026 outlook’ in our Annual Report 2025."
   "The expected amount of expenditures for this facility is approximately DKK 8.5 billion with realised spend of DKK 3.6 billion as of 31 December 2025.")
  ("I.4A" "ITEM 4A UNRESOLVED STAFF COMMENTS None.")
  ("I.5"
   "Further reference is made to ‘Risk management’ on pages 41-42 of our Annual Report 2025."
   "Cash flow in 2025, 2024 and 2023 Reference is made to ’Cash flow statement' on page 84 of our Annual Report 2025."
   "Information about expectations for the financial year 2026 can be found on pages 16-18 in the subsection ‘2026 outlook’.")
  ("I.6" "ITEM 6 DIRECTORS, SENIOR MANAGEMENT AND EMPLOYEES A."
   "Member of the Board of Directors since 2017, stepped down 14 November 2025."
   "In the period from 1 January 2026 until 3 February 2026, no B shares were sold or purchased by the members of the Board of Directors or executives.")
  ("I.7" "ITEM 7 MAJOR SHAREHOLDERS AND RELATED PARTY TRANSACTIONS A."
   "MAJOR SHAREHOLDERS For information on major shareholders reference is made to ‘Shares and capital structure’ on pages 18-19 of our Annual Report 2025."
   "Generally, Euronext does not provide the Company with information with respect to registration.")
  ("I.8" "39% Denmark, 25% North America, 5% UK, and 31% Other."
   "Since 31 December 2025, there have been no further significant transactions with related parties out of the ordinary course of business."
   "INTERESTS OF EXPERTS AND COUNSEL Not applicable.")
  ("I.9"
   "OFFER AND LISTING DETAILS The Company's B shares are listed in Denmark on Nasdaq Copenhagen, and traded under the symbol \"NOVO-B\"."
   "See Exhibit 2.2 to this Form 20-F for a description of the B Shares."
   "MARKETS Reference is made to ‘Shares and capital structure’, on pages 18-19 of our Annual Report 2025.")
  ("I.10" "MEMORANDUM AND ARTICLES OF ASSOCIATION See Exhibit 2.2."
   "+1 (212) 747 9100 In late 2025, the Danish National Tax Tribunal (in Danish:"
   "This Form 20-F is also filed and can be viewed via EDGAR on www.sec.gov.")
  ("I.11"
   "The rates used to mark-to-market the instruments are market data as of 31 December 2025.")
  ("I.12"
   "ITEM 12 DESCRIPTION OF SECURITIES OTHER THAN EQUITY SECURITIES A."
   "Morgan Depositary Receipts Group as Depositary, JPMorgan Chase Bank, N.A., 383 Madison Avenue, Floor 11, New York, United States."
   "See Exhibit 2.1 to this Form 20-F for a description of the rights of holders of the ADRs.")
  ("II.14"
   "ITEM 14 MATERIAL MODIFICATIONS TO THE 29 RIGHTS OF SECURITY HOLDERS AN")
  ("II.15"
   "The Company’s 2025 acquisition of Akero Therapeutics, Inc.")
  ("II.16A"
   "ITEM 16A AUDIT COMMITTEE FINANCIAL EXPERT The Audit Committee is comprised of three members elected by the Board of Directors."
   "Audit Committee member Stephan Engels is designated as both Audit Committee chair, and as Audit Committee financial expert as defined by the SEC."
   "The chair, Stephan Engels is independent as defined by the SEC.")
  ("II.16B"
   "ITEM 16B CODE OF ETHICS Novo Nordisk has a vision and a set of essentials named the Novo Nordisk Way."
   "The Novo Nordisk Way describes who Novo Nordisk as a company is, where Novo Nordisk wants to go and how its employees work.")
  ("II.16C"
   "The audit opinion of Deloitte Statsautoriseret Revisionspartnerselskab (PCAOB no."
   "Under this authorisation, a share repurchase programme for 2024 of DKK 20 billion initiated in February 2024, was completed in February 2025."
   "Our teams are comprised of certified and experienced information systems security professionals and information security managers.")
  ("III.17" "ITEM 17 FINANCIAL STATEMENTS See response to Item 18.")
  ("III.18"
   "The non-IFRS financial measures presented in our Annual Report 2025 are:"
   "Reference is made to the section ‘Non-IFRS financial measures’ on pages 115-118 in our Annual Report 2025."
   "/s/ Deloitte Statsautoriseret Revisionspartnerselskab Copenhagen, Denmark February 4, 2026 We have served as the Company’s auditor since 2021.")
  ("III.19"
   "The term ‘Novo Nordisk A/S’ is used when addressing matters specifically related to this legal entity."
   "Forward-looking statements can be identified by the fact that they do not relate to historical or current facts and include guidance."
   "A substantial portion of the assets of Novo Nordisk A/S, its subsidiaries and such persons are located outside the United States."))
 :text
 ("For capital expenditures expected in 2026, reference is made to pages 16-18 in the subsection ‘2026 outlook’ in our Annual Report 2025."
  "The facility is expected to be gradually finalised from 2026 to 2028 and its production area expected to be 51,100 square metres."
  "Information about expectations for the financial year 2026 can be found on pages 16-18 in the subsection ‘2026 outlook’."
  "Hong Chow Executive vice president, Product & Portfolio Strategy effective 15 February 2026 Born July 1971."
  "Dividends Reference is made to ‘Shares and capital structure’, on pages 18-19 of our Annual Report 2025."
  "Reference is made to the section ‘Non-IFRS financial measures’ on pages 115-118 in our Annual Report 2025."))
