(:sections
 (("I.1"
   "ITEM 1 IDENTITY OF DIRECTORS, SENIOR MANAGEMENT AND ADVISORS Not appli")
  ("I.2"
   "ITEM 2 OFFER STATISTICS AND EXPECTED TIMETABLE Not applicable.")
  ("I.3"
   "dollars in terms of Danish kroner expressed in DKK per USD 1.00."
   "Capitalization and indebtedness Not applicable."
   "Risk factors For information on risk factors, reference is made to our Annual Report 2016 ‘Risk management’ on pages 40-43.")
  ("I.4"
   "ITEM 4 INFORMATION ON THE COMPANY ITEM 4 INFORMATION ON THE COMPANY A."
   "The total sales of NovoLog® Mix/NovoMix® were DKK 10,482 million in 2016 (DKK 11,144 million in 2015)."
   "Novo Industri A/S was the continuing company and its name was changed to Novo Nordisk A/S.")
  ("I.4A" "The facility is expected to be ready for use in 2019."
   "The production area of the facility is 10,300 square meters."
   "The facility will be financed by cash flow from operating activities.")
  ("I.5"
   "New accounting pronouncements Reference is made to Note 1.2 ‘Changes in accounting policies and disclosures’ in our Annual Report 2016."
   "Cash flow in 2016, 2015 and 2014 Reference is made to page 60 ’Statement of cash flows for the year ended 31 December’ in our Annual Report 2016."
   "The other segment of Novo Nordisk is biopharmaceuticals, which comprises haemophilia care, growth hormone therapy and hormone replacement therapy.")
  ("I.6"
   "Key customers in the United States include private payers, PBMs and government payers."
   "Compensation Reference is made to the section ‘Remuneration’ on page 50-53 and Notes 5.1 and 5.2 in our Annual Report 2016 regarding compensation."
   "The Company has not experienced any significant labor disputes.")
  ("I.7"
   "It is estimated that 1,500,000 B shares will be needed for the program."
   "There have not been and there are no loans to members of the Board of Directors or Executive Management in 2016, 2015 or 2014."
   "Interests of experts and counsel Not applicable.")
  ("I.8"
   "ITEM 8 FINANCIAL INFORMATION ITEM 8 FINANCIAL INFORMATION A."
   "At the Annual General Meeting March 23, 2017, the Board of Directors will propose a final dividend of DKK 4.60 for each Novo Nordisk A and B share."
   "Significant changes No significant events have occurred since the date of the annual financial statements.")
  ("I.9"
   "Reference is made to our Annual Report 2016 ‘Shares and capital structure’ on pages 44-45."
   "The B shares have been publicly traded since 1974 and have been listed on Nasdaq Copenhagen since that time."
   "The Nasdaq Copenhagen is the main trading market for the B shares.")
  ("I.10"
   "ITEM 10 ADDITIONAL INFORMATION ITEM 10 ADDITIONAL INFORMATION A."
   "+1 (800) 929 5484 or +1 (212) 747 9100 U.S."
   "The Form 20-F is also filed and can be viewed via EDGAR on www.sec.gov.")
  ("I.11"
   "The rates used to mark-to-market the instruments are market data as of December 30, 2016.")
  ("I.12"
   "In the year ended December 31, 2016, the Depositary reimbursed USD 1,698,710 for costs related to investor relations activities.")
  ("I.12A" "Item 12A. DEBT SECURITIES Not applicable.")
  ("I.12B" "Item 12B. WARRANTS AND RIGHTS Not applicable.")
  ("I.12C"
   "American DEpositary shares Novo Nordisk’s ADR program is administered by J.P."
   "Morgan Depositary Receipts Group as Depositary, JPMorgan Chase Bank, N.A., 4 New York Plaza, New York, United States."
   "dollars and distributes the dividends to the holders of the ADRs.")
  ("II.14"
   "ITEM 14 MATERIAL MODIFICATIONS TO THE RIGHTS OF 33 SECURITY HOLDERS AN")
  ("II.15"
   "ITEM 15 CONTROLS AND PROCEDURES Evaluation of disclosure controls and ")
  ("II.16A"
   "ITEM 16A AUDIT COMMITTEE FINANCIAL EXPERTS The Audit Committee is comprised of four members elected by the Board of Directors."
   "In March 2016, the Board of Directors re-elected the following individuals to the Audit Committee:"
   "Financial expert Liz Hewitt is independent as defined by the SEC.")
  ("II.16B"
   "ITEM 16B CODE OF ETHICS Novo Nordisk has a vision and a set of essentials named the Novo Nordisk Way."
   "The Novo Nordisk Way describes who Novo Nordisk as a company is, where Novo Nordisk wants to go and how its employees work."
   "For further information on the Novo Nordisk Way, reference is made to ‘Doing business the Novo Nordisk Way’ on pages 19-20 in our Annual Report 2016.")
  ("II.16C"
   "Pre-approval policies The Audit Committee assesses and pre-approves all audit and non-audit services provided by the statutory auditors."
   "***) As of February 1, 2016, Novo Nordisk had repurchased a total of 47,739,215 B shares equal to a transaction value of DKK 17,499,999,226."
   "ITEM 16H MINE SAFETY DISCLOSURE Not applicable.")
  ("III.1"
   "A substantial portion of the assets of the Company, its subsidiaries and such persons are located outside the United States.")
  ("III.17" "ITEM 17 FINANCIAL STATEMENTS See response to Item 18.")
  ("III.18"
   "The non-IFRS financial measures presented in our Annual Report 2016 are:"
   "· Operating profit after tax to net operating assets;"
   "The following table shows a reconciliation of free cash flow to ‘Net cash generated from operating activities’.")
  ("III.19"
   "The content of websites, scientific articles and other sources referenced on these pages are not incorporated by reference into this Form 20-F."
   "furnished to the SEC on Form 6-K on February 10, 2016 identified in Item 19.a of the Form 20-F filed on February 10, 2016."
   "Executive Vice Executive Officer President and Chief Financial Officer Bagsværd, Denmark Dated:"))
 :text
 ("Apart from the divestment of NNIT A/S in 2015, no significant divestments took place in the period from 2014–2016."
  "Companies in the Novo Nordisk Group are listed in the Company’s Annual Report 2016 on page 95, ‘Companies in the Novo Nordisk Group.’ D."
  "For further information on trends, reference is made to the section ‘Accomplishments and results 2016’ on pages 1-15 in our Annual Report 2016."
  "24 Novo Nordisk Form 20-F 2016 ITEM 10 ADDITIONAL INFORMATION ITEM 10 ADDITIONAL INFORMATION A."
  "29 Novo Nordisk Form 20-F 2016 ITEM 10 ADDITIONAL INFORMATION Sale or Exchange of ADRs or B Shares A U.S."
  "39 Novo Nordisk Form 20-F 2016 ITEM 17 FINANCIAL STATEMENTS PART III ITEM 17 FINANCIAL STATEMENTS See response to Item 18."))
