(:sections
 (("I.1"
   "Condensed Consolidated Financial Statements (Unaudited) Daré Bioscience, Inc."
   "Liquidation preference of $328,200 and $0 at March 31, 2026 and December 31, 2025, respectively Common stock, $0.0001 par value;"
   "For a discussion of this agreement, see Note 10, Grant Awards.")
  ("I.2"
   "Past operating results are not necessarily indicative of results that may occur in future periods."
   "Section 503B Compounding Our proprietary topical cream formulation of sildenafil is our first product to market under Section 503B."
   "Ovaprene®, an investigational, hormone-free, monthly intravaginal contraceptive currently being evaluated in a pivotal Phase 3 clinical study;")
  ("I.3"
   "Item 3. Quantitative and Qualitative Disclosures About Market Risk Und")
  ("I.4"
   "Item 4. Controls and Procedures Evaluation of Disclosure Controls and ")
  ("II.1"
   "Legal Proceedings From time to time, we may become involved in various claims and legal proceedings.")
  ("II.1A"
   "Risk Factors An investment in shares of our common stock involves a high degree of risk."
   "In these circumstances, the market price of our common stock could decline, and you may lose all or part of your investment."
   "There have been no material changes from the risk factors disclosed in Part I, Item 1A.")
  ("II.2"
   "Item 2. Unregistered Sales of Equity Securities and Use of Proceeds (a")
  ("II.4" "Item 4. Mine Safety Disclosures Not applicable.")
  ("II.5"
   "Item 5. Other Information (a) None. (b) None. (c) During the period fr")
  ("II.6"
   "Exhibits Incorporated by Reference Exhibit Description of Exhibit Form File No."
   "This certification is being furnished solely to accompany this report pursuant to U.S.C."))
 :text
 ("•The terms and conditions of any future strategic collaborations relating to our product candidates;"
  "Cash equivalents (1) $ 18,158,053 $ — $ — $ 18,158,053 Balance at December 31, 2025 Current assets:"
  "A summary of common stock warrants outstanding as of March 31, 2026 and December 31, 2025 is presented below:"
  "The Company recorded a receivable of $0 and $11,000 at March 31, 2026 and December 31, 2025, respectively."
  "The study protocol calls for at least 2,500 cycles of exposure and at least 250 subjects completing 13 menstrual cycles of use."
  "333-278380) declared effective by the SEC on May 10, 2024."))
