(:sections nil :text
	   ("● We face a changing regulatory landscape and increasing compliance costs that must be paid to continue our operations."
	    "To manage the potential growth of our operations and personnel, we will be required to:"
	    "- GPU pricing is typically higher than CPU pricing due to greater processing power."
	    "For the years ended December 31, 2025 and 2024, he was paid $0, and the Company recorded $300,000 as deferred salary payable in each fiscal year."
	    "(“MLM”) in the amounts of $2,219,442, net of reserves of $2,219,442 pursuant to an LOI (see Note 4 – Note Receivable)."
	    "F-18 On January 9, 2025, the Company negotiated the settlement of both notes with the lender and agreed to pay $125,000 to settle both notes in full."))
