(:sections nil :text
	   ("Date of Earliest Transaction (Month/Day/Year) 08/24/2015 4."
	    "Amended Employee Stock Purchase Plan (\"ESPP\") for the ESPP purchase period of August 1, 2014 through January 31, 2015."
	    "Fifty percent of the restricted stock units subject to the award vested on August 24, 2013, and the remaining 50% vested on August 24, 2015."
	    "** Intentional misstatements or omissions of facts constitute Federal Criminal Violations See 18 U.S.C."))
