(:sections nil :text
	   ("The Commission estimates that the burden of completing Form N-17f-2 is approximately 1.0 hours per filing."
	    "This collection of information has been reviewed by the Office of Management and Budget in accordance with the clearance requirements of 44 U.S.C."
	    "Our opinion on the Fund’s compliance with the Specified Requirements does not extend to any other information that accompanies or contains our report."
	    "Management’s responsibilities Management of the Fund is responsible for:"
	    "Our responsibilities The attestation standards established by the American Institute of Certified Public Accountants require us to:"
	    "Our examination does not provide a legal determination on the Fund’s compliance with the Specified Requirements."))
