(:sections nil :text
	   ("3235-0359 Expires:January 31, 2027 Estimated average burden hours per response 1.5 1."
	    "The Commission estimates that the burden of completing Form N-17f-1 is approximately 0.16 hours per filing."
	    "This collection of information has been reviewed by the Office of Management and Budget in accordance with the clearance requirements of 44 U.S.C."
	    "The Funds’ management is responsible for its assertion."
	    "An examination involves performing procedures to obtain evidence about whether management's assertion is fairly stated in all material respects."))
