(:sections
 (("1"
   "Name of Insured (the “Insured”) Bond Number 1290 Funds 02634226B Principal Office:")
  ("2"
   "Item 2. Bond Period: from 12:01 a.m. on April 27, 2026 , to 12:01 a.m.")
  ("3" "Limit of Liability— Subject to Sections 9, 10 and 12 hereof:"
   "OPTIONAL INSURING AGREEMENTS ADDED BY RIDER:")
  ("4"
   "Item 4. Offices or Premises Covered--All the Insured’s offices or othe")
  ("5"
   "1-2-3-4-5-6-7-8 and of all Riders applicable to this Bond issued during the Bond Period."
   "Effective November 29, 2023, the name of the 1290 Retirement 2060 Fund is changed to 1290 Avantis U.S."
   "1290 Funds, AXA Equitable Funds Management Group, LLC, doing business as “1290 Asset Managers” on behalf of each of its Funds By:"))
 :text
 ("2 Blanket Bond (05/23) ---------------------------------------------------------------------------------------------------- E."
  "13 Blanket Bond (05/23) ---------------------------------------------------------------------------------------------------- SECTION 3."
  "(1) is committed by any Unauthorized Third Party anywhere, alone or in collusion with other Unauthorized Third Parties;"
  "Effective November 29, 2023, the name of the 1290 Retirement 2060 Fund is changed to 1290 Avantis U.S."
  "7, effective as of July 16, 2020 (“Amendment No."))
