(:sections nil :text
	   ("No form having been prescribed by the Commission, the Applicants proceed under Rule 0-2 under the 1940 Act."
	    "The Applicants may also offer Interests to such persons in reliance on Section 4 (a)(2) or Regulation D."
	    "In addition, a Partnership may acquire shares of money market funds in compliance with Rule 12d1-1 under the 1940 Act."
	    "_________________ 11 “Audit” will have the meaning defined in Rule l-02(d) of Regulation S-X."
	    "In summary, the requested relief under Section 17(d) of the 1940 Act is necessary in light of the purpose of each Partnership."
	    "The Applicants named below have caused this Application to be duly signed on their behalf on July 16, 2026."))
