(:sections nil :text
	   ("Turner, 11785 Beltsville Drive, Suite, 1600, Beltsville, Maryland 20705 (301) 572-7800 Note:"
	    "Federated Investment Management Company and Federated Investment Counseling, Federated Investors Tower, Pittsburgh, PA 15222 12."
	    "$213,811.47 (b) How were those expenses allocated? N/A."
	    "The undersigned also states that the facts set forth in this Form N-8F application are true to the best of his knowledge, information, and belief."))
