(:sections nil :text
	   ("35463 (January 29, 2025) (Notice) and 35478 (February 25, 2025) (Order) (the “Tweedy Order”);"
	    "34293 (June 2, 2021) (Notice) and 34321 (June 29, 2021) (Order) (“LFT Order”)."
	    "The terms of the Investment Advisory Agreements comply or will comply with Section 15(a) of the 1940 Act."
	    "253 (1940) (statement of David Schenker)."
	    "33169 (July 24, 2018) (notice) and 33207 (August 21, 2018) (order);"
	    "Applicants desire that the Commission issue the requested order pursuant to Rule 0-5 under the 1940 Act without conducting a hearing."))
