(:sections nil :text
	   ("Johnson, Corporate Secretary 613-241-2828 Ext."
	    "(\"Shopify\", \"we\", \"our\", the \"Company\" or the \"Registrant\") for the year ended December 31, 2023, at the time of filing with the U.S."
	    "333-204568), the Registration Statement on Form S-8 of the Registrant, which was originally filed with the Commission on May 12, 2016 (File No."
	    "333-258230), the Registration Statement on Form S-8 of the Registrant, which was originally filed with the Commission on July 20, 2022 (File No."))
