(:sections nil :text
	   ("Employer Identification Number (if applicable)) 150 Elgin Street, 8th Floor Ottawa, Ontario, Canada K2P 1L4 Attention:"
	    "(\"Shopify\", \"we\", \"our\", the \"Company\" or the \"Registrant\") for the year ended December 31, 2016, at the time of filing with the U.S."
	    "The forward-looking statements represent the Company's views as of the date of this annual report on Form 40-F."
	    "the securities registered pursuant to Form 40-F;"))
