(:sections nil :text
	   ("(Exact name of registrant as specified in its charter) Canada 1311,1321,2911, 98-0343201 (Province or other 4613,5171,5172 (I.R.S."
	    "Common Shares As of December 31, 2025 there were 1,193,519,494 Common Shares issued and outstanding Indicate by check mark whether the registrant:"
	    "DISCLOSURE CONTROLS AND PROCEDURES AND INTERNAL CONTROL OVER FINANCIAL REPORTING See pages 1 and 2 of Exhibit 99-2 and page 54 of Exhibit 99-3."
	    "for the fiscal year ended December 31, 2025 dated February 25, 2026 99-2 Audited Consolidated Financial Statements of Suncor Energy Inc."))
