(:sections nil :text
	   ("(2) Includes one share of Common stock and one share of Class B Common stock, which is convertible into one share of Common stock."
	    "(a) our Annual Report on Form 10-K for the fiscal year ended December 31, 2025, filed with the SEC on February 27, 2026;"
	    "See the section entitled “Where You Can Find More Information” found on page 9."
	    "Our principal executive office is located at 2665 South Bayshore Drive, Suite 901, Miami, Florida 33133, and our telephone number is (305) 714-4100."
	    "We have not made an election in our Amended and Restated Articles of Incorporation to opt out of Section 607.0901."
	    "(a) our Annual Report on Form 10-K for the fiscal year ended December 31, 2023, filed with the SEC on February 23, 2024;"))
