(:sections nil :text
	   ("Rochester, NY 14607 (207) 629-1190 Trustee:"
	    "The recovery charges will be segregated only when the servicer remits them to the trustee."
	    "Since April 2024, overdue accounts greater than 30 days has shown a decline."
	    "79 ---------------------------------------------------------------------------------------------------- Table of Contents THE TRUSTEE U.S."
	    "In that regard, the issuing entity will note that the bankruptcy court in In re LTV Steel Company, Inc., et al., 274 B.R."
	    "As a result of such exclusion, the issuing entity will not be subject to regulation as an investment company under the 1940 Act."))
