(:sections nil :text
	   ("“RPL” means Rectitude Pte Ltd, a company incorporated in Singapore on December 26, 1997, and a wholly owned subsidiary of our Company."
	    "In addition, we are guided by a set of safety regulations imposed on us as described in the “Regulatory Environment” section on page 56 below."
	    "The Circuit Breaker Measures were imposed under the COVID-19 Regulations during the period between April 7, 2020 and June 1, 2020 (inclusive)."
	    "Exemption from Section 16 rules regarding sales of ordinary shares by insiders, which will provide less data in this regard than shareholders of U.S."
	    "84 Sale or Other Disposition of Ordinary Shares A U.S."))
