(:sections
 (("2"
   "001-13643) for the year ended December 31, 2025, filed on February 24, 2026;"
   "001-13643) filed on January 26, 2026 (Items 5.02 and 9.01), March 25, 2026 (Items 5.02 and 9.01) and May 21, 2026 (Item 5.07);"
   "The exercise price for warrants will be subject to adjustment as described in the applicable prospectus supplement."))
 :text
 ("Holders that hold our common stock as a “capital asset” within the meaning of Section 1221 of the Code (generally, property held for investment)."
  "Holder owned 5% or more of our common stock at any time during the applicable period, a Non-U.S."
  " “common stock” mean our common stock, par value $0.01 per share;"
  "We have summarized the material terms and provisions of the Indentures in this section."
  "13 ---------------------------------------------------------------------------------------------------- Table of Contents  corporate existence;"
  "The depositary will have its principal office in the United States and a combined capital of at least $50,000,000."))
