(:sections nil :text
	   ("August 6, 2026 Original Interest Accrual March 15, 2026 Date:"
	    "The Treasury Rate shall be determined by us after 4:15 p.m., New York City time (or after such time as yields on U.S."
	    "No Notes of a principal amount of $1,000 or less will be redeemed in part."
	    "Morgan Securities LLC $ 50,000,000 Mizuho Securities USA LLC 40,000,000 MUFG Securities Americas Inc."
	    "The expenses of the sale of the Notes, not including discounts, are estimated at $575,000 and are payable by us."))
