(:sections nil :text
	   ("Pre-Funded Warrants offered by us 1,111,250 Pre-Funded Warrants to purchase up to 1,111,250 Class A Ordinary Shares."
	    "S-19 PROSPECTUS $200,000,000 * SINGULARITY FUTURE TECHNOLOGY LTD."
	    "and ● Lack of proper oversight for the Company’s cash disbursement process that led to misuse of the Company funds by its former executive."
	    "Previous court decisions may be cited as persuasive authority but do not have a binding effect."
	    "Our transfer agent’s phone number is (303) 662-1112 and facsimile number is (727) 269-5616."
	    "and ● any other information we think is important about the share purchase contracts or the share purchase units."))
