(:sections nil :text
	   ("As of May 13, 2026 the Fund had $50,000,000 available to be borrowed and $0 outstanding borrowings under the Credit Facility."
	    "Failure to comply with such requirements could result in rescission rights and monetary and other sanctions."
	    "46 Portfolio Managers The portfolio managers who are primarily responsible for the day-to-day management of our portfolio are as follows:"
	    "As of May 13, 2026, this stockholder held more than 5% of the outstanding shares of the Fund."))
