(:sections nil :text
	   ("· The notes may be purchased in minimum denominations of $1,000 and in integral multiples of $1,000 thereafter."
	    "http://www.sec.gov/Archives/edgar/data/19617/000095010326005889/crt_dp245141-424b2.pdf Our Central Index Key, or CIK, on the SEC website is 19617."
	    "· in a bankruptcy proceeding under Chapter 11 of the U.S."
	    "Callable Fixed Rate Notes PS-3 Selected Risk Considerations An investment in the notes involves significant risks."
	    "· LACK OF LIQUIDITY — The notes will not be listed on any securities exchange."
	    "federal income tax consequences of owning and disposing of the notes."))
