(:sections nil :text
	   ("will receive commissions from the Issuer of up to $9.25 per $1,000 principal amount Note."
	    "Bail-in Power in circumstances in which the relevant U.K."
	    "●You understand and are willing and able to accept the risks associated with an investment linked to the performance of the Reference Asset."
	    "Even if there is a secondary market, it may not provide enough liquidity to allow you to trade or sell the Notes easily."
	    "holders should be required to provide a Form W-8 in order to avoid 30% U.S."))
