(:sections nil :text
	   ("The amounts of any such adjustments could have a material adverse effect on the Companys results of operations or cash flows in a given period."
	    "We had cash of $21.5 million as of December 31, 2023 which is held for working capital and general corporate purposes."
	    "McGetrick qualifies as an audit committee financial expert as such term is defined in Item 407(d)(5) of Regulation S-K."
	    "In addition, it does not address consequences relevant to Non-U.S."
	    "As a result of ASU 2022-06 deferring the sunset date, ASC 848 is effective through December 31, 2024."))
