(:sections nil :text
	   ("Our authorized capital consists of 4,000,000,000 shares of common stock and 100,000,000 shares of preferred stock."
	    "The lease term is from October 1, 2022 to September 30, 2026."
	    "As a result, there were 3,877,282,251 shares of our Common Stock and no shares of preferred stock issued and outstanding on May 11, 2023."
	    "The 3F product is made from specialized oils sourced from botanicals that insects avoid."
	    "As of December 31, 2023 the Company has deemed that no reserve on credit losses were necessary."))
