(:sections nil :text
	   ("$1,000 + ($1,000 × reference asset performance of the least performing reference asset)."
	    "The Historical Performance of the Reference Assets Should Not Be Taken as an Indication of Its Future Performance."
	    "Any IWF change resulting in an IWF of 0.96 or greater is rounded up to 1.00 at the next annual IWF review."
	    "The RTY consists of the smallest 2,000 companies, by market capitalization, included in the Russell 3000® Index."
	    "Each component’s weight is capped at 10% of the EURO STOXX 50® Index’s total free float market capitalization."
	    "This summary supplements the section “U.S."))
