(:sections
 (("2"
   "Item 2.02 or 7.01 of Form 8-K are not incorporated herein by reference."
   "Odyssey Marine Exploration, Inc., 205 South Hoover Boulevard, Suite 210, Tampa, Florida 33609, Attention:"
   "Information available on or through our website is not a part of this prospectus."))
 :text
 ("For the year ended December 31, 2023, our revenue and loss from operations were $804,000 and $10.3 million, respectively."
  "We have experienced a loss from operations in every fiscal year since our inception except for 2004."
  "We may be unsuccessful in raising the necessary capital to fund operations and capital expenditures."
  "As a result, we may be unable to anticipate these incidents or techniques, timely discover them, or implement adequate preventative measures."
  "1,241,747 1,241,747 0 (1) Corbin Capital Partners, L.P."
  " our Annual Report on Form 10-K for the year ended December 31, 2023, filed with the SEC on May 17, 2024;"))
