(:sections nil :text
	   ("159.60 (100.00% of the Starting Value) Call Amounts (per Unit) and $10.90, representing a Call Call Premiums:"
	    "§ If the notes are not called, you accept that your investment will result in a loss, which could be significant."
	    "Therefore, the notes will be called at $10.00 plus the Call Premium of $0.90 = $10.90 per unit."
	    "The level of the Index reflects the total market value of all index stocks relative to the index’s base period of 1941-1943."))
