(:sections nil :text
	   ("The S&P 500® Futures 35% VT Adaptive Response 6% Decrement Index (USD) ER (current Bloomberg symbol:"
	    "LLC August 2026 S&P 500® Futures 35% VT Adaptive Response 6% Decrement Index (USD) ER Supplement Addendum dated August 7, 2026."
	    "The percentage of index exposure to the S&P 500® Futures Excess Return Index on July 31, 2026 is 278.59%."
	    "· S&P 500® Futures Adaptive Response Indices Supplement No."
	    "The information contained in this index supplement addendum, the accompanying S&P 500® Futures Adaptive Response Indices Supplement No."))
