(:sections nil :text
	   ("USE OF HYPOTHETICAL BACKTESTED RETURNS Any backtested historical performance and weighting information included herein is hypothetical."
	    "An affiliate of ours has a 10% ownership interest in the Index Sponsor."
	    "No assurance can be given that the Index will maintain an annualized realized volatility that approximates its target volatility of 35%."
	    " The Index was established on June 22, 2021, has a limited operating history and may perform in unanticipated ways."
	    " The accuracy or completeness of the EURO STOXX 50 ® Index and its data;"))
