(:sections nil :text
	   ("In addition, KLs ability to receive higher fees and reimbursements depends on our continued investment in land assets and other real estate assets."
	    "For Future Property Assets that fall within Type 2, we may, at KLs discretion, accept any transactions presented to us."
	    "Kennedy Lewis launched a Land Banking strategy in June 2021."
	    "We expect the Record Date to be on January 21, 2025."))
