(:sections
 (("28"
   "(a)(2) Certificate of Amendment to the Trust Instrument, is incorporated herein by reference to Post-Effective Amendment No."
   "196 to the Registrant’s Registration Statement on Form N-1A filed on October 28, 2025."
   "(q) Copy of Powers of Attorney, is incorporated by reference to Post-Effective Amendment No.")
  ("29"
   "ITEM 29. Persons Controlled by or Under Common Control with the Regist")
  ("30"
   "The Registrant may, from time to time, enter other contractual arrangements that provide for indemnification."
   "Securities and Exchange Commission such indemnification is against public policy as expressed in the 1933 Act and is, therefore, unenforceable.")
  ("31" "Name of Investment Adviser Form ADV File No.")
  ("32"
   "Principal Underwriter (a) The principal underwriter and distributor for the Registrant is Matrix 360 Distributors, LLC."
   "To the best of the Registrant’s knowledge, Matrix 360 Distributors, LLC also acts as principal underwriter to:"
   "Tactical Investment Series Trust and Leader Funds Trust.")
  ("33"
   "ITEM 33. Location of Accounts and Records The accounts, books, or othe")
  ("34"
   "ITEM 34. Management Services There are no management-related service c")
  ("35" "Poppen, Trustee Date * June 25, 2026 Thomas J."
   "Schmidt, Trustee Date * June 25, 2026 Tom M."
   "Beaver, Jr., Treasurer and Principal Financial Officer Date * By:"))
 :text
 ("Average Annual Total Returns (for the periods ended December 31, 2025) One Year Since Inception 10/22/2024 M3Sixty Onchain U.S."
  "DISTRIBUTION OF SHARES Matrix 360 Distributors, LLC (the “Distributor”) is the Fund’s principal underwriter."
  "The address of each trustee and officer is 4300 Shawnee Mission Parkway, Suite 100, Fairway, Kansas 66205."
  "The maximum tax rate on capital gain dividends individuals receive is generally 20%."))
