(:sections
 (("28"
   "(2) Declaration of Trust of the Registrant, dated as of January 23, 2023, was previously filed with Pre-Effective Amendment No."
   "17 to the Registrant’s registration statement on Form N-1A on October 27, 2025 and is hereby incorporated by reference."
   "(2) Power of Attorney, dated April 22, 2026, for Mr.")
  ("29"
   "Item 29. Persons Controlled by or under Common Control with the Fund A")
  ("30"
   "Indemnification Article IX of the Registrant’s Amended and Restated Declaration of Trust states:"
   "Limitation of Liability of Trustees and Others."
   "(c) Limitation of Liability to Trust and Series.")
  ("31"
   "Adviser / Location Role Funds Advised / Form ADV Sub-Adviser Sub-Advised File No."
   "Atlas Capital Team 6 East 1st Street Investment Adviser Atlas America Fund 801-130378 Inc."
   "Square Small-Mid Cap Value ETF 5th Floor La Jolla, CA 92037 Brandes International ETF Brandes U.S.")
  ("32"
   "ActivePassive Core Bond ETF, Series of Trust for Professional Managers 4."
   "The Distributor’s main business address is 190 Middle Street, Suite 301, Portland, Maine 04101."
   "Edelman 190 Middle Street, Suite Secretary None 301, Portland, ME 04101 Susan L.")
  ("33"
   "6 East 1st Street, Suite 5A New York, New York 10003 Brandes Investment Partners, L.P."
   "388 Greenwich Street New York, NY 10013 Foreside Fund Services, LLC 190 Middle Street, Suite 301 Portland, Maine 04101 Tidal Investments LLC 234 W."
   "Florida Street, Suite 700 Milwaukee, Wisconsin 53204 Transamerica Asset Management, Inc.")
  ("34" "Item 34. Management Services Not Applicable.")
  ("35"
   "Lydon, Jr.* Member of the Board of Trustees April 27, 2026 Thomas F."))
 :text
 ("government securities, term deposits, repurchase agreements collateralized by such securities, money market funds, and high-quality debt investments."
  "NON-DIVERSIFICATION The Fund is classified as a non-diversified investment company under the Investment Company Act of 1940 (the “1940 Act”)."
  "standards and, therefore, disclosure of certain material information may not be made, may be less available, or may be less reliable."
  "Street Global Trustee of The Advisors, Funds 2023 ETF Series Distributors, Trust II LLC (2017-2023) (2023-2025);"
  "61 As of December 31, 2025, the Fund did not have long-term and short-term capital loss carryovers."
  "Syracuse Investment Adviser Harrison Street 801-72298 Private Wealth LLC Street Infrastructure Active ETF Suite 1100 Denver, Colorado 80237 Item 32."))
