(:sections
 (("25" "Financial Statements and Exhibits (1) Financial Statements:"
   "333-240039 and 811-23579) filed on July 23, 2020."
   "333-250039 and 811-23579) filed on April 28, 2026.")
  ("26" "Item 26. Marketing Arrangements Not applicable.")
  ("27"
   "Item 27. Other Expenses of Issuance and Distribution Not applicable.")
  ("28"
   "Information regarding the ownership of Flat Rock Global LLC is set forth in its Form ADV as filed with the SEC (File No.")
  ("29"
   "Item 29. Number of Holders of Securities Number of Holders of Securiti")
  ("30"
   "Item 30. Indemnification Reference is made to Article VIII, Section 2 ")
  ("31" "801-110612), and is incorporated herein by reference.")
  ("32"
   "Bank, the Fund’s custodian, maintains certain required accounting related and financial books and records of the Registrant at 1555 N."
   "Riverside Drive, Suite 302, Milwaukee, Wisconsin 53212."
   "The other required books and records are maintained by the Adviser at 680 S.")
  ("33" "Item 33. Management Services Not Applicable.")
  ("34"
   "(a) to file, during any period in which offers or sales are being made, a post-effective amendment to the registration statement:"
   "or C-3 (2) if the Registrant is subject to Rule 430C [17 CFR 230.430C]:"
   "1 to the Registration Statement filed on December 16, 2022 and incorporated herein by reference."))
 :text
 ("4 The Adviser managed the Predecessor Fund since its inception in 2017."
  "21 Credit risk may change over the life of an instrument, and debt obligations which are rated by rating agencies may be subject to downgrade."
  "Quarterly repurchases will occur in the months of January, April, July and October starting in January 2021."
  "The Fund may be dissolved at any time by vote of a majority of the shares of the Fund entitled to vote on the matter."
  "Box 847 Flat Rock Enhanced Income Morrisville, NC Fund and Flat Rock Global, 27560 LLC (since 2022);"
  "or in accordance with the Fund’s Trust Agreement and Section 23 of the 1940 Act and Rule 23c-2 thereunder."))
