(:sections
 (("25" "Financial Statements and Exhibits (1) Financial Statements:"
   "333-262496 and 811-23778, filed May 12, 2022."
   "5 to the Registrant’s Registration Statement on Form N-2, SEC File No.")
  ("26"
   "Item 26. Marketing Arrangements The information contained under the he")
  ("27"
   "Item 27. Other Expenses of Issuance or Distribution Not applicable.")
  ("28"
   "Item 28. Persons Controlled by or Under Common Control with the Regist")
  ("29" "Number of Holders of Securities As of [ ], 2026:")
  ("30"
   "Indemnification Reference is made to Article VII of the Amended and Restated Declaration of Trust filed as an exhibit herewith."
   "Pursuant to Rule 484 under the Securities Act of 1933, as amended, the Registrant furnishes the following undertaking:")
  ("31"
   "Business and Other Connections of Investment Advisor See “Management” in the Statement of Additional Information.")
  ("32"
   "Item 32. Location of Accounts and Records The books, accounts and othe")
  ("33" "Item 33. Management Services Not applicable.")
  ("34"
   "To file, during any period in which offers or sales are being made, a post-effective amendment to the registration statement:"
   "Petersburg, and the State of Florida, on the 30th day of July 2026."
   "Cox Treasurer, Principal Accounting July 30, 2026 Officer and Principal Finance William C."))
 :text
 ("Dechert LLP 200 Central Avenue Suite 220 1095 Avenue of the Americas St."
  "2 to Amended and Restated Declaration of Trust dated April 6, 2026.(9) (b) Bylaws dated April 27, 2022.(2) (c) Not applicable."
  "333-262496 and 811-23778, filed May 12, 2022."
  "333-262496 and 811-23778, filed November 20, 2024."
  "Pursuant to Rule 484 under the Securities Act of 1933, as amended, the Registrant furnishes the following undertaking:"
  "Petersburg, and the State of Florida, on the 30th day of July 2026."))
