(:sections
 (("25" "Financial Statements and Exhibits (1) Financial Statements:"
   "(a) Audited Consolidated Financial Statements of Coller Secondaries Private Equity Opportunities Fund for the period ended March 31, 2026(6) Part B:"
   "(6) Incorporated herein by reference to the Registrant’s Annual Report on Form N-CSR, filed on June 5, 2026.")
  ("26"
   "Item 26. Marketing Arrangements See the Distribution Agreement and Dea")
  ("27"
   "Item 27. Other Expenses of Issuance and Distribution Not applicable.")
  ("28"
   "Persons Controlled by or Under Common Control with the Registrant As of March 31, 2026, each of C-SPEF Holdings, L.P."
   "(each, a “Subsidiary” and together, the “Subsidiaries”) are wholly owned by the Registrant."
   "Additional information regarding the Adviser is set out in its Form ADV, as filed with the Securities and Exchange Commission (SEC File No.")
  ("29" "Number of Holders of Securities As of June 1, 2026:")
  ("30"
   "Item 30. Indemnification Reference is made to Article V of Registrant’")
  ("31"
   "Business and Other Connections of Investment Adviser See “Management of the Fund” in Part B."
   "801-128738), and is incorporated herein by reference.")
  ("32"
   "Item 32. Location of Accounts and Records All accounts, books, records")
  ("33" "Item 33. Management Services Not applicable.")
  ("34"
   "(a) to file, during any period in which offers or sales are being made, a post-effective amendment to the registration statement:"
   "(1) to include any prospectus required by Section 10(a)(3) of the Securities Act;"
   "Principal Financial Officer and Treasurer By:"))
 :text
 ("8 In addition, certain provisions of the 1940 Act prohibit C-SPEF from engaging in transactions with the Adviser and its affiliates;"
  "The Adviser makes assumptions that are based on market conditions existing at the Determination Date."
  "87 A sale of Shares pursuant to a repurchase of Shares by C-SPEF will result in a “substantially disproportionate” redemption with respect to a U.S."
  "Once this payment is made, neither party has any further obligations on the contract."
  "The modifier 1 indicates that the obligation ranks in the higher end of its generic rating category;"))
