(:sections nil :text
	   ("stock market, which could cause the Underlying Index and Market Reference to perform differently from the overall stock market."
	    "•the trust receiving a payment of $10.00 per unit on the ITM Purchased Call Options;"
	    "Even if there are significant increases in the Market Reference Level, the amount you may receive is capped at $12.31 per trust unit."
	    "Section 1258 of the Code requires the gain from conversion transactions to be recharacterized as ordinary income."
	    "The prospectus for each trust provides additional information regarding each trust’s objective and investment strategy."
	    "The amount of this “creation and development fee” is set forth in the prospectus."))
