(:sections nil :text
	   ("1290 GAMCO Small/Mid Cap Value 1290 FUNDS® 1290 Avantis® U.S."
	    "The purpose of this Supplement is to notify you that on March 26, 2026, Equitable Holdings, Inc."
	    "(“EQH”), the parent company of the Funds’ investment adviser, and Corebridge Financial, Inc."
	    "(“Corebridge”) announced that they have entered into a definitive agreement to merge (the “Transaction”)."
	    "As a result, the closing of the Transaction will cause the Investment Advisory Agreement to terminate automatically in accordance with its terms."))
