(:sections nil :text
	   ("Now Trading on Nasdaq as PWRL Preview Text:"
	    "begin trading on the Nasdaq today under the ticker “PWRL” - an incredible milestone for the entire team."
	    "It is, however, a vehicle designed to give investors a new way to access a category of companies that has historically been hard to reach."
	    "Today is the next step in a journey that you have been part of and for that, I am deeply grateful."
	    "This and other information is in the prospectus, available on EDGAR at sec.gov."
	    "There is no assurance the Fund will achieve its investment objective."))
