(:sections nil :text
	   ("The Example assumes that you invest $10,000 in the Fund for the time periods indicated and then redeem all of your shares at the end of those periods."
	    "national securities exchanges, including through American Depositary Receipts (“ADRs”), which are U.S."
	    "For additional information on these indices, please see “Descriptions of Indices” on page 68 of the Prospectus."
	    "Pacific time on Monday through Thursday or between 9:00 a.m."
	    "Box 219381, Kansas City, MO 64121-9381) or by calling the Transfer Agent at 1-800-261-6950 between 9:00 a.m."))
