(:sections nil :text
	   ("● The lowest Cap that we may establish if we add a new Index Option to the Contract is 0.25%."
	    "A negative Performance Credit means that you can lose principal and previous earnings."
	    "Index Year – a twelve-month period beginning on the Index Effective Date or a subsequent Index Anniversary."
	    "• Withdrawals are subject to income taxes, and may also be subject to a 10% additional federal tax for amounts withdrawn before age 59 1∕2."
	    "• The 10% and 30% Buffers for the currently available Index Options do not change."
	    "large-cap 1-year Point-to-point 30% Buffer 1.50% minimum equities with Cap Cap Russell 2000® U.S."))
