(:sections nil :text
	   ("Election of Two (2) Corporate Auditors Nominee Name For Against Abstain Takeharu Kato 8,468,446 1,192 24 Yashiro Imamura 8,468,446 1,192 24 6."
	    "Resignation of Corporate Auditors Corporate auditors Kensuke Okabe and Hideki Nakamura resigned effective March 27, 2026."
	    "They have advised that their resignations were not a result of any disagreement relating to the Company’s operations, policies, or practices."))
