(:sections
 (("1" "Description of Registrant’s Securities to be Registered.")
  ("2"
   "Exhibit Description Number 4.1 Indenture, dated as of November 29, 2012, between Amazon.com, Inc."
   "/s/ Antonio Masone Antonio Masone Vice President and Treasurer Dated:"))
 :text
 ("8-A12B 1 tm2625860d1_8a12b.htm 8-A12B UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington, D.C."
  "333-293246 Securities to be registered pursuant to Section 12(g) of the Act:"
  "Exhibit Description Number 4.1 Indenture, dated as of November 29, 2012, between Amazon.com, Inc."
  "/s/ Antonio Masone Antonio Masone Vice President and Treasurer Dated:"))
