(:sections
 (("2.02" "Item 2.02 Results of Operations and Financial Condition."
   "(“Apple”) issued a press release regarding Apple’s financial results for its third fiscal quarter ended June 27, 2026."
   "A copy of Apple’s press release is attached hereto as Exhibit 99.1.")
  ("9.01" "Item 9.01 Financial Statements and Exhibits."
   "Exhibit Exhibit Description Number 99.1 Press release issued by Apple Inc."
   "104 Inline XBRL for the cover page of this Current Report on Form 8-K."))
 :text
 ("(Exact name of Registrant as specified in its charter) California 001-36743 94-2404110 (State or other jurisdiction (Commission (I.R.S."
  "(“Apple”) issued a press release regarding Apple’s financial results for its third fiscal quarter ended June 27, 2026."
  "104 Inline XBRL for the cover page of this Current Report on Form 8-K."))
