(:sections
 (("8.01" "333-188191) (the Registration Statement)."
   "The 2024 Notes will mature on January 17, 2024, and the 2027 Notes will mature on September 17, 2027."
   "The Indenture is filed as Exhibit 4.1 to the Registration Statement.")
  ("9.01" "Item 9.01 Financial Statements and Exhibits."
   "(d) Exhibits Exhibit Exhibit Description Number 1.1 Underwriting Agreement, dated as of September 10, 2015, between Apple Inc."))
 :text
 ("The 2024 Notes will mature on January 17, 2024, and the 2027 Notes will mature on September 17, 2027."
  "(d) Exhibits Exhibit Exhibit Description Number 1.1 Underwriting Agreement, dated as of September 10, 2015, between Apple Inc."))
