(:sections
 (("1.01" "Item 1.01 Entry into a Material Definitive Agreement."
   "The information included under the Explanatory Note of this Current Report on Form 8-K is incorporated by reference into this Item 1.01.")
  ("3.01"
   "Item 3.01 Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard;")
  ("3.02" "Item 3.02 Unregistered Sales of Equity Securities.")
  ("3.03"
   "Item 3.03 Material Modification to Rights of Security Holders.")
  ("5.01" "Item 5.01 Changes in Control of Registrant.")
  ("5.02" "Item 5.02 Departure of Directors or Certain Officers;"
   "Ashlie Thorburn, can be found under Item 6A of the Annual Report on Form 20-F filed by Nova Minerals with the SEC on September 19, 2025."
   "Indemnification Agreements US Holdco will enter into indemnification agreements with each of the directors and executive officers of US Holdco.")
  ("5.03"
   "Item 5.03 Amendments to Articles of Incorporation or Bylaws;")
  ("5.05"
   "Item 5.05 Amendments to the Registrant’s Code of Ethics, or Waiver of a Provision of the Code of Ethics."
   "The Code will be made available on US Holdco’s website at www.novamineralscorp.com under the section “Corporate Governance”.")
  ("8.01"
   "time), US Holdco issued a press release announcing the completion of the Redomiciliation and related information."
   "A copy of the press release is filed as Exhibit 99.2 to this Current Report on Form 8-K and is incorporated herein by reference."
   "US Holdco hereby reports this succession in accordance with Rule 12g-3(f) under the Exchange Act.")
  ("9.01"
   "2.2 Deed of Amendment and Restatement to Scheme Implementation Deed, dated March 30, 2026, between Nova Minerals Limited and Nova Minerals Corp."
   "99.2 Press Release, dated June 16, 2026."
   "June 16, 2026 /s/ Christopher Gerteisen Name:"))
 :text
 ("The CUSIPs for US Holdco Common Stock and US Holdco Warrants are 66982H105 and 66982H113, respectively."
  "The information included under the Explanatory Note and Item 8.01 of this Current Report on Form 8-K is incorporated by reference into this Item 5.01."
  "Ashlie Thorburn, can be found under Item 6A of the Annual Report on Form 20-F filed by Nova Minerals with the SEC on September 19, 2025."
  "● Richard Beazley is a Class I director, and his initial term will expire at the annual meeting of stockholders to be held in 2027;"
  "Computershare’s address is 150 Royall Street, Canton, Massachusetts 02021."
  "99.2 Press Release, dated June 16, 2026."))
