(:sections
 (("1.01" "Item 1.01 Entry into a Material Definitive Agreement."
   "As of the date of the Merger Agreement, the Specified Stockholders collectively held approximately 38.9% of the total voting power of the Shares."
   "It is not intended to provide any other factual information about the parties.")
  ("7"
   "(iii) failure to realize the anticipated benefits of the Merger;"
   "(iv) failure to realize expected benefits from MiMedx’s other business strategies;"
   "You may obtain free copies of these documents from Sanara and MiMedx using the sources indicated above.")
  ("7.01"
   "On July 29, 2026, MiMedx issued a press release announcing its entry into the Merger Agreement (the “Merger Press Release”)."
   "A copy of the Merger Press Release is furnished as Exhibit 99.1 and is incorporated herein by reference.")
  ("9.01" "Item 9.01 Financial Statements and Exhibits."
   "(incorporated by reference to Exhibit 2.1 of the Registrant’s Current Report on Form 8-K filed on July 29, 2026)."
   "The Company hereby undertakes to furnish supplemental copies of any of the omitted schedules upon request by the SEC."))
 :text
 ("Item 1.01 Entry into a Material Definitive Agreement."
  "On July 29, 2026, MiMedx issued a press release announcing its entry into the Merger Agreement (the “Merger Press Release”)."
  "(iii) failure to realize the anticipated benefits of the Merger;"
  "(incorporated by reference to Exhibit 2.1 of the Registrant’s Current Report on Form 8-K filed on July 29, 2026)."))
