(:sections nil :text
	   ("The application was filed on February 20, 2026 and amended on April 23, 2026."
	    "The application was filed on December 31, 2024 and amended on November 14, 2025 and April 24, 2025."
	    "Larson, Leuthold Group, LLC dba Leuthold Weeden Capital Management, 150 South Fifth Street, Suite 1700, Minneapolis, MN 55402, glarson@lwcm.com;"
	    "The application was filed on September 4, 2025 and amended on November 25, 2025."
	    "Tara Tilbury, RBC Global Asset Management (U.S.) Inc., 250 Nicollet Mall, Suite 1550, Minneapolis, MN 55401, tara.tilbury@rbc.com;"
	    "Gehl, Esq., Godfrey & Kahn, S.C., 833 East Michigan Street, Suite 1800, Milwaukee, Wisconsin 53202, cgehl@gklaw.com."))
