(:sections
 (("II.14"
   "Please file the remaining exhibits with your next amendment."
   "If you have any questions or comments about this letter or need any further information, please call the undersigned at (628) 231-6803."
   "Moss (SCE Recovery Funding LLC) Kathleen Brennan de Jesus, Esq."))
 :text
 ("333-290112 and 333-290112-01 SEC Comment Letter dated September 30, 2025 Dear Mr."
  "Refer to Item 1100(f) of Regulation AB and Instruction 1 to Item 601 of Regulation S-K."
  "If you have any questions or comments about this letter or need any further information, please call the undersigned at (628) 231-6803."))
