(:sections nil :text
	   ("Appointed CEO at GasLog Partners founding in 2014, Mr."
	    "We did not hold a 2024 annual meeting of stockholders because we were not a publicly traded company prior to January 23, 2025."
	    "Our named executive officers for fiscal year 2024 are:"
	    "Robert Pender On January 10, 2025, we (through our operating subsidiary, VGLNG) entered into an employment agreement with Mr."
	    "If you are not a Venture Global stockholder, you may still view the meeting online at www.virtualshareholdermeeting.com/VG2025."
	    "VOTE BY PHONE - 1-800-690-6903 Use any touch-tone telephone to transmit your voting instructions up until 11:59 p.m."))
