(:sections nil :text
	   ("(vii) to construe and interpret the terms of the 2025 Plan and Awards granted pursuant to the 2025 Plan;"
	    "Percentage ownership is based on 1,484,827 shares of Common Stock and 6,372,874 shares of outstanding Series B Preferred Stock as of August 13, 2025."
	    "(m) “Effective Date” means the effective date of this Plan, September 15, 2025."
	    "☐ Individual, as separate property ☐ Husband and wife, as community property ☐ Joint Tenants A-19 5."
	    "120 Newport Center Drive, Suite 249 Newport Beach, CA 92660 Email:"))
