(:sections nil :text
	   ("Box 43001 Providence, RI 02940-3001 • Registering at the Annual Meeting."
	    "On an annual basis, our General Counsel submits to the NYSE the annual certification required by Section 303A.12(a) of the NYSE Listed Company Manual."
	    "Moore’s July 1, 2024 award vests in 12 equal tranches every 3 months beginning on October 1, 2024 and ending on July 1, 2027."
	    "• GameStop transitioned from a net loss of $(381.3) million in fiscal year 2021 to a net income of $418.4 million for fiscal 2025."
	    "As a result, the CEO Performance Award may result in no increase—or even a net decrease—in stockholder value."
	    "1.409A-1(b)(5) as a stock right and should be interpreted accordingly."))
