(:sections nil :text
	   ("Ge(6), Director 664 *% All officers and directors as a 126,681 5.14% group (7 persons):"
	    "From 2001 to 2005, he served as Director and President, Asia-Pacific Region at Bridgecreek International."
	    "The Audit Committee is responsible for, among other things:"
	    "Wang is entitled to an annual base salary (which is currently $350,000)."
	    "15 ---------------------------------------------------------------------------------------------------- TABLE OF CONTENTS PROPOSAL TWO:"
	    "17 ---------------------------------------------------------------------------------------------------- TABLE OF CONTENTS PROPOSAL THREE:"))
