(:sections nil :text
	   ("Please feel free to call us at (480) 275-7572 should you have any questions on the enclosed Information Statement."
	    "(2) The address of each Officer and Director is c/o Trutankless, Inc., 15900 North 78th Street, Suite 200, Scottsdale, AZ 85260."
	    "Callers in the United States can also call 1-202-551-8090 for further information on the operations of the public reference facilities."))
