(:sections nil :text
	   ("You may vote your shares by telephone by calling toll-free at 855-847-1311."
	    "He served as GameStop’s Chief Operating Officer from September 2008 to June 2010."
	    "(5) As of February 1, 2014, the named Director held 8,780 shares of restricted stock that have not vested."
	    "The specific companies included in the fiscal 2013 peer group, which were unchanged from fiscal 2012, are listed below:"
	    "Hogan effective May 10, 2013, and on November 13, 2013, the Company further amended and restated its employment agreement with Mr."
	    "16 as adopted by the PCAOB, relating to communications with audit committees."))
