(:sections nil :text
	   ("The Proxy confers discretionary authority on the persons named therein with respect to:"
	    "(May 2013 to June 2022 and April 11, 2025 to Present) Silver Predator Corp (2012 to present) LOGO Notes regarding Director Nominees:"
	    "All of the Company’s directors at the time of the 2024 annual meeting of Shareholders attended the annual meeting."
	    "Wilson, based on the positions each held as of December 31, 2024, was competitive with our peers."
	    "14, 2027 SHERIFF 5/17/2023 262,500 87,500 (4) 1.94 May 17, 2028 6/13/2024 81,250 243,750 (5) 3.93 June 13, 2029 W."
	    "at 5950 Berkshire Lane, Suite 210, Dallas, Texas 75225, Attention:"))
