(:sections nil :text
	   ("(the “Company”) will be held at the Commerce Bank Building, 8000 Forsyth Boulevard, Clayton, Missouri 63105 at 9:30 a.m., on June 10, 2026."
	    "Stone ﻿ This Notice also constitutes notice of the 2026 Annual Meeting of Shareholders of the Company."
	    "You will have the opportunity to make a request to receive paper copies for all future meetings or only for the 2026 Annual Meeting of Shareholders."
	    "For information on how to obtain directions to be able to attend the meeting and vote in person, please see page 25 of the Information Statement."))
