(:sections nil :text
	   ("The Company will remain a publicly traded company and shares of Common Stock will continue to be traded on Nasdaq."
	    "Between March 1, 2026 and March 20, 2026, Parent continued and subsequently completed its due diligence of the Company."
	    "Morgan from Advent (including its portfolio companies) were approximately $98.5 million."
	    "Please see the section entitled “Where You Can Find More Information” beginning on page 96."
	    "ARTICLE 2 CONVERSION OF SECURITIES IN THE MERGER 2.1 Conversion of Securities."
	    "§§ 1701–1706), Section 999 of the Internal Revenue Code, the U.S."))
