(:sections nil :text
	   (" a premium of 84% based on the estimated cost basis of TMHC’s top twenty-five investors of $39.46;"
	    "Information reporting and backup withholding (currently at a rate of 24%) may apply to payments made in connection with the merger."
	    "A-46 ---------------------------------------------------------------------------------------------------- Table of Contents SECTION 9.9 Governing Law."))
