(:sections nil :text
	   ("Additional conditions to the Merger are listed in the section entitled “The Merger Agreement – Conditions to the Merger” beginning on Page 50."
	    "On December 11, 2025, management held a meeting with Lake Street to discuss the due diligence process."
	    "1 to our Current Report on Form 8-K/A filed with the SEC on April 27, 2026."
	    "A-11 ---------------------------------------------------------------------------------------------------- TABLE OF CONTENTS Section 3.3 Authority;"
	    "No Violation), Section 3.11 (Employee Benefits Matters), Section 3.13 (Tax Matters),."))
