(:sections nil :text
	   ("On December 19, 2024, following the President-elect’s announcement of Mr."
	    "Zinni 3,000 $6,750 (1) Dollar values are calculated based on the Merger Consideration of $2.25 per share of Company Common Stock."
	    "• the required manager and member approvals;"
	    "(i) 69,000,000 shares of Company Common Stock;"
	    "“Parent Termination Fee” means Eight Million Dollars ($8,000,000)."))
