(:sections nil :text
	   ("20549 hours per response.......2.50 FORM 12b-25 SEC FILE NUMBER 001-41555 CUSIP NUMBER NOTIFICATION OF LATE FILING 00218A105 (Check one):"
	    "and (c) The accountant’s statement or other exhibit required by Rule 12b-25(c) has been attached if applicable."
	    "2 ---------------------------------------------------------------------------------------------------- ASP Isotopes Inc."
	    "(Name of Registrant as Specified in Charter) has caused this notification to be signed on its behalf by the undersigned hereunto duly authorized."))
