(:sections
 (("I.1"
   "Item 1. Identity of Directors, Senior Management and Advisers Not appl")
  ("I.2"
   "Item 2. Offer Statistics and Expected Timetable Not applicable.")
  ("I.3" "Capitalization and Indebtedness Not applicable."
   "We incurred net losses of $4.9 million, $43.3 million, $59.0 million, and $57.4 million in 2025, 2024, 2023, and 2022, respectively."
   "Directors and officers of FPIs remain exempt from the short-swing profits provisions of Section 16(b) and the short-sale prohibition of Section 16(c).")
  ("I.4"
   "History and Development of the Company Newegg Commerce, Inc."
   "Our B2B operations generated net sales of $245.4 million and $200.2 million for the years ended December 31, 2025 and 2024, respectively."
   "We own warehouse facilities in Shanghai, China that are currently leased to third party tenants.")
  ("I.5"
   "This discussion contains forward-looking statements that are subject to known and unknown risks and uncertainties."
   "See “— Newegg’s Business Model.” For the Year Ended December 31, 2025 2024 2023 (in millions) Net Sales $ 1,444.5 $ 1,235.6 $ 1,497.0 Adjustments:"
   "For detailed discussion on stock-based compensation, see Note 12 to the consolidated financial statements.")
  ("I.6" "Directors, Senior Management and Employees A."
   "During the periods from October 2005 to August 2008, January 2013 to January 2015, and October 2019 to March 2020, Mr."
   "Disclosure of a Registrant’s Action to Recover Erroneously Awarded Compensation None.")
  ("I.7" "Major Shareholders and Related Party Transactions A."
   "On February 26, 2024, the Hangzhou Court ruled that Hangzhou Lianluo owed ICBC RMB 332,000,000 (including interest) under one of such loans."
   "The following table sets forth the percentage ownership of our major shareholders during the past three years.")
  ("I.8"
   "Consolidated Statements and Other Financial Information Refer to “Item 18."
   "Dividend Policy To date, we have not paid any cash dividends on our shares.")
  ("I.9" "Offering and Listing Details Not applicable."
   "Markets Our common shares are traded on the Nasdaq Capital Market (“Nasdaq”) under the symbol “NEGG.” D.")
  ("I.10"
   "Rights and Obligations of Shareholders Each of our common shares confers on its holder:"
   "These warrants are exercisable at any time for an exercise price of $352.00 per share, with no expiration date."
   "Annual Report to Security Holders Not applicable.")
  ("I.11"
   "Our primary market risk exposures are changes in interest rates and foreign currency fluctuations."
   "As of December 31, 2025 and 2024, we did not have any outstanding long-term borrowings."
   "We expect our exposure to foreign currency risk will increase as we increase our operations and sales in Canada and other countries and regions.")
  ("I.12"
   "Description of Securities Other than Equity Securities Not applicable.")
  ("II.14"
   "Material Modifications to the Rights of Security Holders and Use of Proceeds See “Item 10.")
  ("II.15"
   "83 Because of its inherent limitations, internal control over financial reporting may not prevent or detect misstatements."
   "Based on this assessment, management has concluded that our internal control over financial reporting was effective as of December 31, 2025.")
  ("II.16" "Item 16. [Reserved]")
  ("II.16A"
   "Item 16A. Audit Committee Financial Expert Our Board has determined th")
  ("II.16B"
   "Item 16B. Code of Ethics We have adopted a Code of Business Conduct an")
  ("II.16C"
   "Principal Accountant Fees and Services Our principal accountants for the years ended December 31, 2025 and December 31, 2024 were BDO USA, P.C."
   "December 31, December 31, 2025 2024 Principal Accountant Fees (U.S."
   "We consider cybersecurity, along with other significant risks that we face, within our overall enterprise risk management framework.")
  ("III.17"
   "Item 17. Financial Statements We have responded to Item 18 in lieu of ")
  ("III.18"
   "Financial Statements INDEX TO CONSOLIDATED FINANCIAL STATEMENTS Page REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUNTING FIRM (BDO USA, P.C.;"
   "2026 $ 15,699 2027 15,495 2028 14,265 2029 4,435 2030 4,088 Thereafter 10,092 Total minimum payments $ 64,074 Less:"
   "Burns, or any other person relating to Mr.")
  ("III.19"
   "Shareholders Agreement (incorporated by reference to the Company’s Registration Statement on Form F-1/A, filed December 10, 2021)."
   "4.3* Newegg’s 2005 Incentive Plan, as Amended (incorporated by reference to the Company’s Registration Statement on Form F-1, filed October 26, 2020)."
   "The omitted information is not material and would likely cause competitive harm to the registrant if publicly disclosed."))
 :text
 ("5 If we are unable to provide a satisfactory customer experience, our reputation would be harmed and we could lose customers."
  "21 The market price of our common shares has been extremely volatile and may continue to be volatile due to numerous circumstances beyond our control."
  "41 Government Regulations We are subject to U.S."
  "Weil satisfy the “independence” requirements of Section 5605(a)(2) of the Nasdaq Listing Rules and Rule 10A-3 under the Exchange Act."
  "As of December 31, 2025 and 2024, we did not have any outstanding long-term borrowings."
  "At December 31, 2025 and 2024, the number of shares of common stock issued and outstanding were 20,972,505 and 19,478,394, respectively."))
