(:sections
 (("I.1"
   "ITEM 1. Identity Of Directors, Senior Management And Advisers Not appl")
  ("I.2"
   "ITEM 2. Offer Statistics And Expected Timetable Not applicable.")
  ("I.3" "CAPITALIZATION AND INDEBTNESS Not applicable."
   "Subsequently, various EU member states enacted the Pillar II mechanism such that it shall become effective by December 31, 2024 or after that date."
   "REASONS FOR THE OFFER AND USE OF PROCEEDS Not applicable.")
  ("I.4"
   "HISTORY AND DEVELOPMENT OF THE COMPANY We were incorporated in May 2018 in Israel as DocoMed Ltd., and originally provided digital health services."
   "333-288621), previously filed by us with the SEC and declared effective by the SEC on July 16, 2025."
   "In July 2019, we changed our name to MeaTech Ltd.")
  ("I.4A" "Unresolved Staff Comments Not Applicable.")
  ("I.5"
   "The following discussion includes forward-looking statements that involve risks, uncertainties and assumptions."
   "Year Ended December 31, 2025 2024 2023 Revenue $ - $ 10 $ - Cost of Revenue $ - $ 22 $ - Gross profit (loss) $ - $ (12 ) $ - Operating expenses:"
   "For further information, see Note 2 to our annual consolidated financial statements included in this Annual Report on Form 20-F.")
  ("I.6" "Directors, Senior Management And Employees 6.A."
   "Arik Kaufman Chief Executive Officer 620 103 134 - 857 Mr."
   "Unless otherwise stated, the address of our executive officers and directors is Steakholder Foods Ltd., 22 Einstein St., Ness Ziona 7403686, Israel.")
  ("I.7" "Major Shareholders And Related Party Transactions 7.A."
   "(3) Consists of 47,391 ADSs and 148,746 ADSs which have vested from employee restricted shares and restricted share units, for which Mr."
   "INTERESTS OF EXPERTS AND COUNSEL Not applicable.")
  ("I.8"
   "CONSOLIDATED STATEMENTS AND OTHER FINANCIAL INFORMATION See “Item 18.—Financial Statements” in this Annual Report on Form 20-F."
   "● On January 6, 2026, we entered into an amendment to the royalties and materials supply agreement with Wyler Farm dated May 12, 2024."
   "In addition, the parties agreed that we will collect the equipment owned by us from Wyler Farm.")
  ("I.9"
   "ITEM 9. The Offer And Listing 9.A. OFFER AND LISTING DETAILS ADSs The ")
  ("I.10"
   "MEMORANDUM AND ARTICLES OF ASSOCIATION A copy of our Articles of Association is attached as Exhibit 1.1 to this Annual Report."
   "Under the Israeli Income Tax Ordinance (New Version), 5721-1961 (the “Ordinance”), a company will be considered as an “Israeli resident” if:"
   "The information on that website is not part of this Annual Report on Form 20-F.")
  ("I.11"
   "ITEM 11. Quantitative And Qualitative Disclosure On Market Risk For qu")
  ("I.12"
   "Description Of Securities Other Than Equity Securities 12.A."
   "Each ADS represents 4,000 ordinary shares (or a right to receive 4,000 ordinary shares)."
   "The methodology used to determine exchange rates used in currency conversions is available upon request.")
  ("II.13"
   "ITEM 13. Defaults, Dividend Arrearages and Delinquencies Not applicabl")
  ("II.14"
   "ITEM 14. Material Modifications To The Rights Of Security Holders And ")
  ("II.15"
   "All internal control systems, no matter how well designed, have inherent limitations."
   "Our management assessed our internal control over financial reporting as of December 31, 2025, the end of our fiscal year."
   "We reviewed the results of our management’s assessment with the Audit Committee of our Board of Directors.")
  ("II.16" "ITEM 16. [reserved]")
  ("II.16A"
   "Eli Arad and David Gerbi are qualified to serve as “audit committee financial experts” as defined by SEC rules.")
  ("II.16B"
   "A copy of the Code of Conduct is available on our website at www.steakholderfoods.com."
   "Any waivers of the Code of Ethics for directors and officers require the approval of the audit committee of our board of directors."
   "We expect that any amendments to the Code of Conduct will be disclosed on our website.")
  ("II.16C"
   "Following are Somekh Chaikin’s fees for professional services in each of the respective fiscal years:"
   "A copy of our insider trading policy is attached as Exhibit 11.1 to this Annual Report."
   "and alerts and reports produced by security tools deployed in the IT environment.")
  ("III.17"
   "ITEM 17. Financial Statements The Registrant has responded to Item 18 ")
  ("III.18"
   "Financial Statements See the financial statements beginning on page F-1.")
  ("III.19" "101.SCH Inline XBRL Taxonomy Extension Schema Document."
   "Years ended December 31, 2025 2024 2023 Israel (7,561 ) (8,521 ) (15,492 ) Foreign - - (55 ) Total (7,561 ) (8,521 ) (15,547 ) B."
   "The Company requires this space in order to meet its expanding office space needs, and due to the property’s central location."))
 :text
 ("Our initial revenues were generated in late 2024, and we cannot guarantee whether or when we will generate substantial revenue from operations."
  "40 Our sales strategy emphasizes the synergistic benefits of purchasing both the 3D printers and the premix blends."
  "Each of the members of the audit committee is required to be “independent” as such term is defined in Rule 10A-3 (b)(1) under the Exchange Act."
  "We granted no waivers under our Code of Ethics and Conduct in 2025."
  "As of December 31, 2025 and 2024, the Company had no finance leases."))
