(:sections
 (("I.1"
   "UNAUDITED BALANCE SHEETS March 31, December 31, 2026 2025 ASSETS Current Assets:"
   "Cash $ 855,526 $ 944,106 Prepaid expense 374,942 311,192 Total current Assets 1,230,468 1,255,298 Non-current assets:"
   "The measure of segment assets is reported on the balance sheets as total assets.")
  ("I.2"
   "Forward-looking statements in this Quarterly Report may include, for example, statements about:"
   "The units were sold at a price of $10.00 per unit, generating gross proceeds to the Company of $345,000,000."
   "Actual results could materially differ from those estimates.")
  ("I.3"
   "Item 3. Quantitative and Qualitative Disclosures About Market Risk We ")
  ("I.4"
   "Item 4. Controls and Procedures Evaluation of Disclosure Controls and ")
  ("II.1A"
   "Risk Factors Investing in our securities involves a high degree of risk.")
  ("II.2"
   "Unregistered Sales of Equity Securities and Use of Proceeds."
   "On May 28, 2025, we issued 12,500,000 founder shares to our sponsor for $25,000."
   "The issuance of the representative shares was made in reliance on the exemption from registration provided by Section 4(a)(2) of the Securities Act.")
  ("II.5" "Item 5. Other Information None")
  ("II.6"
   "Exhibits The following exhibits are filed as part of, or incorporated by reference into, this Quarterly Report on Form 10-Q."
   "Section 1350, as adopted Pursuant to Section 906 of the Sarbanes-Oxley Act of 2002."
   "Chief Executive Officer (Principal Executive Officer) Date:"))
 :text
 ("The Units were sold at a price of $10.00 per Unit, generating gross proceeds to the Company of $345,000,000 (the “Public Proceeds”)."
  "Remeasurement of carrying value to redemption value 684,966 Class A shares subject to possible redemption as of December 31, 2025 345,684,966 Add:"
  "As of March 31, 2026 and December 31, 2025, there were 12,500,000 common stock issued and outstanding."
  "As of March 31, 2026, we have $855,526 available to us held outside the trust account."))
