(:sections
 (("28"
   "(3) Amended and Restated Agreement and Declaration of Trust dated November 22, 2021, incorporated by reference to Pre-Effective Amendment No."
   "36 to the Registrant’s Registration Statement on Form N-1A filed on February 28, 2024."
   "2 to the Registrant’s Registration Statement on Form N-1A filed on December 8, 2021.")
  ("29"
   "ITEM 29. PERSONS CONTROLLED BY OR UNDER COMMON CONTROL WITH THE FUND N")
  ("30"
   "Pursuant to Rule 484 under the Securities Act of 1933, as amended, the Registrant furnishes the following undertaking:")
  ("31"
   "For additional information, please see “Management” in PART A and “Trustees and Officers” in PART B of this Registration Statement."
   "Additional information as to BIM and the partners and executive officers of BIM is included in BIM’s Form ADV filed with the Commission (File No.")
  ("32"
   "Adaptive Core ETF, Series of Collaborative Investment Series Trust 5."
   "The Distributor’s main business address is Three Canal Plaza, Suite 100, Portland, Maine 04101."
   "Kilbourn Treasurer None Ave, Suite 2200, Milwaukee, WI 53202 (c) Not applicable.")
  ("33"
   "BondBloxx ETF Trust 700 Larkspur Landing Circle, Suite 250 Larkspur, California 94939 2."
   "BondBloxx Investment Management Corporation 700 Larkspur Landing Circle, Suite 250 Larkspur, California 94939 3."
   "50 Post Office Square Boston, Massachusetts 02110 5.")
  ("34" "ITEM 34. MANAGEMENT SERVICES Not applicable.")
  ("35"
   "ITEM 35. UNDERTAKINGS Not applicable. C-13 SIGNATURES Pursuant to the "))
 :text
 ("The Fund will provide shareholders with at least 60 days’ notice prior to changing its 80% investment policy."
  "31 Dividends and Distributions General Policies."
  "delays and risks attendant in settlement procedures;"
  "The Trust, BIM, the Sub-Adviser and the Distributor have adopted codes of ethics pursuant to Rule 17j-1 under the 1940 Act."
  "Ropes & Gray LLP, located at 3 Embarcadero Center, San Francisco, CA 94111, is counsel to the Trust."
  "Changebridge Capital Sustainable Equity ETF, Series of Listed Funds Trust 45."))
