(:sections nil :text
	   ("adom20260331_nt10k.htm SEC FILE NUMBER 001-38078 CUSIP NUMBER 29414V 308 UNITED STATES SECURITIES AND EXCHANGE COMMISSION Washington, D.C."
	    "☒ Form 10-K ☐ Form 20-F ☐ Form 11-K ☐ Form 10-Q ☐ Form 10-D ☐ Form N-CEN ☐ Form N-CSR For Period Ended:"
	    "and (c) The accountant's statement or other exhibit required by Rule 12b-25(c) has been attached if applicable."
	    "This explanation is based on the Company’s current expectations as of the date hereof and is subject to the Company’s completion of the Form 10-K."
	    "Other risks affecting the Company are discussed in the Company’s filings with the SEC."
	    "(Name of Registrant as Specified in Charter) has caused this notification to be signed on its behalf by the undersigned hereunto duly authorized."))
