(:sections
 (("28" "Exhibits EXHIBIT (a)(1) — Certificate of Trust."
   "(filed herewith) (a)(2) Amended and Restated Declaration of Trust."
   "(filed herewith) (q) — Powers of Attorney of [ ].")
  ("29"
   "Item 29. Person Controlled or Under Common Control With Registrant Non")
  ("30"
   "Indemnification Reference is made to the provisions of [ ], together with the entirety of [ ].")
  ("31"
   "Business and Other Connections of Investment Adviser First Eagle Investment Management, LLC is the Registrant’s investment adviser."
   "Its primary office is located at 1345 Avenue of the Americas, New York, New York, 10105."
   "Chief Compliance Officer, First Eagle Real Estate Debt Fund;")
  ("32"
   "Principal Underwriters (a) Quasar Distributors, LLC is the Registrant’s distributor (the “Distributor”)."
   "(b) The positions and offices of the Distributor’s directors and officers who serve the Registrant are as follows:"
   "LaFond Vice President and Chief Compliance None Officer and Treasurer Kelly B.")
  ("33"
   "Item 33. Location of Accounts and Records Omitted pursuant to Instruct")
  ("34" "Item 34. Management Services Not applicable.")
  ("35" "FIRST EAGLE ETF TRUST (A Delaware statutory trust) By:"))
 :text
 ("McLennan joined the Adviser in September 2008 after having held various senior positions with Goldman Sachs Asset Management in London and New York."
  "The Funds expect to rely on Rule 12d1-4 to the extent the Adviser deems such reliance necessary or appropriate."
  "Some obligations issued or guaranteed by U.S."
  "The standard Redemption Transaction Fee for each Fund is $250."
  "“A-3” - A short-term obligation rated “A-3” exhibits adequate protection parameters."))
