(:sections nil :text
	   ("20549 FORM 12b-25 NOTIFICATION OF LATE FILING 0001-708441 SEC FILE NUMBER 628988 107 CUSIP NUMBER (Check one):"
	    "☐ Form 10-K ☑ Form 20-F ☐ Form 11-K ☐ Form 10-Q ☐ Form 10-D ☐ Form N-SAR ☐ Form N-CSR For Period Ended:"
	    "The conclusions associated with these accounting judgments are required to finalize the 2025 Financials to be included in the Form 20‑F."
	    "This delay in filing the Form 20‑F could not be eliminated by the Company without unreasonable effort or expense."
	    "(Name of Registrant as Specified in Charter) has caused this notification to be signed on its behalf by the undersigned hereunto duly authorized."))
