(:sections
 (("3" "Item 3. Legal proceedings. 10") ("6" "Item 6. [Reserved]")
  ("9C"
   "Disclosure Regarding Foreign Jurisdictions that Prevent 14 Inspections.")
  ("16" "Item 16. Form 10-K Summary. 23 Signatures 24 2")
  ("I.1"
   "OUR BUSINESS Our Vision Our vision is to secure reliable access to critical minerals and metals for the U.S., its allies, and partners."
   "The growth rate for projected demand in 2050 is presented using 2020 as the base of comparison (Source:"
   "There are no current orders or directions relating to our Company with respect to the foregoing laws and regulations.")
  ("I.1A"
   "Item 1A. Risk Factors Not required for smaller reporting companies.")
  ("I.1B"
   "Item 1B. Unresolved Staff Comments Not required for smaller reporting ")
  ("I.1C"
   "This integration ensures that cybersecurity considerations are an integral part of our decision-making processes at every level."
   "Our management team continuously evaluates and addresses cybersecurity risks in alignment with our business objectives and operational needs."
   "This approach is designed to mitigate risks related to data breaches or other security incidents originating from third parties.")
  ("I.2"
   "Properties Our principal executive offices are located at 885 Tahoe Blvd.")
  ("I.3"
   "Item 3. Legal Proceedings In June of 2025, a lawsuit was filed in Neva")
  ("I.4" "Item 4. Mine Safety Disclosures Not applicable. 10")
  ("II.5"
   "HOLDERS As of March 31, 2026, there were approximately 456 stockholders of record holding 760,182,298 shares of our Common Stock."
   "This number does not include an indeterminate number of stockholders whose shares are held by brokers in street name."
   "RECENT SALES OF UNREGISTERED SECURITIES None.")
  ("II.7"
   "The financial statements of the Company were prepared and presented in accordance with generally accepted accounting principles in the United States."
   "11 Results of Operations for the transition period December 1, 2025 to December 31, 2025 and December 1, 2024 to December 31, 2024:"
   "The increase in net loss is because of a loss in derivative valuation and contingency expense.")
  ("II.7A"
   "Quantitative and Qualitative Disclosures about Market Risk Not required for smaller reporting companies.")
  ("II.8"
   "Item 8. Financial Statements and Supplementary Data The full text of o")
  ("II.9"
   "The decision to replace Pinnacle was approved by the Board of Directors of the Company."
   "The decision to replace Turner Stone was approved by the Board of Directors of the Company.")
  ("II.9A"
   "Item 9A. Controls and Procedures The Company is responsible for establ")
  ("II.9B"
   "Item 9B. Other Information. Rule 10b5-1 Trading Arrangement During the")
  ("II.9C"
   "Item 9C. Disclosure Regarding Foreign Jurisdictions that Prevent Inspe")
  ("III.10"
   "Directors, Executive Officers and Corporate Governance Our executive officers and directors and their respective ages are as follows:"
   "Since January 2023, Al has served as a Senior Instructor for the Next Leadership Academy (since January 2023)."
   "at 885 Tahoe Blvd., Incline Village, NV 89451.")
  ("III.11"
   "Other than as set forth herein, no executive officer’s salary and bonus exceeded $100,000 in any of the applicable years."
   "Rosende’s monthly consulting payment to $54,167 beginning December 1, 2025."
   "Outstanding Equity Awards at Fiscal Year-End There are no outstanding equity awards as of the transition period ended December 31, 2025.")
  ("III.12"
   "As of transition period ended December 31, 2025 there were 716,021,604 shares of Common Stock outstanding."
   "As of transition period ended December 31, 2025 there were 100,000 shares of preferred stock issued and outstanding."
   "(3) This does not include 32,000,000 shares of Common Stock beneficially owned by Rosende Quattro LLC of which Mr.")
  ("III.13"
   "At transition period ended December 31, 2025, $505,499 remained unpaid under the agreement."
   "During the transition period December 31, 2025, the Company paid $43,667."
   "During transition period ended December 31, 2025, the Company paid $43,667.")
  ("III.14"
   "(1) Represents aggregate fees charged by TAAD, LLP for audit of the Company’s financial statements for the transition period ended December 31, 2025."
   "(2) Represents aggregate fees charged by TAAD."
   "“All other fees” are fees billed by the independent accountant for products and services not included in the foregoing categories.")
  ("IV.15"
   "b) Exhibits Exhibit Number Description 2.01 Agreement and Plan of Merger, dated as of May 12, 2023 and entered into by and among Inky, Inc."
   "31.2* Certification of Principal Financial Officer pursuant to Rules 13a-14(a) and 15d-14(a) of the Securities Exchange Act, as amended."
   "104 Cover Page Interactive Data File (formatted as Inline XBRL and contained in Exhibit 101).")
  ("IV.16"
   "FINANCIAL STATEMENTS TABLE OF CONTENTS Page Report of Independent Registered Public Accounting Firm (TAAD, LLP PCAOB ID:"
   "During the fiscal years ended November 30, 2025 and 2024, the Company incurred losses of $6,492,569 and $3,887,261, respectively."
   "The settlement is further detailed in Note 4 above."))
 :text
 ("The growth rate for projected demand in 2050 is presented using 2020 as the base of comparison (Source:"
  "11 Results of Operations for the transition period December 1, 2025 to December 31, 2025 and December 1, 2024 to December 31, 2024:"
  "at 885 Tahoe Blvd., Incline Village, NV 89451."
  "Level 1 – Quoted market prices in active markets for identical assets or liabilities."
  "On March 23, 2026, the Company entered into an extension of this note payable from December 31, 2025 to September 30, 2026."))
