(:sections
 (("28"
   "(d) (1) Management Agreement between the Registrant and Simplify Asset Management Inc."
   "21 Filed as an exhibit to the Registration Statement on October 27, 2023."
   "22 Filed as an exhibit to the Registration Statement on February 16, 2024.")
  ("29"
   "Persons Controlled by or Under Common Control with the Funds The table below depicts the persons controlled or under common control with the Funds:")
  ("30"
   "(i) Distributor serving as distributor for the Trust in compliance with this Agreement and applicable law;"
   "(iv) the breach by the Registrant of any obligation, representation or warranty contained in this Agreement;"
   "or (v) the Registrant’s failure to comply in any material respect with applicable securities laws.")
  ("31"
   "The Adviser’s Form ADV may be obtained, free of charge, at the SEC’s website at www.adviserinfo.sec.gov."
   "A Sub-Adviser’s Form ADV may be obtained, free of charge, at the SEC’s website at www.adviserinfo.sec.gov.")
  ("32" "13D Activist Fund, Series of Northern Lights Fund Trust 2."
   "The Distributor’s main business address is Three Canal Plaza, Suite 100, Portland, Maine 04101."
   "Whetstone Three Canal Plaza, Secretary None Suite 100, Portland, ME 04101 Susan L.")
  ("33" "and Bank of New York Mellon 240 Greenwich St.")
  ("34" "Item 34. Management Services Not applicable.")
  ("35"
   "Item 35. Undertakings Not applicable C-7 SIGNATURES Pursuant to the re"))
 :text
 ("Tracking error is the divergence of a Fund’s performance from that of its Index."
  "For pools of fixed-rate 30-year mortgages in a stable interest rate environment, a common industry practice in the U.S."
  "15 Illiquid and Restricted Securities A Fund may invest up to 15% of its net assets in illiquid securities."
  "(ii) maintenance of security ledgers and books and records as required by the 1940 Act;"
  "Proxy votes generally will be cast in favor of proposals that maintain or strengthen the shared interests of shareholders."))
