(:sections
 (("1.01" "Entry into a Material Definitive Agreement."
   "Consummation of the Transaction is subject to, among other things:"
   "and (viii) the completion and acceptance of the independent valuation of the preferred units.")
  ("7.01"
   "A copy of the press release is attached hereto as Exhibit 99.1 and is incorporated herein by reference."
   "risks related to the Investment Company Act of 1940, as amended;"
   "The forward-looking statements made in this Current Report on Form 8-K relate only to events as of the date on which the statements are made.")
  ("9.01"
   "Item 9.01. Financial Statements and Exhibits. (d) Exhibits. Exhibit De"))
 :text
 ("A copy of the press release is attached hereto as Exhibit 99.1 and is incorporated herein by reference."
  "risks related to the Investment Company Act of 1940, as amended;"
  "The forward-looking statements made in this Current Report on Form 8-K relate only to events as of the date on which the statements are made."))
