(:sections nil :text
	   ("As of March 31, 2024, stocks must have a market capitalization between $900 million and $5.8 billion for initial inclusion in the Parent Index;"
	    "this range and constituents' market capitalization may fluctuate depending on the overall level of the equity markets."
	    "government securities are not considered to be issued by members of any industry."
	    "Common stock is subordinated to preferred securities and debt in a company’s capital structure."
	    "The best calendar quarter return during the periods shown above was 29.74% in the 4th quarter of 2020;"
	    "White have been Portfolio Managers of the Fund since 2025."))
