(:sections nil :text
	   ("For the fiscal year ended May 31, 2025, the amount of the waiver was 0.083%."
	    "Bitcoin and ether are both digital assets."
	    "In 2023 and over the course of 2024, crypto prices have continued to exhibit extreme volatility."
	    "7 PROSHARES.COM ---------------------------------------------------------------------------------------------------- swings, changes and uncertainty."
	    "In addition, ---------------------------------------------------------------------------------------------------- 8 ::"
	    "Adjusted to reflect the reinvestment of dividends paid by issuers in the Index."))
