(:sections
 (("I.1" "Item 1. Business.") ("I.1A" "Item 1A. Risk Factors.")
  ("I.1B" "Item 1B. Unresolved Staff Comments. None.")
  ("I.2" "Item 2. Properties.") ("I.3" "Item 3. Legal Proceedings.")
  ("I.4"
   "No single obligor represents 10% or more of the pool assets held by CarMax Auto Owner Trust 2026-1 (the \"Issuing Entity\")."
   "Based on the standards set forth in Item 1115(b) of Regulation AB, no information is required in response to this item."
   "Significant Obligors of Pool Assets (Financial Information).")
  ("II.5"
   "Item 5. Market for Registrant's Common Equity, Related Stockholder Mat")
  ("II.6" "Item 6. Selected Financial Data.")
  ("II.7"
   "Item 7. Management's Discussion and Analysis of Financial Condition an")
  ("II.7A"
   "Item 7A. Quantitative and Qualitative Disclosures About Market Risk.")
  ("II.8" "Item 8. Financial Statements and Supplementary Data.")
  ("II.9"
   "Item 9. Changes in and Disagreements With Accountants on Accounting an")
  ("II.9A" "Item 9A. Controls and Procedures")
  ("II.9B"
   "Item 9B. Other Information. None. ------------------------------------")
  ("III.10"
   "Item 10. Directors, Executive Officers and Corporate Governance.")
  ("III.11" "Item 11. Executive Compensation.")
  ("III.12"
   "Item 12. Security Ownership of Certain Beneficial Owners and Managemen")
  ("III.13"
   "Item 13. Certain Relationships and Related Transactions, and Director ")
  ("III.14"
   "Information required by Item 1119 of Regulation AB has been omitted from this report on Form 10-K in reliance on the Instruction to Item 1119."
   "The Compliance Statement is attached as an exhibit to this report on Form 10-K."
   "Affiliations and Certain Relationships and Related Transactions.")
  ("IV.15" "Exhibits and Financial Statement Schedules."
   "(a)(3) The exhibits filed in response to Item 601 of Regulation S-K are listed in the Exhibit Index."
   "(b) The exhibits filed in response to Item 601 of Regulation S-K are listed in the Exhibit Index.")
  ("IV.16" "May 27, 2026 CARMAX AUTO OWNER TRUST 2026-1 By:"
   "CarMax Auto Funding LLC, as Depositor on behalf of CarMax Auto Owner Trust 2026-1 By:"
   "** Incorporated by reference from the registration statement on Form S-3 of CarMax Auto Funding LLC originally filed on August 4, 2005 (File No."))
 :text
 ("0001259380 CARMAX AUTO FUNDING LLC (Exact name of the Depositor as specified in its charter) Central Index Key Number of sponsor (if applicable):"
  "and (3) Any prospectus filed pursuant to Rule 424(b) or (c) under the Securities Act of 1933."
  "Information required by Item 1119 of Regulation AB has been omitted from this report on Form 10-K in reliance on the Instruction to Item 1119."
  "May 27, 2026 CARMAX AUTO OWNER TRUST 2026-1 By:"
  "** Incorporated by reference from the registration statement on Form S-3 of CarMax Auto Funding LLC originally filed on August 4, 2005 (File No."))
