(:sections
 (("28"
   "Description of Exhibit (a)(i) Certificate of Trust of Corgi ETF Trust I (the \"Trust\" or the \"Registrant\") - filed herewith."
   "(a)(ii) Certificate of Amendment to Certificate of Trust of Corgi ETF Trust I - filed herewith."
   "(p)(ii) Code of Ethics for Sub-Adviser - to be filed by subsequent amendment.")
  ("29"
   "Item 29. Persons Controlled by or Under Common Control with Registrant")
  ("30"
   "Indemnification Reference is made to Article IX of the Registrant's Agreement and Declaration of Trust."
   "Pursuant to Rule 484 under the Securities Act of 1933, as amended (the \"Securities Act\"), the Registrant furnishes the following undertaking:")
  ("31"
   "Business and Other Connections of Investment Adviser Corgi Strategies, LLC - SEC File No."
   "As of the date of this filing, the adviser's registration is pending."
   "Each Form ADV may be obtained, without charge, at www.adviserinfo.sec.gov when available.")
  ("32"
   "Principal Underwriter The principal underwriter for the Funds (the \"Distributor\") will be [ ].")
  ("33"
   "Item 33. Location of Accounts and Records The books and records requir")
  ("34" "Item 34. Management Services Not applicable.")
  ("35" "Yuan President and Principal Executive Officer;"
   "Principal Accounting Officer (Treasurer) Brianna A."
   "Murray Lead Independent Trustee Name /s/ Bryant C."))
 :text
 ("Preferred stock generally has no voting rights."
  "since 2025 Insurance Services, Anti-Money Laundering Inc., an insurance Officer agency (since 2025);"
  "or (4) in such other circumstances as are permitted by the SEC."))
