(:sections nil :text
	   ("As of December 31, 2025, KfW held own debt securities (registered and non-registered) in a principal amount of EUR 4.2 billion."
	    "18 to 21, 65, 71 to 93 and 94 to 108 of Exhibit (e), which are hereby incorporated by reference herein."
	    "G-44 to G-47 of Exhibit (d), which are hereby incorporated by reference herein."
	    "No foreign exchange control not previously reported was established by the Federal Republic during 2025."
	    "Exhibit (d) - Description of KfW and the Federal Republic of Germany, dated May 7, 2026."
	    "(d) Description of KfW and the Federal Republic of Germany, dated May 7, 2026."))
