(:sections nil :text
	   ("☐ Form 10-K ☐ Form 20-F ☒ Form 11-K ☐ Form 10-Q ☐ Form 10-D ☐ Form N-CEN ☐ Form N-CSR For Period Ended:"
	    "and (c) The accountant’s statement or other exhibit required by Rule 12b-25(c) has been attached if applicable."
	    "The Auditor’s statement regarding such delay is attached hereto as Exhibit 99.1."
	    "ATTENTION Intentional misstatements or omissions of fact constitute Federal Criminal Violations (See 18 U.S.C."))
