(:sections nil :text
	   ("☐ Form 10-K ☒ Form 20-F ☐ Form 11-K ☐ Form 10-Q ☐ Form 10-D ☐ Form N-CEN ☐ Form N-CSR For Period Ended:"
	    "and (c) The accountant’s statement or other exhibit required by Rule 12b-25(c) has been attached if applicable."
	    "As a result, the Registrant is still in the process of compiling required information to complete the Form 20-F."
	    "(Name of Registrant as Specified in Charter) has caused this notification to be signed on its behalf by the undersigned hereunto duly authorized."))
