(:sections
 (("I.1" "General Non-Invasive Monitoring Systems, Inc."
   "The Company’s offices are located at 4400 Biscayne Boulevard, Miami, Florida, 33137 and its telephone number is (305) 575-4200."
   "The Company is a shell company as defined in Rule 12b-2 of the Exchange Act.")
  ("I.1A"
   "Our future operating results may vary substantially from anticipated results due to a number of factors, many of which are beyond our control."
   "The future issuance of any such additional shares of our common stock may create downward pressure on the trading price of the common stock."
   "The following discussion highlights some of these factors and the possible impact of these factors on our future results of operations.")
  ("I.1B" "Item 1B. Other Information None")
  ("I.1C"
   "Cybersecurity We are currently a shell company with no business operations."
   "Since May 2019, we have been in search of a suitable merger or acquisition candidate."
   "These measures are integrated into the Company’s overall risk management system to protect its information systems from cybersecurity threats.")
  ("I.2"
   "Item 2. Properties. Our principal corporate office is located at 4400 ")
  ("I.4" "Item 4. Mine Safety Disclosures. Not applicable. 7")
  ("II.5"
   "Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities."
   "At December 31, 2025, we had 1,390 shareholders of record based on information provided by our transfer agent, Equity Stock Transfer."
   "Recent Sales of Unregistered Securities and Use of Proceeds.")
  ("II.6" "Item 6. [Reserved].")
  ("II.7"
   "Management’s Discussion and Analysis of Financial Condition and Results of Operations."
   "Net loss was $49,000 for the five months ended December 31, 2025, as compared to $101,000 for the five months ended December 31, 2024."
   "We will need to raise additional capital.")
  ("II.7A"
   "Quantitative and Qualitative Disclosures About Market Risk.")
  ("II.8" "Financial Statements and Supplementary Data."
   "December 31, 2025 July 31, 2025 Federal and State net $ 3,886 $ 3,886 operating loss Foreign net operating 18 18 loss Other - - 3,904 3,904 Less:"
   "The 2026 Frost Gamma Note may be prepaid in advance of the June 30, 2026 maturity date without penalty.")
  ("II.9A"
   "Internal control over financial reporting includes those policies and procedures that:"
   "Process and procedures – The Company does not employ a sufficient number of individuals to maintain optimal segregation of duties."
   "Since internal control procedures are not formally documented, management cannot monitor their effectiveness.")
  ("II.9B"
   "Item 9B. Other Information. During the five months ended December 31, ")
  ("II.9C"
   "Item 9C. Disclosure Regarding Foreign Jurisdictions That Prevent Inspe")
  ("III.10" "Directors, Executive Officers and Corporate Governance."
   "from 2004 to 2006 and as Chairman from July 2006 until September 2018."
   "Neither our website nor any information contained or linked therein constitutes a part of this report.")
  ("III.11"
   "We refer to these persons as our named executive officers."
   "We did not have any equity award plan during the year ended December 31, 2025 and we did not have any outstanding."
   "Hsiao, Chairman/CEO – Phillip Frost, M.D.")
  ("III.12"
   "Security Ownership of Certain Beneficial Owners and Management and Related Stockholder Matters."
   "(3) Based on 154,810,655 shares of common stock issued and outstanding as of December 31, 2025."
   "Equity Compensation Plan Information The Company does not have any approved equity compensation plans.")
  ("III.13"
   "Certain Relationships and Related Transactions, and Director Independence."
   "Phillip Frost, who beneficially owns approximately 35% of the Company’s outstanding common equity, James J."
   "CERTAIN RELATIONSHIPS AND RELATED TRANSACTIONS Dr.")
  ("III.14"
   "The services requiring pre-approval by the audit committee may include audit services, audit related services, tax services and other services."
   "Following Steve Rubin’s resignation from the Audit Committee in March 2023, pre-approval services were conducted by the full Board.")
  ("IV.15"
   "Exhibits, Financial Statement Schedules (a) List of documents filed as part of this report:"
   "10.91 Form of Stock Purchase Agreement, dated December 21, 2018 (incorporated by reference from Exhibit 10.1 to Form 8-K filed December 28, 2018)."
   "32.1* Certification of Chief Executive Officer pursuant to 18 U.S.C."))
 :text
 ("The Company’s offices are located at 4400 Biscayne Boulevard, Miami, Florida, 33137 and its telephone number is (305) 575-4200."
  "Net loss was $49,000 for the five months ended December 31, 2025, as compared to $101,000 for the five months ended December 31, 2024."
  "The Company had approximately $6,000 and $3,000, on deposit in bank operating accounts at December 31, 2025 and July 31, 2025, respectively."
  "The interest rate payable by NIMS on the 2026 Frost Gamma Note is 11% per annum, payable on the maturity date of June 30, 2026."
  "We did not have any equity award plan during the year ended December 31, 2025 and we did not have any outstanding."
  "10.91 Form of Stock Purchase Agreement, dated December 21, 2018 (incorporated by reference from Exhibit 10.1 to Form 8-K filed December 28, 2018)."))
