(:sections
 (("5.02" "Item 5.02 Departure of Directors or Certain Officers;"
   "Compensatory Arrangements of Certain Officers."
   "Second Amended and Restated 2008 Incentive Compensation Plan\" and such description is incorporated by reference herein.")
  ("5.07"
   "Item 5.07 Submission of Matters to a Vote of Security Holders."
   "46,296,745 25,909,618 27,968 5,095,808 Shirley A."
   "The Plan was approved by the Company’s shareholders, by the votes set forth in the table below:")
  ("9.01" "Item 9.01 Financial Statements and Exhibits."
   "Exhibit Index 10.1 Pediatrix Medical Group, Inc."
   "104 Cover Page Interactive Data File (embedded within the Inline XBRL document)."))
 :text
 ("McEachin 70,107,436 2,093,168 33,727 5,095,808 Kurt D."
  "46,296,745 25,909,618 27,968 5,095,808 Shirley A."
  "For Against Abstained Broker Non-Vote 70,257,832 1,960,931 15,568 5,095,808 Proposal 4:"
  "Exhibit Index 10.1 Pediatrix Medical Group, Inc."))
