(:sections
 (("II.6"
   "ITEM 6: INDEMNIFICATION OF DIRECTORS AND OFFICERS The corporate laws o")
  ("II.7"
   "None of these transactions involved any underwriter’s underwriting discounts or commissions, or any public offering."
   "During the year ended August 31, 2025, 1,470,000 Pre-Funded Warrants were converted into 1,470,000 Voting Common Shares."
   "As a result, the Company issued 250,000 Voting Common Shares to the plaintiffs at a value of $832,500.")
  ("II.8"
   "10.2 Commercial Lease Agreement, dated April 1, 2019, between California Electric Boat Company Inc."
   "10.3 Amended and Restated Share Option Plan."
   "+ Confidential Treatment has been requested for portions of this exhibit.")
  ("II.9" "UNDERTAKINGS The undersigned Registrant hereby undertakes:"
   "(i) Include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "Lauderdale, Florida, on December 5, 2025."))
 :text
 ("The weighted average interest rate on floor plan facilities was 9.7% as of August 31, 2025."
  "In fiscal 2025, we made the first sale of our E-Motion™ Electric Powertrain System and generated $57 thousand from such sales."
  "20 We may not receive any additional funds upon the exercise of the pre-funded warrants."
  "(8) Includes 498 common shares underlying options that have vested or will vest within the next 60 days."
  "holder that is greater than 125% of the average annual distributions paid in the three preceding taxable years or, if shorter, the U.S."
  "001-39730), filed with the SEC on November 20, 2020, and any amendment or report filed for the purpose of updating such description."))
