(:sections
 (("II.6" "Indemnification of Directors and Officers."
   "(1) indemnify the eligible party under section 160 (a) in respect of the proceeding;"
   "(4) order a company to pay some or all of the expenses actually and reasonably incurred by any person in obtaining an order under this section;")
  ("II.7" "Recent Sales of Unregistered Securities."
   "On February 12, 2025, we issued 2,670,000 subscription receipts at $1.00 per subscription receipt, for gross proceeds of $20,000,000."
   "The subscription receipts were issued pursuant to the exclusion from registration under the Securities Act under Regulation S.")
  ("II.8" "Exhibits and Financial Statement Schedules."
   "(a) The following exhibits are included in this registration statement on Form F-1:"
   "A copy of any omitted schedule and/or exhibit will be furnished to the SEC upon request.")
  ("II.9" "Undertakings The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"
   "/s/ Janet Lee-Sheriff Janet Lee-Sheriff Title:"))
 :text
 ("From time to time, we may rely on debt financing for a portion of our business activities, including capital and operating expenditures."
  "The estimate of mineral resources includes the Crownpoint area located in portions of Sections 24, Township 17 North, Range 13 West;"
  "Gabruch, former CEO and director, exercised his Verdera Options on February 17, 2026."
  "Holders who use the accrual method of tax accounting."
  "As at April 30, 2025, the weighted-average remaining life of the stock options was 4.63 years (March 31, 2025 – 4.71 years)."))
