(:sections
 (("II.6" "Notwithstanding the foregoing, a company may:")
  ("II.7"
   "Recent Sales of Unregistered Securities Set forth below is information regarding ordinary shares issued by us during the last three years."
   "During the year ended December 31, 2024, the Company issued 1 share to Lim Sin Foo, Harris for the consideration of US$0.001."
   "In consideration for entering into the ELOC Purchase Agreement, on July 8, 2026, the Company issued to the ELOC Investor 502,008 ordinary shares.")
  ("II.8" "Exhibits and Financial Statement Schedules."
   "The following is a list of exhibits filed as a part of this registration statement:"
   "23.1* Consent of Assentsure PAC., Independent Registered Public Accounting Firm.")
  ("II.9"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"
   "Senior Vice-President on behalf of Cogency Global Inc."))
 :text
 ("We are an exempted company incorporated on May 31, 2024 under the laws of the Cayman Islands."
  "In addition, section 38(5) of the Singapore EA limits the extent of overtime work that a relevant employee can perform, to 72 hours a month."
  "17755 US Hwy 19 N Suite 140, Clearwater, FL 33764."
  "For the year ended February 28, 2025 and 2026, no impairment loss was recognized."))
