(:sections
 (("II.8" "Indemnification of Directors and Officers.")
  ("II.9"
   "Item 9. Exhibits. See Exhibit Index beginning on page II-4 of this reg")
  ("II.10" "(A) The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by Section 10(a)(3) of the Securities Act of 1933, as amended, or the Securities Act;"
   "Senior Vice President on behalf of Cogency Global Inc."))
 :text
 ("Securities Act of 1933, as amended (the “Securities Act”)."
  "10 DESCRIPTION OF THE SECURITIES We may issue, offer and sell from time to time, in one or more offerings, the following securities:"
  "● the merger agreement does not amend in any respect its certificate of incorporation;"
  "(1) the depositary has closed its transfer books or we have closed our transfer books;"
  "43 The prospectus supplement relating to any offering will identify or describe:"
  "50 ENFORCEABILITY OF CIVIL LIABILITIES We were incorporated under the laws of the Cayman Islands as an exempted company with limited liability."))
