(:sections
 (("II.8"
   "In connection with the Closing, the Company entered into indemnification agreements with each post-Closing director of the Company.")
  ("II.9" "Exhibits and Financial Statement Schedules Exhibit No."
   "333-268970) of Critical Metals Corp., filed with the SEC on December 7, 2023)."
   "(incorporated by reference to Exhibit 96.1 to the Form 6-K of Critical Metals Corp., filed with the SEC on March 12, 2025).")
  ("II.10"
   "Undertakings (1) The undersigned Registrant hereby undertakes:"
   "(i) To include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "and (iv) Any other communications that is an offer in the offering made by the undersigned registrant to the purchaser."))
 :text
 ("Accordingly, we are required to file reports and other information with the SEC, including annual reports on Form 20-F and reports on Form 6-K."
  "(USD $) Actual As-Adjusted Cash and cash 149,480 24,699,480 equivalents Equity:"
  "The address of the Selling Securityholder is 161A Shedden Road, 1 Artillery Court, PO Box 10085, Grand Cayman KY1-1001, Cayman Islands."
  "19 THIS DISCUSSION IS ONLY A SUMMARY OF CERTAIN U.S."
  "22 The QEF election is made on a shareholder-by-shareholder basis and, once made, can be revoked only with the consent of the IRS."
  "333-268970) of Critical Metals Corp., filed with the SEC on December 7, 2023)."))
