(:sections
 (("II.8"
   "Our Articles of Association provide that, subject to the provisions of the Companies Law, we may:"
   "(1) Obtain insurance for our office holders for liability for an act performed in their respective capacities as an office holder with respect to:"
   "or (iv) fine, financial sanction or monetary settlement in lieu of criminal proceedings imposed on such office holder.")
  ("II.9"
   "Item 9. Exhibits Exhibit Description Number 1.1 Form of Underwriting A")
  ("II.10"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"
   "This Power of Attorney may be signed in several counterparts."))
 :text
 ("The closing sale price of our ordinary shares on the Nasdaq Global Select Market on May 6, 2026 was $2.65 per share."
  "A (7th Floor), PO Box 112, Rosh Ha’Ayin, Israel, 4810002, and our telephone number is +972-3-543-1000."
  "The indenture will be subject to and governed by the terms of the Trust Indenture Act of 1939."
  "and • a description of the provisions for the payment, settlement, transfer or exchange of the units."
  "A (7th Floor), PO Box 112, Rosh Ha’Ayin, Israel, 4810002."
  "(i) To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"))
