(:sections
 (("II.20"
   "Issuer) for the costs of defense, settlement or payment of claims and judgments under certain circumstances."
   "This regulation shall only have effect in so far as its provisions are not avoided by section 235."
   "Global Aviation LLC or International Lease Finance Corporation may be entitled.")
  ("II.21"
   "Item 21. Exhibits and Financial Statement Schedules See Exhibit Index ")
  ("II.22"
   "Undertakings (a) The undersigned registrants hereby undertake:"
   "in the United States of America, has signed this Registration Statement on Form F-4 filed with the SEC in Newark, Delaware on March 1, 2024."
   "Scot Kennedy Director & Vice President March 1, 2024 J."))
 :text
 ("and  AerCaps Current Reports on Form 6-K, as filed with the SEC on January 4, 2024, January 11, 2024 and January 22, 2024;"
  "The Notes and the guarantees are effectively subordinated to our and the guarantors existing and future secured indebtedness."
  "Unless waived, any defects or irregularities in connection with tenders of Unregistered Notes must be cured within a time period we will determine."
  "(1) change the stated maturity of the principal of or any installment of principal or interest on any Note;"
  "(d) as specified in Section 276(7) of the SFA;"
  "The foregoing discussion is general in nature and is not intended to be all-inclusive."))
