(:sections
 (("II.20" "Indemnification of Directors and Officers."
   "We have entered into indemnification agreements with our directors and executive officers.")
  ("II.21" "Exhibits and Financial Statement Schedules."
   "(a) Exhibits See Exhibit Index beginning on page II-4 of this registration statement.")
  ("II.22"
   "Undertakings (a) The undersigned Registrant hereby undertakes:"
   "as Trustee 4.2 First Supplemental Indenture, dated as of November 26, 2024, between the Registrant and Citibank, N.A."
   "TSAI /s/ Eddie Yongming WU Director and Chief Executive Officer (Principal Executive Officer) Eddie Yongming WU /s/ J."))
 :text
 ("• “Share(s)” or “ordinary share(s)” are to ordinary share(s) in our capital with par value of US$0.000003125 each;"
  "US01609WBM38 Identification Numbers for the 2035 Notes Common Code:"
  "801 Pennsylvania Ave, Suite 219287 Kansas City, MO 64105-1307 Ref:"
  "(3) we have paid or caused to be paid all sums payable by us under the Indenture with respect to the Notes of such series;"
  "1156 of the Swiss Code of Obligations or the disclosure standards for listing prospectuses under art."))
