(("NPORT-P"
  :registrant-name "EAGLE CAPITAL GROWTH FUND, INC."
  :cik "0000850027"
  :report-date "2026-06-30"
  :net-assets "48326253.52"
  :holding-count 26
  :first-holding-name "Alphabet, Inc. A"
  :first-holding-cusip "02079K305"
  :first-holding-value "4288440")
 ("N-MFP3"
  :registrant-name "Northwestern Mutual Series Fund, Inc."
  :cik "0000742212"
  :report-date "2026-08-31"
  :holding-count 161)
 ("N-CEN"
  :registrant-name "Financial Investors Trust"
  :cik "0000915802"
  :report-date "2026-04-30"
  :holding-count 0))
