(:sections nil :text
	   ("3 business days after the Final Valuation Date, expected to be July 31, 2031."
	    "The Notes may not be suitable for you if:"
	    "The MQVTUSTE was launched on May 30, 2025 and the Sub-Index was launched on December 15, 2023 and each therefore has limited historical performance."
	    "$0.00 $0.00 Final Valuation N/A 1,050.00 / 620.00 / -38.00% 400.00 / Date 5.00% -60.00% Call Premium:"
	    "The MQVTUSTE may underperform an alternative investment that more directly tracks the relevant market volatility."
	    "See “Supplemental Plan of Distribution (Conflicts of Interest)” on page S-87 in the prospectus supplement."))
