(:sections nil :text
	   ("The Company advises the Staff that the disclosure on pages 1, 72, 128 and 136 of Submission No."
	    "2 has been revised to disclose the Company’s total indebtedness as of March 31, 2026."
	    "The Company advises the Staff that the disclosure on pages 123 and 124 of Submission No."
	    "Refer to Item 101(c)(1) of Regulation S-K and ASC 275-10-50-16."
	    "In response to the Staff’s comment, the Company has revised the disclosure on pages 179 and F-13 of Submission No."
	    "Securities and Exchange Commission May 7, 2026 Page 31 51."))
