(:sections
 (("II.14" "Other Expenses of Issuance and Distribution."
   "Set forth below is an estimate of the approximate amount of fees and expenses which may be incurred by BCB Bancorp, Inc.")
  ("II.15" "Indemnification of Directors and Officers."
   "The statute also provides for indemnification of directors and officers by court order."
   "shall be eliminated or limited to the fullest extent permitted by the New Jersey Business Corporation Act as so amended.")
  ("II.16"
   "The following is a list of exhibits filed as part of the Registration Statement:")
  ("II.17" "The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "Exhibit 5.1 Opinion of Stevens & Lee, P.C."))
 :text
 ("The date of this prospectus is May 4, 2026."
  "Optional cash payments by eligible participants must be at least $50 per investment and may not exceed a total of $100,000 in any calendar quarter."
  "These statements are the participant’s continuing record of the purchase price of the shares of BCB Bancorp, Inc."
  "6 ---------------------------------------------------------------------------------------------------- Withdrawals From The Plan 21."
  "Accordingly, actual results may differ materially from anticipated results."
  "(included in Exhibit 5.1) 24.1 Power of Attorney (contained on signature page of this filing) 107.1 Filing Fee Table Item 17."))
