(:sections nil :text
	   ("To attend the Special Meeting, you must register at www.cstproxy.com/aerwins/2023 by 11:59 p.m., Eastern Daylight Time, on November 29, 2023."
	    "We encourage you to access the meeting before the start time of 11:00 a.m., Eastern Daylight Time, on November 20, 2023."
	    "3 requires an affirmative vote of a majority of the outstanding common stock entitled to vote thereon."
	    "Such filing may occur as soon as the day of the Special Meeting or at any time prior to the 2024 special meeting of stockholders."
	    "(2) a corporation (including any entity taxable as a corporation for U.S."
	    "The Company filed a Registration Statement on May 12, 2023, but it has not been declared effective as of the date of this proxy statement."))
