(:sections nil :text
	   ("On September 6, 2023, the Concerned FBRX Stockholders issued the following press release:"
	    "In addition, Forte also uses stale data instead of the balance sheets as of June 30, 2023."
	    "· Following this failure, the Company made a highly speculative pivot to the development of FB-102 for autoimmune diseases in 2022."
	    "*** VOTE “FOR” THE CONCERNED STOCKHOLDERS’ HIGHLY QUALIFIED NOMINEES ON THE WHITE PROXY CARD AHEAD OF FORTE’S ANNUAL MEETING ON SEPTEMBER 19, 2023."
	    "Camac prides itself on its unique sourcing, flexible mandate, and constant focus on non-competitive opportunities."))
