(:sections nil :text
	   ("20549 SCHEDULE 14D-9 Solicitation/Recommendation Statement under Section 14(d)(4) of the Securities Exchange Act of 1934 YATRA ONLINE, INC."
	    "The offer is scheduled to expire at 12:00 midnight, New York City time, on September 17, 2026, unless extended, and is subject to proration."
	    "Private Securities Litigation Reform Act of 1995, as amended."
	    "The Company will file a solicitation/recommendation statement on Schedule 14D-9 with the SEC."))
