(:sections nil :text
	   ("Shareholders Should Support Proposal 7 · Agricultural ingredients are critical to General Mills’ products and cost base."
	    "Proposal 7 focuses on the next investor-relevant question:"
	    "24, 2024, https://www.nytimes.com/2024/03/24/world/europe/india-sugar-cane-fields-child-labor-hysterectomies.html;"
	    "25, 2023, https://www.nytimes.com/2023/02/25/us/unaccompanied-migrant-child-workers-exploitation.html."
	    "15 Unilever, Modern Slavery Statement, March 2026, https://www.unilever.com/files/unilever-modern-slavery-statement-march-2026.pdf."))
