(:sections nil :text
	   ("Batta served as Managing Partner of Dazzle Designs LLC, a jewelry manufacturer and seller, from 1995 to 1999."
	    "(n/k/a “Spencer Savings Bank, SLA”), a commercial bank, from 2018 to 2019."
	    "2025 Equity Incentive Plan (the “2025 Stock Plan”), which the Board adopted on July 16, 2025 to replace the Volcon, Inc."
	    "For information regarding the transactions in the securities of the Company during the past two (2) years by the Participants, see Schedule I."
	    "The address for such reporting persons is 300 East Randolph Street, Suite 40.150, Chicago, IL 60601."))
