(:sections nil :text
	   ("The 13-property, $42 million portfolio, sold to us by Modiv is very much congruent with what GIPR has set out to aggregate for our shareholders."
	    "At the meeting, the use of cameras, audio or video recording equipment, communications devices or similar equipment will be prohibited."
	    "Proxies submitted by telephone or through the internet must be received by 11:59 p.m., Eastern Time on [●], 2023."
	    "226,100 8.3 % — — Revocable Family Trust(2) Thomas E."
	    "(11) Consists of 19,366 shares of restricted Common Stock that vest over a 3-year period and 132,432 shares of Common Stock."
	    "V23323-TBD GENERATION INCOME PROPERTIES, INC."))
