(:sections
 (("II.12" "Other Expenses of Issuance and Distribution.")
  ("II.13" "Indemnification of Directors and Officers."
   "The registration fee represents the filing fee of $1,123,116.40 that was previously paid in connection with Unsold Securities to be carried forward."
   "The policies contain self-insured retention provisions.")
  ("II.14"
   "Exhibit Description Number 1.1 — Form of Underwriting Agreement."
   "4.11 — Form of Terms Document for Class C Notes."
   "23.1 — Consent of Alston & Bird LLP (included in the opinions filed as Exhibit 5.1 and Exhibit 8.1).")
  ("II.15" "The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"
   "Butwin Chief Executive Officer and Manager June 26, 2026 Talia A."))
 :text
 (" “i” is a series of whole numbers from one to d0, each representing the relevant U.S."
  "2505 (June 27, 2016) because they are non-bank entities that are not entitled to the benefits of federal preemption."
  " $40 (or total amount owed if less than $40);"
  "Requests from investors to communicate with other investors will also be included in monthly reports on Form 10-D."
  "Department of Defense regulations implementing the Military Lending Act of 2006 became effective for credit card products in October 2017."
  "plus (3) an amount equal to the product of:"))
