(:sections nil :text
	   ("Items #1-7 listed above were first used or made available on August 9, 2023."
	    "and the impact of public health outbreaks, epidemics, or pandemics (such as the COVID-19 pandemic) on Regenerons or Decibels respective businesses."
	    "99.2 Email from Laurence Reid, Ph.D., President and Chief Executive of the Company, sent to the Companys employees, dated August 9, 2023."
	    "99.4 Email to advocacy groups, dated August 9, 2023."))
