(:sections
 (("9" "Our Estimated NAV Per Share as of June 30, 2023 was $17.88."
   "Potential Conflicts of Interest Appraisals are performed by employees of the Administrator."
   "FOR THE FORGOING REASONS YOU ARE CAUTIONED NOT TO PLACE UNDUE RELIANCE ON THE ESTIMATED NAV PER SHARE."))
 :text
 ("20549 FORM 1-U CURRENT REPORT Pursuant to Regulation A of the Securities Act of 1933 July 6, 2023 Date of Report:"
  "Our Estimated NAV Per Share as of June 30, 2023 was $17.88."
  "no assurance can be given that a truly independent appraisal would not produce a different outcome."
  "The effective date differs from the issuance date."
  "Valuation is heavily reliant on an analysis of sales history of similar artwork."
  "FOR THE FORGOING REASONS YOU ARE CAUTIONED NOT TO PLACE UNDUE RELIANCE ON THE ESTIMATED NAV PER SHARE."))
