(:sections nil :text
	   ("The mailing address of the principal executive offices of the Fund is 321 North Clark Street #2430, Chicago, IL 60654."
	    "In September 2017, the Fund completed its IPO and began trading on the New York Stock Exchange, raising approximately $73 million at $10 per share."
	    "On July 1, 2026, Octagon delivered a demand to the Fund pursuant to Rule 14a-7 of the Exchange Act requesting certain shareholder list materials."
	    "Octagon estimates that its expenses in connection with this solicitation to date are approximately $750,000."
	    "Law directly beneficially owns 4,000 Common Shares."
	    "* 520 8th Avenue, 14th Floor New York, NY 10018 (212) 257-1311 Shareholders call toll-free at (888) 368-0379 Email:"))
