(:sections
 (("1"
   "Each of the following Series' properties are currently vacant."
   "The terms of each Additional Borrowing are listed in the table below and as per form of loan agreement attached as Exhibit 6.1."
   "Landa Holdings, Inc., as member manager By:"))
 :text
 ("July 23, 2026 Landa App LLC (Exact name of issuer as specified in its charter) Delaware 85-1099443 (State or other jurisdiction of (I.R.S."
  "The terms of each Additional Borrowing are listed in the table below and as per form of loan agreement attached as Exhibit 6.1."
  "1 EXHIBITS The following exhibits are filed herewith:"
  "Landa Holdings, Inc., as member manager By:"))
