(:sections
 (("II.13" "Other Expenses of Issuance and Distribution."
   "The following table sets forth the fees and expenses payable in connection with the registration of the securities hereunder."
   "All amounts are estimates except the SEC registration fee.")
  ("II.14" "Indemnification of Directors and Officers."
   "In October 2006, GeoVax and our subsidiary, GeoVax, Inc."
   "The agreements also provide for the advancement of expenses to these individuals subject to specified conditions.")
  ("II.15" "Recent Sales of Unregistered Securities."
   "On August 10, 2023, we issued 11,883 shares of our restricted common stock to Outside the Box Capital, Inc."
   "pursuant to a professional services agreement.")
  ("II.16" "Exhibits and Financial Statement Schedules."
   "and City of Hope, dated November 9, 2021 (11) *** 10.13.1 Amendment to License Agreement, dated April 11, 2023, between GeoVax, Inc."
   "(32) Incorporated by reference from the registrant’s Annual Report on Form 10-K filed April 15, 2026.")
  ("II.17"
   "Undertakings (a) The undersigned Registrant hereby undertakes:"
   "Kollintzas * Director April 15, 2026 Nicole Lemerond * Director April 15, 2026 Robert T."
   "McNally * Director April 15, 2026 Jayne Morgan *."))
 :text
 ("(678) 384-7220 (Name, address, including zip code, and telephone number, including area code, of agent for service) Copies to:"
  "On August 10, 2023, we issued 11,883 shares of our restricted common stock to Outside the Box Capital, Inc."
  "and City of Hope, dated November 9, 2021 (11) *** 10.13.1 Amendment to License Agreement, dated April 11, 2023, between GeoVax, Inc."
  "(15) Incorporated by reference from the registrant’s Annual Report on Form 10-K filed March 23, 2023."
  "(28) Incorporated by reference from the registrant’s Quarterly Report on Form 10-Q filed November 13, 2025."
  "Kollintzas * Director April 15, 2026 Nicole Lemerond * Director April 15, 2026 Robert T."))
