(:sections nil :text
	   ("2) Has P&G had enough time to effectively respond to the 2020 proposal?;"
	    "“P&G CDP Forestry Response.” https://s1.q4cdn.com/695946674/files/doc_downloads/2022/12/Forestry-2022_ProcterGamble.pdf."
	    "“Forestry Practices Update July 2022.” https://s1.q4cdn.com/695946674/files/doc_downloads/2022/07/Forestry-Practices-Update-July-2022.pdf."
	    "“Shareholder Proposal for 2022 Annual Shareholder Meeting.” https://www.sec.gov/divisions/corpfin/cf-noaction/14a-8/2022/greenp&g071822-14a8.pdf."
	    "“Investor rebellion at Procter & Gamble over environmental concerns.” https://www.ft.com/content/1dd92502-e95b-4c21-be1c-c18a598acf1a."))
