(:sections nil :text
	   ("We intend to mail the Proxy Materials on or about ________ __, 2026 to all stockholders of record entitled to vote at the Special Meeting."
	    "Your telephone vote must be received by 11:59 p.m., Eastern Time on ________ _ _, 2026 to be counted."
	    "Can I change my vote after submitting my proxy? Stockholder of Record:"
	    "AIGH Capital Management LLC 7,531,532 9.12 % (1) Alyeska Master Fund, L.P.(2) 4,901,960 5.94 % Named Executive Officers and Directors:"))
