(:sections
 (("II.8" "Indemnification of Officers and Directors.")
  ("II.9"
   "Exhibit Description of Document 1.1 Form of underwriting agreement."
   "23.2 Consent of Nagashima Ohno & Tsunematsu (included in Exhibit 5.1)."
   "25.1 Statement of Eligibility on Form T-1 of The Bank of New York Mellon, as trustee under the senior indenture.")
  ("II.10" "The undersigned registrant hereby undertakes:"
   "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act;"
   "Executive Vice President, General Counsel and Secretary;"))
 :text
 ("Securities Act of 1933, as amended (the “Securities Act”), and Section 21E of the U.S."
  "You should refer to those documents for additional information."
  "and 15 o the beneficial owners of the series of senior debt securities being defeased will be subject to U.S."
  "21 Clearstream Clearstream is incorporated as a bank under Luxembourg law."
  "· a description of the transaction and the senior debt securities to be offered;"
  "23.2 Consent of Nagashima Ohno & Tsunematsu (included in Exhibit 5.1)."))
