(:sections nil :text
	   ("20549 FORM F-1 REGISTRATION STATEMENT UNDER THE SECURITIES ACT OF 1933 Micware Co., Ltd."
	    "333-294081) initially filed by Micware Co., Ltd."
	    "Signature Title Date /s/ Kenji Narushima Representative Director, May 13, 2026 President, Chairman, and Name:"
	    "Masahide Shigeno Chief Technology Officer /s/ Takuma Segawa Chief Financial Officer May 13, 2026 Name:"
	    "Yuko Osumi * Independent Director May 13, 2026 Name:"))
