(:sections
 (("1" "The Company was subsequently renamed Red Metal Resources Ltd."
   "on August 27, 2008, and on February 10, 2021 continued from the State of Nevada to the Province of British Columbia, Canada."
   "The Company filed its most recent annual report on Form 20-F for the fiscal year ended January 31, 2025 on June 2, 2025.")
  ("2"
   "Item 2. Recent United States Market Activity The Company has not sold ")
  ("3" "Foreign Listing and Primary Trading Market A."
   "The Common Shares have been listed on the CSE since February 22, 2023 and on the FSE since February 28, 2023."
   "The Company has maintained a listing of its Common Shares on the CSE for at least the 12 months preceding the filing of this Form 15F.")
  ("4"
   "Comparative Trading Volume Data The Company's trading volume data relied upon under Rule 12h-6(a)(4)(i) of the Exchange Act are as follows:"
   "The Applicable Period is the recent 12-month period from April 29, 2025 to April 29, 2026, used to meet the requirements of Rule 12h-6(a)(4)(i)."
   "RMESF) was 1,376.4 Common Shares per day, and the worldwide average daily trading volume was 138,486.1 Common Shares per day across all markets.")
  ("5" "Item 5. Alternative Record Holder Information Not applicable.")
  ("6" "Item 6. Debt Securities Not applicable.")
  ("7"
   "The Company disseminated the notice in the United States and Canada by means of a press release (the \"Press Release\") published via Newsfile Corp."
   "The Company has submitted a copy of the Press Release under cover of a Form 6-K filed concurrently with this Form 15F."
   "A copy of the Press Release is attached as Exhibit 99.1 to this Form 15F.")
  ("8" "Item 8. Prior Form 15 Filers Not applicable.")
  ("II.9"
   "Item 9. Rule 12g3-2(b) Exemption All information required to be publis")
  ("III.10"
   "Exhibits Exhibit 99.1 Press Release of Red Metal Resources Ltd.")
  ("III.11"
   "or (3) It otherwise did not qualify for termination of its Exchange Act reporting obligations under Rule 12h-6."
   "SIGNATURE Pursuant to the requirements of the Securities Exchange Act of 1934, Red Metal Resources Ltd."
   "has duly authorized the undersigned person to sign on its behalf this certification on Form 15F."))
 :text
 ("The Applicable Period is the recent 12-month period from April 29, 2025 to April 29, 2026, used to meet the requirements of Rule 12h-6(a)(4)(i)."
  "RMESF) was 1,376.4 Common Shares per day, and the worldwide average daily trading volume was 138,486.1 Common Shares per day across all markets."
  "A copy of the Press Release is attached as Exhibit 99.1 to this Form 15F."
  "SIGNATURE Pursuant to the requirements of the Securities Exchange Act of 1934, Red Metal Resources Ltd."))
