(:sections nil :text
	   ("$15,000,000,000 (or its equivalent in other currencies) aggregate principal amount of its debt securities."
	    "• the rate of any interest the debt securities will bear and, if variable, the method by which the interest rate will be calculated;"
	    "and • all payments on the global security will be made to the depositary or its nominee."
	    "In addition, this notice shall be given between 30 and 60 days before the meeting date;"
	    "Any holder who wants to receive these additional amounts would have to present the debt security for payment within 30 days of when payment is due."
	    "3 to the Registrant’s Annual Report on Form 18-K/A for the fiscal year ended December 31, 2024 and incorporated by reference herein."))
