(:sections
 (("II.14" "OTHER EXPENSES OF ISSUANCE AND DISTRIBUTION."
   "All of such expenses are being borne by Carnival Corporation Ltd.")
  ("II.15" "INDEMNIFICATION OF DIRECTORS AND OFFICERS."
   "Section 98A of the Bermuda Companies Act permits Carnival Corporation Ltd."
   "may otherwise indemnify such officer or director.")
  ("II.16"
   "3.1 Memorandum of Continuance of Carnival Corporation Ltd."
   "(incorporated by reference to the Current Report on Form 8-K of Carnival Corporation Ltd., filed on May 7, 2026)."
   "24.1* Powers of Attorney (included on signature pages).")
  ("II.17" "UNDERTAKINGS (a) The Registrants hereby undertake:"
   "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "Gearhart /s/ Katie Lahey Director Katie Lahey /s/ Stuart Subotnick Director Stuart Subotnick /s/ Laura Weil Director Laura Weil /s/ Randall J."))
 :text
 ("Common Shares with a convenient method of purchasing additional Carnival Corporation Ltd."
  "7 USE OF PROCEEDS Carnival Corporation Ltd."
  "In the event the Agent should resign or otherwise cease to act as an agent or as custodian of shares under the Plan, Carnival Corporation Ltd."
  "14 (2) A participant’s holding period for Carnival Corporation Ltd."))
