(:sections
 (("1"
   "The following discussion contains forward-looking statements that reflect our plans, estimates, and beliefs."
   "As of June 30, 2026, the Company had $263,003 of cash and cash equivalents, compared to $1,970,251 as of December 31, 2025."
   "Method of Accounting The compensation described in this section was calculated using the accrual method in accordance with U.S.")
  ("2" "Item 2. Other Information None.")
  ("3"
   "Net income $ 73,011 $ 80,661 Depreciation 111,604 97,957 Non-cash lease expense 9,721 10,337 Changes in assets and liabilities:"
   "As of June 30, 2026 and December 31, 2025, 9,535,129 and 6,680,210 Class A Investor Shares, respectively, were issued and outstanding."
   "No Class B, Class C, or Class D Investor Shares were issued or outstanding as of June 30, 2026 or December 31, 2025.")
  ("4"
   "Factors which could have a material adverse effect on our operations and future prospects include, but are not limited to:"
   "**As of June 30, 2026 Loans Issued As of the date of this Semi-Annual Report, the Company has issued one (1) Loan."
   "The table below lists the total amount the Company has lent to each Borrower and the maximum loan amount."))
 :text
 ("Page 2 Our Business Energea Portfolio 4 USA LP (the \"Company\") is a limited partnership organized under the laws of Delaware."
  "The July 4, 2026, safe harbor deadline has created a near-term \"build window\" for eligible projects."
  "During the six months ended June 30, 2026 and 2025, investor share issuances, net of issuance costs, totaled $2,950,388 and $1,205,895, respectively."
  "F-6 Capitalization and investment in Project assets A Project has four basic phases:"
  "Credit risk is actively monitored on an ongoing basis at both the individual borrower level and the portfolio level."
  "As of June 30, 2026 and December 31, 2025, 9,535,129 and 6,680,210 Class A Investor Shares, respectively, were issued and outstanding."))
