(:sections
 (("1"
   "“Masterworks” refers to Masterworks, LLC, and or its wholly owned subsidiaries."
   "A summary of the financial condition of the Administrator as of June 30, 2023 is provided in Note 3 to the Financial Statements."
   "Additionally, the Company plans to own the Artwork for an indefinite period.")
  ("2" "Item 2. Other Information None 4")
  ("3"
   "Cash and Cash Equivalents $ 4,644,600 Total Current Assets 4,644,600 Total Assets $ 4,644,600 LIABILITIES AND MEMBERS’ EQUITY Current Liabilities:"
   "F-2 MASTERWORKS 239, LLC INCOME STATEMENT (UNAUDITED) For the Period January 24, 2023 Through June 30, 2023 Income:"
   "As of September 27th, 2023, such consent has been received and such changes are expected to become effective in the fourth quarter of 2023.")
  ("4" "Glenday Chief Executive Officer September 27th, 2023 Nigel S."
   "Glenday Chief Financial Officer September 27th, 2023 (Principal Financial Officer Nigel S."
   "Goldstein Member of the Board of September 27th, 2023 Managers Joshua B."))
 :text
 ("As of June 30, 2023, the Segregated Portfolio did not hold any material assets and had no liabilities."
  "Cash and Cash Equivalents $ 4,644,600 Total Current Assets 4,644,600 Total Assets $ 4,644,600 LIABILITIES AND MEMBERS’ EQUITY Current Liabilities:"
  "Member’s Liability – The Company is organized as a Delaware limited liability company."
  "See Note 3, which summarizes certain financial statement information of the Administrator."
  "The weighted average grant-date fair value of shares issued, if any, to the administrator during 2023 were $0.00 ."
  "As of September 27th, 2023, such consent has been received and such changes are expected to become effective in the fourth quarter of 2023."))
