(:sections nil :text
	   ("ADB’s 2025 investments across Asia and the Pacific are expected to generate more than 3.3 million jobs."
	    "Available Asian Development Fund Resourcesi 2,322 1,787 2,441 2,387 2,053 C."
	    "It will directly benefit 1.1 million people, including more than 530,000 women, 346,900 rural residents, and 24,700 people with disabilities."
	    "In 2025, ADB committed $650 million to support India’s national rooftop solar program, which aims to scale solar adoption for 10 million households."
	    "It also conducted 42 seminars on loan and grant disbursement and accounting, involving 1,408 participants from 17 DMCs."
	    "---------------------------------------------------------------------------------------------------- * 72 ANNUAL REPORT 2025 Appendix 7B:"))
