(:sections
 (("II.31" "Other Expenses of Issuance and Distribution."
   "All expenses incurred with respect to the registration of the Common Stock will be borne by us."
   "All amounts are estimates except the SEC registration fee.")
  ("II.32" "Item 32. Sales to Special Parties. Not applicable.")
  ("II.33" "Recent Sales of Unregistered Securities."
   "All of the foregoing issuances of Common Stock and Series D Preferred Stock were made to accredited investors.")
  ("II.34" "Indemnification of Directors and Officers."
   "We have entered into indemnification agreements with each of our current directors and executive officers."
   "We also intend to enter into indemnification agreements with future directors and executive officers.")
  ("II.35" "Treatment of Proceeds from Stock Being Registered.")
  ("II.36"
   "Item 36. Financial Statements and Exhibits. (a) Financial Statements. ")
  ("II.37" "(i) The undersigned registrant hereby undertakes:"
   "333-198245) filed on August 20, 2014 pursuant to the Securities Act of 1933)."
   "Stilwell Director June 22, 2026 Joseph D."))
 :text
 ("5 RISK FACTORS You should carefully consider the risks described below before making an investment decision."
  "22 Additionally, we possess Phase I Environmental Site Assessments for all of the properties in our portfolio."
  "Under the Significant Lease, the Significant Tenant leases 147,400 square feet of space at an effective rental rate per square foot of $4.28."
  "53 Provided that the Company continues to qualify for taxation as a REIT, we generally will not be required to pay U.S."
  "66 Passive Activity Losses and Investment Interest Limitations."
  "filed with SDAT on September 16, 2016 (Filed as exhibit to Form 8-K, filed on September 20, 2016)."))
