(:sections nil :text
	   ("As of the date hereof, the participants in this solicitation collectively beneficially own 3,079,000 shares of Common Stock (the “Group Shares”)."
	    "Calculated as of the close of business on May 24, 2023."
	    "WE STRONGLY URGE YOU TO VOTE “FOR” THE ELECTION OF THE NOMINEES ON THE ENCLOSED WHITE UNIVERSAL PROXY CARD."
	    "The Annual Meeting webcast will begin promptly at 10:00 a.m., Pacific Time."
	    "Shahinian is 350 Park Avenue, 13th Floor, New York, New York 10022."
	    "info@saratogaproxy.com WHITE UNIVERSAL PROXY CARD PRELIMINARY COPY SUBJECT TO COMPLETION DATED AUGUST 17, 2023 FORTE BIOSCIENCES, INC."))
