(:sections
 (("I.1"
   "Home Jurisdiction Documents The following documents are attached hereto as exhibits to this form:")
  ("I.2"
   "Informational Legends The required legends are included in the document referred to in Item 1."
   "The Tier I exemption exempts the Offer from most provisions of Regulation 14D and Rules 14e-1 and 14e-2 under the Exchange Act."
   "ANY REPRESENTATION TO THE CONTRARY IS A CRIMINAL OFFENCE IN THE UNITED STATES."))
 :text
 ("Description 99.1 Offer to the shareholders of Humana AB Item 2."
  "The Tier I exemption exempts the Offer from most provisions of Regulation 14D and Rules 14e-1 and 14e-2 under the Exchange Act."
  "1 The receipt of the Consideration (including the Cash Consideration, the Share Consideration and the CVR Instrument) pursuant to the Offer by a U.S."
  "state and local, as well as foreign and other, tax laws."
  "Holders to enforce their rights and any claims they may have arising under the U.S."))
