(:sections
 (("II.9"
   "Exhibits The following documents are filed as part of this registration statement on Form F-3."
   "24.1 Powers of Attorney (incorporated by reference to Exhibit 24.1 to the Prior Registration Statement)."
   "has signed this Registration Statement on Form F-3 in the Newark, Delaware on June 2, 2026."))
 :text
 ("20549 FORM F-3 REGISTRATION STATEMENT UNDER THE SECURITIES ACT OF 1933 GORILLA TECHNOLOGY GROUP INC."
  "333-274053) (the “Prior Registration Statement”), which was declared effective by the Commission on August 29, 2023."
  "24.1 Powers of Attorney (incorporated by reference to Exhibit 24.1 to the Prior Registration Statement)."))
