(:sections nil :text
	   ("Harris Corporate Secretary Grand Island, Nebraska July _______, 2026 IMPORTANT:"
	    "Age information is as of March 31, 2026, and term as a director includes service with Home Federal Savings."
	    "Central Plains Bancshares, Inc., 221 South Locust Street, Grand Island, Nebraska 68801, Attention:"
	    "Garness 2026 225,454 1,700 131,490 87,897 93,834 3,394 543,769 President and Chief Executive — — Officer Steven D."
	    "Expenses recognized in connection with the 401(k) Plan totaled approximately $145,000 for the year ended March 31, 2026."
	    "The 2027 annual meeting of stockholders is expected to be held August 27, 2027."))
