(:sections
 (("I.1"
   "Item 1. Home Jurisdiction Documents. Offer to Purchase and Circular, d")
  ("I.2"
   "Item 2. Informational Legends. See “Notice to Shareholders in the Unit")
  ("III.1"
   "Such information shall be set forth in amendments to this Schedule.")
  ("III.2"
   "Consent to Service of Process (a) The bidder has filed with the Commission a written irrevocable consent and power of attorney on Form F-X."))
 :text
 ("20549 SCHEDULE 14D-1F TENDER OFFER STATEMENT PURSUANT TO RULE 14d-1(b) UNDER THE SECURITIES EXCHANGE ACT OF 1934 AURORA CANNABIS INC."
  "2.2* Press release dated August 18, 2026 relating to Curaleaf Holdings, Inc.’s offer for all outstanding common shares of Aurora Cannabis Inc."
  "with respect to the fiscal year ended December 31, 2025 3.3* Annual Information form of Curaleaf Holdings, Inc."
  "for the three and six months ended June 30, 2026 3.6* Management’s Discussion and Analysis of Curaleaf Holdings, Inc."
  "Such information shall be set forth in amendments to this Schedule."
  "Boris Jordan Chief Executive Officer Date:"))
