(:sections
 (("II.14"
   "All amounts shown are estimates except for the Securities and Exchange Commission, or the SEC, registration fee.")
  ("II.15"
   "• any breach of their duty of loyalty to us or our stockholders;"
   "• unlawful payments of dividends or unlawful stock repurchases or redemptions as provided in Section 174 of the Delaware General Corporation Law;"
   "We believe that these agreements are necessary to attract and retain qualified individuals to serve as directors and executive officers.")
  ("II.16"
   "Item 16. Exhibits Exhibit Incorporation by Reference Filed Number Here")
  ("II.17"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act;"
   "1 to the Registration Statement on Form S-3ASR has been signed by the following persons in the capacities and on the dates indicated:"))
 :text
 ("SUBJECT TO COMPLETION, DATED APRIL 30, 2026 PROSPECTUS [MISSING IMAGE:"
  "Common Stock The selling stockholder may offer shares of our common stock, par value $0.0001 per share."
  "Ltd.(1)(2) 13,889,183 16.6% 13,889,183 0 0.0% (1) Consists of 13,889,183 outstanding shares of our common stock."
  "We will not receive any proceeds from the sale of the shares of our common stock covered hereby."
  "• our Quarterly Report on Form 10-Q for the quarter ended March 31, 2026, filed with the SEC on April 30, 2026;"
  "II-2 ---------------------------------------------------------------------------------------------------- TABLE OF CONTENTS Item 17."))
