(:sections
 (("II.12"
   "All amounts are estimated except the Securities and Exchange Commission registration fee.")
  ("II.13" "provided that, no such person will be indemnified:"
   "(ix) for costs, charges, expenses, liabilities and losses arising under Section 310 or 316 of the California Corporations Code;"
   "SCE has also entered into written agreements with each of its directors incorporating the indemnification provisions of its Amended Bylaws.")
  ("II.14"
   "Exhibits List of Exhibits EXHIBIT DESCRIPTION OF EXHIBIT NO."
   "99.1 Financing Order 99.2 Form of Opinion of Norton Rose Fulbright US LLP with respect to U.S.")
  ("II.15"
   "Undertakings (a) The undersigned registrant hereby undertakes that:"
   "Taylor* May 28, 2026 Keith Trent* May 28, 2026 *By:"
   "Moss President and Manager May 28, 2026 Aaron D."))
 :text
 ("- 7 - ---------------------------------------------------------------------------------------------------- Table of Contents Transaction Parties:"
  "Currently the direct access program is limited to 13,456.87 gigawatt hours of annual sales for SCE’s service area."
  "On February 24, 2021, we issued the Series 2021-A Bonds, which was our first issuance of recovery bonds."
  "ABS Corporate Trust Administration, Chicago, IL 60602."
  "federal estate, gift, alternative minimum tax or foreign tax considerations."
  "Internal Revenue Code means the Internal Revenue Code of 1986, as amended."))
