(:sections nil :text
	   ("A copy of the Amended Plan is attached to this Information Statement as Exhibit B-1 and Exhibit B-2 (marked copy)."
	    "A participant receiving ISOs should not recognize taxable income upon grant."
	    "Lyons directly and (b) 172,095 of which are held by 2136305 Ontario, Inc., which Mr."
	    "Harwood Street, 19th Floor, Dallas, Texas 75201."
	    "December 30, 2022 /s/ Travis VanderZanden Dated Name:"))
