(:sections
 (("1" "Furnish the following information as to the Trustee."
   "a) Name and address of each examining or supervising authority to which it is subject."
   "b) Whether it is authorized to exercise corporate trust powers.")
  ("2"
   "If the obligor is an affiliate of the Trustee, describe each such affiliation.")
  ("16"
   "List below all exhibits filed as a part of this statement of eligibility and qualification."
   "The consent of the Trustee required by Section 321(b) of the Trust Indenture Act of 1939, attached as Exhibit 6."
   "SIGNATURE Pursuant to the requirements of the Trust Indenture Act of 1939, as amended, the Trustee, U.S."))
 :text
 ("BANK TRUST COMPANY, NATIONAL ASSOCIATION (Exact name of Trustee as specified in its charter) 91-1821036 I.R.S."
  "The consent of the Trustee required by Section 321(b) of the Trust Indenture Act of 1939, attached as Exhibit 6."))
