(:sections nil :text
	   ("JHG is expected to exercise its option to acquire Brendan Boyle’s 51% ownership interest in Privacore Capital by the end of October 2026."
	    "Each individual’s address is c/o Privacore Capital Advisors, LLC, 1411 Broadway, New York, NY 10018."
	    "Bank”), whose principal business address is 615 East Michigan Street, Milwaukee, WI 53202, to provide administrative services and accounting services."
	    "provide appropriate and timely responses to reasonable requests made by such persons;"))
