(:sections
 (("II.13" "Other Expenses of Issuance and Distribution."
   "The following is a statement of estimated expenses in connection with the offering described in this registration statement."
   "All amounts are estimates except the SEC registration fee.")
  ("II.14" "Indemnification of Directors and Officers."
   "The provisions do not alter the liability of directors under the federal securities laws."
   "Reference is made to Item 17 for our undertakings with respect to indemnification for liabilities arising under the Securities Act.")
  ("II.15" "Recent Sales of Unregistered Securities."
   "No underwriters were involved in the transaction.")
  ("II.16"
   "Exhibits, Financial Statements and Financial Statement Schedules.")
  ("II.17" "The undersigned registrant hereby undertakes:"
   "10.17 Settlement Agreement with Kieran Murphy, dated December 21, 2021 (incorporated by reference to Exhibit 10.16 to the Registrants Amendment No."
   "Madden Director Tomislav Mihaljevic Director William J."))
 :text
 ("§ 200.83 TRADEMARKS AND COPYRIGHTS GE HealthCare and the GE Monogram Logo are trademarks of GE."
  "§ 200.83 the effectiveness of our internal control over financial reporting."
  "The address of GE is 5 Necco Street, Boston, MA 02210."
  "These authorities may change or be subject to differing interpretations."
  "status, such as by furnishing a valid IRS Form W-8BEN, W-8BEN-E, W-8ECI or other applicable IRS form, or otherwise establishes an exemption."
  "10.17 Settlement Agreement with Kieran Murphy, dated December 21, 2021 (incorporated by reference to Exhibit 10.16 to the Registrants Amendment No."))
