(:sections
 (("1"
   "We incurred net losses of $41.8 million and $29.5 million for the years ended December 31, 2024 and 2023, respectively."
   "We have no control over the analysts or the content and opinions included in their reports."
   "In August 2024, we announced the successful completion of our end-of-Phase 2 meeting with the U.S.")
  ("1A" "Item 1A. Risk Factors 29")
  ("1B" "Item 1B. Unresolved Staff Comments 79")
  ("1C"
   "Our assessment and management of material risks from cybersecurity threats are considered as part of our risk management processes."
   "The IT Lead has 4 years of experience in roles that include oversight of cybersecurity risk management programs."
   "In addition, the Company’s incident response processes include reporting to the audit committee for certain cybersecurity incidents.")
  ("2"
   "We believe our existing facilities are sufficient for our needs for the foreseeable future.")
  ("3"
   "LEGAL PROCEEDINGS 80 \fWe are not currently a party to any material legal proceedings."
   "From time to time, we may be involved in legal proceedings or subject to claims incident to the ordinary course of business.")
  ("4" "Item 4. Mine Safety Disclosures 81 PART II 82")
  ("5"
   "This number of holders of record also does not include stockholders whose shares may be held in trust by other entities."
   "Dividend Policy We have never declared or paid cash dividends on our capital stock."
   "Recent Sales of Unregistered Securities None.")
  ("6"
   "Our actual results and the timing of events could differ materially from those discussed in these forward-looking statements."
   "Our net losses were $41.8 million and $29.5 million for the years ended December 31, 2024 and 2023, respectively."
   "In determining the fair value of stock options, we use the Black-Scholes option-pricing model.")
  ("7"
   "Item 7. Management’s Discussion and Analysis of Financial Condition an")
  ("7A"
   "QUANTITATIVE AND QUALITATIVE DISCLOSURES ABOUT MARKET RISK Not required for smaller reporting companies."
   "Total Commitment Year Ending (in thousands) 2025 1,861 2026 1,926 2027 1,994 2028 and beyond 6,410 Total minimum lease payments 12,191 Less:"
   "The CODM monitors the Company's cash and cash equivalents as reported on the Consolidated Balance Sheets.")
  ("8" "Item 8. Financial Statements and Supplementary Data 94")
  ("9"
   "Item 9. Changes in and Disagreements with Accountants on Accounting an")
  ("9A"
   "Because of its inherent limitations, internal control over financial reporting may not prevent or detect misstatements."
   "Our management assessed the effectiveness of our internal control over financial reporting as of December 31, 2024."
   "Attestation Report of the Registered Public Accounting Firm.")
  ("9B"
   "DISCLOSURE REGARDING FOREIGN JURISDICTIONS THAT PREVENT INSPECTIONS.")
  ("9C"
   "Item 9C. Disclosure Regarding Foreign Jurisdictions that Prevent Inspe")
  ("10"
   "Code of Business Conduct and Ethics We have adopted a Code of Business Conduct that applies to all officers, directors and employees."
   "The full text of our Code of Conduct is available at the investors section of our website at www.tempesttx.com.")
  ("11"
   "ITEM 11. EXECUTIVE COMPENSATION Information regarding our Executive Co")
  ("12"
   "ITEM 12. SECURITY OWNERSHIP OF CERTAIN BENEFICIAL OWNERS AND MANAGEMEN")
  ("13"
   "ITEM 13. CERTAIN RELATIONSHIPS AND RELATED TRANSACTIONS, AND DIRECTOR ")
  ("14"
   "ITEM 14. PRINCIPAL ACCOUNTANT FEES AND SERVICES Information regarding ")
  ("15"
   "EXHIBITS AND FINANCIAL STATEMENT SCHEDULES We have filed the following documents as part of this Annual Report:"
   "8-K 001-35890 10.4 7/07/2021 Lease Agreement, dated January 24, 2022, by and between HCP Life Science 10.24 REIT, Inc."
   "^ These certifications are being furnished solely to accompany this Annual Report pursuant to 18 U.S.C.")
  ("16"
   "/s/ Stephen Brady Stephen Brady Chief Executive Officer & President (Principal Executive Officer) By:"
   "/s/ Nicholas Maestas Nicholas Maestas Chief Financial Officer & Head of Corporate Strategy (Principal Financial Officer) Date:"
   "/s/ Christine Pellizzari Director March 27, 2025 Christine Pellizzari /s/ Ronit Simantov Director March 27, 2025 Ronit Simantov, M.D."))
 :text
 ("License Agreements Roche Collaboration Agreement In February 2021, we entered into a collaboration agreement with F."
  "The address of the SEC’s website is www.sec.gov."
  "As part of any marketing approval, a manufacturer and its processes are required to be qualified by the FDA prior to regulatory approval."
  "The outcome for any particular patent 68 \ffollowing legal assertions of invalidity and unenforceability is unpredictable."
  "Our net losses were $41.8 million and $29.5 million for the years ended December 31, 2024 and 2023, respectively."
  "As of December 31, 2024, there were 508,017 shares available for future grant under the 2023 Plan."))
