(:sections nil :text
	   ("As of September 22, 2026, approximately US$ 74,900,460.95 was held in the Trust Account."
	    "13 Required Votes for Each Proposal to Pass Assuming the presence of a quorum at the Special Meeting:"
	    "Quartzsea Acquisition Corporation, 1185 Avenue of the Americas, suite 349, New York, NY 10036."
	    "The Company’s existing Trust Agreement provides that the Company must complete its initial business combination by October 19, 2026."
	    "ET on October 13, 2026, virtually, via live webcast, for which advance registration is required."))
