(:sections nil :text
	   ("· Also on September 15, 2023, the Company filed its preliminary consent revocation statement with the SEC."
	    "---------------------------------------------------------------------------------------------------- 1 Infinity press release issued July 25, 2023."
	    "Funicular is a private investment partnership whose principal business is investing and trading in securities."
	    "19 Old Kings Highway S., Suite 130, Darien, CT 06820, (877) 972-0090 (Stockholders), (203) 972-9300 (Banks and Brokers)."
	    "THE PARTICIPATING STOCKHOLDERS RECOMMEND THAT YOU CONSENT TO PROPOSALS 1 AND 2."))
