(:sections
 (("II.13"
   "All the amounts shown are estimates except the SEC registration fee and the FINRA filing fee.")
  ("II.14"
   "Indemnification of Directors and Officers The Registrant is incorporated under the laws of the State of Delaware."
   "● transaction from which the director derives an improper personal benefit;"
   "Under these agreements, the Registrant is not required to provide indemnification for certain matters, including:")
  ("II.15"
   "● On December 5, 2022, we issued an aggregate of 1,919 shares of our common stock to a consultant in consideration of services.")
  ("II.16"
   "333-219386), as amended, originally filed on July 21, 2017."
   "+ Indicates management contract or compensatory plan."
   "4.6 Form of Warrant, incorporated by reference to Exhibit 10.2 of the Registrant’s Current Report on Form 8-K filed on November 22, 2019.")
  ("II.17"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "Confer Member of the Board of Directors [●], 2025 Brent M."
   "Longnecker Chairman of the Board of Directors [●], 2025 Jose Antonio Moreno Toscano Member of the Board of Directors [●], 2025 Will R."))
 :text
 ("Delivery of the securities offered hereby is expected to be made on or about , 2025, subject to satisfaction of customary closing conditions."
  "On December 30, 2024, we submitted to the Staff a plan to regain compliance with Listing Rule 5550(b)(1)."
  "see “Prospectus Summary–Recent Developments–Nasdaq Compliance Matters”, above, and the Risk Factor addressing Nasdaq compliance matters below;"
  "As of April 21, 2025, there were 25,414,250 shares of Common Stock issued and outstanding and no shares of Preferred Stock issued and outstanding."
  "To obtain copies of these filings, see “Where You Can Find More Information” in this prospectus."
  "21.1 Subsidiaries of the Registrant, incorporated by reference to Exhibit 21.1 of the Registrant’s Annual Report on Form 10-K filed on April 1, 2025."))
