(:sections nil :text
	   ("An investment advisory agreement automatically terminates upon its “assignment” under the applicable provisions of the agreement and the 1940 Act."
	    "If you need additional copies of this Proxy Statement or proxy card, please contact our proxy solicitor, Computershare, toll-free at 1-866-905-8143."
	    "(1) the nature, extent, and quality of the services to be provided by the Adviser with respect to the Fund;"
	    "Tidal is located at 234 West Florida Street, Suite 203, Milwaukee, Wisconsin 53204."
	    "provided, however, that such allocation comports with applicable law including, without limitation, Rule 12b-1(h) under the 1940 Act."
	    "MET_33538_091523 PLEASE MARK, SIGN, AND DATE ON THE REVERSE SIDE AND RETURN THE PROXY CARD USING THE ENCLOSED ENVELOPE."))
