(:sections nil :text
	   ("· On February 23, 2023, MEI Pharma and Infinity Pharmaceuticals, Inc."
	    "The Participating Stockholders will reimburse these holders for their reasonable out-of-pocket expenses in so doing."
	    "19 Old Kings Highway S., Suite 130, Darien, CT 06820, (877) 972-0090 (Stockholders), (203) 972-9300 (Banks and Brokers)."
	    "☐ ☐ ☐ Consent Against Consent Abstain 2."))
