(:sections nil :text
	   ("The Special Meeting will be held on , 2026 at , Eastern Time."
	    "On April 27, 2026, a representative of Brookfield contacted Mr."
	    "and · persons who do not hold Company Common Shares as capital assets within the meaning of Section 1221 of the Code."
	    "provided that no such adjournment pursuant to this sentence will be required to be for a period exceeding ten (10) business days, in the aggregate."
	    "“Parent Termination Payment” means an amount equal to $288,654,765."
	    "(New York City time) on January 19, 2027 (the “Outside Date”);"))
