(:sections
 (("1" "Description of Registrant’s Securities to be Registered."
   "The securities to be registered hereby are the class R units of VistaOne, L.P."
   "Unitholders of record as of the record date will be eligible for distributions (if any) declared.")
  ("2"
   "Exhibit Number Description 3.1 Second Amended and Restated Limited Partnership Agreement of VistaOne, L.P."
   "(incorporated by reference to Exhibit 3.1 to the Registrant’s Quarterly Report on Form 10-Q, filed on August 13, 2025)."))
 :text
 ("(Exact Name of Registrant as Specified in its Charter) Delaware 33-1386882 (State or other jurisdiction of incorporation (I.R.S."
  "Description of Registrant’s Securities to be Registered."
  "Exhibit Number Description 3.1 Second Amended and Restated Limited Partnership Agreement of VistaOne, L.P."
  "(incorporated by reference to Exhibit 3.1 to the Registrant’s Quarterly Report on Form 10-Q, filed on August 13, 2025)."))
