(:sections nil :text
	   ("1 - REVERSE STOCK SPLIT PROPOSAL 8 PROPOSAL NO."
	    "Proxies submitted by mail must be received before the polls close at the Special Meeting on September 22, 2026."
	    "The 2026 Notes mature on October 1, 2026, before the November 4, 2026, expiration of Nasdaq’s Initial Compliance Deadline."
	    "federal income tax purposes pursuant to Section 368(a)(1)(E) of the Code."
	    "Fanning (8) 527,283 * Michelle Kerrick (9) 189,813 * Brian Miller (10) 33,603,776 25.8% Doug Schillinger(11) 216,035 * Sachin Shridharani, M.D."
	    "VOTE BY PHONE - 1 - 800 - 690 - 6903 Use any touch - tone telephone to transmit your voting instructions up until 11 :"))
