(:sections
 (("II.8"
   "Generally, under the Companies Act, a company may not indemnify its directors against personal liability covering:"
   "liability to the company in cases where the company sues the director (i.e., only liability to third parties can be the subject of an indemnity);"
   "The Company will enter into a deed of indemnity with each of its directors and officers.")
  ("II.9"
   "Exhibits The following is a list of exhibits filed as a part of this registration statement:"
   "Nikolaus Senn Director June 5, 2026 Prem Parameswaran Director June 5, 2026 David Chung-Hua Bolocan Director June 5, 2026 Dr."
   "Mustafa Ergen II-4 SIGNATURE OF AUTHORIZED U.S."))
 :text
 ("In addition, as long as we remain an emerging growth company, we will qualify for certain limited exceptions from the Sarbanes-Oxley Act of 2002."
  "Our principal executive office is located at 50 Liverpool Street, London, EC2M 7PY, and our phone number is +44 (0) 207 754 3735."
  "● in an “at the market” offering within the meaning of Rule 415(a)(4) of the Securities Act;"
  "13 Subscription Rights We may issue rights to purchase our securities."
  "The percentage ownership information shown in the table is based upon 59,362,026 ordinary shares outstanding as of May 28, 2026."
  "+44 (0) 207 754 3735 21 PART II — INFORMATION NOT REQUIRED IN PROSPECTUS Item 8."))
