(:sections nil :text
	   ("times  (x) the number of days in the applicable interest period based on a 360-day year of twelve 30-day months, divided by (y) 360;"
	    "For example, the new credit card accounts may have higher or lower fees or interest rates, or different payment terms."
	    "In addition, JPMorgan Chase Bank may extend reduced rate offers to retain certain accounts."
	    "Holders of notes will not be charged any service charge for the exchange or transfer of their notes."
	    "In January 2025, the CFPB issued a notice seeking information for the 2025 report."
	    "333-272941, 333-272941-01) relating to the offered notes with the SEC."))
