(:sections
 (("I.1"
   "Item 1. Exchange Act Reporting History A. Westpac Banking Corporation ")
  ("I.2"
   "Item 2. Recent United States Market Activity A. The Company’s securiti")
  ("I.3"
   "Item 3. Foreign Listing and Primary Trading Market Not applicable.")
  ("I.4" "Item 4. Comparative Trading Volume Data Not applicable.")
  ("I.5" "Alternative Record Holder Information Not applicable.")
  ("I.6"
   "Item 6. Debt Securities The number of record holders on a worldwide ba")
  ("I.7"
   "Item 7. Notice Requirement A. As required by Rule 12h-6(h), the Compan")
  ("I.8" "Item 8. Prior Form 15 Filers Not applicable.")
  ("II.9"
   "Item 9. Rule 12g3-2(b) Exemption The Company will publish the informat")
  ("III.10"
   "Item 10. Exhibits Exhibit 99.1 Media Release pursuant to Rule 12h-6(h)")
  ("III.11"
   "Item 11. Undertakings The undersigned issuer hereby undertakes to with"))
 :text
 ("Exhibits Exhibit 99.1 Media Release pursuant to Rule 12h-6(h), dated March 5, 2026."))
