(:sections nil :text
	   ("_________________________ SUPPLEMENT DATED SEPTEMBER 28, 2026 TO THE PROXY STATEMENT OF DGB INVESTMENT, INC."
	    "Farooq Kathwari (1) 2,279,723 – 2,279,723 Tara I."
	    "Sable – 10,208 10,208 Cynthia Ekberg Tsai 1,000 10,208 11,208 Amy Phillips 11,075 – 11,075 Matthew J."
	    "OkapiColorFinal.tif Okapi Partners LLC 1212 Avenue of the Americas, 17th Floor New York, New York 10036 Stockholders may call toll-free:"
	    "Stacom ¨ ¨ e) Cynthia Ekberg Tsai ¨ ¨ DGB MAKES NO RECOMMENDATION WITH RESPECT TO PROPOSAL 2."))
