(:sections
 (("I.1"
   "The following documents are attached as exhibits to this Form CB:")
  ("I.2" "Item 2. Informational Legends. Not applicable."))
 :text
 ("Exhibit Name of Exhibit Number 99.1 Repricing Notice to Israeli employees and directors."
  "PART II - INFORMATION NOT REQUIRED TO BE SENT TO SECURITY HOLDERS Not applicable."
  "PART III - CONSENT TO SERVICE OF PROCESS On the date hereof, Foresight Autonomous Holdings Ltd."))
