(:sections
 (("II.8"
   "This standard of conduct is generally the same as permitted under the Delaware General Corporation Law for a Delaware corporation.")
  ("II.9"
   "ITEM 9. EXHIBITS See Exhibit Index beginning on page II-4 of this regi")
  ("II.10" "(a) The undersigned registrant hereby undertakes:"
   "1 to be signed on its behalf by the undersigned, thereunto duly authorized, in Singapore, on April 15, 2026."
   "Senior Vice President on behalf of Cogency Global Inc."))
 :text
 ("• “Series A-1 Preferred Shares” are to our series A-1 convertible preferred shares, par value $0.00000005 per share;"
  "• an exempted company may obtain an undertaking against the imposition of any future taxation (such undertakings are given for up to 30 years);"
  "Cayman Islands law governs shareholder rights."
  "• when you owe money to pay fees, taxes and similar charges;"
  "• the extent to which such subscription rights are transferable;"
  "28 Ayer Rajah Crescent #06-08 Singapore 139959 Tel:"))
