(:sections
 (("1.02"
   "ITEM 1.02 Termination of a Material Definitive Agreement In connection")
  ("3.01"
   "ITEM 3.01 Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard;")
  ("3.03"
   "ITEM 3.03 Material Modification to Rights of Security Holders.")
  ("5.03"
   "ITEM 5.03 Amendments to the Articles of Incorporation or Bylaws;")
  ("8.01"
   "The information set forth in the Introductory Note of this report is incorporated by reference into this Item 8.01."
   "On July 29, 2026, the Company issued a press release regarding the completion of the Conversion and approval of the U.S."
   "The press release is filed as Exhibit 99.1 to this report and incorporated herein by reference.")
  ("9.01" "ITEM 9.01 Financial Statements and Exhibits."
   "is expected to be completed in January 2027 NEW YORK, July 29, 2026 – Criteo S.A."
   "(d) Exhibits Exhibit Description Number 3.1 Articles of Association of Criteo S.A."))
 :text
 ("On July 29, 2026, the Company issued a press release regarding the completion of the Conversion and approval of the U.S."
  "ITEM 9.01 Financial Statements and Exhibits."
  "10.5.1 that the Remaining Holder may, within thirty (30) days from the Acquisition Notice Date, exercise that choice;"
  "12Board Observers 12.1Pursuant to a proposal of the Board of Directors, the General Meeting may appoint Board observers."
  "is expected to be completed in January 2027 NEW YORK, July 29, 2026 – Criteo S.A."))
