(:sections nil :text
	   ("Such forward-looking information includes, but is not limited to, statements related to:"
	    "2 Hydro One owns and operates approximately 94% of the transmission system in Ontario based on the total OEB approved revenue requirement."
	    "On 29 January 2026, the Department of Finance (Canada) released the Hybrid Mismatch Proposals for consultation."
	    "Notice on the Sale of Investment Products and MAS Notice FAA-N16:"
	    "The Board of Directors has appointed Harry Taylor as Interim President and Chief Executive Officer effective August 25, 2025."))
