(:sections
 (("5"
   "Management (a) Investment Adviser Eaton Vance Management (“Eaton Vance”) serves as investment adviser to the Fund."
   "Ott, who has managed the Fund since March 31, 2026 and Kenneth D."
   "Zinner, who has managed the Fund since July, 2021.")
  ("6"
   "Purchase and Sale of Fund Shares (a) Purchase of Fund Shares Registrant does not offer shares of the Fund (as defined in Item 9 below) for sale."
   "(b) Sale of Fund Shares A shareholder may redeem Fund shares on any business day, which is any day the New York Stock Exchange is open for business."
   "You may redeem Fund shares directly from the Fund either by writing to Eaton Vance Funds, P.O.")
  ("7"
   "Tax Information The Fund’s distributions are expected to be taxed as ordinary income and/or capital gains to investors subject to taxation.")
  ("8"
   "Item 8. Financial Intermediary Compensation Information concerning the")
  ("9"
   "Investment Objectives, Principal Investment Strategies, Related Risks and Disclosure of Portfolio Holdings."
   "(a) Investment Objective The Registrant is an open-end diversified management investment company."
   "The Fund’s investment practices and risks are the same as those of the Feeder Fund.")
  ("10"
   "(b) Capital Stock The Fund is the sole series of the Registrant, a Massachusetts business trust.")
  ("11"
   "Eastern time) on each day that the NYSE is open for business (typically Monday through Friday) (the “Pricing Time”)."
   "normally, when the redemption or repurchase price equals or exceeds $2,500 portfolio securities will be used by the Registrant."
   "federal income taxes and any state or local taxes on any such distributions of taxable income from the Fund.")
  ("12" "The Fund can withdraw from the Portfolio at any time."
   "A-5 PART B This Part B should be read in conjunction with Part A."
   "Capitalized terms used in this Part B and not otherwise defined have the meanings given them in Part A.")
  ("14"
   "Item 14. Cover Page and Table of Contents Eaton Vance Series Trust Pag")
  ("15"
   "Item 15. Fund History The Registrant is organized as a business trust ")
  ("16"
   "Description of the Fund and Its Investments and Risks (a) Classification The Registrant is an open-end diversified management investment company."
   "(b) Investment Strategies and Risks The Fund’s investment strategies and risks are the same as those of the Feeder Fund."
   "Information concerning the Fund’s investment restrictions is incorporated by reference from “Investment Restrictions” in the Feeder Fund SAI.")
  ("17"
   "(see “Principal Underwriter” under “Other Service Providers”)."
   "Mosley $ 48 $10, 4235 $ 431,2506 Keith Quinton $51 $10,968 $453,901 Marcus L."
   "6 Includes $30,000 of deferred compensation.")
  ("18"
   "B-6 Northern Trust FBO Survivors Tust Under McCarthy Rev Tr Chicago, IL 10.60% Gordon E."
   "Moore & Betty I Moore Tr U/A DTD 10/09/1973 Woodside, CA 5.49% Northern Trust Co.")
  ("19"
   "Eaton Vance and its predecessor organizations have been managing assets since 1924 and managing mutual funds since 1931."
   "For the fiscal years ended December 31, 2024 , 2023 and 2022 , the Fund incurred no investment adviser fee."
   "(h) Other Service Providers The Fund’s custodian and independent registered public accounting firm are the same as those of the Feeder Fund.")
  ("20" "Barton None $ 100 ,001 - $ 500 ,000 Sabrina G.")
  ("21"
   "Item 21. Brokerage Allocation and Other Practices Information concerni")
  ("22"
   "The Trustees have the authority under the Declaration of Trust to create additional classes of shares with differing rights and privileges."
   "or (2) by the approval of a majority of the Trustees then in office, to be followed by a written notice to shareholders."
   "The B-9 assets of each Fund are readily marketable and will ordinarily substantially exceed its liabilities.")
  ("23"
   "Purchase, Redemption, and Pricing (a) and (b) The Registrant does not offer shares of the Fund for sale."
   "(c) The Fund’s net asset value is determined in the same manners as the Feeder Fund’s net asset value.")
  ("24"
   "Taxation of the Fund The following is a summary of some of the tax consequences affecting a Fund and its shareholders."
   "B-21 In addition to the Section 817(h) diversification requirements, “investor control” limitations also are imposed on owners of Variable Contracts."
   "The taxation of the Fund, the Portfolio (if any), the Subsidiary (if any) and shareholders may be adversely affected by future legislation, U.S.")
  ("25"
   "Item 25. Underwriters Not applicable because Registrant does not make ")
  ("26" "Item 26. Calculation of Performance Data Not applicable.")
  ("27"
   "Item 27. Financial Statements Information concerning the audited finan")
  ("28" "40 of the Registrant filed April 28, 2016 (Accession No."
   "333-182175, 811-22714) filed November 27, 2023 (Accession No."
   "0001133228-26-004073) and incorporated herein by reference.")
  ("29"
   "Item 29. Persons Controlled by or under Common Control with Registrant")
  ("30"
   "Article XI of the By-Laws contains indemnification provisions.")
  ("31"
   "Business and Other Connections of Investment Adviser Reference is made to:"
   "(ii) the Morgan Stanley 10-K filed under the Securities and Exchange Act of 1934 (File No."
   "and (iii) the Form ADV of Eaton Vance (File No.")
  ("32"
   "Item 32. Principal Underwriters Not applicable because Registrant does")
  ("33"
   "Item 33. Location of Accounts and Records All applicable accounts, boo")
  ("34" "Item 34. Management Services Not Applicable")
  ("35"
   "Item 35. Undertakings Not Applicable C-3 SIGNATURE Pursuant to the req"))
 :text
 ("Interests in the Portfolio generally will not be priced on days that the NYSE is closed."
  "1959 &hairsp;Trustee since 2025 Formerly, and Trustee Trustee at since 2016 Wheelock College (postsecondary institution) (2012-2018)."
  "Zinner None $ 100 ,001 - $ 500 ,000 Item 21."
  "B-14 Investments in PFICs could subject the Fund to U.S."
  "status (including, in general, furnishing an IRS Form W-8BEN, IRS Form W-8BEN-E, or substitute form)."
  "002-27962, 811-01545) filed September 27, 2010 (Accession No."))
