(:sections
 (("15"
   "(2) the director or officer actually received an improper personal benefit in money, property or services;"
   "or (3) in the case of any criminal proceeding, the director or officer had reasonable cause to believe that the act or omission was unlawful."
   "BCPL has entered into indemnification agreements with each of its directors and officers.")
  ("16"
   "1 to Form 10 filed on April 23, 2018) (13)(b) Dividend Reinvestment Plan of the Registrant (incorporated by reference to Exhibit 10.3 to Amendment No."
   "Bank Trust Company, National Association, U.S.")
  ("17"
   "Item 17. Undertakings. (1) The undersigned registrant agrees that prio"))
 :text
 ("1 year 3 years 5 years 10 years You would pay the following expenses on a $1,000 investment:"
  "• the announcement of the Merger Agreement or the transactions contemplated thereby or the identities of the parties to the Merger Agreement;"
  "For taxable years beginning in 2026 or later, miscellaneous itemized deductions generally are deductible by a noncorporate U.S."
  "• any person who beneficially owns 10% or more of the voting power of the corporation’s stock;"
  "HSR Act filing not required, assuming the Company’s total assets remain under $252.9 million."))
