(:sections
 (("15" "Item 15. Indemnification. To be included by amendment.")
  ("16"
   "The following exhibits are incorporated by reference to the Registrant’s previously filed documents indicated below, except as noted:"
   "None other than those contained in Exhibits (1) and (2)."
   "(16) Powers of Attorney (May 20, 2026) attached as Exhibit No.")
  ("17"
   "Lytle President/Chief Executive Officer May 22, 2026 Shawn K."
   "Abernathy * Trustee May 22, 2026 Jerome D."
   "Lytle as Attorney-in-Fact for each of the persons indicated (Pursuant to Powers of Attorney filed herewith) 4 U.S."))
 :text
 ("534437, 1350 Penn Avenue Suite 102, Pittsburgh, PA 15222 by overnight courier service, or call toll-free (800) 523-1918."
  "All shares of a Fund represent an undivided proportionate interest in the 29 assets of the Fund."
  "The performance shown for the Nomura Smid Cap Core Fund from before April 30, 2021 are from such Fund’s prior investment manager."))
