(:sections
 (("28"
   "Bank National Association (1) (h) (1) Fund Administration, Accounting and Transfer Agency Agreement between the Registrant and U.S."
   "(q) Powers of Attorney (1) (1) Filed herewith.")
  ("29" "Item 29. Persons Controlled By or Under Common Control with Registrant")
  ("30" "Item 30. Indemnification Under the terms of the Delaware Statutory Tru")
  ("31" "288829), as required under applicable state securities laws and regulations.")
  ("32"
   "ActivePassive Core Bond ETF, Series of Trust for Professional Managers 4."
   "CYBER HORNET S&P 500® and Bitcoin 75/25 Strategy ETF, Series of ONEFUND Trust 51."
   "Whetstone Three Canal Plaza, Suite Secretary None 100, Portland, ME 04101 Susan L.")
  ("33"
   "Location of Accounts and Records All accounts, books and other documents required to be maintained by Section 31(a) of 15 U.S.C."
   "80a-3-(a) and rules under that section, are maintained by U.S.")
  ("34" "Item 34. Management Services Not Applicable.")
  ("35"
   "Bank National Association (h)(1) Fund Administration, Accounting and Transfer Agency Agreement by and between the Registrant and U.S."))
 :text nil)
