(:sections
 (("25"
   "4 to the Registrant’s Registration Statement on Form N-2 (File Nos."
   "333-196590 and 811-22974) and incorporated by reference herein."
   "5 to the Registrant’s Registration Statement on Form N-2 (File Nos.")
  ("26"
   "ITEM 26. MARKETING ARRANGEMENTS The information contained under the he")
  ("27"
   "Any registration fees will be paid subsequently on a pay-as-you-go basis."
   "(2) These fees will be calculated based on the securities offered and the number of issuances and accordingly, cannot be estimated at this time.")
  ("28"
   "ITEM 28. PERSONS CONTROLLED BY OR UNDER COMMON CONTROL Eagle Point Cre")
  ("29"
   "ITEM 29. NUMBER OF HOLDERS OF SECURITIES The following table sets fort")
  ("30"
   "ITEM 30. INDEMNIFICATION Directors and Officers Reference is made to A")
  ("31"
   "ITEM 31. BUSINESS AND OTHER CONNECTIONS OF INVESTMENT ADVISER A descri")
  ("32"
   "(1) the Registrant, Eagle Point Credit Company, 600 Steamboat Road, Suite 202, Greenwich, CT 06830;")
  ("33" "ITEM 33. MANAGEMENT SERVICES Not applicable.")
  ("34"
   "(a) to file, during any period in which offers or sales are being made, a post-effective amendment to the registration statement:"
   "(1) to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "Tramontano /s/ * Trustee May 22, 2026 Jeffrey L."))
 :text
 ("333-286484 Check each box that appropriately characterizes the Registrant:"
  "Chief Executive Officer and Trustee May 22, 2026 Majewski Thomas P."))
