(:sections
 (("25" "FINANCIAL STATEMENTS AND EXHIBITS (1) Financial Statements:"
   "[To be included with subsequent amendment].")
  ("26" "ITEM 26. MARKETING ARRANGEMENTS Not Applicable.")
  ("27"
   "ITEM 27. OTHER EXPENSES OF ISSUANCE AND DISTRIBUTION The following tab")
  ("28"
   "ITEM 28. PERSONS CONTROLLED BY OR UNDER COMMON CONTROL The information")
  ("29"
   "NUMBER OF HOLDERS OF SECURITIES Set forth below is the number of holders of securities of the Registrant as of March 2, 2026:")
  ("30"
   "ITEM 30. INDEMNIFICATION Section 2-418 of the Maryland General Corpora")
  ("31"
   "ITEM 31. BUSINESS AND OTHER CONNECTIONS OF ADVISER A description of an")
  ("32"
   "ITEM 32. LOCATION OF ACCOUNTS AND RECORDS All accounts, books and othe")
  ("33" "ITEM 33. MANAGEMENT SERVICES Not Applicable.")
  ("34"
   "or (2) the net asset value increases to an amount greater than the net proceeds as stated in the prospectus."
   "Director and Chief Executive Officer Joseph A."
   "Stein Chief Operating Officer, Treasurer and Secretary *Thomas Massie Director Thomas Massie *Andrew W."))
 :text
 ("In February 2026, x.AI was acquired by and consolidated into SpaceX."
  "nationalization of companies by foreign governments;"
  "-44- • a trust that (i) is subject to the primary supervision of a court within the U.S."
  "The Fund’s principal address is 1000 RXR Plaza, Uniondale, New York 11556, and its telephone number is 212-440-9644."
  "Stein Over $100,000 Over $100,000 Independent Directors Andrew W."))
