(:sections nil :text
	   ("1800 Avenue of the Stars, Suite 1400 Los Angeles, CA 90067 under the Investment Company Act of 1940 Investment Company Act File No."
	    "Series A Mandatory Redeemable Preferred Stock, par value $0.001 per share, liquidation preference of $25.00 per share (CUSIP No."
	    "July 15, 2026 (3) The applicable provisions of the governing instrument pursuant to which the securities are to be called or redeemed:"
	    "The Fund intends to redeem all 800,000 of the issued and outstanding Series A MRP Shares."
	    "Ares Dynamic Credit Allocation Fund,Inc."))
