(:sections nil :text
	   ("The repurchase offer period will begin on May 18, 2026 and end on June 29, 2026."
	    "On May 11, 2026, the NAV of the Class I Shares (AXOIX) was $9.61 per Share."
	    "All Repurchase Requests must be received in proper form by 4:00 p.m., Eastern Time, on June 29, 2026."
	    "* AXXES OPPORTUNISTIC CREDIT FUND REPURCHASE REQUEST FORM MUST BE RECEIVED BY 4:00 P.M., EASTERN TIME, ON June 29, 2026."
	    "Please contact the Fund at 877-462-9937 to determine if a Medallion Signature Guarantee is necessary for your repurchase."))
