(:sections
 (("25"
   "(iii) may apply contract standards of “materiality” that are different from “materiality” under the applicable securities laws;"
   "333-250205), as filed with the Commission on July 28, 2022."
   "(t) Power of Attorney is incorporated by reference to Exhibit (t) to the Registration on Form N-2 of BlackRock Debt Strategies Fund, Inc.")
  ("26"
   "Item 26. Marketing Arrangements The information contained under the se")
  ("27"
   "Item 27. Other Expenses Of Issuance And Distribution The following tab")
  ("28"
   "Item 28. Persons Controlled By Or Under Common Control With The Regist")
  ("29" "Number Of Holders Of Shares As of July 1, 2026:")
  ("30" "Article V of the Registrant’s Charter provides as follows:"
   "C-5 ---------------------------------------------------------------------------------------------------- Section 3."
   "Survival of Indemnification and Advancement of Expenses.")
  ("31"
   "Item 31. Business And Other Connections Of Investment Advisor BlackRoc")
  ("32"
   "Item 32. Location Of Accounts And Records Omitted pursuant to the Inst")
  ("33"
   "Item 33. Management Services Not Applicable C-6 ----------------------")
  ("34"
   "(3) The securities being registered will be offered on a delayed or continuous basis in reliance on Rule 415 under the Securities Act of 1933."
   "(1) if the Registrant is relying on Rule 430B [17 CFR 230.430B]:"
   "Steinmetz) ROBERT FAIRBAIRN* Director (Robert Fairbairn) *By:"))
 :text
 ("In order to be payable, distributions on such preferred securities must be declared by the issuer’s board of directors."
  "Generally, ASC 820 and other accounting rules applicable to funds and various assets in which they invest are evolving."
  "See “Terms of the Rights Offering.” The Fund has declared monthly distributions payable on [●], 2026 with a record date of [●], 2026."
  "While the Commodity Futures Trading Commission (“CFTC”) and other U.S."
  "status (including, in general, furnishing an IRS Form W-8BEN, W-8BEN-E, or substitute Form)."
  "9 The ISSB is an independent standard-setting body within the International Financial Reporting Standards (IFRS) Foundation."))
