(:sections nil :text
	   ("5,310,732 1,226,672,877 Johnson & Johnson 5,310,732 1,220,671,750 JPMorgan Chase & Co."
	    "Net assets, $42,843,689 $41,635,900 $35,434,158 $27,065,830 $29,290,744 $30,031,985 end of period (in 000s) Ratios to average net assets:"
	    "ICE is a publicly-traded entity, trading on the NYSE under the symbol “ICE.” Note 2 — Segment Reporting The Trust has one reportable segment."
	    "There were no such expenses for the year ended October 31, 2025."
	    "The Adjustment Amount included an excess of net transaction fees from processing orders of $508,593 and a Trustee earnings credit of $997,184."
	    "The identity and weighting of common stocks that are included in the DJIA and the Portfolio Securities change from time to time."))
