(:sections nil :text
	   ("In March, the S&P 500 declined 5.0%, posting one of its worst monthly returns since the fall of 2022, and finished the quarter down 4.3%."
	    "This compared to the -4.3% total return for the S&P 500 and a -4.4% total return for the Morningstar U.S."
	    "Class A 153,988,380 5.4 Microsoft Corporation 151,103,394 5.3 Amazon.com, Inc."
	    "177,100 24,682,427 Johnson & Johnson 102,800 25,128,432 Medtronic plc 192,900 16,714,785 Merck & Co., Inc."
	    "275,500 16,193,890 Nucor Corporation 83,200 14,069,120 50,979,475 Real Estate — 1.9% CBRE Group, Inc."
	    "Sloan, CPA Treasurer and Director of Human Resources 500 East Pratt Street, Suite 1300, Baltimore, MD 21202 410.752.5900 800.638.2479 Website:"))
