(:sections
 (("27"
   "29, 2006, filed electronically as Exhibit 1.11 to Registrant's Post-Effective Amendment No."
   "333-139764 on or about April 24, 2008 is incorporated by reference herein."
   "(p)(ii) Resolution of Board of Directors regarding Power of Attorney is filed electronically herewith.")
  ("28"
   "Name Principal Business Address* Position and Offices With Depositor Jason J."
   "Bohn 940 Cape Marco Drive #2205Marco Director Island FL 34145 Ronald L."
   "Senior Vice President - Insurance & Wolfrath Annuities Product Development & Management Matthew J.")
  ("29" "SUBSIDIARIES AND AFFILIATES OF AMERIPRISE FINANCIAL, INC."
   "3 Limited England & Wales Sackville UK Property Select II Nominee (3) Limited England & Wales Sackville UK Property Select III (GP) No."
   "Luxembourg Sackville UK Property Select IV (GP) No.")
  ("30"
   "Item 30. Indemnification The amended and restated By-Laws of the depos")
  ("31" "Principal Underwriter (a) RiverSource Distributors Inc."
   "Minella Secretary Theodore Horwith Chief Financial Officer * The business address is 70100 Ameriprise Financial Center, Minneapolis, MN 55474."
   "(c) RiverSource Distributors Inc., the principal underwriter during Registrant’s last fiscal year, was paid the following commissions:")
  ("32" "Item 32. Location of Accounts and Records Not applicable")
  ("33" "Item 33. Management Services Not applicable.")
  ("34" "Fee Representation The RiverSource Life Insurance Co."
   "The Company hereby represents that it is relying on the November 28, 1988 no-action letter (Ref."
   "The combined Statement of Additional Information and Financial Statements for RiverSource of New York Variable Annuity Account."))
 :text
 ("If you request a full surrender, the contract will terminate."
  "We credit and compound interest daily based on a 365-day year (366 in a leap year) so as to produce the annual effective rate which we declare."
  "We seek to restrict the transfer privileges of a contract owner who makes more than three Subaccount transfers in any 90-day period."
  "If you are age 75 or younger at contract issue and did not opt out of the Standard Death Benefit, you may select the MAV Death Benefit."
  "Its offices are located at 829 Ameriprise Financial Center, Minneapolis, MN 55474."))
