(:sections nil :text
	   ("(212) 715-3880 Name and address of agent for service of The Corporation Trust Company process:"
	    "Corporate Trust Center 1209 Orange Street Wilmington, Delaware 19801 Check one of the following:"
	    "that it will be operated for the purpose of making investments in securities described in Section 55(a)(1) through (3) of the Act;"
	    "and that it will make available significant managerial assistance with respect to issuers of such securities to the extent required by the Act."
	    "President and Chief Executive Officer Attest:"))
