(:sections nil :text
	   ("(212) 478-9200 File Number under the Securities Exchange Act 000-56757 of 1934:"
	    "does not have more than 100 security holders for purposes of section 3 (c)(1) of the Act and the rules thereunder;"
	    "or (2) merged into or consolidated with another company."
	    "The company has filed a notice of registration under section 8 of the Act."
	    "Explain the circumstances surrounding the withdrawal of election."))
