(:sections
 (("30"
   "(c) (1) Selling Agreement between The Lincoln National Life Insurance Company and Lincoln Financial Distributors, Inc."
   "333-248990) filed on September 23, 2020."
   "(r) Form of Initial Summary Prospectus filed herein.")
  ("31"
   "Directors and Officers of the Depositor Name Positions and Offices with Depositor Craig T."
   "Beazer* Executive Vice President, General Counsel and Director Adam M."
   "Wilmer*** Assistant Vice President and Director *Principal business address is 150 N.")
  ("32"
   "Item 32. Persons Controlled by or Under Common Control with the Deposi")
  ("33"
   "Indemnification (a) Brief description of indemnification provisions:"
   "6(b) hereto) for the full text of the indemnification provisions."
   "(b) Undertaking pursuant to Rule 484 of Regulation C under the Securities Act of 1933:")
  ("34"
   "Principal Underwriter (a) Lincoln Financial Distributors, Inc."
   "(“LFD”) currently serves as Principal Underwriter for:"
   "Seifert Sr* Senior Vice President and Director *Principal business address is 150 N.")
  ("35"
   "Item 35. Location of Accounts and Records This information is provided")
  ("36" "Item 36. Management Services Not applicable.")
  ("37"
   "Cooper _____________________________ President and Director Ellen G."
   "Neczypor _____________________________ Christopher M."
   "Speas * By ________________________________________ Brittany S."))
 :text
 ("Annual Fee Minimum Maximum Underlying Fund Fees and 0.23% 2.41% Expenses* *As a percentage of Underlying Fund assets."
  "or • Combine the Separate Account with another separate account."
  "International Benefits are limited to the number of months shown in the Policy Specifications."
  "This Rider is intended to be a qualified long-term care insurance policy under Section 7702B(b) of the Internal Revenue Code, as amended."
  "Section 7702 of the Internal Revenue Code of 1986 as amended (“Code”) establishes a statutory definition of life insurance for federal tax purposes."
  "333-248990) filed on September 23, 2020."))
