(:sections nil :text
	   ("Route 66, Suite 226 Glendora, California 91740 (626) 385-5777 diane.drake@mfac-ca.com 7."
	    "(b) Why has the fund retained the remaining assets? (c) Will the remaining assets be invested in securities? ☐ Yes ☐ No 21."
	    "(b) How were those expenses allocated? (c) Who paid those expenses? (d) How did the fund pay for unamortized expenses (if any)? 23."
	    "The undersigned also states that the facts set forth in this Form N-8F application are true to the best of her knowledge, information and belief."))
