(:sections nil :text
	   ("Shane Duggan, Acting Assistant Director, at (202) 551-6367 or Chief Counsel’s Office at (202) 551-6821;"
	    "The application was filed on September 29, 2025, and amended on April 30, 2026 and May 21, 2026."
	    "The application was filed on December 18, 2025, and amended on May 12, 2026."
	    "The application was filed on March 16, 2026, and amended on May 28, 2026."))
