(:sections nil :text
	   ("36221 / June 24, 2026 In the Matter of :"
	    "On May 29, 2026, a notice of filing of the application was issued (Investment Company Act Release No."
	    "Accordingly, IT IS ORDERED, under section 8(f) of the Act, that applicant’s registration under the Act shall forthwith cease to be in effect."
	    "For the Commission, by the Division of Investment Management, under delegated authority."))
