(:sections
 (("1"
   "REPORTS TO SHAREHOLDERS The Semi-Annual report to Shareholders of the M3Sixty Onchain U.S."
   "You can also request this information without charge by contacting the Fund at (877) 244-6235."
   "If you would prefer that your Fund documents not be householded, please contact the Fund at (877) 244-6235 or contact your financial intermediary.")
  ("2" "ITEM 2. CODE OF ETHICS. Not applicable at this time.")
  ("3"
   "ITEM 3. AUDIT COMMITTEE FINANCIAL EXPERT. Not applicable at this time.")
  ("4"
   "ITEM 4. PRINCIPAL ACCOUNTANT FEES AND SERVICES. Not applicable at this")
  ("5" "ITEM 5. AUDIT COMMITTEE OF LISTED REGISTRANTS. Not applicable")
  ("6"
   "ITEM 6. SCHEDULE OF INVESTMENTS. Included in Semi-Annual Financial Sta")
  ("7"
   "Financial Statements and Financial Highlights for Open-End Management Investment Companies:"
   "Government securities during the six months ended March 31, 2026, were $616,826 and $1,147,548, respectively."
   "Shareholders should consult their own tax advisors.")
  ("8"
   "Changes in and Disagreements with Accountants for Open-End Management Investment Companies.")
  ("9"
   "Proxy Disclosures for Open-End Management Investment Companies.")
  ("10"
   "Remuneration Paid to Directors, Officers, and Others of Open-End Management Investment Companies."
   "Trustee fees paid by the Fund are within Item 7.")
  ("11"
   "Statement Regarding Basis for Approval of Investment Advisory Contract.")
  ("12"
   "DISCLOSURE OF PROXY VOTING POLICIES AND PROCEDURES FOR CLOSED-END MANAGEMENT INVESTMENT COMPANIES.")
  ("13"
   "PORTFOLIO MANAGERS OF CLOSED-END MANAGEMENT INVESTMENT COMPANIES.")
  ("14"
   "PURCHASES OF EQUITY SECURITIES BY CLOSED-END MANAGEMENT INVESTMENT COMPANY AND AFFILIATED PURCHASERS.")
  ("15" "SUBMISSION OF MATTERS TO A VOTE OF SECURITY HOLDERS.")
  ("16"
   "ITEM 16. CONTROLS AND PROCEDURES. (a) The registrant’s principal execu")
  ("17"
   "DISCLOSURE OF SECURITIES LENDING ACTIVITIES FOR CLOSED-END MANAGEMENT INVESTMENT COMPANIES.")
  ("18" "RECOVERY OF ERRONEOUSLY AWARDED COMPENSATION.")
  ("19"
   "/s/ Randy Linscott Randy Linscott Principal Executive Officer Date:"
   "Treasurer and Principal Financial Officer Date:"))
 :text
 ("Investments, at cost $ 34,204 Investments, at value $ 34,204 Due from Adviser 26,767 Receivables:"
  "The Trust is registered as an open-end management investment company under the Investment Company Act of 1940 (the “1940 Act”)."
  "Government securities during the six months ended March 31, 2026, were $616,826 and $1,147,548, respectively."
  "As of March 31, 2026, CERES Coin, LLC held 71.97% of the Fund’s shares and CM Solutions, LLC held 27.86% of the Fund’s shares."
  "PORTFOLIO MANAGERS OF CLOSED-END MANAGEMENT INVESTMENT COMPANIES."))
