(:sections nil :text
	   ("Any representation to the contrary is a criminal offense."
	    "$1,087 $1,752 Lowest Annual Cost FPA Highest Annual Cost FPA Contracts:"
	    "You can also request this information at no cost by calling 800.574.9267 or by sending an email request to mutualofamerica@dfinsolutions.com."
	    "Dimensional appreciation Fund Advisors LP Equity Fund DWS Capital Growth VIP 0.49% 12.53% 10.92% 15.29% Seeks to provide Adviser:"
	    "Equity Fund Fidelity VIP Contrafund® 0.54% 21.52% 15.37% 15.78% Seeks long-term capital Portfolio appreciation Adviser:"
	    "1 Since Inception date September 22, 2017."))
