(:sections nil :text
	   ("At December 31, 2025, the Account had two investment divisions (the “Divisions”), each which invest in independently managed mutual funds."
	    "The Account’s assets are recorded at fair value on the Statements of Assets and Liabilities and are categorized as Level 1 as of December 31, 2025."
	    "The account had no liabilities as of December 31, 2025."
	    "Daily charges are deducted at annual rates of 0.65% of the average daily net asset value of each Division of the Account."
	    "BThe Investment Income Ratio represents dividends received by the Division, excluding capital gains distributions, divided by the average net assets."))
