(:sections
 (("1"
   "You can also request this information by calling 1-800-373-9387 (inside the U.S."
   "How did the Fund perform last year ? * For the 12-month period ended December 31, 2025, the Fund’s Class A shares returned 11.95%."
   "For more current information visit bny.com/investments/literaturecenter .")
  ("2"
   "Item 2. Code of Ethics. The Registrant has adopted a code of ethics th")
  ("3" "The Registrant's Board has determined that Alan H.")
  ("4" "These services consisted of one or more of the following:"
   "(e)(1) Audit Committee Pre-Approval Policies and Procedures."
   "Pre-approvals pursuant to the Policy are considered annually.")
  ("5"
   "Item 5. Audit Committee of Listed Registrants. Not applicable.")
  ("6"
   "View your next shareholder report online as soon as it’s available."
   "Log into www.bny.com/investments and sign up for eCommunications."
   "All other required items will be filed with the Securities and Exchange Commission (the “SEC”).")
  ("7"
   "Financial Statements and Financial Highlights for Open-End Management Investment Companies."
   "Class A 6,827,415 4,141,866 Class C 232,032 62,457 Class I 14,715,444 5,033,242 Class Y 22,147 302,961 Distributions reinvested:"
   "Shareholders will receive notification in early 2026 of the percentage applicable to the preparation of their 2025 income tax returns.")
  ("8"
   "Item 8. Changes in and Disagreements with Accountants for Open-End Man")
  ("9"
   "Shares For Withheld To elect seven Board Members to the Board of Directors of the Fund:")
  ("10"
   "The fund is charged for services performed by the fund’s Chief Compliance Officer."
   "Compensation paid by the fund during the period to the board members and the Chief Compliance Officer are within Item 7."
   "The aggregate amount of Directors’ fees and expenses and Chief Compliance Officer fees paid by the fund during the period was $77,768.")
  ("11"
   "In considering the renewal of the Agreements, the Board considered several factors that it believed to be relevant, including those discussed below."
   "29 ---------------------------------------------------------------------------------------------------- Item 11."
   "The Board determined to renew the Agreements.")
  ("12"
   "Disclosure of Proxy Voting Policies and Procedures for Closed-End Management Investment Companies.")
  ("13"
   "Portfolio Managers for Closed-End Management Investment Companies.")
  ("14"
   "Purchases of Equity Securities By Closed-End Management Investment Companies and Affiliated Purchasers.")
  ("15" "Submission of Matters to a Vote of Security Holders.")
  ("16"
   "Item 16. Controls and Procedures. (a) The Registrant's principal execu")
  ("17"
   "Disclosure of Securities Lending Activities for Closed-End Management Investment Companies.")
  ("18" "Recovery of Erroneously Awarded Compensation.")
  ("19" "(a)(1) Code of ethics referred to in Item 2."
   "(a)(2) Certifications of principal executive and principal financial officers as required by Rule 30a-2(a) under the Investment Company Act of 1940."
   "(b) Certification of principal executive and principal financial officers as required by Rule 30a-2(b) under the Investment Company Act of 1940."))
 :text
 ("How did the Fund perform last year ? * For the 12-month period ended December 31, 2025, the Fund’s Class I shares returned 12.23%."
  "12,020 2,297,022 ATI, Inc.(a) 12,197 1,399,728 Axon Enterprise, Inc.(a) 3,266 1,854,859 BWX Technologies, Inc.(b) 12,413 2,145,463 Cummins, Inc."
  "A(a) 15,012 775,970 Pegasystems, Inc.(b) 19,116 1,141,608 PTC, Inc.(a) 15,258 2,658,096 Qualys, Inc.(a) 8,033 1,067,586 RingCentral, Inc., Cl."
  "The fund is an investment company and applies the accounting and reporting guidance of the FASB ASC Topic 946 Financial Services-Investment Companies."
  "The reduction in expenses, pursuant to the undertaking, amounted to $615,742 during the period ended December 31, 2025."
  "29 ---------------------------------------------------------------------------------------------------- Item 11."))
