(:sections
 (("3"
   "Item 3 U Credit Rating Affiliates Moody's Investors Service Limited MIS Brazil Serviços Técnicos Ltda."
   "20124 Milan,Italy Paris, 75009, France Moody’s Canada Inc."
   "International Financial Centre Street, 137 Telok Ayer Street #08-01 Singapore 068602 PO Box 506845, Dubai UAE Principal Place of Business:")
  ("8"
   "Item 8 Supplement In the United States, MIS conducts background checks through a third-party vendor in connection with hiring employees."
   "The following material changes to the NRSRO’s Update of Registration to Form NRSRO as of October 10, 2025 are noted below:"
   "Updated to reflect the modified statement:"))
 :text
 ("78c(a)(42)), municipal securities as that term is defined in section 3(a)(29) of the Exchange Act (15 U.S.C."
  "78c(a)(42)), municipal securities as that term is defined in section 3(a)(29) of the Exchange Act Ƒ ✔   (15 U.S.C."
  "International Financial Centre Street, 137 Telok Ayer Street #08-01 Singapore 068602 PO Box 506845, Dubai UAE Principal Place of Business:"
  "The following material changes to the NRSRO’s Update of Registration to Form NRSRO as of June 3, 2026 are noted below:"))
