(:sections nil :text
	   ("20549 FORM 12b-25 SEC FILE NUMBER 000-52838 NOTIFICATION OF LATE FILING (Check one):"
	    "The Company intends to file 3Q2017 coincidently with 10-K 2016."
	    "The Company sees the filing as a priority and will transact as soon as possible."
	    "(Name of Registrant as Specified in Charter) has caused this notification to be signed on its behalf by the undersigned hereunto duly authorized."))
