(:sections nil :text
	   ("[ ] Form 10-K [ ] Form 20-F [ ] Form 11-K [ ] Form 10-Q [ ] Form 10-D [ ] Form N-CEN [X] Form N-CSR For Period Ended:"
	    "and (c) The accountant’s statement or other exhibit required by Rule 12b-25(c) has been attached if applicable."
	    "The Registrant currently expects to file its Form N-CSR on or before the 15th calendar day following its prescribed due date."))
