(:sections nil :text
	   ("20549 hours per response 2.50 FORM 12b-25 SEC FILE NUMBER NOTIFICATION OF LATE FILING CUSIP NUMBER (Check one):"
	    "This Form is required by Rule 12b-25 (17 CFR 240.12b-25) of the General Rules and Regulations under the Securities Exchange Act of 1934."
	    "This Form shall not be used by electronic filers with respect to the submission or posting of an Interactive Data File (§232.11 of this chapter)."))
