(:sections nil :text
	   ("20549 FORM N-2 REGISTRATION STATEMENT UNDER THE SECURITIES ACT OF 1933 ¨ Pre-Effective Amendment No."
	    "(202) 689-2862 Approximate date of commencement of proposed sale to the public:"
	    "¨ Emerging Growth Company (as defined by Rule 12b-2 under the Securities Exchange Act of 1934 (“Exchange Act”)."
	    "Koenig Chairman, Chief Executive Officer April 7, 2026 and Director Theodore L."
	    "Allison Director April 7, 2026 Thomas J."))
