(:sections nil :text
	   ("Parent must pay the Company a termination fee of $84,000,000 if any of the following events occur:"
	    "24 ---------------------------------------------------------------------------------------------------- Table of Contents On December 3, 2025, Mr."
	    "This discussion is based on the Internal Revenue Code of 1986, as amended (the “Code”), applicable U.S."
	    "or (iii) an “employee life and health trust” as such term is defined in subsection 248(1) of the ITA."
	    "Each Stockholder Releasor Party has been made aware of, and understand, the provisions of California Civil Code Section 1542, which provides:"))
