(:sections nil :text
	   ("6 Because the Company has not yet announced its first annual meeting of shareholders, the May 29 Meeting, if held as properly called by Mr."
	    "66 at Alfred Lerner College of Business and Economics, University of Delaware from 2000 to 2021."
	    "SOIL), a Canadian energy company, since June 2023."
	    "1 to its Annual Report for the fiscal year ended December 31, 2025, filed with the SEC on April 30, 2026."
	    "The address for Caddis Holdings, LP and Caddis Holdings, LLC is 1333 Oak Lawn Avenue, Suite 900, Dallas, Texas 75207."))
