(:sections nil :text
	   ("million Zero Plc Coupon Notes USD 20 Borrowing 26-Feb-26 05-Mar-26 05-Mar-36 USD 20.00 Nomura Inter."
	    "Attached hereto please find a soft copy of the Bank's annual financial statement for the period ending 31 March 2026."
	    "No material modifications or amendments of any exhibits previously filed with the Commission under any statute were made during the Quarter."))
