(:sections
 (("II.13" "Other Expenses of Issuance and Distribution."
   "The following table sets forth the costs and expenses, other than the underwriting discounts and commissions, payable by Rivian Automotive, Inc."
   "(the Registrant) in connection with the sale of its Class A common stock being registered.")
  ("II.14" "Indemnification of Directors and Officers."
   "The registrant is governed by the Delaware General Corporation Law (the DGCL)."
   "We intend to enter into indemnification agreements with each of our directors and officers.")
  ("II.15" "Recent Sales of Unregistered Securities."
   "Set forth below is information regarding all unregistered securities sold by us since January 1, 2018."
   "In February 2019, the 2018 Convertible Notes were converted into an aggregate of 24,650,550 shares of common stock.")
  ("II.16" "Exhibits and Financial Statement Schedules."
   "10.14 Commercial Letter Agreement, dated as of February 15, 2019, by and between Rivian Automotive, Inc."
   " Portions of this exhibit (indicated by asterisks) have been redacted in compliance with Regulation S-K Item 601(b)(10)(iv).")
  ("II.17" "The undersigned Registrant hereby undertakes that:"
   "Scaringe Chief Executive Officer and Chairman of the October 1, 2021 Board of Directors Robert J."))
 :text
 (" a 50-for-1 forward stock split of our common stock and contingently redeemable convertible preferred stock, effected on December 20, 2019;"
  "being exempt from compliance with the auditor attestation requirements of Section 404(b) of the Sarbanes-Oxley Act;"
  "We assume the LTR opportunity from software to be $15,500."
  "As of September 30, 2021 we had registered trademarks and had filed trademark applications with domestic and foreign trademark offices."
  "We have not sought and will not seek any rulings from the IRS regarding the matters discussed below."
  "For the years ended December 31, 2019 2020 Net loss $ (426) $ (1,018) attributable to Rivian Less:"))
