(:sections
 (("9"
   "These documents contain important information about us and our finances."
   "● our Annual Report on Form 10-K for the fiscal year ended December 31, 2025, filed with the SEC on February 19, 2026, as amended by Amendment No."
   "19 7,163,000 Shares of Common Stock (including up to 4,615,000 Warrant Shares) BiomX Inc.")
  ("II.13" "All such costs and expenses shall be borne by us."
   "Except for the Securities and Exchange Commission registration fee, all the amounts shown are estimates.")
  ("II.14"
   "Section 145 of the Delaware General Corporation Law concerning indemnification of officers, directors, employees and agents is set forth below."
   "Indemnification of officers, directors, employees and agents;")
  ("II.15"
   "No underwriters were involved, and no underwriting discounts or commissions were paid, in connection with these issuances."
   "1,300,000 shares of Common Stock and a non-convertible promissory note in the principal amount of $1,250,000."
   "and (iv) a Five Year Warrant exercisable for an aggregate of 3,692,000 shares of Common Stock at an exercise price of $12.00 per share.")
  ("II.16"
   "10.1** Amended and Restated Chardan Healthcare Acquisition Corp."
   "(Incorporated by reference to Exhibit 10.1 to the Company’s Current Report on Form 8-K filed by the Company on April 1, 2026) 19.1 BiomX Inc."
   "** Indicates a management contract or a compensatory plan or agreement.")
  ("II.17"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "(1) To file, during any period in which offers or sales are being made, a post-effective amendment to this registration statement:"
   "(i) to include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"))
 :text
 ("For additional information on the possible methods of sale, see “Plan of Distribution” beginning on page 16."
  "333-275935) and a separate prospectus supplement, most recently the prospectus supplement we filed on June 16, 2026."
  "We acquired 60% of the issued and outstanding voting equity capital of DFSL on a fully-diluted basis, with the remaining 40% held by Dr."
  "As of June 2, 2026, there were 11,160,153 shares of Common Stock issued and outstanding."
  "17 LEGAL MATTERS The validity of the securities offered by this prospectus will be passed upon for us by Aboudi Legal Group PLLC, New York, New York."
  "1,300,000 shares of Common Stock and a non-convertible promissory note in the principal amount of $1,250,000."))
