(:sections
 (("II.13"
   "All amounts shown are estimates except for the SEC registration fee, the Nasdaq listing fee and the FINRA filing fee:")
  ("II.14" "Indemnification of Directors and Officers."
   "Section 145 of the DGCL concerning indemnification of officers, directors, employees and agents is set forth below."
   "The registrant believes that this insurance is necessary to attract and retain qualified directors and officers.")
  ("II.15"
   "Various employees and executives as September 29, 2023 Granted Non-qualified Stock Option;"
   "Common 289,296 $ 1.33 part of their accrued compensation Stock forgiveness A consultant January 24, 2024 Granted Non-qualified Stock Option;"
   "Common 49,605 $ 1.33 Chief Financial Officer Stock A consultant April 17, 2024 Granted Non-qualified Stock Option;")
  ("II.16" "Exhibits and Financial Statement Schedules (a) Exhibits.")
  ("II.17" "The undersigned registrant hereby undertakes:"
   "Silva (filed as Exhibit 10.12 to the Company’s Annual Report on Form 10-K filed with the SEC on April 1, 2026)† 10.11 Amendment No."
   "Hemmerly Independent Director June 26, 2026 Nicholas H."))
 :text
 ("We will not receive any proceeds from the sale of shares of common stock by the Selling Stockholder pursuant to this prospectus."
  "annual net sales thresholds of $333,333,333, $1,000,000,000 and $2,000,000,000, respectively."
  "Christer Rosén 13,080,566 (2) 25.8 Marshall Hayward, Ph.D 4,015,175 (3) 8.1 Saleem Elmasri 766,755 (4) 1.6 Alison D."
  "federal income tax purposes may also be subject to an additional “branch profits tax” imposed at a 30% rate (or lower applicable treaty rate)."
  "Common 49,605 $ 1.33 Chief Financial Officer Stock A consultant April 17, 2024 Granted Non-qualified Stock Option;"))
