(:sections
 (("II.14"
   "All amounts are estimates except the Securities and Exchange Commission registration fee.")
  ("II.15"
   "or (v) for any transaction from which the director derived an improper personal benefit."
   "The corporation may also advance legal expenses, subject to repayment if indemnification is ultimately found to be inappropriate."
   "In addition, the registrant has entered into indemnification agreements with its officers and directors and certain stockholders.")
  ("II.16"
   "Item 16. Exhibits Exhibit Description Number 4.1 Form of Series D-1 Co")
  ("II.17"
   "Undertakings The undersigned registrant hereby undertakes:"
   "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933 (“Securities Act”);"
   "4) That, for the purpose of determining liability under the Securities Act to any purchaser:"))
 :text
 ("Dated July 28, 2026 PROSPECTUS a01.jpg AUTONOMIX MEDICAL, INC."
  "The number of shares of our common stock outstanding was reduced from 11,409,344 shares to 542,349 shares."
  "Up to 857,462 shares of common stock issuable upon exercise of the Warrants Shares of common stock outstanding as of July 971,043 27, 2026:"
  "Percentage of beneficial ownership is calculated based on 971,043 shares of common stock outstanding as of July 27, 2026."
  "● settlement of short sales entered into after the effective date of the registration statement of which this prospectus is a part;"
  "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933 (“Securities Act”);")
 :named-sections
 (("Risk Factors"
   "Before making an investment decision, in addition to the risks set forth below")))
