(:sections
 (("7"
   "● the description of our shares of common stock contained in Item 1 of the Registration Statement on Form 8-A (File No."
   "Investor Relations, Indaptus Therapeutics, Inc., Three Columbus Circle, 15th Floor New York, NY 10019, (646) 427-2727."
   "Investors should not rely on any such information in deciding whether to purchase our securities.")
  ("II.14"
   "Item 14. Other Expenses of Issuance and Distribution The following tab")
  ("II.15" "Indemnification of Directors and Officers."
   "● any breach of the director’s duty of loyalty to the corporation or its stockholders;"
   "or ● any transaction from which the director derived an improper personal benefit.")
  ("II.16"
   "Item 16. Exhibits. Exhibit Description of Document Number 1.1* Form of")
  ("II.17"
   "Undertakings (a) The undersigned Registrant hereby undertakes:"
   "To include any prospectus required by section 10(a)(3) of the Securities Act of 1933;"
   "Martell, M.D., Director August 13, 2025 Ph.D."))
 :named-sections
 (("Risk Factors"
   "An investment in our securities involves a high degree of risk."))
 :text
 ("1 RISK FACTORS An investment in our securities involves a high degree of risk."
  "By May 2025, we had enrolled 13 participants on Decoy20 as a single dose and 32 participants in the weekly dosing among the two Decoy20 dose levels."
  "● the price, if any, for the subscription rights;"
  "23 In addition, if the terms of the debt securities of a series permit us to do so, we may elect either of the following:"
  "28 PLAN OF DISTRIBUTION We may sell the securities described in this prospectus from time to time in one or more of the following ways:"
  "** To be incorporated by reference from a subsequent filing in accordance with Section 305(b) (2) of the Trust Indenture Act of 1939."))
