(:sections
 (("II.14" "Other Expenses of Issuance and Distribution.")
  ("II.15" "Indemnification of Directors and Officers."
   "If we do not assume the defense, expenses must be advanced to an Indemnitee under certain circumstances."
   "In addition, we have entered into indemnification agreements with all of our directors and executive officers.")
  ("II.16"
   "Item 16. Exhibits. Exhibit Index Exhibit No. Description 1.1* Form of ")
  ("II.17" "The undersigned Registrant hereby undertakes:"
   "(i) to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933, as amended (the Securities Act);"
   "/s/ Alon Lazarus Director May 8, 2025 Alon Lazarus, Ph.D."))
 :named-sections
 (("Risk Factors"
   "Investing in our securities involves significant risk."))
 :text
 ("11 ---------------------------------------------------------------------------------------------------- Table of Contents Events of Default."
  "Written notice must be mailed to each stockholder entitled to vote not less than ten nor more than 60 days before the date of the meeting."
  " the record date for stockholders entitled to receive the rights;"
  "Our business and an investment in our common stock involve significant risks."))
