(:sections
 (("II.20"
   "Such statement or statements shall reasonably evidence the expenses incurred by the indemnitee."
   "Any advances and undertakings to repay pursuant to the indemnification agreement shall be unsecured and interest free.")
  ("II.21"
   "(included as Annex A to the joint proxy statement/prospectus contained in this registration statement)."
   "(incorporated by reference to Exhibit 21.1 of Indivior Pharmaceuticals, Inc.’s Form 10-K filed on February 26, 2026)."
   "A copy of any omitted schedule will be furnished supplementally to the Securities and Exchange Commission upon request.")
  ("II.22"
   "Undertakings (a) The undersigned registrant hereby undertakes:"
   "(i) To include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "(c) (1) The undersigned registrant hereby undertakes as follows:"))
 :text
 ("The issuance of Jefferies’ opinion was authorized by Jefferies’ fairness committee."
  "From 2000 to 118 ---------------------------------------------------------------------------------------------------- TABLE OF CONTENTS 2003, Dr."
  "requires the affirmative vote of at least 75% of the voting power of the outstanding shares entitled to vote on the subject matter;"))
