(:sections
 (("II.20" "Indemnification of Directors and Officers."
   "The Olin bylaws require that Olin indemnify a director, officer or employee unless:")
  ("II.21"
   "Description 2.1 Agreement and Plan of Merger, dated as of June 15, 2026, by and among Olin Corporation, Huntsman Corporation, Olympus Merger Sub, Inc."
   "LLC 99.4 Consent of Citigroup Global Markets Inc."
   "Olin agrees to furnish a supplemental copy of such schedules to the Securities and Exchange Commission upon its request.")
  ("II.22" "(a) The undersigned registrant hereby undertakes:"
   " to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "Weideman Director July 2, 2026 William H."))
 :text
 ("The Olin board has fixed [ ], 2026 as the record date for the Olin special meeting."
  " “FOR” the Olin direct merger proposal;"
  "Lane, the current President and Chief Executive Officer of Olin, will serve as chief executive officer of the combined company, (ii) Peter R."
  "See “Where You Can Find More Information” beginning on page 225 of this joint proxy statement/prospectus."
  "Venue A-97 Section 10.07 Assignment A-98 Section 10.08 Specific Performance A-98 Section 10.09 Waiver of Jury Trial A-98 Exhibit A:"
  "This Article III was adopted by the shareholders at the Annual Meeting of Shareholders, April 28, 1994."))
