(:sections
 (("II.20"
   "Indemnification of Directors and Officers Comcast Corporation Indemnification under Pennsylvania Law and Comcast’s Charter and Bylaws."
   "Except as otherwise provided in the corporation’s by-laws, advancement of expenses must be authorized by the board of directors."
   "NBCUniversal Media, LLC NBCUniversal Media, LLC is a limited liability company organized under the laws of the State of Delaware.")
  ("II.21"
   "Exhibits and Financial Statement Schedule (a) The following exhibits are filed as part of this Registration Statement:")
  ("II.22"
   "Undertakings (a) The undersigned registrants hereby undertakes:"
   " to include any prospectus required by Section 10(a)(3) of the Securities Act of 1933;"
   "REID Director of Comcast Holdings Corporation, Sole Member July 30, 2026 of Comcast Cable Communications, LLC Thomas J."))
 :text
 ("Because this is only a summary, it may not contain all of the information that may be important to you in understanding the Exchange Offer."
  "Notes Offered 5.168% Notes due 2037 (the “Exchange Notes”)."
  "Tenders of Original Notes will be accepted only in minimum denominations of $2,000 and multiples of $1,000 thereafter."
  " are issuable in fully registered form, in denominations of $2,000 and multiples of $1,000 in excess thereof."
  "(2) default in paying principal on the senior debt securities of such series when due;"
  "ROBERTS Chairman and Co-Chief Executive July 30, 2026 Officer;"))
