(:sections nil :text
	   ("The Trust has a Mandatory Termination Date of August 20, 2027."
	    "In addition, small and mid-cap stocks may not be widely followed by the investment community, which may result in low demand."
	    "For example, this summary generally does not describe your situation if you are a broker/dealer or other investor Page 20 with special circumstances."
	    "The Redemption Price per Unit is determined by the Trustee by:"
	    "ETFs are either open-end management investment companies or unit investment trusts registered under the Investment Company Act of 1940, as amended."
	    "In addition, the legal remedies in emerging and developing markets are often more limited than the remedies available in the United States."))
