(:sections
 (("II.3" "Incorporation of Documents by Reference."
   "(a) The Company’s Annual Report on Form 10-K for the fiscal year ended December 31, 2025, filed with the Commission on February 18, 2026 (File No."
   "(f) All other reports filed pursuant to Section 13(a) or 15(d) of the Exchange Act since the end of the fiscal year covered by the Annual Report;")
  ("II.4" "Item 4. Description of Securities. Not applicable.")
  ("II.5"
   "Item 5. Interests of Named Experts and Counsel. Not applicable.")
  ("II.6" "Indemnification of Directors and Officers."
   "The TBOC does not authorize elimination or limitation of liability to the extent the director or officer is found liable under applicable law for:"
   "however, such permissive indemnification is subject to certain limitations and the director satisfying specified standards of conduct.")
  ("II.7"
   "Item 7. Exemption from Registration Claimed. Not applicable. ---------")
  ("II.8"
   "5.1* Opinion of Timothy Kim, Esq., Counsel - Corporate for ExxonMobil Holdings Corporation."
   "10.1* 2003 Incentive Program of Exxon Mobil Corporation."
   "23.2* Consent of Timothy Kim, Esq., Counsel - Corporate for ExxonMobil Holdings Corporation (included in Exhibit 5.1).")
  ("II.9" "(a) The undersigned Registrant hereby undertakes:"
   "(i) To include any prospectus required by Section 10(a)(3) of the Securities Act;"
   "Karsner Director Director /s/ Lawrence W."))
 :text
 ("333-183012 POST-EFFECTIVE AMENDMENT NO.2 TO FORM S-8 REGISTRATION STATEMENT NO."
  "Chapman Vice President, Corporate Finance and Treasurer ExxonMobil Holdings Corporation 22777 Springwoods Village Pkwy Spring, Texas 77389-1425 Tel:"
  "333-183012 relating to the 2003 Incentive Program of Exxon Mobil Corporation, (iv) Registration No."
  "(b) The Company’s Quarterly Report on Form 10-Q for the fiscal quarter ended March 31, 2026, filed with the Commission on May 4, 2026 (File No."
  "10.1* 2003 Incentive Program of Exxon Mobil Corporation."
  "and (iv) Any other communication that is an offer in the offering made by the undersigned Registrant to the purchaser."))
