(:sections
 (("II.3" "Incorporation of Documents by Reference."
   "The Registrant hereby incorporates by reference into this Registration Statement the following documents previously filed with the SEC:"
   "(1)Registrant’s Annual Report on Form 10-K filed on February 20, 2026;")
  ("II.4"
   "The value of each Phantom Share thereafter fluctuates pari passu with the fair market value of a share of the Company's Common Stock."
   "If a Participant fails to specify a deferral period, the deferral period will expire upon the Participant's termination of service for any reason.")
  ("II.5"
   "Item 5. Interests of Named Experts and Counsel. Not applicable.")
  ("II.6" "Indemnification of Directors and Officers."
   "The Registrant pays the entire premium of this policy.")
  ("II.7"
   "Item 7. Exemption from Registration Claimed. Not applicable.")
  ("II.8"
   "Item 8. Exhibits. See the Exhibit Index immediately preceding the sign")
  ("II.9" "(a)The undersigned Registrant hereby undertakes:"
   "Director April 28, 2026 Linda Filler /s/ Françoise Colpron Director April 28, 2026 Françoise Colpron /s/ Daniel L."
   "Williams Director April 28, 2026 Thomas L."))
 :text
 ("333-274789) filed on September 29, 2023, as amended on February 28, 2024."
  "(1)Registrant’s Annual Report on Form 10-K filed on February 20, 2026;"
  "Director April 28, 2026 Linda Filler /s/ Françoise Colpron Director April 28, 2026 Françoise Colpron /s/ Daniel L."
  "Schwieters Director April 28, 2026 John T."))
