(:sections nil :text
	   ("On April 29, 2024, a final judgment was entered in the matter in Securities and Exchange Commission v."
	    "CALM) from August 2022 to September 2023."
	    "In 2002, Los Angeles Mayor James Hahn appointed Mr."
	    "The stock awards reported for Fiscal Year 2024 represent awards of 2,345,175 shares of Common Stock granted to Mr."
	    "2025 2024 Summary Comp Table $ 32,500 $ 228,050 Less:"
	    "Marshall of 20,000 shares of Common Stock on March 17, 2025 that was reported on April 7, 2026, (iv) the sale by Mr."))
