(:sections
 (("3"
   "Item 3 If this statement is filed pursuant to rules 13d-1(b), or 13d- 2(b), check whether the person filing is a:")
  ("4" "Item 4 Ownership (a) Amount Beneficially Owned:"
   "2.29% (c) Number of shares as to which such person has:")
  ("5" "Item 5 Ownership of Five Percent or Less of a Class.")
  ("6"
   "Item 6 Ownership of More than Five Percent on Behalf of Another Person .")
  ("7"
   "Item 7 Identification and Classification of the Subsidiary Which Acquired The Security Being Reported on by the Parent Holding Company.")
  ("8"
   "Item 8 Identification and Classification of Members of the Group.")
  ("9"
   "Item 9 Notice of Dissolution of Group. NOT APPLICABLE CUSIP No. 36467W")
  ("10"
   "Item 10 Certification. By signing below I certify that, to the best of"))
 :text
 ("36467W109 Item 3 If this statement is filed pursuant to rules 13d-1(b), or 13d- 2(b), check whether the person filing is a:"
  "36467W109 13G Item 4 Ownership (a) Amount Beneficially Owned:"
  "[ X ] Item 6 Ownership of More than Five Percent on Behalf of Another Person ."
  "NOT APPLICABLE Item 8 Identification and Classification of Members of the Group."))
