(:sections
 (("1"
   "In this Schedule 14D-9, “we,” “us,” “our,” “Company” and “Cidara” refer to Cidara Therapeutics, Inc.")
  ("2" "Identity and Background of Filing Person."
   "Stein and RA Capital held approximately 0.26% and 10.7% of the voting power of all outstanding Common Shares, respectively."
   "Box 2000, Rahway, NJ 07065 and the telephone number at such principal office is (908) 740-4000.")
  ("3" "Past Contacts, Transactions, Negotiations and Agreements."
   "$ 2,393,920 $ 206,145,750 $ 49,000 $ 13,133,371 $ 221,722,041 Leslie Tari, Ph.D."
   "The Confidentiality Agreement does not include any standstill provisions.")
  ("4"
   "Later, on November 19, 2024, Cidara entered into a confidentiality agreement, without a standstill, with Company A."
   "100 % 18 % February 3, 2021 GW Pharmaceuticals plc Jazz Pharmaceuticals plc 50 % 39 % August 19, 2020 Momenta Pharmaceuticals, Inc."
   "To our knowledge, after making reasonable inquiry, all of our executive officers and directors (including Dr.")
  ("5" "Person/Assets Retained, Employed, Compensated or Used."
   "The Solicitation or Recommendation,” which is filed as Annex I hereto and incorporated herein by reference."
   "The Solicitation or Recommendation,” which is filed as Annex II hereto and incorporated herein by reference.")
  ("6" "Interest in Securities of the Subject Company.")
  ("7" "Purposes of the Transaction and Plans or Proposals.")
  ("8" "Golden Parachute Compensation See “Item 3."
   "THIS SCHEDULE 14D-9 CONSTITUTES THE FORMAL NOTICE OF APPRAISAL RIGHTS UNDER SECTION 262 OF THE DGCL."
   "Cidara’s stockholders and investors are cautioned not to unduly rely on these forward-looking statements.")
  ("9"
   "(a)(3) Form of Notice of Guaranteed Delivery (incorporated by reference to Exhibit (a)(1)(iii) to the Schedule TO)."
   "Employee Letter, first used on November 14, 2025 (incorporated by reference to Exhibit 99.1 to Cidara’s Schedule 14D9-C, filed November 14, 2025)."
   "(j) The costs of the proceeding may be determined by the Court and taxed upon the parties as the Court deems equitable in the circumstances."))
 :text
 ("17,475 18.14 3,553,634.00 — — Chrysa Mineo 39,600 27.33 7,689,069.00 — — Josh Resnick, M.D."
  "On July 17, 2025, representatives of Goldman Sachs met with members of the Transaction Committee to present Goldman Sachs’ capabilities."
  "On the morning of November 8, 2025, Merck submitted a revised proposal to acquire Cidara for $156 per share (the “November 8 Proposal”)."
  "and  other risks of the type and nature as further described below in the section titled “Item 8."
  "THIS SCHEDULE 14D-9 CONSTITUTES THE FORMAL NOTICE OF APPRAISAL RIGHTS UNDER SECTION 262 OF THE DGCL."
  "212-902-3000 LOGO PERSONAL AND CONFIDENTIAL November 13, 2025 Board of Directors Cidara Therapeutics, Inc."))
