(:sections
 (("1" "MoPac Expressway, Suite 450, Austin, Texas 78746."
   "As of the close of business on June 26, 2026 there were (i) 118,322,488 Shares issued and outstanding;"
   "(ii) up to 3,544,555 Shares issuable upon the exercise of outstanding stock options;")
  ("2"
   "A copy of the Merger Agreement is filed as Exhibit (e)(1) hereto and is incorporated herein by reference.")
  ("3"
   "Arrangements with Parent and Purchaser Merger Agreement On June 15, 2026, the Company, Parent and Purchaser entered into the Merger Agreement."
   "Feldstein 386,461 — — — 386,461 Michelle Glasl 38,556 76,471 542,247 449,877 1,107,151 Blair J."
   "No other current named executive officer is entitled to a single-trigger bonus amount.")
  ("4"
   "One of the Company’s primary insurance partners, AmTrust Financial Services, Inc."
   "Implied Share Price Metric Low High Q1 2026 LTM EBITDA $ 1.35 $ 1.76 2026E EBITDA 1.98 2.80 Selected Precedent Transactions Analysis."
   "FT Partners and its affiliates do not hold shares of ANV or AmTrust.")
  ("5"
   "ITEM 5. PERSON/ASSETS, RETAINED, EMPLOYED, COMPENSATED OR USED The Com")
  ("6"
   "ITEM 6. INTEREST IN SECURITIES OF THE SUBJECT COMPANY Other than the s")
  ("7"
   "ITEM 7. PURPOSES OF THE TRANSACTION AND PLANS OR PROPOSALS Except as o")
  ("8"
   "Appraisal Rights No appraisal rights are available in connection with the Offer."
   "MoPac Expressway, Suite 450, Austin, Texas 78746, Attention:"
   "(viii) the risk of actual or threatened litigation in connection with the Offer and Merger;")
  ("9" "The following exhibits are filed with this Schedule 14D-9:"
   "(a)(5)(C) Internal Associate Announcement (incorporated by reference to Exhibit 99.1 to Open Lending’s Schedule 14D-9C filed on June 16, 2026)."
   "Very truly yours, FINANCIAL TECHNOLOGY PARTNERS LP By:"))
 :text
 ("Feldstein 386,461 — — — 386,461 Michelle Glasl 38,556 76,471 542,247 449,877 1,107,151 Blair J."
  "On June 30, 2025, the Company and AmTrust entered into a non-disclosure agreement."
  "On February 25, 2026, representatives of Jones Day provided a revised draft of the merger agreement to ANV’s counsel."
  "Based on these updates, the Company’s management prepared the June 2026 Forecasts."
  "06/2025 Sagard Holdings UL Ethniki Hellenic General Insurance Company Piraeus Bank 03/2025 Argus Group Holdings Limited Eleos Health, Ltd."
  "(a)(5)(C) Internal Associate Announcement (incorporated by reference to Exhibit 99.1 to Open Lending’s Schedule 14D-9C filed on June 16, 2026)."))
