(:sections
 (("1" "ITEM 1. SUBJECT COMPANY INFORMATION 1")
  ("2" "ITEM 2. IDENTITY AND BACKGROUND OF FILING PERSON 1")
  ("3"
   "ITEM 3. PAST CONTACTS, TRANSACTIONS, NEGOTIATIONS AND 4 AGREEMENTS")
  ("4" "ITEM 4. THE SOLICITATION OR RECOMMENDATION 14")
  ("5"
   "ITEM 5. PERSON/ASSETS RETAINED, EMPLOYED, COMPENSATED OR USED 48")
  ("6" "ITEM 6. INTEREST IN SECURITIES OF THE SUBJECT COMPANY 49")
  ("7" "ITEM 7. PURPOSES OF THE TRANSACTION AND PLANS OR PROPOSALS 49")
  ("8" "ITEM 8. ADDITIONAL INFORMATION 49")
  ("9"
   "EXHIBITS 56 ANNEX I OPINION OF EVERCORE GROUP L.L.C I-1 ANNEX II OPINION OF GOLDMAN SACHS & CO."
   "$ 2,393,920 $ 206,145,750 $ 49,000 $ 13,133,371 $ 221,722,041 Leslie Tari, Ph.D."
   "(j) The costs of the proceeding may be determined by the Court and taxed upon the parties as the Court deems equitable in the circumstances."))
 :text
 ("17,475 18.14 3,553,634.00 — — Chrysa Mineo 39,600 27.33 7,689,069.00 — — Josh Resnick, M.D."
  "On July 17, 2025, representatives of Goldman Sachs met with members of the Transaction Committee to present Goldman Sachs’ capabilities."
  "On the morning of November 8, 2025, Merck submitted a revised proposal to acquire Cidara for $156 per share (the “November 8 Proposal”)."
  "and  other risks of the type and nature as further described below in the section titled “Item 8."
  "THIS SCHEDULE 14D-9 CONSTITUTES THE FORMAL NOTICE OF APPRAISAL RIGHTS UNDER SECTION 262 OF THE DGCL."
  "212-902-3000 LOGO PERSONAL AND CONFIDENTIAL November 13, 2025 Board of Directors Cidara Therapeutics, Inc."))
