(:sections
 (("1"
   "Summary Term Sheet The information set forth in the Proxy Statement under the following captions is incorporated herein by reference:")
  ("2" "Subject Company Information (a) Name and Address."
   "The information set forth in the Proxy Statement under the following caption is incorporated herein by reference:"
   "“SUMMARY TERM SHEET” “QUESTIONS AND ANSWERS” “THE SPECIAL MEETING — Record Date;")
  ("3"
   "Identity and Background of Filing Person (a) – (c) Name and Address;"
   "Business and Background of Natural Persons."
   "Select Medical Holdings Corporation is the subject company.")
  ("4" "Terms of the Transaction (a)(1) Tender Offers."
   "Ortenzio” 7 ---------------------------------------------------------------------------------------------------- “Annex I:")
  ("5"
   "Past Contacts, Transactions, Negotiations and Agreements (a) Transactions."
   "Ortenzio” (b) Significant Corporate Events."
   "Interim Investors Agreement” (c) Negotiations or Contacts.")
  ("6"
   "Purposes of the Transaction and Plans or Proposals (b) Use of Securities Acquired."
   "“SUMMARY TERM SHEET” “QUESTIONS AND ANSWERS” “SPECIAL FACTORS — Reasons for the Merger;")
  ("7" "Purposes, Alternatives, Reasons and Effects (a) Purposes."
   "THE COMPENSATION PROPOSAL” “ROLLOVER AGREEMENTS” “Annex A — Agreement and Plan of Merger” “Annex B — Opinion of Goldman Sachs & Co.")
  ("8" "Fairness of the Transaction (a) – (b) Fairness;"
   "Factors Considered in Determining Fairness."
   "LLC” The discussion materials prepared by Goldman Sachs & Co.")
  ("9"
   "Reports, Opinions, Appraisals and Negotiations (a) – (c) Report, Opinion or Appraisal;"
   "Preparer and Summary of the Report, Opinion or Appraisal;"
   "The information set forth in the Proxy Statement under the following captions is incorporated herein by reference.")
  ("10"
   "Source and Amount of Funds or Other Consideration (a) – (b) Source of Funds;"
   "21 ---------------------------------------------------------------------------------------------------- (c) Expenses."
   "“SUMMARY TERM SHEET” “SPECIAL FACTORS — Reasons for the Merger;")
  ("11"
   "Interest in Securities of the Subject Company (a) Securities Ownership.")
  ("12"
   "The Solicitation or Recommendation (d) Intent to Tender or Vote in a Going-Private Transaction."
   "THE MERGER PROPOSAL” “ROLLOVER AGREEMENTS” “Annex C:")
  ("13" "Financial Statements (a) Financial Information.")
  ("14"
   "Persons/Assets, Retained, Employed, Compensated or Used (a) – (b) Solicitations or Recommendations;")
  ("15"
   "Additional Information (b) The information set forth in the Proxy Statement under the following captions is incorporated herein by reference:")
  ("16" "Exhibits The following exhibits are filed herewith:"
   "Ortenzio Revocable Trust, DTD 8-14-2007, As Amended (incorporated by reference to Exhibit 99.11 to the Schedule 13D/A filed by Mr."
   "Select Asset Management & Truste, Robert Nause, Secretary & Treasurer Title:"))
 :text
 ("In connection with entering into the Merger Agreement, on March 2, 2026, Parent, Merger Sub, WCAS, Mr."
  "LLC, dated February 10, 2026, for the Special Committee of the Board of Directors of Select Medical Holdings Corporation."
  "Jackson (incorporated by reference to Exhibit 99.12 to the Schedule 13D/A filed by Mr."))
