(:sections
 (("1"
   "The principal executive office of AmBase is located at 7857 West Sample Rd., Suite 134, Coral Springs, Florida 33065.")
  ("2"
   "Item 2 of the Schedule 13D is amended and supplemented as follows:"
   "307 Fifth Avenue, 8th Floor New York, New York 10016 Attn:"
   "1) (a) BARC Investments LLC, a Connecticut limited liability Company (“BARC Investments”) (b) Address c/o Barry M.")
  ("3" "Source and Amount of Funds and Other Considerations."
   "On March 16, 2009, BARC Investments acquired 16,000,000 shares of AmBase Common Stock from Richard A."
   "The Equity Offering is expected to close on or about April 7, 2024.")
  ("5"
   "Item 5 of the Schedule 13D is amended and supplemented as follows:"
   "Bianco, Jr., as managing members of BARC Investments, share voting and dispositive power with respect to shares held by BARC Investments."
   "Pursuant to Rule 13d-4, each of Alessandra F.")
  ("6"
   "Contracts, Arrangements, Understandings or Relationships with Respect to Securities of the Issuer.")
  ("7"
   "Joint Filing Agreement by and among BARC Investments, Alessandra F."
   "Bianco, Jr., dated March 26, 2009 (previously filed with the Schedule 13D on March 26, 2009)."
   "Form of Standby Purchase Agreement (filed herewith)."))
 :text
 ("The principal executive office of AmBase is located at 7857 West Sample Rd., Suite 134, Coral Springs, Florida 33065."
  "On March 16, 2009, BARC Investments acquired 16,000,000 shares of AmBase Common Stock from Richard A."
  "On February 28, 2024, AmBase commenced a private placement offering (the “Equity Offering”) of 44,200,460 shares (the “Shares”)."
  "Bianco, Jr., dated March 26, 2009 (previously filed with the Schedule 13D on March 26, 2009)."))
