(:sections
 (("3"
   "The Reporting Person owns of record and beneficially 100,000 shares of Class B Common Stock."
   "The Reporting Person owns of record and beneficially and has the right to vote 100,000 shares of the Class B Common Stock."
   "There are a total of 101,102 shares of Class B Common Stock outstanding as of the date hereof.")
  ("4"
   "Item 4. Statement of Ownership From a Nominating Shareholder or Each M")
  ("5"
   "Item 5. Disclosure Required for Shareholder Nominations Submitted Purs")
  ("6"
   "Disclosure Required by § 240.14a-18 (a) The Reporting Person has nominated each of Bill H."
   "63rd Place, Suite 230, Tulsa, Oklahoma 74133-1246."
   "and (3) other material relationships between the Participants, and/or the Issuer or any affiliate of the Issuer not otherwise disclosed herein.")
  ("7"
   "Item 7. Notice of Dissolution of Group or Termination of Shareholder N")
  ("8" "Zahn 636,366 6.82 % 100,000 98.9 % Gary L."))
 :text
 ("7633 East 63rd Place, Suite 230 Tulsa, Oklahoma 74133-1246 Item 2(a)."
  "33719Q 10 5 Class A 33719Q 20 4 Class B Item 3."
  "Zahn, 6344 E 88th Street, Tulsa, Oklahoma 74137 Information relating to each of the Nominees and Reporting Person is set forth below."
  "From 2004 until October 2007 he was First Trinity’s Director of Training and Recruiting."
  "He also has served as a Director of FTFC, TLIC and TMC since 2015 and TRCC since 2021."
  "Zahn 636,366 6.82 % 100,000 98.9 % Gary L."))
