(:sections
 (("10" "Item 10. Financial Statements. Not applicable.")
  ("12"
   "Description (a)(1)(i)* Offer to Purchase, dated as of December 5, 2025."
   "(a)(5)(ii) Investigator Site Letter first sent on November 14, 2025 (incorporated by reference to Exhibit 99.2 of the first Cidara Therapeutics, Inc."
   "Senior Vice President, Head of Business Development MERCK SHARP & DOHME LLC By:"))
 :text
 ("Description (a)(1)(i)* Offer to Purchase, dated as of December 5, 2025."
  "(a)(5)(ii) Investigator Site Letter first sent on November 14, 2025 (incorporated by reference to Exhibit 99.2 of the first Cidara Therapeutics, Inc."
  "employees first sent on November 14, 2025 (incorporated by reference to Exhibit 99.1 of the first Cidara Therapeutics, Inc."
  "(d)(3)* Tender and Support Agreement, dated as of November 13, 2025, by and between Merck Sharp & Dohme LLC, Caymus Purchaser, Inc."))
