(:sections
 (("1"
   "Item 1. Summary Term Sheet. The information set forth under “Summary T")
  ("2"
   "The telephone number of its principal executive office is (479) 361-9111."
   "(b) The information set forth under “Introduction” in the Offer to Purchase is incorporated herein by reference.")
  ("3" "Identity and Background of Filing Person."
   "The Company’s address and telephone number are set forth in Item 2 above.")
  ("4" "• Section 2 (“Purpose of the Tender Offer;"
   "• Section 10 (“Interest of Directors and Executive Officers;"
   "and • Section 14 (“Extension of the Tender Offer;")
  ("5" "Past Contacts, Transactions, Negotiations and Agreements."
   "(e) The information set forth in the Offer to Purchase under Section 10 (“Interest of Directors and Executive Officers;")
  ("6" "Purposes of the Transaction and Plans or Proposals."
   "(a), (b) and (c) The information set forth in the Offer to Purchase under Section 2 (“Purpose of the Tender Offer;")
  ("7" "Source and Amount of Funds or Other Consideration."
   "(a) The information set forth in the Offer to Purchase under Section 8 (“Source and Amount of Funds”) is incorporated herein by reference.")
  ("8" "Interest in Securities of the Subject Company."
   "(a) and (b) The information set forth in the Offer to Purchase under Section 10 (“Interest of Directors and Executive Officers;")
  ("9" "Persons/Assets, Retained, Employed, Compensated or Used.")
  ("10" "Item 10. Financial Statements. Not applicable.")
  ("11"
   "(a) The information set forth in the Offer to Purchase under Section 10 (“Interest of Directors and Executive Officers;"
   "Registration under the Exchange Act”) and Section 12 (“Legal Matters;"
   "To the knowledge of the Company, no material legal proceedings relating to the tender offer are pending.")
  ("12"
   "Item 12. Exhibits. (a)(1)(A)* Offer to Purchase dated April 3, 2025. (")
  ("13"
   "Vice President of Finance, Chief Financial Officer and Treasurer iv EXHIBIT INDEX (a)(1)(A)* Offer to Purchase dated April 3, 2025."))
 :text
 ("The telephone number of its principal executive office is (479) 361-9111."
  "• Section 10 (“Interest of Directors and Executive Officers;"
  "(a) and (b) The information set forth in the Offer to Purchase under Section 10 (“Interest of Directors and Executive Officers;"))
