(:sections
 (("12"
   "Item 12. Exhibits. Exhibit Description 99.1 Posting by ANV, via Linked"))
 :text
 ("¨ amendment to Schedule 13D under Rule 13d-2."
  "¨ If applicable, check the appropriate box(es) below to designate the appropriate rule provision(s) relied upon:"
  "The information contained in, or that can be accessed through, Open Lending’s website is not a part of, or incorporated by reference herein."
  "the effects of the announcement of the transaction on the trading price of shares of Open Lending common stock;"
  "In addition, the forward-looking statements included in this communication speak only as of the date hereof."))
