(:sections
 (("12"
   "ITEM 12. Exhibits. Exhibit Number Description 99.1 Form of Announcemen"))
 :text
 ("20549 SCHEDULE TO TENDER OFFER STATEMENT UNDER SECTION 14(d)(1) OR 13(e)(1) OF THE SECURITIES EXCHANGE ACT OF 1934 Cresco Labs Inc."
  "Cresco Labs Inc., 600 West Fulton Street, Suite 800, Chicago, IL 60661."
  "2 ---------------------------------------------------------------------------------------------------- ITEM 12."))
