(:sections
 (("1"
   "Item 1. Summary Term Sheet. The information set forth in the sections ")
  ("2"
   "The name, address, and telephone number of the subject company’s principal executive offices are as follows:"
   "CureVac Shares are the subject securities in the Exchange Offer."
   "As of October 17, 2025, there were 225,181,647 CureVac Shares outstanding.")
  ("3" "Identity and Background of Filing Person."
   "and Business and Background of Natural Persons.")
  ("4"
   "Item 4. Terms of the Transaction. (a) Material Terms. The information ")
  ("5" "Past Contacts, Transactions, Negotiations and Agreements.")
  ("6" "Purposes of the Transaction and Plans or Proposals.")
  ("7" "Source and Amount of Funds or Other Consideration.")
  ("8" "Interest in Securities of the Subject Company."
   "Neither BioNTech nor any of its majority-owned subsidiaries beneficially own any CureVac Shares.")
  ("9" "Persons/Assets Retained, Employed, Compensated, or Used.")
  ("10"
   "Item 10. Financial Statements. (a) Financial Information. The informat")
  ("11"
   "(a) Agreements, Regulatory Requirements and Legal Proceedings.")
  ("12"
   "Description (a)(1)(A) Form of Letter of Transmittal (incorporated by reference to Exhibit 99.1 to Amendment No."
   "(incorporated by reference to Exhibit 99.1 to the Current Report on Form 6-K filed by BioNTech with the SEC on June 17, 2025)."
   "2 to the Registration Statement on Form F-4 filed with the SEC on October 21, 2025).")
  ("13"
   "Item 13. Information Required by Schedule 13E-3. Not applicable. -----"))
 :text
 ("As of October 17, 2025, there were 225,181,647 CureVac Shares outstanding."
  "“Summary,” “Background of the Transactions,” “The Offer,” “The Purchase Agreement,” and “The Tender and Support Agreements.” Item 6."
  "(incorporated by reference to Exhibit 99.1 to the Current Report on Form 6-K filed by BioNTech with the SEC on June 17, 2025)."))
