(:sections
 (("1"
   "As of the close of business on June 25, 2026, there was approximately $38,098,241 (or 1,859,760 Shares) outstanding capital of the Fund."
   "The net asset value per Share as of the close of business on June 25, 2026 was $20.49."
   "Until the Notice Due Date, Shareholders have the right to edit or withdraw any tenders of their Shares.")
  ("2"
   "The principal executive office of the Fund is located at 140 Lakeside Avenue, Suite 100, Seattle, WA 98122."
   "(b) The title of the securities that are the subject of the Offer is “common shares of beneficial interest,” or portions thereof, in the Fund."
   "As of the close of business on June 25, 2026, there was approximately $38,098,241 outstanding in capital of the Fund.")
  ("3" "IDENTITY AND BACKGROUND OF FILING PERSON."
   "The principal executive office of the Adviser is located at 140 Lakeside Avenue, Suite 100, Seattle, WA 98122."
   "Their address is c/o USVC Venture Capital Access Fund, 140 Lakeside Avenue, Suite 100, Seattle, WA 98122.")
  ("4" "· A Shareholder may tender all or some of its Shares."
   "(iii) The Offer is scheduled to expire at 11:59 p.m., Eastern Time, on July 28, 2026."
   "Shareholders should consult their own tax advisers concerning any possible disclosure obligation with respect to their investment in Shares.")
  ("5" "PAST CONTRACTS, TRANSACTIONS, NEGOTIATIONS AND AGREEMENTS."
   "The Fund’s registration statement on Form N-2, filed with the U.S."
   "and (ii) any other person, with respect to the Shares.")
  ("6" "PURPOSES OF THIS TENDER OFFER AND PLANS OR PROPOSALS."
   "(1) an extraordinary transaction, such as a merger, reorganization or liquidation, involving the Fund;"
   "Because Shares are not traded in any market, Subsections (6), (7) and (8) of Regulation M-A ss.")
  ("7" "SOURCE AND AMOUNT OF FUNDS OR OTHER CONSIDERATION."
   "cash on hand or proceeds from the sale of portfolio holdings (as described in paragraph (d) below)."
   "There are currently no alternative financing plans or arrangements for the transaction.")
  ("8"
   "(a) Based on June 25, 2026 values, the Adviser has $10,215,640 in the Fund (approximately 26.8% of all Shares)."
   "(b) Based on June 25, 2026 values, Erik Syvertsen, the Fund’s interested Trustee, has $25,625 in the Fund (approximately 0.07% of all Shares)."
   "David Borecky and Nimesh Gupta, independent Trustees of the Fund, do not have any beneficial ownership in the Fund.")
  ("9" "PERSONS/ASSETS RETAINED, EMPLOYED, COMPENSATED OR USED.")
  ("10"
   "Such financial statements are incorporated herein by reference in their entirety."
   "(2) The Fund is not required to and does not file quarterly unaudited financial statements under the Exchange Act."
   "The Fund does not have earnings per share information.")
  ("11"
   "ITEM 11. ADDITIONAL INFORMATION. (a) (1) None. (2) None. (3) Not appli")
  ("12"
   "Reference is hereby made to the following exhibits, which collectively constitute the Offer to Shareholders and are incorporated herein by reference:"
   "Email from USVC to Notify Shareholders that the Repurchase Window Has Opened."
   "E Forms of Email from the Fund to Shareholders in connection with the Fund’s acceptance of tenders of Shares."))
 :text
 ("As of the close of business on June 25, 2026, there was approximately $38,098,241 (or 1,859,760 Shares) outstanding capital of the Fund."
  "The principal executive office of the Adviser is located at 140 Lakeside Avenue, Suite 100, Seattle, WA 98122."
  "withholding tax at the rate of 30% (unless a reduced rate applies under an applicable tax treaty)."
  "Sections 1471-1474 of the Code and the U.S."
  "(a) Based on June 25, 2026 values, the Adviser has $10,215,640 in the Fund (approximately 26.8% of all Shares)."
  "Reference is hereby made to the following exhibits, which collectively constitute the Offer to Shareholders and are incorporated herein by reference:"))
