(:sections
 (("12"
   "Item 12. Exhibits. (a)(5)(a) Social media content by Mondher Mahjoubi "))
 :text
 ("Chudd Daniel Brass Davis Polk & Wardwell LLP 450 Lexington Avenue New York, NY 10017 Telephone:"
  "☐ amendment to Schedule 13D under Rule 13d-2."
  "Additional Information The tender offer for the Shares referenced in this announcement has not yet commenced."
  "the anticipated benefits of the acquisition;"
  "Actual results may differ materially from those currently anticipated due to a number of risks and uncertainties."
  "the failure to realize anticipated benefits of the proposed acquisition when expected or at all;"))
