(:sections
 (("1"
   "Item 1. Summary Term Sheet. Reference is made to the Summary Term Shee")
  ("2"
   "(a) The name of the issuer is PGIM Private Credit Fund (the “Fund”)."
   "The principal executive office of the Fund is located at 655 Broad Street, Newark, NJ 07102 and the telephone number is (844)-753-6354."
   "The Shares subject to the Offer represent approximately 5% of the Fund’s Shares outstanding as of March 31, 2026.")
  ("3" "Identity and Background of Filing Person."
   "The Manager’s principal address is 655 Broad Street, Newark, NJ 07102-4410 and its telephone number is 1-888-778-5471."
   "The Trustees and the executive officers of the Fund may be reached at the Fund’s business address and phone number set forth in Item 2(a) above.")
  ("4"
   "(b) To the Fund’s knowledge, none of the officers, Trustees, or affiliates of the Fund intends to tender Shares in the Offer.")
  ("5"
   "Past Contracts, Transactions, Negotiations and Agreements With Respect to the Issuer’s Securities."
   "The Manager expects that it will recommend to the Board that the Fund purchase Shares from Shareholders quarterly."
   "However, the Fund is not required to conduct tender offers.")
  ("6" "Purposes Of This Tender Offer And Plans Or Proposals."
   "(a)-(b) Reference is made to Section 1 “Background and Purpose of the Offer” of the Offer to Purchase, which is incorporated herein by reference."
   "(c) Reference is made to Section 8 “Certain Information About the Fund” of the Offer to Purchase, which is incorporated herein by reference.")
  ("7" "Source and Amount of Funds or Other Consideration."
   "(a)-(b) Reference is made to Section 6 “Purchases and Payment” of the Offer to Purchase, which is incorporated herein by reference.")
  ("8" "Interest in Securities of the Subject Company.")
  ("9" "Persons/Assets Retained, Employed, Compensated or Used.")
  ("10"
   "Item 10. Financial Statements. (a) The audited annual financial statem")
  ("11"
   "Item 11. Additional Information. (a) (1) None. (2) None. (3) Not appli")
  ("12"
   "(a)(1) (i) Cover Letter to Offer to Purchase and Letter of Transmittal."
   "June 29, 2026 EXHIBIT INDEX Exhibit (a)(1)(i) Cover Letter to Offer to Purchase and Letter of Transmittal."
   "(a)(1)(iii) Form of Letter of Transmittal."))
 :text
 ("The principal executive office of the Fund is located at 655 Broad Street, Newark, NJ 07102 and the telephone number is (844)-753-6354."
  "The Manager’s principal address is 655 Broad Street, Newark, NJ 07102-4410 and its telephone number is 1-888-778-5471."
  "Because Shares are not traded in any market, subsections (6), (7), and (8) of Regulation M-A Item 1006(c) are not applicable to the Fund."
  "June 29, 2026 EXHIBIT INDEX Exhibit (a)(1)(i) Cover Letter to Offer to Purchase and Letter of Transmittal."))
