(:sections
 (("1"
   "Item 1. Summary Term Sheet. The information set forth in the \"Summary ")
  ("2"
   "(a) The name of the subject company and the issuer of the securities to which this Schedule TO relates is TubeMogul, Inc., a Delaware corporation."
   "TubeMogul's principal executive offices are located at 1250 53rd Street, Suite 2, Emeryville, CA 94608."
   "(c) The information set forth in Section 6 (entitled \"Price Range of Shares;")
  ("3" "Identity and Background of the Filing Person."
   "(a) - (c) This Schedule TO is filed by Purchaser and Adobe.")
  ("4"
   "Federal Income Tax Consequences of the Offer\"  Section 11  \"The Merger Agreement;"
   "Plans for TubeMogul\"  Section 13  \"Certain Effects of the Offer\"  Section 15  \"Conditions of the Offer\"  Section 16  \"Certain Legal Matters;")
  ("5" "Past Contacts, Transactions, Negotiations and Agreements."
   "(a), (b) The information set forth in the following sections of the Offer to Purchase is incorporated herein by reference:")
  ("6" "Purposes of the Transaction and Plans or Proposals."
   "(a), (c)(1) - (7) The information set forth in the following sections of the Offer to Purchase is incorporated herein by reference:"
   " the \"Introduction\"  the \"Summary Term Sheet\"  Section 10  \"Background of the Offer;")
  ("7" "Source and Amount of Funds or Other Consideration."
   " the \"Summary Term Sheet\"  Section 9  \"Source and Amount of Funds\" (b), (d) Not applicable.")
  ("8" "Interest in Securities of the Subject Company."
   " the \"Summary Term Sheet\"  Section 8  \"Certain Information Concerning Adobe and Purchaser\"  Section 11  \"The Merger Agreement;")
  ("9" "Persons/Assets, Retained, Employed, Compensated or Used."
   " the \"Summary Term Sheet\"  Section 3  \"Procedures for Accepting the Offer and Tendering Shares\"  Section 10  \"Background of the Offer;")
  ("10" "Item 10. Financial Statements. Not applicable.")
  ("11"
   "(a)(1) The information set forth in the following sections of the Offer to Purchase is incorporated herein by reference:"
   "Plans for TubeMogul\"  Section 15  \"Conditions of the Offer\"  Section 16  \"Certain Legal Matters;"
   "Plans for TubeMogul\" (a)(2) The information set forth in the following sections of the Offer to Purchase is incorporated herein by reference:")
  ("12"
   "(a)(5)(C) FAQ issued by Adobe on November 10, 2016 (incorporated by reference to Exhibit 99.3 to the Schedule TO filed by Adobe on November 10, 2016)."
   "7 ---------------------------------------------------------------------------------------------------- Exhibit No."
   "4 ---------------------------------------------------------------------------------------------------- Exhibit No."))
 :text
 ("1 for Fiscal Year 2017, issued August 31, 2016, by multiplying the transaction value by 0.0001159."
  "TubeMogul's principal executive offices are located at 1250 53rd Street, Suite 2, Emeryville, CA 94608."
  "Plans for TubeMogul\"  Section 13  \"Certain Effects of the Offer\"  Schedule I Item 7."
  "Past Contacts or Negotiations with TubeMogul\"  Section 18  \"Fees and Expenses\" Item 10."
  "7 ---------------------------------------------------------------------------------------------------- Exhibit No."))
