(:sections
 (("1" "(b) Address of issuer's principal executive offices:")
  ("2"
   "Ali Ehad Turker (b) Address or principal business office or, if none, residence:"
   "601 Brickell Key Dr, Suite 700, Miami, FL 33131 (c) Citizenship:"
   "Albania (d) Title of class of securities:")
  ("3"
   "If this statement is filed pursuant to §§ 240.13d-1(b) or 240.13d-2(b) or (c), check whether the person filing is a:"
   "(d) Checkbox not checked Investment company registered under section 8 of the Investment Company Act of 1940 (15 U.S.C."
   "institution in accordance with § 240.13d-1(b)(1)(ii)(J), please specify the type of institution:")
  ("4" "Ownership (a) Amount beneficially owned:"
   "0.0288 % (c) Number of shares as to which the person has:"
   "28777 (iv) Shared power to dispose or to direct the disposition of:")
  ("5" "Ownership of 5 Percent or Less of a Class.")
  ("6" "Ownership of more than 5 Percent on Behalf of Another Person.")
  ("7"
   "Identification and Classification of the Subsidiary Which Acquired the Security Being Reported on by the Parent Holding Company or Control Person.")
  ("8" "Identification and Classification of Members of the Group.")
  ("9"
   "Item 9. Notice of Dissolution of Group. Not Applicable Checkbox not ch")
  ("10"
   "Item 10. Certifications: By signing below I certify that, to the best "))
 :text
 ("If this statement is filed pursuant to §§ 240.13d-1(b) or 240.13d-2(b) or (c), check whether the person filing is a:"
  "(e) Checkbox not checked An investment adviser in accordance with § 240.13d-1(b)(1)(ii)(E);"
  "institution in accordance with § 240.13d-1(b)(1)(ii)(J), please specify the type of institution:"
  "28777 (ii) Shared power to vote or to direct the vote:"
  "Ownership of more than 5 Percent on Behalf of Another Person."))
