(:sections
 (("1.01"
   "Information presented in this report is based on calendar years."
   "For more detail on Apple’s progress visit:"
   "Geological Survey, a survey of smelters and refiners, and third-party reviews of publicly available information.")
  ("1.02"
   "Item 1.02 Exhibit Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report.")
  ("2.01"
   "Item 2.01 Resource Extraction Issuer Disclosure and Report Not applicable.")
  ("3.01"
   "Item 3.01 Exhibits Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report."))
 :text
 ("☒ Rule 13p-1 under the Securities Exchange Act (17 CFR 240.13p-1) for the reporting period from January 1 to December 31, 2025."
  "Section 3 – Exhibits Item 3.01 Exhibits Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report."))
