(:sections
 (("1.01"
   "Overview During the Reporting Period, the Company’s business consisted of CompoSecure, Inc."
   "CompoSecure’s supply chain for Modules has several key suppliers which have product association with tin, tantalum, tungsten, and gold (“3TG”)."
   "Moreover, to the extent 3TG are present in Modules incorporated into CompoSecure’s products, the content is at trace levels.")
  ("1.02"
   "Item 1.02 Exhibit Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report.")
  ("2.01"
   "Item 2.01 Resource Extraction Issuer Disclosure and Report Not applicable.")
  ("3.01"
   "Item 3.01 Exhibits Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report."))
 :text
 ("☒ Rule 13p-1 under the Securities Exchange Act (17 CFR 240.13p-1) for the reporting period from January 1 to December 31, 2025."
  "Section 3 – Exhibits Item 3.01 Exhibits Pursuant to the 2017 SEC Statement, no exhibit is filed as part of this report."))
