(:sections
 (("1.01"
   "Item 1.01 Conflict Minerals Disclosure and Report LightPath Technologies, Inc.")
  ("1.02"
   "Item 1.02 Exhibit The Conflict Minerals Report is attached as Exhibit 1.01 to this report.")
  ("2.01"
   "Item 2.01 Resource Extraction Issuer Disclosure and Report Not applicable.")
  ("3.01"
   "Item 3.01 Exhibits The following exhibit is filed as part of this report."
   "Description 1.01 Conflict Minerals Report for the Covered Period as required by Items 1.01 and 1.02 of this Form SD."))
 :text
 ("[X] Rule 13p-1 under the Securities Exchange Act (17 CFR 240.13p-1) for the reporting period from January 1 to December 31, 2025."
  "[ ] Rule 13q-1 under the Securities Exchange Act (17 CFR 240.13q-1) for the fiscal year ended:"
  "Description 1.01 Conflict Minerals Report for the Covered Period as required by Items 1.01 and 1.02 of this Form SD."))
