(:submission-type "13F-NT" :report-period "06-30-2026" :amendment-p
		  nil :manager-cik "0001451086" :manager-name
		  "Attucks Asset Management, LLC" :manager-address
		  (:street-1 "321 N. CLARK STREET" :street-2
			     "SUITE 740" :city "CHICAGO"
			     :state-or-country "IL" :zip "60654")
		  :report-type "13F NOTICE" :form-13f-file-number
		  "028-13412" :crd-number nil :sec-file-number nil
		  :other-managers
		  ((:cik nil :crd-number nil :sec-file-number nil
			 :name "The Edgar Lomax Company")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Paradigm Asset Management, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Seizert Capital Partners")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Channing Capital Management, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Affinity Investment Advisors, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Heard Capital LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Phocas Financial")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Denali Advisors")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Lisanti Capital Growth LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Decatur Capital Management, Inc.")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Profit Investment Management, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Summit Creek Advisors LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Pacific Ridge Capital Partners, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "ARGA Investment Management, LP")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "GlobeFlex Capital, LP")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Slow Capital, inc")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Ancora Advisors, LLC")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Heron Bay Capital Management")
		   (:cik nil :crd-number "000310355" :sec-file-number
			 "801-119868" :name
			 "V-Square Quantitative Management LLC.")
		   (:cik nil :crd-number nil :sec-file-number nil
			 :name "Isthmus Partners, LLC"))
		  :signature
		  (:name "Derek A. Talley" :title
			 "Chief Compliance Officer/Chief Operating Officer"
			 :phone "312-422-9900" :signature
			 "Derek A. Talley" :city "Chicago"
			 :state-or-country "IL" :date "11-12-2025"))
