(:submission-type "13F-NT" :report-period "06-30-2026" :amendment-p
		  nil :manager-cik "0001767867" :manager-name
		  "RWC (US) LLC" :manager-address
		  (:street-1 "2640 S. BAYSHORE DRIVE, SUITE 201"
			     :street-2 nil :city "MIAMI"
			     :state-or-country "FL" :zip "33133")
		  :report-type "13F NOTICE" :form-13f-file-number
		  "028-19401" :crd-number nil :sec-file-number nil
		  :other-managers
		  ((:cik "0001638081" :crd-number "000166517"
			 :sec-file-number "801-77698" :name
			 "RWC ASSET ADVISORS (US) LLC"))
		  :signature
		  (:name "Fadi Freiha" :title "Compliance Officer"
			 :phone "44-0-20-7227-6150" :signature
			 "/s/ Fadi Freiha" :city "London"
			 :state-or-country "X0" :date "07-15-2026"))
