(:issuer (:cik "0001341439" :name "ORACLE CORP" :ticker "ORCL")
 :owner
 (:cik "0002129261" :name "Maxson Hilary B"
  :address (:street-1 "C/O DELPHI ASSET MGMT CORPORATION"
            :street-2 "200 S. VIRGINIA ST., SUITE 625"
            :city "RENO" :state "NV" :zip "89501" :country nil)
  :is-director nil :is-officer t :is-ten-percent-owner nil
  :is-other nil :officer-title "Chief Financial Officer" :other-text nil)
 :transactions nil :holdings nil :footnotes nil
 :signatures
 ((:name "/s/ Aimee Weast by Aimee Weast, Attorney in Fact for Hilary B. Maxson (POA filed 4/14/2026)"
   :date "2026-04-14")))
