(:issuer (:cik "0002012807" :name "RF Acquisition Corp II" :ticker "RFAI")
 :owner
 (:cik "0002013019" :name "Alfa 24 Ltd"
  :address (:street-1 "111 SOMERSET, #05-07" :street-2 nil
            :city "SINGAPORE" :state nil :zip "238164" :country nil)
  :is-director nil :is-officer nil :is-ten-percent-owner t :is-other nil
  :officer-title nil :other-text nil)
 :transactions nil
 :holdings
 ((:kind non-derivative
   :security-title "Ordinary Shares, par value $0.0001 per share"
   :date nil :code nil :shares nil :price nil :acquired-disposed nil
   :shares-owned-following "3230000" :direct-indirect "D"
   :nature-of-ownership nil :exercise-price nil :exercise-date nil
   :expiration-date nil :underlying-security-title nil
   :underlying-security-shares nil :footnote-ids ("F1")
   :footnotes
   ("Includes 2,875,000 ordinary shares (of which 375,000 ordinary shares are subject to forfeiture based on the underwriters' exercise of their overallotment option) and 355,000 ordinary shares underlying the private placement units, which were sold in a private placement taking place simultaneously with the RF Acquisition Corp II's initial public offering."))
  (:kind derivative :security-title "Rights" :date nil :code nil
   :shares nil :price nil :acquired-disposed nil
   :shares-owned-following nil :direct-indirect "D"
   :nature-of-ownership nil :exercise-price nil :exercise-date nil
   :expiration-date nil :underlying-security-title "Ordinary Shares"
   :underlying-security-shares "17750" :footnote-ids ("F2")
   :footnotes
   ("Includes 355,000 rights underlying the private placement units, which were sold in a private placement taking place simultaneously with the RF Acquisition Corp II's initial public offering. Each right is exchangeable for one twentieth of one ordinary share upon the completion of RF Acquisition Corp II's initial business combination.")))
 :footnotes
 ((:id "F1" :text "Includes 2,875,000 ordinary shares (of which 375,000 ordinary shares are subject to forfeiture based on the underwriters' exercise of their overallotment option) and 355,000 ordinary shares underlying the private placement units, which were sold in a private placement taking place simultaneously with the RF Acquisition Corp II's initial public offering.")
  (:id "F2" :text "Includes 355,000 rights underlying the private placement units, which were sold in a private placement taking place simultaneously with the RF Acquisition Corp II's initial public offering. Each right is exchangeable for one twentieth of one ordinary share upon the completion of RF Acquisition Corp II's initial business combination."))
 :signatures ((:name "/s/ Tse Meng Ng, as managing member"
               :date "2024-05-23")))
