(:issuer
 (:cik "0001005210" :name "SUBURBAN PROPANE PARTNERS LP" :ticker "SPH")
 :owners
 ((:cik "0001307744" :name "Swift Jane" :address
	(:street-1 "C/O SUBURBAN PROPANE PARTNERS, L.P." :street-2
		   "240 ROUTE 10 WEST" :city "WHIPPANY" :state "NJ"
		   :zip "07981-0206" :country nil)
	:is-director t :is-officer nil :is-ten-percent-owner nil
	:is-other nil :officer-title nil :other-text nil))
 :holdings nil :footnotes nil :10b5-1 nil :signatures
 ((:name "Bryon Koepke, by power of attorney" :date "2026-09-29")))
