(:issuer (:cik "0000730263" :name "THOR INDUSTRIES INC" :ticker "THO")
	 :owners
	 ((:cik "0001488301" :name "Kelley William J. JR" :address
		(:street-1 "C/O THOR INDUSTRIES, INC." :street-2
			   "2900 INDEPENDENCE COURT" :city "ELKHART"
			   :state "IN" :zip "46514" :country nil)
		:is-director t :is-officer nil :is-ten-percent-owner
		nil :is-other nil :officer-title nil :other-text nil))
	 :holdings nil :footnotes
	 ((:id "F1" :text
	       "Represents shares withheld for taxes with respect to the vesting of a previously granted restricted stock unit award."))
	 :10b5-1 nil :signatures
	 ((:name
	   "/s/ Barb Montague, attorney-in-fact for William J. Kelley Jr"
	   :date "2026-09-02")))
