(:issuer-cik "0001833928"
 :issuer-name "Airthium Inc."
 :issuer-website "https://www.airthium.com"
 :co-issuer-names
 ("Airthium III, a series of Wefunder SPV, LLC"
  "Airthium III EB, a series of Wefunder SPV, LLC")
 :intermediary-name "Wefunder Portal LLC"
 :security-type "Other"
 :securities-offered 50000
 :price "1.00000"
 :offering-amount "50000.00"
 :maximum-offering-amount "1000000.00"
 :deadline "04-30-2027"
 :current-employees "14"
 :total-assets-current "3822557.00"
 :total-assets-prior "5426773.00"
 :revenue-current "1519556.00"
 :revenue-prior "1232953.00"
 :net-income-current "-1603653.00"
 :net-income-prior "-1452577.00"
 :signatures
 ((:name "Andrei Klochko" :title "Co-Founder, CEO & CSO" :date "06-10-2026")
  (:name "Franck Lahaye" :title "Co-Founder, COO" :date "06-10-2026")))
