(:issuer-cik "0001959002"
 :period "12-31-2025"
 :issuer-name "Qnetic Corp"
 :issuer-website "https://qnetic.energy"
 :co-issuer-name "Qnetic II, a series of WeFunder SPV, LLC"
 :current-employees "16.00"
 :total-assets-current "4322940.00"
 :total-assets-prior "250179.00"
 :cash-current "3790836.00"
 :cash-prior "204469.00"
 :revenue-current "0.00"
 :revenue-prior "0.00"
 :net-income-current "-3793103.00"
 :net-income-prior "-1250875.00"
 :signatures
 ((:name "Michael Alexander Pratt" :title "Director" :date "09-18-2026")
  (:name "Loic Bastard" :title "Director" :date "09-18-2026")
  (:name "Malcolm Mathews" :title "Director" :date "09-18-2026")
  (:name "Mohammed Abdulaziz A. Al Tuwaijri" :title "Director" :date "09-18-2026")))
