(:issuer-cik "0002139881" :issuer-name "Sapor Syrup Inc."
	     :issuer-website "https://drinkaboveboard.com"
	     :co-issuer-names
	     ("Above Board I, a series of Wefunder SPV, LLC"
	      "Above Board I EB, a series of Wefunder SPV, LLC")
	     :intermediary-name "Wefunder Portal LLC" :security-type
	     "Other" :securities-offered 50000 :price "1.00000"
	     :offering-amount "50000.00" :maximum-offering-amount
	     "124000.00" :deadline "04-30-2027" :current-employees "2"
	     :total-assets-current "214158.93" :total-assets-prior
	     "51131.43" :revenue-current "155202.74" :revenue-prior
	     "43462.50" :net-income-current "-150517.70"
	     :net-income-prior "-182748.95" :signatures
	     ((:name "Brent Slone" :title "CFO" :date "09-28-2026")
	      (:name "Nicole Cammarano" :title "CEO" :date
		     "09-29-2026")
	      (:name "Arbeth Sackett" :title "Director" :date
		     "09-29-2026")))
