(:issuer-cik "0002136589" :issuer-name "String Cubed Inc"
	     :issuer-website "www.stringcubed.com" :co-issuer-names
	     nil :intermediary-name "DEALMAKER SECURITIES LLC"
	     :security-type "Other" :securities-offered 100000 :price
	     "0.40000" :offering-amount "40000.00"
	     :maximum-offering-amount "5000000.00" :deadline
	     "06-01-2027" :current-employees "1.00"
	     :total-assets-current "82998.00" :total-assets-prior
	     "115169.00" :revenue-current "7912.00" :revenue-prior
	     "69350.00" :net-income-current "-25640.00"
	     :net-income-prior "46788.00" :signatures
	     ((:name "Manuel Rendon" :title "CEO" :date "09-30-2026")))
