(:form "SC 13G/A" :sections
       (("3"
	 . "Item 3   If this statement is filed pursuant to rules 13d-1(b), or 13d-\n         2(b), check whether the person filing is a:\n     (a) [ ] Broker or Dealer registered under Section 15 of the Act\n     (b) [ ] Bank as defined in Section 3(a)(6) of the Act\n     (c) [ ] Insurance Company as defined in Section 3(a)(19) of the Act\n     (d) [ ] Investment Company registered under Section 8 of\n             the Investment Company Act\n     (e) [X] Investment Adviser registered under Section 203 of\n             the Investment Advisers Act of 1940\n     (f) [ ] Employee Benefit Plan, Pension Fund which is\n             subject to the provisions of the Employee\n             Retirement Income Security Act of 1974 or Endowment Fund\n     (g) [ ] Parent Holding Company, in accordance with Rule 13d-1 (b)(ii)(G)\n     (h) [ ] Group\nCUSIP No. 36467W109   13G")
	("4"
	 . " Item 4  Ownership\n     (a) Amount Beneficially Owned:\n                          2,648,566\n     (b) Percent of Class:\n                          2.29%\n     (c)     Number of shares as to which such person has:\n\n         (i) sole power to vote or to direct the vote\n                                              2,648,566\n\n         (ii)    shared power to vote or to direct the vote\n                                         __________\n        (iii)    sole power to dispose or to direct the disposition\n                 of                              2,648,566\n         (iv)    shared power to dispose or to direct the\n                 disposition of                  __________")
	("5"
	 . "Item 5   Ownership of Five Percent or Less of a Class. [   X   ]")
	("6"
	 . "Item 6   Ownership of More than Five Percent on Behalf of Another Person .\n             NONE")
	("7"
	 . "Item 7   Identification and Classification of the Subsidiary Which Acquired\n         The Security Being Reported on by the Parent Holding\n         Company.\n             NOT APPLICABLE")
	("8"
	 . "Item 8   Identification and Classification of Members of the Group.\n             NOT APPLICABLE")
	("9"
	 . "Item 9   Notice of Dissolution of Group.\n             NOT APPLICABLE\n\nCUSIP No. 36467W109   13G")
	("10"
	 . "Item 10  Certification.\n\n By signing below I certify that, to the best of my knowledge and belief,\n the securities referred to above were acquired  and are held in the ordinary\n course of business and were not acquired and are not held for the purpose of\n or with the effect of changing or influencing the control of the issuer of\n the securities and were not acquired and are not held in connection with\n or as a participant in any transaction having that purpose or effect.\n\n                                   Signature\n\n After reasonable inquiry and to the best of my knowledge and belief,\n I certify that the information set forth in this statement with respect\n to it is true, complete and correct.\n\nDate:    January 28, 2014\n\n\n\n\n\n\nBy: John E. Denneen, Secretary")))
