(:form "SC 13G/A"
 :sections
 (("3" . "Item 3   If this statement is filed pursuant to rules 13d-1(b), or 13d-
         2(b), check whether the person filing is a:
     (a) [ ] Broker or Dealer registered under Section 15 of the Act
     (b) [ ] Bank as defined in Section 3(a)(6) of the Act
     (c) [ ] Insurance Company as defined in Section 3(a)(19) of the Act
     (d) [ ] Investment Company registered under Section 8 of
             the Investment Company Act
     (e) [X] Investment Adviser registered under Section 203 of
             the Investment Advisers Act of 1940
     (f) [ ] Employee Benefit Plan, Pension Fund which is
             subject to the provisions of the Employee
             Retirement Income Security Act of 1974 or Endowment Fund
     (g) [ ] Parent Holding Company, in accordance with Rule 13d-1 (b)(ii)(G)
     (h) [ ] Group
CUSIP No. 36467W109   13G
")
  ("4" . " Item 4  Ownership
     (a) Amount Beneficially Owned:
                          2,648,566
     (b) Percent of Class:
                          2.29%
     (c)     Number of shares as to which such person has:

         (i) sole power to vote or to direct the vote
                                              2,648,566

         (ii)    shared power to vote or to direct the vote
                                         __________
        (iii)    sole power to dispose or to direct the disposition
                 of                              2,648,566
         (iv)    shared power to dispose or to direct the
                 disposition of                  __________
")
  ("5" . "Item 5   Ownership of Five Percent or Less of a Class. [   X   ]
")
  ("6" . "Item 6   Ownership of More than Five Percent on Behalf of Another Person .
             NONE
")
  ("7" . "Item 7   Identification and Classification of the Subsidiary Which Acquired
         The Security Being Reported on by the Parent Holding
         Company.
             NOT APPLICABLE
")
  ("8" . "Item 8   Identification and Classification of Members of the Group.
             NOT APPLICABLE
")
  ("9" . "Item 9   Notice of Dissolution of Group.
             NOT APPLICABLE

CUSIP No. 36467W109   13G
")
  ("10" . "Item 10  Certification.

 By signing below I certify that, to the best of my knowledge and belief,
 the securities referred to above were acquired  and are held in the ordinary
 course of business and were not acquired and are not held for the purpose of
 or with the effect of changing or influencing the control of the issuer of
 the securities and were not acquired and are not held in connection with
 or as a participant in any transaction having that purpose or effect.

                                   Signature

 After reasonable inquiry and to the best of my knowledge and belief,
 I certify that the information set forth in this statement with respect
 to it is true, complete and correct.

Date:    January 28, 2014






By: John E. Denneen, Secretary")))
