(:form "SCHEDULE 13G" :cover
       (:issuer
	(:cik "0001745916" :name "PennyMac Financial Services, Inc."
	      :cusips nil)
	:reporting-persons
	((:name "Millennium Management LLC" :cik nil :shares
		"2535760.00" :percent-of-class "4.9"
		:type-of-reporting-person "OO" :sole-voting-power
		"0.00" :shared-voting-power "2535760.00"
		:sole-dispositive-power "0.00"
		:shared-dispositive-power "2535760.00" :item-4-amount
		"See response to Item 9 on each cover page.\n\nAfter acquiring beneficial ownership of more than 5% of the outstanding Common Stock on March 27, 2026, the reporting persons ceased to be beneficial owners of more than 5% of the outstanding Common Stock by the date of this filing."
		:item-4-percent
		"See response to Item 11 on each cover page.")
	 (:name "Millennium Group Management LLC" :cik nil :shares
		"2535760.00" :percent-of-class "4.9"
		:type-of-reporting-person "OO" :sole-voting-power
		"0.00" :shared-voting-power "2535760.00"
		:sole-dispositive-power "0.00"
		:shared-dispositive-power "2535760.00" :item-4-amount
		"See response to Item 9 on each cover page.\n\nAfter acquiring beneficial ownership of more than 5% of the outstanding Common Stock on March 27, 2026, the reporting persons ceased to be beneficial owners of more than 5% of the outstanding Common Stock by the date of this filing."
		:item-4-percent
		"See response to Item 11 on each cover page.")
	 (:name "Israel A. Englander" :cik nil :shares "2535760.00"
		:percent-of-class "4.9" :type-of-reporting-person "IN"
		:sole-voting-power "0.00" :shared-voting-power
		"2535760.00" :sole-dispositive-power "0.00"
		:shared-dispositive-power "2535760.00" :item-4-amount
		"See response to Item 9 on each cover page.\n\nAfter acquiring beneficial ownership of more than 5% of the outstanding Common Stock on March 27, 2026, the reporting persons ceased to be beneficial owners of more than 5% of the outstanding Common Stock by the date of this filing."
		:item-4-percent
		"See response to Item 11 on each cover page.")))
       :purpose nil)
