(:form "SCHEDULE 13D/A"
 :cover (:issuer (:cik "0001829864" :name "TaskUs, Inc." :cusips ("87652V109"))
         :reporting-persons
         ((:name "Think Investments LP" :cik "0001635999" :shares "3734665.00"
           :percent-of-class "19.8" :type-of-reporting-person "IA"
           :sole-voting-power "0.00" :shared-voting-power "3734665.00"
           :sole-dispositive-power "0.00" :shared-dispositive-power "3734665.00"
           :item-4-amount nil :item-4-percent nil)
          (:name "Think India Opportunities Master Fund LP" :cik nil
           :shares "3157150.00" :percent-of-class "16.8"
           :type-of-reporting-person "PN" :sole-voting-power "0.00"
           :shared-voting-power "3157150.00" :sole-dispositive-power "0.00"
           :shared-dispositive-power "3157150.00" :item-4-amount nil
           :item-4-percent nil)))
 :purpose "The Reporting Persons have acquired shares in the issuer for investment purposes and would like to express an intent to explore further opportunities in its business to maximize value. This may include discussions with management, the acquirers or other relevant parties with respect to the terms of the recently announced take-private transaction.

The Reporting persons may, from time to time, review or reconsider their position and may formulate plans or proposals with respect to the issuer or its securities, but has no present plans or proposals in place. The Reporting Persons may from time to time and at any time, in their sole discretion, acquire or cause to be acquired, additional equity or debt securities or other instruments of the issuer, its subsidiaries or affiliates, or dispose or cause to be disposed, such equity or debt securities or instruments, in any amount that the Reporting Persons may determine in their sole discretion, through open market transactions, privately negotiated transactions or otherwise.")
