(:form "SCHEDULE 13G"
 :cover (:issuer (:cik "0001326380" :name "GameStop Corp." :cusips ("36467W109"))
         :reporting-persons
         ((:name "Turker Ali Ehad" :cik nil :shares "128777.00"
           :percent-of-class "0.0" :type-of-reporting-person "IN"
           :sole-voting-power "28777.00" :shared-voting-power "0.00"
           :sole-dispositive-power "28777.00" :shared-dispositive-power "0.00"
           :item-4-amount "128777" :item-4-percent "0.0288")))
 :purpose nil)
