(:form "SCHEDULE 13D" :cover
       (:issuer
	(:cik "0001529274" :name "ALKAMI TECHNOLOGY, INC." :cusips nil)
	:reporting-persons
	((:name "JANA PARTNERS MANAGEMENT, LP" :cik "0001998597"
		:shares "5431388.00" :percent-of-class "5.1"
		:type-of-reporting-person "IA" :sole-voting-power
		"5431388.00" :shared-voting-power "0.00"
		:sole-dispositive-power "5431388.00"
		:shared-dispositive-power "0.00" :item-4-amount nil
		:item-4-percent nil)))
       :purpose
       "The Reporting Person acquired the Shares because it believes the Shares are undervalued and represent an attractive investment opportunity.")
